### ISSUE TITLE
Custom ores do not generate for Worlds loaded after ItemsAdder is loaded

### ISSUE THREAD

**Issue by BillyGalbreath** [LoneDev6/ItemsAdder#10]
IA seems to register events for worlds when the plugin first loads. It checks world config values against all loaded worlds at this time. (see lines 57 and 74 of `dev.lone.itemsadder.c.d.e`)

The problem with this approach is not all worlds are loaded when ItemsAdder loads up, so any extra worlds loaded afterwards do not get any listeners registered that do the custom ore replacements in the worlds.

My suggestion is to check for the worlds and register these listeners in the [ServerLoadEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/server/ServerLoadEvent.html) to ensure any world loader plugins have had time to load up any additional worlds.

As a temporary work-around, I have edited ItemAdder's plugin.yml file to include my world loaders in `softdepend` to ensure they load before IA does.

**Comment by LoneDev6** [comment]
Interesting approach, so probably I'll just have to edit plugin.yml to include most used world loader plugins right?
Seems more cleaner than hoping that world plugins had loaded worlds after ServerLoadEvent (which I don't think always happens instantly), right?

**Comment by LoneDev6** [comment]
Update to latest version, now should work on dynamically loaded worlds too.
No need to edit the plugin.yml file
