### ISSUE TITLE
Error starting server

### ISSUE THREAD

**Issue by TheMrLhuixx** [LoneDev6/ItemsAdder#100]
Hi Lonedev, I have this error when starting the server but ItemsAdder seems to work correctly, the only things that don't work for me are the sounds of the light swords, weapons, and the astral bow ...

Minecraft Version Paper Spigot 1.15.2

Error Console: https://pastebin.com/arrQKdJA

**Comment by LoneDev6** [comment]
Please open sounds.json file from this folder: plugins\ItemsAdder\data\resource_pack\assets\itemsadder

and replace it with this: https://hasteb.in/zidibeka.json

**Comment by TheMrLhuixx** [comment]
I did what you told me, but it still doesn't work u.u

**Comment by TheMrLhuixx** [comment]
Sorry, I am missing adding it in the pack.zip, that's why it did not work for me yet, but now it does work... thanks :]

Now, the error is not what is due, since it still appears

**Comment by LoneDev6** [comment]
> Sorry, I am missing adding it in the pack.zip, that's why it did not work for me yet, but now it does work... thanks :]
happy we fixed sounds.

> 
> Now, the error is not what is due, since it still appears
"The server has not responded for 10 seconds! Creating thread dump"
What are your server specs? Seems server was lagging during resourcepack compression process

**Comment by TheMrLhuixx** [comment]
It is a small server that I only use to work with a couple of friends

Spec
1 core - Xeon E5-1630v3 @ 3.7Ghz
5 GB DDR4 2133MHz ECC Memory
250Mbps Uplink
Unmetered Enterprise grade SSDs

Now I realize that the error is clearly due to the server specifications, but apparently it does not affect the operation of itemsadders, although I tried itemsadder v1.1.xx with the same resource package, and the error does not appear and works correctly

**Comment by LoneDev6** [comment]
> 
> 
> It is a small server that I only use to work with a couple of friends
> 
> Spec
> 1 core - Xeon E5-1630v3 @ 3.7Ghz
> 5 GB DDR4 2133MHz ECC Memory
> 250Mbps Uplink
> Unmetered Enterprise grade SSDs
> 
> Now I realize that the error is clearly due to the server specifications, but apparently it does not affect the operation of itemsadders, although I tried itemsadder v1.1.xx with the same resource pack, and the error does not appear and works correctly too.

That's because IA 2 is generating the pack when plugin is loaded, while IA 1 uses a pregenerated resourcepack which had less features because of this limitation
