### ISSUE TITLE
Bug TownyAdvanced + ItemsAdder

### ISSUE THREAD

**Issue by Mrkhris** [LoneDev6/ItemsAdder#102]
Spigot 1.15.2
Last version Towny and ItemsAdder

https://youtu.be/CgDNszn6-Q4

The bug allows us to dupe
 the seeds in someone else's territory where we can't break blocks

**Comment by LoneDev6** [comment]
Please as Towny dev to get in touch with me, I have to know how they manage priority of events in order to fix this

**Comment by Mrkhris** [comment]
I am not the developer of this plugin, I'm Dmitry from the discord :)

**Comment by LoneDev6** [comment]
Can you try with ItemsAdder 2.0?
**Use it on a test server** as upgrading from 1.0 to 2.0 is not automatic. https://itemsadder.plugin.ga/updating-from-1.0

**Comment by LoneDev6** [comment]
v2 doesn't have this issue, please consider updating:
https://i.imgur.com/grGLsBm.mp4
