### ISSUE TITLE
Trade machine can't change trade gui name.

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#105]
![註解 2020-03-21 013006](https://user-images.githubusercontent.com/50344708/77190175-beed6100-6b13-11ea-8c37-196838c41d97.png)
![註解 2020-03-21 013026](https://user-images.githubusercontent.com/50344708/77190185-c3b21500-6b13-11ea-9d4b-6988a8a1aa13.png)

**Comment by LoneDev6** [comment]
Sadly it's not possible to change this title, it's inside Minecraft
