### ISSUE TITLE
request: Hope can add minecraft original item to the block of drops

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#107]
like this picture
![註解 2020-03-21 160741](https://user-images.githubusercontent.com/50344708/77222446-1a5c3500-6b8e-11ea-92fb-39cdd2eb28a2.png)
Data:
![註解 2020-03-21 160833](https://user-images.githubusercontent.com/50344708/77222453-3c55b780-6b8e-11ea-8b26-559a3129038c.png)

**Comment by LoneDev6** [comment]
Yes you can make drop vanilla items from custom blocks, can you test it?
