### ISSUE TITLE
[2.0.6] Attributes missing on items with lore

### ISSUE THREAD

**Issue by spathizilla** [LoneDev6/ItemsAdder#111]
When creating an item (sword in this instance) with a lore set, the attributes for attackDamage and attackSpeed are no longer shown. When the lore text is removed from config, the attackDamage and attackSpeed lore lines are displayed correctly.

Tested on IA2.0.6 Beta 
Server version: Paper(155) 1.15.2-R0.1-SNAPSHOT

**Comment by spathizilla** [comment]
![greatsword](https://user-images.githubusercontent.com/638845/78075388-58cace80-739c-11ea-92f4-b40e5735392b.png)

**Comment by LoneDev6** [comment]
Fixed in next release, please reopen this if the update won't fix the issue.
(i'll post the update in a day)
