### ISSUE TITLE
Unable to paint armor

### ISSUE THREAD

**Issue by Mrkhris** [LoneDev6/ItemsAdder#113]
On versions of ItemsAdder V1, I created custom leather armor, which later could be painted through a workbench. That is, a person crafted leather armor with a durability system from the ItemsAdder plugin, and this leather armor could be easily painted, while retaining the feature with durability from the plugin. But in V2 versions this cannot be done while "internal" is present

Yes, I could use and create armor through Armor.yml indicating the required color, but my players could specify the color themselves, and this armor also had a durability system, and it was much more convenient for me than I would create 256 types of multi-colored armor

**Comment by Mrkhris** [comment]
![2020-04-03_18 34 16](https://user-images.githubusercontent.com/46727551/78378566-d3346200-75d9-11ea-824d-b3fb12fe9c93.png)
![2020-04-03_18 34 18](https://user-images.githubusercontent.com/46727551/78378572-d4fe2580-75d9-11ea-834f-20a7ba7359a6.png)

**Comment by LoneDev6** [comment]
You can fix this creating a machine similar to the "Customization Table" :D

**Comment by Mrkhris** [comment]
This does not solve the problem, can you imagine how many types of armor you will have to create to take into account all possible combinations that can be used to paint leather armor? Is there no way to fix this? Earlier on the previous version, the same thing worked, and it worked well

**Comment by LoneDev6** [comment]
> 
> 
> This does not solve the problem, can you imagine how many types of armor you will have to create to take into account all possible combinations that can be used to paint leather armor? Is there no way to fix this? Earlier on the previous version, the same thing worked, and it worked well

On IA 1.0 this worked?
I will make more tests then, thanks!

**Comment by LoneDev6** [comment]
Fixed!
I will release 2.0.8 update later ;)
