### ISSUE TITLE
[VISUAL BUG] Big brown mushroom

### ISSUE THREAD

**Issue by yttalium** [LoneDev6/ItemsAdder#116]
Bonjour,

In natural generation I found brown mushroom with fake texture. 

Screenshot: 
https://zupimages.net/up/20/14/znz6.png
https://zupimages.net/up/20/14/1td8.png
https://zupimages.net/up/20/14/1nom.png

Nothing of special appened if I break a bloc.

**Comment by LoneDev6** [comment]
> 
> 
> Bonjour,
> 
> In natural generation I found brown mushroom with fake texture.
> 
> Screenshot:
> https://zupimages.net/up/20/14/znz6.png
> https://zupimages.net/up/20/14/1td8.png
> https://zupimages.net/up/20/14/1nom.png
> 
> Nothing of special appened if I break a bloc.

Interesting, this has been reported multiple times, I will make more tests to fix this, thanks!

**Comment by 100petr** [comment]
https://imgur.com/a/Xik3ROb
Place a block fixes it, but it's with every mushroom - it's impossible to fix it manually

**Comment by LoneDev6** [comment]
did you set this in config.yml?

  fix-bugged-mushrooms:
    enabled: true
    only-new-chunks: true

**Comment by 100petr** [comment]
in config I have
```  fix_bugged_mushrooms:
    enabled: true
    only_new_chunks: false```

**Comment by yttalium** [comment]
For me 

fix-bugged-mushrooms:
    enabled: true
    only-new-chunks: true

**Comment by LoneDev6** [comment]
does this happens on new generated chunks?
That's what I did:
- delete world
- start server
- copy seed with /seed
- paste it here https://www.chunkbase.com/apps/biome-finder
- get the coords and /tppos
- see if there is no bugged mushroom

I see no bugged mushroom, so it's surely another reason

**Comment by yttalium** [comment]
Unfortunately I no longer know where the area was but these were chunks generated before I did the Beta 2.0.6 update.
However, now I have no mushroom bug on the new chunks under 2.0.7.

**Comment by LoneDev6** [comment]
Amazing, so you all confirm that the bug was before 2.0.6?

**Comment by yttalium** [comment]
You have to believe yes, it does less work for you :p

**Comment by LoneDev6** [comment]
Eh :') Surely it was a bug before 2.0.7 and 2.0.6

**Comment by LoneDev6** [comment]
Some users reported that issue to be still an issue on latest versions of the plugin.
I still have to get logs with errors that justify this problem

**Comment by LoneDev6** [comment]
In the next update be sure to set this in config.yml:

`only-new-chunks: false`

**Comment by LoneDev6** [comment]
Should be fixed in 2.0.15 update that I will release in some hours.
Please after update reopen this issue if this problem will still occur.

Thanks

**Comment by 100petr** [comment]
A similar problem with blocks from https://www.spigotmc.org/resources/blocks-builders-basics-itemsadder-addon.78339/
![2020-05-13_13 18 47](https://user-images.githubusercontent.com/29830635/81806435-bfefad00-951c-11ea-9bd5-628a6cbb001b.png)

**Comment by LoneDev6** [comment]
This is really rare and I won't fix it because it would cause a lot of CPU usage.
For now the fix works but not in biomes where mushrooms can't spawn. That's why part of the mushroom looks ok while other part not (the bugged part is in a chunk where mushrooms cannot spawn)

It's good that it's only a graphical glitch and won't cause a problem of free rare blocks for players.
