### ISSUE TITLE
Bug and Suggestion

### ISSUE THREAD

**Issue by killic07** [LoneDev6/ItemsAdder#117]
Bug: if you set kick on  refuse to true when the player log back it kick it automaticaly even if he accept the texture pack after
if someone refuse the texture pack he cant download it again

Suggestion:
Make api for skript user i'd really love to use them with my skript gui and be able to use it with Mobs plugins(MythicalMob)
Make non-op(remove permission) player to use "/iadownload"

**Comment by LoneDev6** [comment]
> Bug: if you set kick on refuse to true when the player log back it kick it automaticaly even if he accept the texture pack after
if someone refuse the texture pack he cant download it again

that's strange, does it happens on the latest update?

> Make api for skript

done https://itemsadder.plugin.ga/developers/skript-api

> Make non-op(remove permission) player to use "/iadownload"

Please give the correct permission to each user, I cannot remove it.
`ia.user.iatexture`
https://itemsadder.plugin.ga/plugin-usage/permissions
