### ISSUE TITLE
Action bar problems

### ISSUE THREAD

**Issue by Alejitus** [LoneDev6/ItemsAdder#119]
I'm having trouble with the messages in the action bar.

I send messages through the action bar with the "MyCommand" plugin.

Without ItemsAdder: https://youtu.be/wgyJX677m1A

With ItemsAdder: https://youtu.be/nHijHKwXklw

When i connect: https://i.imgur.com/HrZ4pi6.png

**Comment by LoneDev6** [comment]
Hello!
Since itemsadder uses actionbar to draw custom huds on screen you'll have to disable the huds functionality in config.yml

set enabled: false in huds category of config.yml
