### ISSUE TITLE
[Suggestion] when in main hand

### ISSUE THREAD

**Issue by MrCoby220** [LoneDev6/ItemsAdder#126]
Currently ItemsAdder display on swords and other tools looks like this 

https://cdn.discordapp.com/attachments/609542046595678210/697505608953495673/unknown.png

but vanilla swords and tools look like this 

https://cdn.discordapp.com/attachments/609542046595678210/697505547980898436/unknown.png

My suggestion is that you make the ItemsAdder display look like the vanilla one and also add an per item option to hide Durability on ItemsAdder items

**Comment by LoneDev6** [comment]
> My suggestion is that you make the ItemsAdder display look like the vanilla one

Should be fixed in next update 2.0.10.
I will publish it today.

> add an per item option to hide Durability on ItemsAdder items

Why per item option? and not global option?
Also, do you think is this necessary? I think players must know the durability of a non vanilla item
