### ISSUE TITLE
Natural music (background)/Loop music

### ISSUE THREAD

**Issue by The-Gust** [LoneDev6/ItemsAdder#1275]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Gust#1337

### Describe the solution you'd like

New feature can allow users to create a random/loop playing music in specific areas of the worlds.

Features of suggestion:
- When music starts playing - ItemsAdder can show soundtrack name in hotbar, if enabled; 
- ItemsAdder can remove vanilla songs naturally and making illusion of playing this music (if not possible - make /stopsound-like thing, when IA music starts);   
- Songs per world;
- Songs per biome;
- Songs per blocks under player feets;
- Songs per Y-position of player;
- IA songs can't overlay each other, duration is calculating automatically (if possible);
- If user added 2 different songs with same conditions (world/block/biome) - plugin can play them in 50/50% chance.

### Is your feature request related to a problem?

All plugins with familiar features is outdated, used this in other way or doesn't support ItemsAdder. 

### Describe alternatives you've considered

"Music" plugin (mechanic looks more like mp3-player, not vanilla-like one, maybe abandoned);
"Gmusic" plugin (noteblocks music, not what we actually need);
"McMusic" plugin (outdated, noteblocks music).

### Additional context

Configuration example:

in config.yml
```  
  music_random_playing_interval: 20000-30000       #interval from 20000 (~19 minutes) to 30000 (~25 minutes) in ticks
  mute_vanilla_music: true      #true / false      Stop any vanilla natural music playing.
  imitate_vanilla_music: true      #true / false   #If true - vanilla music becomes a part of intervals.         if previous line is false - value here is false too.          Vanilla sounds can be imitated by user manually, for this - keep this false and make items_packs config for.

```

In items_packs
```
info:
  namespace: music_core
music:
  name:
    sample: "itemsadder:despacito_idk"
    type: random      #random / loop
    channel: master      #master / ambient / voice / music / hostile / record / weather / neutral / block / player
    hotbar: enabled
    hotbar_display: "Luis Fonsi, Daddy Yankee - Deeee-spaaa-cito"     
    music_properties:
      worlds:              #play if player in needed world
      - world_nether
      biomes:             #play if player stand in any biome from list
      - CRIMSON_FOREST
      on_block:           #play if player stand on any block from list
      - NETHERRACK
      - CRIMSON_NYLIUM
      - ingredients:nether_ore
      max_height: 26     #max height for playing
      min_height: 3       #min height for playing
```

**Comment by LoneDev6** [comment]
I think it's a niche feature and can be implemented by an addon.
It's not really something ItemsAdder should take care of.
