### ISSUE TITLE
Light Bug

### ISSUE THREAD

**Issue by D3nied** [LoneDev6/ItemsAdder#128]
So i testet this on a clean server only with Lightapi,protocollib,itemsadder and ialib
so lamps placed on version 2.0.6 gives lights out even in newer versions but lamps placed in version 
2.0.7 and above dont give any light out

**Comment by LoneDev6** [comment]
Should be fixed in next update 2.0.10.
I will publish it today.
Reopen this issue if it's not fixed, thanks!
