### ISSUE TITLE
Cooking recipes about smoker and blast_furnace

### ISSUE THREAD

**Issue by minecraft-dripdrop** [LoneDev6/ItemsAdder#1286]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

A smoker is a type of furnace that cooks food items, similar to a furnace, but twice as fast. 
A blast furnace is a block that smelts ores, raw metals, iron and gold armor and tools, similar to a furnace, but at twice the rate. 

So if you want to add a new food vanilla like minecraft's food.In your cooking recipe,you have to edit twice.It's inconvenient.

Maybe add an option: 'smoker_recipe:true' and ‘blast_recipe:true’ and create the same recipe but half of the cook_time.
 
    cooked_camel:
      permission: dripdrop.cooked_camel
      ingredient:
        item: dripdrop:raw_camel
      machines:
      - FURNACE
      exp: 1
      cook_time: 200
      result:
        item: dripdrop:cooked_camel
        amount: 1

    cooked_camel:
      permission: dripdrop.cooked_camel
      ingredient:
        item: dripdrop:raw_camel
      machines:
      - SMOKER
      exp: 1
      cook_time: 100
      result:
        item: dripdrop:cooked_camel
        amount: 1

### Is your feature request related to a problem?

just inconvenient sometimes

### Describe alternatives you've considered

Maybe add an option: 'smoker_recipe:true' and ‘blast_recipe:true’ and automatically create the same recipe but half of the cook_time.

**Comment by LoneDev6** [comment]
It would be very confusing for people to configure it like that.
The current method is easier to understand.
