### ISSUE TITLE
Resource pack will be download repeated

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#129]
I use custom resource pack (depend on default pack just add some disc). 
When player first join, they will download resource pack twice; When player exit server and rejoin, nothing wrong but when player exit server, close game and rejoin, they will be ask for download resource pack again.
Version: 2.0.9

**Comment by LoneDev6** [comment]
Download or apply?
I mean, will the user see the download progress with percentage or only the red bar?

If they see only the red bar it's normal, it's not download, it's applying the pack.
If they always see the download percentage it's not normal and it's downloading it everytime.

Let me know

**Comment by R-Josef** [comment]
it is download percentage.

**Comment by LoneDev6** [comment]
> 
> 
> it is download percentage.

Can you contact me via private message on SpigotMC and send me your config.yml?
Thanks!

**Comment by RustyDagger** [comment]
i too am noticing this on my test server despite making no changes to the pack when I leave and join I am again promted to click the download and install button. its acting like the hash is not set.

**Comment by spathizilla** [comment]
Also seen this a few times but usually only on the first connect of the day.

**Comment by RustyDagger** [comment]
im self hosting and the plugin never seems to save any thing inside its data.yml its always blank every time I look at it. does it auto fill this or is it something we ment to do by hand?

**Comment by LoneDev6** [comment]
This should be fixed in new 2.0.11 update because I added a command: /iazip

this command will update the pack.zip instead of doing that on every server restart, which has no sense if you didn't change anything, no need to regen it everytime. I hope it's clear.

Reopen this issue if it's not fixed
