### ISSUE TITLE
[Suggestion] Add plan to deal with v1's items and furnitures

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#130]
Hello author, I updated itemadder v1 to v2. But now, two kind of v1 old hammer can not be used, All of the old machines and furnitures's texture was lost, and the left block from old furniture can not be broken currently. Will you find a way to deal with these old furnitures? Maybe auto destroy them or change them to new version?

**Comment by LoneDev6** [comment]
Please contact me via private message on SpigotMC and send me screenshots of the problem.
Thanks
