### ISSUE TITLE
ItemsAdder Block Drop amount

### ISSUE THREAD

**Issue by MelleVM** [LoneDev6/ItemsAdder#134]
When i break a custom block with a configured loot it will only drop 1 of that specific loot, even when min_amount is set to 2 or more.

example:
    ruby_ore:
      type: itemsadder:ruby_ore
      items:
        ruby:
          item: itemsadder:ruby
          min_amount: 3
          max_amount: 5
          chance: 100

**Comment by LoneDev6** [comment]
thanks!
fixed, i will post the update today/tomorrow
