### ISSUE TITLE
Renamed items doesn't work on recipes

### ISSUE THREAD

**Issue by xdec0de** [LoneDev6/ItemsAdder#135]
Version: Paper 1.15.2 (165)

![2020-04-13_17 04 18](https://user-images.githubusercontent.com/63256529/79131555-15635d80-7da9-11ea-89d5-745198cd3091.png)

![2020-04-13_17 04 31](https://user-images.githubusercontent.com/63256529/79131573-1ac0a800-7da9-11ea-97b9-1924d204a973.png)

**Comment by LoneDev6** [comment]
Should be fixed in next update 2.0.10.
I will publish it today.
Reopen this issue if it's not fixed, thanks!
