### ISSUE TITLE
[Suggestion] Vehicle Fuel info in bossbar

### ISSUE THREAD

**Issue by D3nied** [LoneDev6/ItemsAdder#139]
**Is your feature request related to a problem? Please describe.**
The fuel info and the huds both use actionbar to display

**Describe the solution you'd like**
Perhaps you can change where the fuel is displayed like in bossbar/scoreboard

**Comment by LoneDev6** [comment]
That's a good idea, I'm going to implement this in next update, thanks! 2.0.11

Maybe in the future I will add an option to make it shown as a custom HUD, but I don't know because someone doesn't like custom huds and prefer vanilla.
