### ISSUE TITLE
[BUG] Repair Custom sword with other sword if you do a little tricky thing

### ISSUE THREAD

**Issue by D3nied** [LoneDev6/ItemsAdder#140]
**Describe the bug**
So if i put a custom sword into anvil and a diamond sword for example the result will be canceld but not fast enough

if you spam a key to rename item and spawm left klick to drag the repaird sword out of the anvil it will work after a while

https://streamable.com/u0ddi6

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: Vanilla(with optifine 1.15.2)
 - Plugin version: 2.0.10

My idea is if there is a diamond sword in the second slot you cant event put the custom sword in the first stot of anvil or if you custom sword is in the first slot you cant put the diamond sword in the second slot

**Comment by LoneDev6** [comment]
No errors in console?

**Comment by LoneDev6** [comment]
fixed in 2.0.11, reopen this issue if after update you still have problems
