### ISSUE TITLE
[BUG] Could not pass event PrepareItemCraftEvent to ItemsAdder v2.0.10

### ISSUE THREAD

**Issue by RustyDagger** [LoneDev6/ItemsAdder#141]
**Describe the bug**
placing ANY item in the players 2x2 crafting grid generates the error. and allows custom items such as RUBY to be used as vanilla items eg iron trap doors. or weighted pressure plates.

**To Reproduce**
1. open inventory
2. place item in 2x2 crafting grid
3. see error.

[latest.log](https://github.com/LoneDev6/ItemsAdder/files/4484772/latest.log)

**Expected behavior**
Not spam console with a million lines or garbage :) and prevent IA items being used as vanilla items.

**Screenshots**
Not needed I hope,

**Info (please complete the following information):**
 - Server version: paper 1.15.2 Build 184
 - Client version: vanilla 1.15.2
 - Plugin version: 2.0.10

**Additional context**
This is a fresh install only running the plugins the new install told me to it is a local dev server using self hosting for the pack. ( im sure you could of got most that from the log file. )

**Comment by LoneDev6** [comment]
Fixed in 2.0.11, reopen this issue if after update you still have problems. I will post the update today.
Thanks for the report.
