### ISSUE TITLE
[BUG] Server crashes when people use a plane

### ISSUE THREAD

**Issue by imparium-de** [LoneDev6/ItemsAdder#144]
**Describe the bug**
The server recently starts to crash after a while when people use a plane to explore the map. 

**To Reproduce**
1. Use a plane
2. Fly around for a while
3. The server crashes

**Expected behavior**
The server shouldn't crash

**Info (please complete the following information):**
 - Server version: Paper 1.15.2
 - Client version: Vanilla 1.15.2
 - Plugin version: 2.0.10

**Additional context**
Console output: https://pastebin.com/KAd2SKkM
Crashlog: https://pastebin.com/P33p9diP

**Comment by imparium-de** [comment]
We did some more research on the issue and it seems like your .nbt files for those specific chunks are corrupted. The `r.21.95.nbt` is definitely having problems as we can't open the file with "NBTExplorer". We hope this gives you some more insight on the actual problem.
Download to a few .nbt files: https://send.firefox.com/download/7a6067460c9242a1/#FWHU46gbZHyWFR4Isaw11w

**Comment by LoneDev6** [comment]
Fixed in 2.0.11, reopen this issue if after update you still have problems. I will post the update today.
Thanks for the report.

Can happen when a player is exploring the world at high speed and causes concurrency on saving data on region files
