### ISSUE TITLE
[BUG] Hammer does not reduce the durability value.

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#145]
**Describe the bug**
When player broke torch/scaffolding use hammer, the hammer won't reduce the durability.

**To Reproduce**
1. place a torch/scaffolding on where you wanna mine.
2. use hammer to broke the torch/scaffolding
3. torch/scaffolding and stone will drop, but the durability of hammer will not lost.

**Info (please complete the following information):**
 - Server version: tuinity 1.15.2
 - Client version: vanilla
 - Plugin version: 2.0.9

**Additional context**
After use the above method to mine a lot of stone, and then use this hammer to broke a stone, you will seen a negative durability value hammer.
![https://fengshuai.oss-cn-shenzhen.aliyuncs.com/%E5%9B%BE%E5%BA%8A/negative_durability_value_hammer.png](https://fengshuai.oss-cn-shenzhen.aliyuncs.com/%E5%9B%BE%E5%BA%8A/negative_durability_value_hammer.png)
If you use it again at this time, it will break.

**Comment by LoneDev6** [comment]
Fixed in 2.0.11, reopen this issue if after update you still have problems. I will post the update today.
Thanks for the report.
