### ISSUE TITLE
can't destroy table and other things in mc 1.14.3

### ISSUE THREAD

**Issue by JaHollYT** [LoneDev6/ItemsAdder#15]
Hey, i found a bug - you cant destroy a table or something else you place for decoration in the newest version 1.14.3 - hope you can fix it soon

Best Regards,
Jakob

**Comment by LoneDev6** [comment]
Please provide a video, thanks

**Comment by JaHollYT** [comment]
https://www.youtube.com/watch?v=UorJiCEfL1g&

with the Version 1.0.31 -- we using worldguard, towny and for the world multiverse core, but i checkt it also in a world where towny is disabled and no worldguard region is and it is not working to

**Comment by LoneDev6** [comment]
Mmhh I think there is another plugin interfering, can you destroy normal armorstands?
Thanks

**Comment by JaHollYT** [comment]
yeah, they are destroyable - i will research a bit and maybe it just works with the next update :)

**Comment by LoneDev6** [comment]
did you try the latest spigot version?

**Comment by JaHollYT** [comment]
Problem Solved!
It was an incompatibility with the Plugin Lootchest:
https://www.spigotmc.org/resources/lootchest.61564/

I dont know why, but for me and my Server it's no Problem, we just removed it.

Thanks for your support!

**Comment by Guarmanda** [comment]
Hello, lootchest is my plugin, someone said "please make compatibility with itemAdder", on my plugin page, then I looked further at itemadder pages, and after some clicks I fell here.
Lootchest protects invisible armorstands, may it is a problem?

**Comment by LoneDev6** [comment]
This Github issue report is from 2019, please open a new one and add more details to your report.
Thanks
