### ISSUE TITLE
[Suggestion] ItemsAdder overwrites all changes to Minecraft JSONs for other RPs

### ISSUE THREAD

**Issue by spathizilla** [LoneDev6/ItemsAdder#150]
As per https://github.com/LoneDev6/ItemsAdder/issues/56 - this method no longer works with IA2 as it overwrites the minecraft/models/item jsons each startup even with extract default off. 

I have tried remote hosting to avoid the overwrite but this results in a resource pack loading screen loop over and over.

Would be nice if we could combine other resource pack using plugins as with IA1

**Comment by RustyDagger** [comment]
heres an idea for you. inside storage it has a default pack saved. maybe try changing the item.json files inside that. Im sure it will break with every plugin update tho.

**Comment by spathizilla** [comment]
> 
> 
> heres an idea for you. inside storage it has a default pack saved. maybe try changing the item.json files inside that. Im sure it will break with every plugin update tho.

Considered trying that but assumed the plugin would hash the file to see if it needed updating with the plugin's version (since it is "default"). However, inside that file it only has the very base things pre plugin modification and the vast majority of items are missing.

**Comment by RustyDagger** [comment]
fair enough its not something id looked at a lot or had any knowledge of it was just that "an idea."

**Comment by LoneDev6** [comment]
Explain what you need to change in each .json file of vanilla Minecraft, so I know how to handle that.

Problem is that my plugin is generating Minecraft vanilla .json files to support custom items, but doesn't take in account that someone may want to edit them manually, to avoid issues.

**Comment by RustyDagger** [comment]
I dont know about spathizilla, But i for one would imagine other packs also wanting to assign custom model data making merging them impossible. as IA would want to undo those changes.

im having a similar issue with slimefun but thankfully slimefun has changeable custommodel data per item ( it has a file i can set it per item. )

Currently i'm in the process of making every item in slimefun inside IA so IA will generate all the json files for me. I can then open the cache of IA and read out the custommodel data of each item and set it inside the slimefun file.

to that end if spathizilla knew the base item and the custommodel data it needed to be it could be made inside IA and that way it would not be wiped from the file. setting any thing other than model data inside the json yep thats going to need something other than a hacky work around.

**Comment by spathizilla** [comment]
I am trying to support the Magic plugin's resource pack. I know in the previously linked issue that you said it can be done with adding custom model data 0. I don't know how well they allow you to change their data values in order to support inside IA itself.

**Comment by RustyDagger** [comment]
so the slimefun items im making inside IA are useless they are not craftable or dropped from any where they are only there for the sole purpose of having the Json file made with a number assigned for custom model data.

You could by hand adjust AI's cache for your fake magic items to assign the same Custom Model data that the magic plugin assigns,  If you have CMI plugin you can use /itemnbt to see the nbt data of the item your holding.

**Comment by spathizilla** [comment]
Perhaps a way to make this work is to have IA ignore anything with custom model data 0 so we can use the old method which doesn't use the custom model data methods. Anything needing to use custom model ids can be created inside IA like Rusty is doing or perhaps have a config setting where we can define other model ids that IA needs to ignore in the JSON files? Don't need to make it automatic, just make us set them in config?

**Comment by spathizilla** [comment]
> so the slimefun items im making inside IA 

Are you making them in their own item namespace? If so would love to get a copy since I was considering using Slimefun in future.

**Comment by LoneDev6** [comment]
Related to: https://github.com/LoneDev6/ItemsAdder/issues/310
