### ISSUE TITLE
[BUG] Shifted bars

### ISSUE THREAD

**Issue by Andrew99CZ** [LoneDev6/ItemsAdder#151]
**Describe the bug**
Hello, everything works fine for me except that thirst and mana bars are shifted. Can I somehow shift or at least turn off your thirst with the bar.

**To Reproduce**
Install plugin

**Screenshots**
https://ctrlv.cz/M5EU

**Info (please complete the following information):**
 - Server version: spigot1.15.2
 - Client version: 1.15.2
 - Plugin version: 2.0.10

**Additional context**
I putted off all plugins except Itemadder and ProtocolLib, IALib and LightAPI and it was still shifted.
In creative I see mana bar normal.

**Comment by LoneDev6** [comment]
Do you have any other resourcepack installed in your game?
Are you using optifine or a custom client?
can you ask a friend to join your server and see if they see them correctly or not?

**Comment by Andrew99CZ** [comment]
> Do you have any other resourcepack installed in your game?
> Are you using optifine or a custom client?
> can you ask a friend to join your server and see if they see them correctly or not?

I am restarted plugin and used default resource pack destination from you and it is same. 
I am using original minecraft launcher and friends have this bug too (they didnt use original launcher).

**Comment by LoneDev6** [comment]
Send me your Discord tag, I will contact you

**Comment by Andrew99CZ** [comment]
ɅƝĐƦƩШ#8139

**Comment by LoneDev6** [comment]
Related to errors downloading default_pack.zip file, probably network was blocking connection.
Fixed sending him a copy of default_pack.zip and pasting it into the cache folder manually.
