### ISSUE TITLE
[BUG] Server shut down

### ISSUE THREAD

**Issue by Andrew99CZ** [LoneDev6/ItemsAdder#152]
**Describe the bug**
When I fly and generate world faster, the server crashes and crashes right after restarting it. It will only work after I remove the Item adder from the plugin and then return it there.

**To Reproduce**
Fly and generate world faster.
Plugins:
![pluginy_pic](https://user-images.githubusercontent.com/63855329/79576760-11df1780-80c4-11ea-84a1-44af810f29de.PNG)

**Info:**
 - Server version: (spigot 1.15.2)
 - Client version: (1.15.2)
 - Plugin version: ( 2.0.10)

**Additional context**
First crashlog:
[crash-2020-04-17_15.43.11-server.txt](https://github.com/LoneDev6/ItemsAdder/files/4493363/crash-2020-04-17_15.43.11-server.txt)

After restart crashlog:
[crash-2020-04-17_15.45.36-server.txt](https://github.com/LoneDev6/ItemsAdder/files/4493366/crash-2020-04-17_15.45.36-server.txt)

**Comment by LoneDev6** [comment]
Thanks for the report: https://github.com/LoneDev6/ItemsAdder/issues/144
