### ISSUE TITLE
[BUG] Player can not see categories in ia menu.

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#155]
**Describe the bug**
Player can only see the "all" categorie in ia menu.

**To Reproduce**
1. Add `ia.user.ia` and `ia.user.ia.*` for all users
2. Open the menu as a default user
3. Can only see "all"

**Expected behavior**
Add other categories.

**Screenshots**
![categories](https://fengshuai.oss-cn-shenzhen.aliyuncs.com/%E5%9B%BE%E5%BA%8A/ia_categories.jpg)

**Info (please complete the following information):**
 - Server version: tuinity 1.15.2
 - Client version: vanllia 1.15.2
 - Plugin version: 2.0.12

**Comment by LoneDev6** [comment]
https://itemsadder.plugin.ga/plugin-usage/ia

give permission: `ia.menu.*`

**Comment by R-Josef** [comment]
thanks, it works now.
