### ISSUE TITLE
[BUG] Inventory 2x2 crafting window does not follow permissions or recipes

### ISSUE THREAD

**Issue by spathizilla** [LoneDev6/ItemsAdder#159]
**Description**
With 2.0.12 - Any ItemsAdder item can be used to gain the result of the vanilla item recipe. For example, coal nuggets and fossils are using the iron ingot as the underlying vanilla item. If you open the player inventory and place it in the 2x2 crafting slots you will get the iron nuggets. This also does not follow the permissions required for crafting. Have confirmed that 2.0.9 is not vulnerable to this issue (assuming it is due to the changes made in 2.0.10 again)

**How To Reproduce**
1. Spawn a coal nugget or fossil
2. Open player inventory
3. Place coal nugget or fossil into the 2x2 craft window
4. See Iron nuggets appear in the result window 

**Expected behavior**
This should at first not allow any result because of crafting permissions not being set.
Secondly the iron nuggets should not be displayed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/638845/79674291-835cba00-81d9-11ea-80cd-fdb395566adf.png)

**Info:**

CMI: 8.6.22.2 BungeeCord
Server version: Paper(185) 1.15.2-R0.1-SNAPSHOT
Vault version: 1.7.3-b

Plugin Information: ItemsAdder
- Version: 2.0.12
- Author(s): LoneDev, LoneDev
- Status: Enabled
- Depends: IALibs, ProtocolLib

**Comment by spathizilla** [comment]
This does **NOT** happen with 2.0.9

**Comment by RustyDagger** [comment]
Confirmed: 2x2 was broken in .10 with the changes,

 its stopped throwing errors in .11 and .12 but is still broken not respecting crafting. Quite frustrating as it poses some risk as economys dont allow for this kind of thing when setting prices. I guess one way to solve it would be to change the base item but whats an item that has no use in the 2x2.

**Comment by LoneDev6** [comment]
Thanks, should be fixed in next update.
I will publish the update later, reopen this issue if the problem is still there after 2.0.13
