### ISSUE TITLE
plugin won't work

### ISSUE THREAD

**Issue by vkaygaming** [LoneDev6/ItemsAdder#16]
when i do /pl the plugin shows up as red

**Comment by LoneDev6** [comment]
https://lonedev.gitbook.io/itemsadder/faq

**Comment by vkaygaming** [comment]
you can send me the faq all you want i already went through it all and it didn't help me at all

**Comment by LoneDev6** [comment]
You can contact me on my discord support server as this issue is not related to the plugin.
