### ISSUE TITLE
[BUG] Fossil can be used as iron ingot

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#161]
**Describe the bug**
Fossil can be used as iron ingot in 2*2 crafting grid

**To Reproduce**
1. Open inventory and put fossil into crafting grid
2. Then get 9 iron nugget

**Screenshots**
![fossil_to_iron_nugget](https://fengshuai.oss-cn-shenzhen.aliyuncs.com/%E5%9B%BE%E5%BA%8A/fossil_to_iron_nugget.png)

**Info (please complete the following information):**
 - Server version: tuinity 1.15.2
 - Client version: vanllia
 - Plugin version: 2.0.12

**Comment by R-Josef** [comment]
this is a same problem that [issues 159](https://github.com/LoneDev6/ItemsAdder/issues/159) described

**Comment by LoneDev6** [comment]
Thanks, should be fixed in next update.
I will publish the update later, reopen this issue if the problem is still there after 2.0.13
