### ISSUE TITLE
[BUG] Client crashes when loading a too large "emoji" on a sign

### ISSUE THREAD

**Issue by Golshr** [LoneDev6/ItemsAdder#162]
**Describe the bug**
I try to use large png files as emojis that I put on signs to make new paintings that doesn't use entities. Problem is that when png file is too big, client crashes when putting the emoji tag on a sign (the :emoji: thing). But when you reconnect to the server, the "painting" is here with the right size.

**To Reproduce**
1. Create a large png file (max seems to be 250*250px)
2. Declare it as an emoji
3. Put the emoji tag on a sign

**Expected behavior**
The png file shows normally.

**Info (please complete the following information):**
 - Server version: Spigot 1.15.2
 - Client version: Vanilla 1.15.2
 - Plugin version: 2.0.9

**Comment by LoneDev6** [comment]
It's a Minecraft bug, you should try to report it to Mojang, but I doubt they'll fix it.
I cannot fix that sadly, I hoped no one would ever tried to use big emojis on signs as I found this bug while I tried to retexture signs using that method.
