### ISSUE TITLE
[BUG]  Exception while reading a NBT File!

### ISSUE THREAD

**Issue by a7ssan** [LoneDev6/ItemsAdder#164]
**Describe the bug**
CRASH REPORT FILE: https://pastebin.com/1F4j588z
FULL SERVER LOG: https://pastebin.com/tkRfrthE

**--To Reproduce--**

**Expected behavior**
When i teleport to my friend server crash.

**Screenshots**
Add me Discord if want join screenshare.

**Info:**
 - Server version: (BeeSpigot 1.15.2)
 - Client version: (Vanilla 1.15.2)
 - Plugin version: (2.0.12)

**Additional context**
Some blocks in world not loading correctly and show purple blocks.

**Comment by LoneDev6** [comment]
https://github.com/LoneDev6/ItemsAdder/issues/127
Related to NBTApi not thread safe problem, will fix in next update

**Comment by LoneDev6** [comment]
Issue should be fixed in the upcoming release of IA
https://github.com/tr7zw/Item-NBT-API/commit/ca2bb4d0b377e6e623e8c9ec6107cbf1d7ae213a
