### ISSUE TITLE
"Null" Action Bar Message (when Manabar is disabled?)

### ISSUE THREAD

**Issue by Gixr** [LoneDev6/ItemsAdder#167]
I just installed ItemsAdder and noticed that i get randomly "null" messages in the actionbar i just disabled the mana bar and did some testings 
Results:
Mana + Water disabled -> Null
Mana disabled + Water enabled -> Null
Water disabled -> Mana enabled -> no Null
Mana + Water enabled -> no Null

so it most likely has something to do with the Mana bar but im not 100% sure. 
the Null Messages looks like this: [https://media.discordapp.net/attachments/533413171403292712/701958311637024788/2020-04-21_02.48.34.png?width=1204&height=677](url)

**Comment by LoneDev6** [comment]
Should be fixed in latest updates of the plugin, i will publish it today.
Reopen this issue if it will still happen, thanks!
