### ISSUE TITLE
[Suggestion] API Addition - Play Sound

### ISSUE THREAD

**Issue by brettsaunders21** [LoneDev6/ItemsAdder#170]
Add a new function to the developer API to allow custom sound files to be played. 
This would allow developers creating plugins with ItemsAdder as a dependency to play custom sounds in many situations.

**Comment by LoneDev6** [comment]
You can do it easly with Spigot builtin function:
`player.playSound(player.getLocation(), "itemsadder:item.revolver.shot", SoundCategory.MASTER, 1, 1);`
