### ISSUE TITLE
[BUG] Emojis in chat messages with VentureChat do not display

### ISSUE THREAD

**Issue by spathizilla** [LoneDev6/ItemsAdder#173]
**Describe the bug**
When using venturechat and the emoji codes (like :heart:) it fails to change into the required unicode character to display the emoji. If you send the unicode character directly it will display correctly. Chat emoji is turned on in config.

**To Reproduce**
Install IA and Venturechat
Type an emoji trigger like :heart: 

**Expected behavior**
Emoji should be displayed in chat

**Info (please complete the following information):**
ItemsAdder Version: 2.0.13
VentureChat Version: 2.18.4
Server Version: Paper(208) 1.15.2-R0.1-SNAPSHOT

**Comment by sam33256** [comment]
I've had the same issue, does ver 2.0.9 work as it should? https://github.com/LoneDev6/ItemsAdder/issues/181

**Comment by LoneDev6** [comment]
Duplicate
