### ISSUE TITLE
See unused textures

### ISSUE THREAD

**Issue by srnyx** [LoneDev6/ItemsAdder#1733]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

srnyx#0001

### Describe the solution you'd like

When the plugin is reloaded, send messages about textures that aren't being used.
I'm pretty sure there are either a lot or at least a few unused in the **default/example** packs that are added when you first install the plugin.

### Is your feature request related to a problem?

Unused textures make the pack bigger than necessary.

### Describe alternatives you've considered

Manually going through all ~500 items/blocks/emojis/emotes/etc... to find unused textures. Potentially risking removing textures that **are** used.

**Comment by LoneDev6** [comment]
> I'm pretty sure there are either a lot or at least a few unused in the default/example packs that are added when you first install the plugin.
