### ISSUE TITLE
[BUG] trade gui's name can not change

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#175]
**Describe the bug**
trade gui's name can not change

**To Reproduce**
1. change it's name in block.yml
2. enter command "/iareload"
3. enter command "/ia" in block gui take a restoration table
4. no change

**Expected behavior**
tab gui's name is change

**Screenshots**
![註解 2020-04-25 111152](https://user-images.githubusercontent.com/50344708/80270059-985cb000-86e7-11ea-9910-49a4a8d39680.png)
![註解 2020-04-25 111141](https://user-images.githubusercontent.com/50344708/80270061-9abf0a00-86e7-11ea-98b9-9adc783d4921.png)
![註解 2020-04-25 112950](https://user-images.githubusercontent.com/50344708/80270162-5122ef00-86e8-11ea-9d87-16249d970f24.png)
![註解 2020-04-25 113038](https://user-images.githubusercontent.com/50344708/80270164-541ddf80-86e8-11ea-8dc7-92345ac6f780.png)

**Info (please complete the following information):**
 - Server version: spigot 1.15.2
 - Client version: fabric 1.15.2 with WWE
 - Plugin version: 2.0.13

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/80516593-fc030980-8983-11ea-90fd-df17bb55552d.png)
Please use "title" not "name", thanks!
