### ISSUE TITLE
Emoji placeholder does not display correctly in font-image-chat-hover

### ISSUE THREAD

**Issue by nhanledev** [LoneDev6/ItemsAdder#1754]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

The description when hover on font image (emoji) in chat does not display the placeholder correctly.

Expect: 
- Showing {placeholder} as :my_emoji: as usage should be showed as plain text.

Current:
- Showing {placeholder} as the font image itself.

![image](https://user-images.githubusercontent.com/28459250/172036026-2cab9e1b-a919-499d-a726-80e4ace082ab.png)

### Steps to reproduce the issue

1. Make a font image, eg `:my_emoji:`
2. Grant permission `ia.user.image.use.*` to default group
3. Type `:my_emoji:` in chat
4. Use the mouse to read the hover description of the emoji

### Server version

Paper 1.17.1 Build 409

### ItemsAdder Version

ItemAdder 3.2.0

### ProtocolLib Version

ProtocolLib 4.8.0

### LoneLibs Version

LoneLibs 1.0.18

### LightAPI Version (optional)

LightAPI 5.2.0

**Comment by LoneDev6** [comment]
Strange, it works fine for me

![immagine](https://user-images.githubusercontent.com/27242001/174810084-0c053db8-6e4b-4632-a872-5e40da6ba4ea.png)
