### ISSUE TITLE
[BUG] copy custom block have bug

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#176]
**Describe the bug**
copy custom block have bug

**To Reproduce**
1. place a custom block 
2. Click with Middle key on custom block x3
3. copy a brown mushroom block not custom block

**Expected behavior**
only copy custom block not a brown mushroom block

**Screenshots**
https://youtu.be/o6m4Bneu1SI  <--- this is a video to Demo bug

**Info (please complete the following information):**
 - Server version: spigot 1.15.2
 - Client version: fabric 1.15.2 with WWE
 - Plugin version: 2.0.13

**Comment by LoneDev6** [comment]
Thanks for the report I will fix that as soon as possible, I hope to find a way because it's not really easy

**Comment by LoneDev6** [comment]
let me know if update 2.0.15 will fix the issue. I'll publish it today.
Reopen this issue if the problem still persist.
Thanks!
