### ISSUE TITLE
Citizens not working correctly when mounting entity

### ISSUE THREAD

**Issue by Toinetoine1** [LoneDev6/ItemsAdder#1775]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

I use citizens because I need to create a custom and customisable entity. It must allow control of the entity when mounted (I don't use the itemsadder system directly because the behaviour is not what I want).
The problem is that it doesn't work. When I run my code, I mount the sheep and then I go back down. (I upload a video to show you what happenned behind)

### Steps to reproduce the issue

Here is my code:

        NPC npc = CitizensAPI.getNPCRegistry().createNPC(EntityType.SHEEP, Integer.toHexString(ThreadLocalRandom.current().nextInt()));

        npc.addTrait(WynControllableTrait.class);
        npc.setProtected(false);

        npc.spawn(sheepLocation);
        
        //Must use this because there is no alternative using the Itemsadder api directly
        Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "iaentity citizens "+npc.getId()+" model mysheep:boardingtest");

        CustomEntity.byAlreadySpawned(npc.getEntity()).addPassenger(shooter);

### Server version

Current: git-Purpur-1623 (MC: 1.18.2)*
Previous: git-Paper-339 (MC: 1.18.2)
Download the new version at: https://purpurmc.org/downloads

### ItemsAdder Version

ItemsAdder version 3.2.0b-beta4

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.18

### Screenshots/Videos (you can drag and drop files or paste links)

https://user-images.githubusercontent.com/45132539/174098448-94a2ac57-19ce-4d80-bddb-f4c7161a0c4a.mp4

**Comment by LoneDev6** [comment]
May I know why did you close it?

**Comment by Toinetoine1** [comment]
The fact that the plugin is not open-source. The API is also very small, which constrains me a lot.
A really nice change for the devs would be to make the project open-source but let the plugin be paid for by those who want support on the plugin.

**Comment by LoneDev6** [comment]
> A really nice change for the devs would be to make the project open-source but let the plugin be paid for by those who want support on the plugin.

This would mean the death of ItemsAdder, I sadly can't make the plugin opensource as people would simply copy and paste the code and 90% of people won't buy it.

Anyway you didn't answer my question: why did you close the issue report?
Be more specific, I'll fix the issue if enough information is shared.
If you need some API functionality request it like everyone else is doing. I cannot add features if I don't know what you need, please think about that.

**Comment by Toinetoine1** [comment]
Firstly, using Citizens for my problem was not a good solution.

Features that would be interesting:
- better management of mounts (to be able to create your own controller). This would solve my problem
- Be able to add nametags on entities

A big addition would be to be able to create your own NMS entity. This would allow to have fully customisable behaviours.

**Comment by LoneDev6** [comment]
>  (to be able to create your own controller)

What do you mean exactly?
I have no idea of what you're trying to do.

Right now you can create two types of controllers: walking or flying.
You just have to set entity type to the vanilla entity type which has the correct controller you want.
For example PHANTON if you want to fly, ZOMBIE if you want to walk.

> Be able to add nametags on entities

Not currently possible, might be added in the future.


> A big addition would be to be able to create your own NMS entity. This would allow to have fully customisable behaviours.

You might request a "convert" method to convert any entity to a custom modeled entity, this is what you need.
https://github.com/PluginBugs/Issues-ItemsAdder/issues/new/choose

**Comment by Toinetoine1** [comment]
> Right now you can create two types of controllers: walking or flying.
Yes, but i can't create my own controllers. For example, if i want to create a controller that force the player to stay on the entity, i can't.
