### ISSUE TITLE
[BUG] can not use type:ZOMBIE_PIGMAN

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#178]
**Describe the bug**
can not use type:ZOMBIE_PIGMAN

**To Reproduce**
1. write type:ZOMBIE_PIGMAN in loot table
2. enter command "/iareload"
3. See error

**Expected behavior**
zombie pigman can drop custom item

**Screenshots**
![註解 2020-04-25 211249](https://user-images.githubusercontent.com/50344708/80280855-886dbc00-8739-11ea-8588-51ee00cc540e.png)
![註解 2020-04-25 211240](https://user-images.githubusercontent.com/50344708/80280857-8ad01600-8739-11ea-9600-25f8aa6f66bf.png)

**Info (please complete the following information):**
 - Server version: spigot 1.15.2
 - Client version: fabric 1.15.2 with WWE
 - Plugin version: 2.0.13

**Additional context**
[error report.txt](https://github.com/LoneDev6/ItemsAdder/files/4532991/error.report.txt)

**Comment by LoneDev6** [comment]
[PIG_ZOMBIE](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html#PIG_ZOMBIE)
