### ISSUE TITLE
[BUG] Mineral blocks become mushrooms.

### ISSUE THREAD

**Issue by Deathroner** [LoneDev6/ItemsAdder#179]
**Describe the bug**
Mineral blocks become mushrooms by breaking or hitting the sides.

**To Reproduce**
1. Go to "Any mineral formed into a chunk"
2. Click on "The minerals"
4. See error "They can disappear or transform into mushrooms"

**Expected behavior**
It must come out of the mineral, but the block disappears or becomes a mushroom.

**Screenshots**
Video: [https://www.youtube.com/watch?v=o7lhKj6Z1pA](url)

**Info:**
 - Server version: PaperMC 1.15.2
 - Client version: Vanilla 1.15.2
 - Plugin version: 2.0.13

**Additional context**
There is another mistake with minerals when putting them in the oven, but I will comment later.

**Comment by LoneDev6** [comment]
Hello, do you know if these chunks where generated with version of itemadder < 2.0.13?
Maybe 2.0.11-2.0.12?
Previous versions had a bug on saving blocks which I fixed in 2.0.13, so ores spawned in new chunks won't be bugged anymore.


Please let me know, thanks a lot

**Comment by Deathroner** [comment]
The truth is that you just understand the plugin in version 2.0.13

**Comment by LoneDev6** [comment]
> 
> 
> The truth is that I just bought the plugin in version 2.0.13

Interesting... well that's strange, does it happens for every custom block generated underground?
Did you try travelling on new generated chunks?

Any error in console? Can you check your old logs of when these chunks got generated? It's really important to help me understand, thanks

**Comment by LoneDev6** [comment]
@Deathroner did that happen again? I didn't receive any news, thanks

**Comment by 100petr** [comment]
IA 2.0.21
![2020-05-10_20 58 00](https://user-images.githubusercontent.com/29830635/81507952-12548200-9301-11ea-8d9e-5db40d468976.png)
![2020-05-10_20 58 09](https://user-images.githubusercontent.com/29830635/81507953-141e4580-9301-11ea-8c3f-120bd795e025.png)

It's probably an older chunk

**Comment by 100petr** [comment]
After destroying the blocks around, it change into a mushroom.
![2020-05-10_21 13 21](https://user-images.githubusercontent.com/29830635/81508208-226d6100-9303-11ea-8af8-03e5c1a8d5fe.png)
![2020-05-10_21 13 27](https://user-images.githubusercontent.com/29830635/81508209-24cfbb00-9303-11ea-9ed2-a4eef3b42fc8.png)

**Comment by LoneDev6** [comment]
- did you delete your itemsadder folder after you generated the chunks? it's important not to delete the "storage" folder of itemsadder because it contains world data
- are these old chunks from previous 2.0.20 versions?
- can you verify that doesn't happen in new chunks?

thanks

**Comment by 100petr** [comment]
I didn't delete the folder. These are probably older chunks (previous 2.0.20). I haven't found it in the new chunks.

**Comment by LoneDev6** [comment]
> 
> 
> I didn't delete the folder. These are probably older chunks (previous 2.0.20). I haven't found it in the new chunks. I found a dirt gold ore nearby and that didn't change.

Perfect, it's surely due to an old bug of the block saving, it was fixed in some of the latest updates
