### ISSUE TITLE
/iareload problem

### ISSUE THREAD

**Issue by Padlick01** [LoneDev6/ItemsAdder#18]
When I've edited names from items, and did /iareload, 
every player gets this error spam:
![image](https://user-images.githubusercontent.com/44584223/61131692-26014300-a4ba-11e9-9244-1d3b68cc4708.png)

But when we do /ia, every Item is showed correctly, so resourcepack works anyway.

Also, when we shutdown the server, this error appears:
https://pastebin.com/XBDGDQHD

**Comment by LoneDev6** [comment]
It's impossible that this issue is related to your edit.
Please share your edited items .yml files and config.yml file via private chat on discord, i'll see what's the issue.

**Comment by LoneDev6** [comment]
Fixed in latest update, i'll publish in some minutes
