### ISSUE TITLE
[BUG] Emoji's not working in DeluxeChat

### ISSUE THREAD

**Issue by sam33256** [LoneDev6/ItemsAdder#181]
**Describe the bug**
ItemsAdder doesn't replace a message like :emote: with the proper Unicode. No error in the console and no error for the player itself.

**To Reproduce**
Install DeluxeChat and IA and try to use an emote.

**Expected behavior**
The message should have replaced with the Unicode to display the emote.

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: optifine 1.15.2
 - Plugin version: 2.0.13

**Additional context**
The issue occurred after the 2.0.10 update.

**Comment by LoneDev6** [comment]
Please @spathizilla and @sam33256 let me know if update 2.0.14 will fix the issue. I'll publish it today.
Reopen this issue if the problem still persist.
Thanks!
