### ISSUE TITLE
[BUG] Re-use Mysterious Amulets

### ISSUE THREAD

**Issue by alejandro0256** [LoneDev6/ItemsAdder#184]
**Describe the bug**
Mysterious amulets can be reused by saving them for later after use it and stacking it with other amulets with the same uses left.
For example if we stack 3 amulets with 0 uses left and we use them we lose one amulet but the next starts again with 20 uses left.

**To Reproduce**
1. Get a few used mysterious amulets with the same uses left
2. Stack the mysterious amulets
3. Spend all the uses left of the first mysterious amulet

**Expected behavior**
It should avoid to stack used mysterious amulets or fix the issue by other way

**Screenshots**
https://imgur.com/a/O8SKHbn

**Info:**
 - Server version: paper 1.15.2 (Build: 183)
 - Client version: minecraft Optifine
 - Plugin version: 2.0.13

**Comment by LoneDev6** [comment]
Thanks for the report, I will investigate on this and find the best way to fix that problem.
Surely on 2.0.15 update

**Comment by LoneDev6** [comment]
Reopen this issue if in the next update is not fixed, thanks!
