### ISSUE TITLE
[BUG] Getting diamond or other minerals by smelting ores that aren't supposed to be smelted

### ISSUE THREAD

**Issue by alejandro0256** [LoneDev6/ItemsAdder#185]
**Describe the bug**
Wen you smelt ruby, spinel, turquoise, aqua aura or amethyst you get the result of smelting the vanilla item.
For example you can get a diamond by smelting turquoise ore.

**To Reproduce**
1. Smelt in a furnace an ore that's not supposed to be smelted like the Ruby Ore

**Expected behavior**
It shouldn't be able to smelting any of this ores.

**Screenshots**
https://imgur.com/a/9hxwyob

**Info:**
 - Server version: paper 1.15.2 (Build: 183)
 - Client version: minecraft Optifine
 - Plugin version: 2.0.13

**Comment by Deathroner** [comment]
I confirm, the same thing happens to me

**Comment by D3nied** [comment]
https://github.com/LoneDev6/ItemsAdder/issues/177#issuecomment-619637561
LoneDev already wrote that he is going to fix this

**Comment by LoneDev6** [comment]
Duplicate https://github.com/LoneDev6/ItemsAdder/issues/177
