### ISSUE TITLE
[Suggestion] Custom GUIs creation with API

### ISSUE THREAD

**Issue by Golshr** [LoneDev6/ItemsAdder#187]
**Is your feature request related to a problem? Please describe.**
I want to create a custom GUI with a with custom visual. 

**Describe the solution you'd like**
I just want to replace something like this : 
`Bukkit.createInventory(InventoryHolder inventoryHandler, int places, String name);`
to something like this : 
`ItemsAdder.createInventory(InventoryHolder inventoryHandler, int places, String name, String guiName);`

**Describe alternatives you've considered**
I tried to change the name of my inventory and adding the unicode code of the gui into it but it wasn't well positioned, I don't know how you are positioning it well and I didn't get any further yet.

**Comment by LoneDev6** [comment]
Really cool idea, I will definitely work on this on the freetime as right now I'm flooded with support requests.

I will also write detailed tutorials on how to manage them and create GUIs.
I was working on a sample plugin that shows RAM and CPU usage onscreen, this is a WIP of RAM indicator:
![image](https://user-images.githubusercontent.com/27242001/80529791-48584480-8998-11ea-92f1-84e61194c4b7.png)
