### ISSUE TITLE
[BUG] TownyAdvanced and ItemsAdder

### ISSUE THREAD

**Issue by Deathroner** [LoneDev6/ItemsAdder#189]
**My server uses TownyAdvanced, I tried on a local server adding each plugin from my main server, until I got to Towny and discovered that this was the one that generated an error without reporting anything in the console.**

- Fuel messages do not appear
- It does not allow you to enter the vehicle, and then does not allow anything to be done; the chat hangs with the message "could not send the message".

**Evidence**
**With TownyAdvanced:** [https://www.youtube.com/watch?v=FBkit4ypr1c](url)
**Without Towny**: [https://www.youtube.com/watch?v=RJ6VcHXPBnU](url)

**Info (please complete the following information):**
 - Server version: PaperMC 1.15.2
 - Client version: Vanilla 1.15.2
 - Plugin version: Tested with 2.0.13 and new 2.0.14

**Additional context**
From what I've noticed, the problem of blocking the user to interact occurs only within a city.
But it does not show the fuel information neither inside nor outside the city.

**Comment by spathizilla** [comment]
This is caused by towny blocking interaction for outsiders with armorstands (which is what holds the vehicle).. probably needs Towny to do something about it really or override Towny. 

Alternatively, if IA is still made aware of the event it could ignore Towny cancelling the event - but this could cause extra load since IA would need to still process all cancelled interactions with armorstands to see whether it is a vehicle.

**Comment by LoneDev6** [comment]
Towny is doing something strange, I don't know how to fix that, I'm just spawning an armorstand and when you rightclick it I set you as passenger of the armorstand...
I really have no clue on wtf is towny doing, can you please send this conversation to towny devs?
Thanks

**Comment by Deathroner** [comment]
Now I'll send a message to Towny.
LoneDev, please do not close the ticket here to answer what they tell me ^^

**Comment by spathizilla** [comment]
> Towny is doing something strange with vehicles/armorstands, I don't know how to fix that, I'm just spawning an armorstand and when you rightclick it I set you as passenger of the armorstand...

At a guess, Towny is monitoring all interactions inside their regions and matching the config settings to entities. In this case armor stands are protected inside towny regions without exception so unless you have permission to mess with them, it cancels the event.

**Comment by LlmDl** [comment]
Towny operates on the PlayerInteractAtEntityEvent with `priority = EventPriority.HIGH, ignoreCancelled = true`

IA needs to operate on HIGHEST to override Towny.

**Comment by LoneDev6** [comment]
> 
> 
> Towny operates on the PlayerInteractAtEntityEvent with `priority = EventPriority.HIGH, ignoreCancelled = true`
> 
> IA needs to operate on HIGHEST to override Towny.

That's already what I do, so I have no clue.
![image](https://user-images.githubusercontent.com/27242001/80700004-48ae2800-8add-11ea-8304-be71251786b0.png)

I think towny is removing entities or something similar because it's like the armorstand/slime disappears from the server but not from the client, that's probably why player is bugged and can't write chat messages

**Comment by LlmDl** [comment]
Towny does not remove armor stands, it will remove slimes if they are part of the town_mob_removal list.

**Comment by LoneDev6** [comment]
MMhhh interesting, well the strange thing is that if I put some breakpoins in the code on where IA is sending bossbar it does get executed but player sees no bossbar (bossbar is used to show how much fuel is getting loaded into the vehicle on interaction using coal), it's strange.
It's like something is interfering but has no sense because the event is called correctly

**Comment by LoneDev6** [comment]
> 
> 
> MMhhh interesting, well the strange thing is that if I put some breakpoins in the code on where IA is sending bossbar it does get executed but player sees no bossbar (bossbar is used to show how much fuel is getting loaded into the vehicle on interaction using coal), it's strange.
> It's like something is interfering but has no sense because the event is called correctly
@LlmDl do you have anything in mind on what could be the issue cause?

**Comment by LlmDl** [comment]
Your plugin is closed-source and premium, so no.

**Comment by LoneDev6** [comment]
@Deathroner @spathizilla 
Please can you try setting this in config.yml of towny?
`  town_mob_removal_entities: Monster,Flying,Shulker,SkeletonHorse,ZombieHorse`
seems to fix the issue, please confirm

**Comment by Deathroner** [comment]
![image](https://user-images.githubusercontent.com/62408689/80999446-b7a7bb80-8e12-11ea-8a28-22ff0118d869.png)

In fact, that's how I had it configured and the problem persists :(

**Comment by LoneDev6** [comment]
Remove the Slime as I did in my config

**Comment by LoneDev6** [comment]
@Deathroner 
Remove the Slime as I did in my config

Let me know

**Comment by Deathroner** [comment]
We switch to the plugin "Residence" and it continues to happen.
But, the following message appeared on the console:

`09.05 04:00:32 [Server] ERROR POI data mismatch: never registered at BlockPosition{x=-4801, y=64, z=2432}
09.05 04:00:38 [Server] INFO Attempt to teleport dead player Deathroner_ restricted
09.05 04:00:38 [Server] INFO Attempt to teleport dead player Deathroner_ restricted`

I am in version 2.0.19
It happens to me also in all the previous versions.

But the important thing is that the console gave a message this time. Can it be fixed?

**Comment by LoneDev6** [comment]
Is Residence based on Towny's sourcecode? Seems impossible to me that it's the same exact problem (chat problem and invisible player after riding the vehicle).
Did you try to set the config settings I sent you? Maybe there is something similar regards slime in Residence

**Comment by Deathroner** [comment]
Residence is different from towny, very different.
I don't see configuration that has to do with "ArmorStand"

-.-

**Comment by LoneDev6** [comment]
As I asked before:
1. is this the same problem? (chat problem and invisible player after riding the vehicle)
2. Did you try to set the config settings I sent you? (in towny)
3. can you open another issue regards Residence and provide updated videos? I cannot fix anything if the info provided is not valid

**Comment by Deathroner** [comment]
I will open a new Issue for this ^^.
