### ISSUE TITLE
strange behaviour from diamond hammer

### ISSUE THREAD

**Issue by Padlick01** [LoneDev6/ItemsAdder#19]
My users found out, that the diamond hammer got an strange behaviour since some versions.
Here's an video where you can see it:
https://cdn.discordapp.com/attachments/406794998638706699/599581864675639348/Minecraft_1.14.3_2019-07-13_14-43-40.mp4

My config part for diamond hammer:
![image](https://user-images.githubusercontent.com/44584223/61172166-21ec2880-a581-11e9-8ad6-00e2c493f3a8.png)

**Comment by Padlick01** [comment]
Never mind. It comes from our anti-cheat.

**Comment by LoneDev6** [comment]
Can I know the name of the anticheat and which option you disabled in the anticheat to fix this?
Thanks!

**Comment by Padlick01** [comment]
We use Matrix Anticheat. 
https://www.spigotmc.org/resources/matrix-anticheat-hack-killaura-blocker-machine-learning-1-8-1-12-1-13-1-14.64635/

The Check we disabled to let it work again was the block check. (Fastplace/Fastbreak)
