### ISSUE TITLE
[BUG] Damage lore isn't hidden when unbreakable

### ISSUE THREAD

**Issue by badhaloninja** [LoneDev6/ItemsAdder#191]
**Describe the bug**
The damage values for items that have the unbreakable tag are still shown in the lore.

**To Reproduce**
- Add `unbreakable: true` to the `durability` section
- Optional: Add the `HIDE_ATTRIBUTES` flag to the `item_flags` section

**Expected behavior**
With advanced tool tips showing, durability is hidden when an item has the unbreakable tag, however the plugin still adds the durability to the lore when the custom item has the unbreakable tag. 

**Screenshots**
Diamond Sword w/o Unbreakable
![Tool Tip of Diamond Sword w/o Unbreakable](https://stuff.badhalo.ninja/images/ia_ds.png)
Diamond Sword w/ Unbreakable
![Tool Tip of Diamond Sword w/ Unbreakable](https://stuff.badhalo.ninja/images/ia_ds-u.png)
Custom Sword w/ Unbreakable
![Tool Tip of Voice of Canis w/ Unbreakable (Custom Sword)](https://stuff.badhalo.ninja/images/ia_vc-u.png)

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: modded & vanilla 1.15.2
 - Plugin version: v2.0.13

**Additional context**
I think I read in the wiki somewhere it saying that adding the `HIDE_ATTRIBUTES` flag would hide the durability, maybe that was the v1 wiki, either way that doesn't work. Also isn't there a hide unbreakable flag? It would be nice if this was fixed to say `Unbreakable` (as seen in the second image) and hide *that* if `HIDE_UNBREAKABLE` was used, if it's not already implemented.

**Comment by LoneDev6** [comment]
Fixed in the upcoming release, thanks
