### ISSUE TITLE
[BUG] Console spam 

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#192]
**Describe the bug**
There are errors in the console https://pastebin.com/RYWa3AFT

**Info (please complete the following information):**
 - Server version: paper 1.15.2 Build 226
 - Plugin version: 2.0.14

**Comment by LoneDev6** [comment]
let me know if update 2.0.15 will fix the issue. I'll publish it today.
Reopen this issue if the problem still persist.
Thanks!
