### ISSUE TITLE
[BUG] Error occurs while clicking in a furnace gui

### ISSUE THREAD

**Issue by PeterMa9621** [LoneDev6/ItemsAdder#194]
**Describe the bug**
While opening a furnace, click my inventory will throw an error.

**To Reproduce**
1. Open a furnace
2. Click anywhere in the player's inventory
3. See error

**Expected behavior**
No errors will be thrown

**Screenshots**
![image](https://user-images.githubusercontent.com/26262538/80619908-92761000-8a02-11ea-8509-443a6d3756fa.png)

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: vanilia 1.15.2
 - Plugin version: 2.0.14

**Additional context**

**Comment by LoneDev6** [comment]
Will fix in next update, thanks
