### ISSUE TITLE
[BUG] Vanilla Recipes Not Functional

### ISSUE THREAD

**Issue by spathizilla** [LoneDev6/ItemsAdder#195]
**Edit:** Turns out this is not limited to iron helmets - The following I have found to be non functional vanilla recipes with 2.0.15
Iron Helmet
Iron Sword
Iron Axe
Iron Hoe
Iron Shovel

**Describe the bug**
In 2.0.14 there was an issue with some vanilla recipes with was partially fixed in 2.0.15 - However, Iron helmets only can be crafted if the materials are placed towards the bottom of the crafting bench. If people place the iron ingots at the top of the workbench then it will show a blank item.

**To Reproduce**
1. Place workbench
2. Get a bunch of iron ingots.
3. Place 3 ingots along the top row of the bench
4. Place 1 ingot on the left middle and right middle row
5. See blank result item when should show Iron Helmet.
![image](https://user-images.githubusercontent.com/638845/80651718-537da400-8a6e-11ea-8c4d-b1b93ca5002d.png)

However, if you move them one row down:
![image](https://user-images.githubusercontent.com/638845/80651756-685a3780-8a6e-11ea-9ecd-ed729b1ab1ff.png)

**Info (please complete the following information):**
[22:09:34 INFO]: Server version: Paper(227) 1.15.2-R0.1-SNAPSHOT
[22:09:24 INFO]: ItemsAdder Version: 2.0.15

**Comment by LoneDev6** [comment]
Thanks for the report, I'll try my best.

All these problems are coming from the fix that allows players to craft custom items using renamed items, this originated a lot of more checks and complex stuff in the recipe system which seems to break some vanilla recipes.
I now make some tests to identify wtf is blocking these recipes

**Comment by AshleyFOXXX** [comment]
Hi. Same issue with my itemsadder. This happened when I put the craftable things that came with my itemsadder purchase
