### ISSUE TITLE
[BUG] Random Texturing 

### ISSUE THREAD

**Issue by l-404-l** [LoneDev6/ItemsAdder#199]
**Describe the bug**
Randomly generates Mushroom trees that will have the textures of items

**To Reproduce**
Just loaded a default world.

**Screenshots**
https://streamable.com/jq86ht

**Info (please complete the following information):**
 - paper 1.15.2
 - fabric 1.15.2
 - 2.0.17

**Comment by canissorion** [comment]
I have the same error but it solved after this config.
only-new-chunks: false in config.yml

**Comment by LoneDev6** [comment]
> 
> 
> I have the same error but it solved after this config.
> only-new-chunks: false in config.yml

exact, that's how to fix it, i specified in the itemsadder latest update https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-itemsadder%E2%9C%A8custom-items-huds-guis-textures-3dmodels-emojis-blocks-wings-hats.73355/update?update=332083

![image](https://user-images.githubusercontent.com/27242001/80970458-7cf65100-8e1b-11ea-8708-69f760abd8ca.png)
