### ISSUE TITLE
Custom music not working

### ISSUE THREAD

**Issue by TectonicGrinch** [LoneDev6/ItemsAdder#2]
I tried to add my own custom music disc with custom sound but me and even someone more familiar with java then me cant get it to work we have tried two sounds in ogg format. When we enable default link we can see it in the game but it doesnt play any sound when we use a custom link the script will download to about 99% before telling me to contact an admin we have tried drop box yes with the dl=1 and our own hosting on the vps send help

**Comment by LoneDev6** [comment]
please refer to the faq https://lonedev.gitbook.io/itemsadder/faq
