### ISSUE TITLE
[BUG] Crafting Bugs and Permissions Bugs

### ISSUE THREAD

**Issue by canissorion** [LoneDev6/ItemsAdder#200]
**Describe the bug**

1.- Item bug, when crafting enchanted arrows you get uncraftable tipped arrow.

2.- By putting 1 bone meal on a crafting table you get a Shulker box.

3.-When you take away the permission from the users to craft an item, if this item has a common crafting with a tool, the vanilla tool cannot be crafted.

**To Reproduce**

Arrow Bugs
     1. Go to crafting table and try to make any enchanted arrow
     2. Click on result
     3. Get the uncraftable tipped arrow

Bone meal to Shulker Box
    1. Go to crafting table and put one of bone meal
    2. Get a White Shulker Box

Permission Bugs
    1. Revoke a crafting permission, ex: Bronze_pickaxe
    2. Try to make a iron Pickaxe
    3. Not allowed

**Screenshots**

![](https://cdn.discordapp.com/attachments/533413171403292712/706208416477085803/Captura_de_Pantalla_2020-05-02_a_las_14.20.02.png)

![glitch](https://user-images.githubusercontent.com/33471737/80894879-587c6680-8cad-11ea-9711-56b364642edb.png)

<img width="359" alt="Captura de Pantalla 2020-05-02 a la(s) 19 45 56" src="https://user-images.githubusercontent.com/33471737/80894904-8c578c00-8cad-11ea-92e7-3207b0cfc06a.png">

**Info (please complete the following information):**
 - Server version: paper 1.14.4
 - Client version: Vanilla 1.14.4
 - Plugin version: 2.0.17

**Comment by LoneDev6** [comment]
Did you try the plugin on a clean server? seems something is interfering
![image](https://user-images.githubusercontent.com/27242001/80970171-06f1ea00-8e1b-11ea-91a3-fb49905088bf.png)
![image](https://user-images.githubusercontent.com/27242001/80970267-2db02080-8e1b-11ea-9119-84f409b0b974.png)

![image](https://user-images.githubusercontent.com/27242001/80970357-4d474900-8e1b-11ea-812c-29f4b099389c.png)

**Comment by canissorion** [comment]
Mmm weird i will try it but i ask on discord i some one have the same bug and i am not the only one i will try it tnk u.

Pd: Nice Work 👏🏻👏🏻👏🏻👏🏻👏🏻
<img width="422" alt="Captura de Pantalla 2020-05-04 a la(s) 14 38 58" src="https://user-images.githubusercontent.com/33471737/81000975-ffc7dd80-8e14-11ea-9886-8b0889acdf51.png">

**Comment by canissorion** [comment]
I Try it again, shulker bug and pickaxe bug just solved but the arrow bug happen in a clean server

**Comment by LoneDev6** [comment]
> 
> 
> I Try it again, shulker bug and pickaxe bug just solved but the arrow bug happen in a clean server

Mmh... are you running the very latest version of Spigot/Paper?
Can you try https://papermc.io/downloads ?
Can you make a video if you have time?

Thanks a lot

**Comment by canissorion** [comment]
Mark it as closed in the latest vrs it just fixed. idk 

Tnk u Lone

**Comment by LoneDev6** [comment]
Np, probably was a Spigot/Paper bug they fixed on a recent update
