### ISSUE TITLE
[BUG] IA Menu permissions don't work

### ISSUE THREAD

**Issue by HolographicWings** [LoneDev6/ItemsAdder#203]
Hello, i wish allow players to see only some categories in the /ia menu
but players see nothing in the categories
![1](https://user-images.githubusercontent.com/19623115/81062572-7f69b100-8ed6-11ea-8ec8-c5820d109d19.JPG)
![2](https://user-images.githubusercontent.com/19623115/81062573-80024780-8ed6-11ea-961a-aff8e034e78f.JPG)
![3](https://user-images.githubusercontent.com/19623115/81062575-80024780-8ed6-11ea-866a-0f7ad544c59e.JPG)
![4](https://user-images.githubusercontent.com/19623115/81062576-80024780-8ed6-11ea-9fd6-446b4dfe16cb.JPG)

**Comment by LoneDev6** [comment]
answered via PM on spigot.
was missing permission:
ia.user.ia.*
