### ISSUE TITLE
[BUG] Blocks don't drop if use silk touch

### ISSUE THREAD

**Issue by JoanBarceloFiol** [LoneDev6/ItemsAdder#207]
**Describe the bug**
Blocks that use "cancel_drop: false" like Mysterious ore, Bonze ore, Modern Sandstone don't drop anything if you mine them wiht silk touch.

**To Reproduce**
1. Enchant a pickaxe with silktouch
2. Mine one of the following blocks with the enchanted pickaxe: Mysterious ore, Bonze ore, Modern Sandstone, Block of Ruby...

**Expected behavior**
It should drop the block destroyed.

**Info (please complete the following information):**
Server version: paper 1.15.2 (Build: 220)
Client version: minecraft Optifine
Plugin version: 2.0.18

**Comment by LoneDev6** [comment]
thanks, fixed in next update
