### ISSUE TITLE
[BUG] Destroy furnitures in gamemode spectator

### ISSUE THREAD

**Issue by alejandro0256** [LoneDev6/ItemsAdder#208]
Describe the bug
Is possible to destroy furnitures in gamemode spectator using left click

To Reproduce
1. Place a furniture
2. Get in gamemode spectator
3. Use left click on the furniture

Expected behavior
It shouldn't be possible to destroy the furniture in gamemode spectator.

Info (please complete the following information):
Server version: paper 1.15.2 (Build: 220)
Client version: minecraft Optifine
Plugin version: 2.0.18

**Comment by LoneDev6** [comment]
fixed in next update, thanks
