### ISSUE TITLE
[BUG] Smelting blocks that shouldn't be smeltable

### ISSUE THREAD

**Issue by alejandro0256** [LoneDev6/ItemsAdder#209]
**Describe the bug**
Is possible to use the furnance to smelt blocks like modern sandstone, mysterious ore, ruby ore...

**To Reproduce**
1. Get a furnance
2. Add Coal on the furnance
3. Put the block on the furnance (Moden sandstone, Mysterious ore, Ruby ore)

Info (please complete the following information):
Server version: paper 1.15.2 (Build: 220)
Client version: minecraft Optifine
Plugin version: 2.0.18

**Comment by LoneDev6** [comment]
This is an intended feature. It's the only way to fix this bug: https://github.com/LoneDev6/ItemsAdder/issues/185

put the item:
![immagine](https://user-images.githubusercontent.com/27242001/81277622-f4fb8b80-9054-11ea-805c-2e992f7da8b6.png)
it smelts but you get it back
![immagine](https://user-images.githubusercontent.com/27242001/81277643-f9c03f80-9054-11ea-81d3-7bc83f216cdd.png)

this is to avoid the furnace getting stuck smelting infinitely the same item
