### ISSUE TITLE
Keeping potion effect even after tool unheld.

### ISSUE THREAD

**Issue by Zangerine** [LoneDev6/ItemsAdder#213]
If an item has a potion effect on it you can make it so you can keep the enchant forever. 

If you are holding the pickaxe and you press f to swap it to your off hand you can now keep it in your inventory and you will always have the potion_effect.

There needs to be a way to turn off the effect if they swap it from their main hand, or if they remove it from their main/off hand completely.

Many thanks!

**Comment by LoneDev6** [comment]
ItemsAdder version?
try the latest, this has been fixed before
