### ISSUE TITLE
[BUG] Keep potion effect forever

### ISSUE THREAD

**Issue by Zangerine** [LoneDev6/ItemsAdder#214]
**Describe the bug**
I've been told this has been fixed but it has not. When you put it in a chest it is fixed but not this way. If you are holding a tool that has a potion effect on it and you swap it to your off hand, the effect will not go away and you will have it indefinitely.

**To Reproduce**
1. Hold a tool with a potion effect on held:
2. Press F (or whatever keybind swaps to off hand for you)
3. You now have the potion effect indefinitely, even if you have it removed on unheld.

**Expected behavior**
The potion effect to be removed on hand switch.

**Screenshots**
N/A

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: 1.15.2 
- Plugin version: 2.0.19

**Comment by LoneDev6** [comment]
Thanks it's fixed in the next update, I will publish that as soon as possible
