### ISSUE TITLE
[BUG] Error reloading the plugin

### ISSUE THREAD

**Issue by Deathroner** [LoneDev6/ItemsAdder#217]
**When reloading the plugin on the server, this error is generated.**

https://pastebin.com/0k9ADUjN

It happens to me from version 2.0.19 onwards.

**Comment by LoneDev6** [comment]
Even with that error is the plugin working after reload?
just making sure

**Comment by Deathroner** [comment]
I have not checked it, but I have noticed that sometimes after using the / iareload command there are more errors in the console than normal

**Comment by LoneDev6** [comment]
Should be fixed in next update
