### ISSUE TITLE
[Suggestion] replace_near_blocks no physics

### ISSUE THREAD

**Issue by YoutubeNosios** [LoneDev6/ItemsAdder#219]
**Is your feature request related to a problem? Please describe.**
Hey ! Can you add an option to disable physics on replace_near_blocks action please ?

**Describe the solution you'd like**
There is a function in spigot to do that :
loc.getBlock().setType(material, false);

**Additional context**
Thank you in advance !

**Comment by LoneDev6** [comment]
Added in upcoming release
https://itemsadder.plugin.ga/plugin-usage/adding-content/item-properties/events/actions
