### ISSUE TITLE
Applying redstone current or somehow updating blocks breaks textures.

### ISSUE THREAD

**Issue by TheMGRF** [LoneDev6/ItemsAdder#22]
Some sort of block update or power applications really messes with block textures and the mushroom blocks. The blocks become normal mushroom blocks OR other custom blocks. It appears client side and fixes on relog but when breaking the block I get the changed block.

https://i.gyazo.com/895c19d525652eeba56d3048ad206483.mp4

**Comment by TheMGRF** [comment]
In that particular setup noted above the middle block is always turned into a seemingly client side mushroom block.

**Comment by TheMGRF** [comment]
When breaking the redstone on top of the blocks the effect is permanent and not client side.

**Comment by LoneDev6** [comment]
Temporary fix applied in latest version, I disabled placing of every redstone block on custom blocks to avoid this strange behaviour

**Comment by Andre601** [comment]
It's to note that this also happens when you place a mushroom block on the custom block (which is a mushroom)

**Comment by LoneDev6** [comment]
> 
> 
> It's to note that this also happens when you place a mushroom block on the custom block (which is a mushroom)

It's only client side, not server side.
Also ban your users if they keep to complain about this XD why would someone place mushroom blocks on custom itemsadder blocks?

**Comment by Andre601** [comment]
> > It's to note that this also happens when you place a mushroom block on the custom block (which is a mushroom)
> 
> It's only client side, not server side.
> Also ban your users if they keep to complain about this XD why would someone place mushroom blocks on custom itemsadder blocks?

Banning someone would be harsh. Also I talk about experiencing this myself when I picked up the block in creative mode (which gave me a normal mushroom block) and then placed it. This seems to be fixed in the latest version.

Also I didn't make an issue with this yet so I first ask: Would it be somehow possible to add a way to directly get the custom block in creative mode by just middle-clicking it?

**Comment by LoneDev6** [comment]
I was joking about ban btw, lol

sadly it's not possible as I don't think client sends middleclick event to server, so i can't detect it
