### ISSUE TITLE
Hand items not reappearing after emotes ends

### ISSUE THREAD

**Issue by glutaminus** [LoneDev6/ItemsAdder#2227]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already asked on the **#💬ia-community-help** channel on **Discord** to know if anyone already has a solution for the issue.

### What happened?

after you do the emotes, it will take item from your hand and pass it to the emote model, when the emote end, it didn't give back the item immediately(the inventory slot is still blank) until you need to open your inventory and click on that slot again to get the item back. (it's big problem because player will can't see the weapon until they open their inventory and click on it)

### Steps to reproduce the issue

1. Hold any items.
2. play the emote
3. item lost its visibility and being copied to the emote model while it plays.
4. emote end but the item in your hand is still not getting the visibility back. 

### Server version

git-Purpur-1838 (MC: 1.19.2)

### ItemsAdder Version

Itemsadder version 3.3.0b-r2

### ProtocolLib Version

5.0.0-SNAPSHOT-b602

### LoneLibs Version

LoneLibs version 1.0.19

### LightAPI Version (optional)

didn't use

### LibsDisguises Version (optional)

LibsDisguises version 10.0.31

### FULL server log

nothing is wrong internal

### Screenshots/Videos (you can drag and drop files or paste links)

hold item
![image](https://user-images.githubusercontent.com/90768288/210028809-7eb8b650-06e7-466c-aad2-ea4275f1294a.png)
play emote
![image](https://user-images.githubusercontent.com/90768288/210028827-f2f2285e-9e7c-4a93-a2bb-ccc987d88b04.png)
lost the item until click on the slot you hold
![image](https://user-images.githubusercontent.com/90768288/210028839-b8fb5576-4926-4cc5-a891-f12c8bef1176.png)

**Comment by DarkyCat** [comment]
+1

**Comment by LoneDev6** [comment]
I'll try to reproduce it, but shouldn't happen since it just hides the item, it doesn't actually remove it

**Comment by glutaminus** [comment]
I mean yeah, it doesn't actually remove, but player can't interact with the item anymore (right click interactions etc.) until they have to click on the slot again, it's kinda too annoying for the players that they have to do this everytime they play emotes. Just thought that it's fixable because other plugin can return the item immediately after emote ended (don't know if it's matter but that plugin can't show item in hand on the emote so i don't use it), but nvm deal with it i guess.

**Comment by glutaminus** [comment]
Was it really 

> I'll try to reproduce it, but shouldn't happen since it just hides the item, it doesn't actually remove it. You can click on the empty slot and see the item appear again.

Just wondering why was this is not reproduceable? even though the off-hand item are appearing perfectly after the emotes end.
