### ISSUE TITLE
Weird vehicles [BUG]

### ISSUE THREAD

**Issue by Jirsaacek** [LoneDev6/ItemsAdder#226]
When i place vehicle from IA, i can put coal in as a fuel, but when I want to sit in, nothing happnes, when I want to write in chat (commands too) I get "Cannot send chat mesaage" and when that happens, I and vehicle too for other players just disappear...  Only way to fix it is by relog. 
Paper 1.15.2
Thanks :)

**Comment by Deathroner** [comment]
https://github.com/LoneDev6/ItemsAdder/issues/218

**Comment by Deathroner** [comment]
Do you have any land protection system?
The same happens to me, but only in protected areas.

**Comment by LoneDev6** [comment]
If you're using Towny read this: https://itemsadder.plugin.ga/faq/towny-vehicles-bug

**Comment by 100petr** [comment]
We do not use Towny.

**Comment by LoneDev6** [comment]
Which plugins are you using?

**Comment by Jirsaacek** [comment]
We are using Residence plugin - It only happens in residences

**Comment by LoneDev6** [comment]
Ok thanks I will make some tests to see why that happens. I suspect it's something similar to this problem which was fixed: https://itemsadder.plugin.ga/faq/towny-vehicles-bug

**Comment by LoneDev6** [comment]
Moved to: https://github.com/LoneDev6/ItemsAdder/issues/218
