### ISSUE TITLE
Texture: new item adding problem

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#227]
Ciao LoneDev...

Ascolta, ho bisogno di una mano.

Io ho questo items
[https://minecraft.novaskin.me/skin/4755302427656192/diamond-sword](url)

Ho cliccato su download e mi ha dato l'immagine diamond_sword.png

ho rinominato l'immagine blacklorem_sword.png e l'ho messo nella cartalla:
plugins/ItemsAdder/data/resource_pack/assets/itemsadder/textures/item

poi sono andato nella cartalla
plugins/ItemsAdder/data/resource_pack/assets/itemsadder/models/auto_generated
e ho caricato il file blacklorem_sword.json :

`{
  "parent": "item/handheld",
  "textures": {
    "layer0": "itemsadder:item/blacklorem_sword"
  }
}`

Poi ho modificato il file swords.yml nella cartella
plugins/ItemsAdder/data/items_packs/itemsadder

Infine ho fatto /iareload
/iazip
[pack9.zip](https://github.com/LoneDev6/ItemsAdder/files/4618828/pack9.zip)

poi ho caricato su sito web
ho modificato file config mettendo pack9

e però non funziona.

Non ci sono errori in console.. però la spada mi esce cosi, 
![image](https://user-images.githubusercontent.com/20026629/81753470-25f41a00-94b4-11ea-8a3c-f194059fbf9f.png)
invece di uscirmi come ti avevo mostrato nel link iniziale.

**Comment by Fargus5** [comment]
Ciao, dopo aver eseguito un riavvio del server senza toccare null'altro ho notato che la spada che ho aggiunto si vede benissimo e funziona. Di conseguenza se ne deduce che è il riavvio resta ancora necessario e che non basta fare /iareload

**Comment by LoneDev6** [comment]
Hai provato a fare /iareload nuovamente dopo aver modificato il link nel config.yml?
Dopo che hai caricato il file .zip intendo.

Fammi sapere

**Comment by LoneDev6** [comment]
Colgo l'occasione per invitarti a non usare il namespace "itemsadder", devi crearne uno tuo per evitare problemi nel caso in cui resettassi le cartelle di itemsadder:
https://itemsadder.plugin.ga/plugin-usage/adding-content/creating-your-namespace

**Comment by Fargus5** [comment]
Si si certo che ho fatto /iareload almeno una cinquantina di volte. ahahahah

comunque si, nella guida sei stato anche abbastanza chiaro circa la creazione di un proprio namespace. E si ho intenzione di spostare questa spada che ho creato nel mio personale namespace. Ma non è cosi evidente.... poiché devo capire come spostare i file e soprattutto nei file di configurazione come inserire gli indirizzi.... stile 

..item/itemsadder:xx.png
non è cosi evidente in che modo funzionano quei puntini etc. non è chiaro. se devo specificare una sottocartella etc. insomma. una volte che avrò capito poi sistemo tutto.
per ora piano piano sto studiando per bene il tuo plubin.
E vorrei poter aggiungere tante cose....
non ho nemmeno capito come fa a modificare automaticamente il file delle diamond_sword dentro la cartella models di minecraft.... insomma ci sono molte cose che nella tua guida sono mancanti e per capirle in pratica devo ogni volta rompêre il plugin ed il server e fare 30 riavvii al giorno perché anche /iareload non funziona perfettamente.

**Comment by LoneDev6** [comment]
Per facilità usa [Plugman](https://dev.bukkit.org/projects/plugman), ti permette di fare `/plugman reload ItemsAdder`, così non devi riavviare tutto il server. Funziona con quasi tutti i plugin, ma alcuni possono avere problemi.
ItemsAdder no.



Comunque da cosa scrivi capisco che non stai seguendo questo suggerimento, cioè lavorare sul proprio pc per fare molto prima ed evitare di caricare 300 volte su dropbox il file, ci metti 3 ore per ogni oggetto altrimenti..
https://itemsadder.plugin.ga/plugin-usage/tips-for-fastest-usage
Lavorare sul server online non ha senso, non solo per ItemsAdder ma per tutto in generale, non è mai un bene lavorare prima online, cioè che senso ha perdere tempo a fare mille modifiche tutte con FTP e da pannelli web, molto meglio farle da file sul proprio PC e vedere tutto già in azione senza perdere tempo a caricare file online.

Perciò ora cerco di aiutarti, leggi attentamente qui:

Per poter creare un server Minecraft sul tuo PC non ci vuole niente:
- scarica ed estrai questo zip in una cartella che vuoi del TUO PC, non sul server online: https://www.dropbox.com/s/cfsav45tbdxea2y/test_server.zip?dl=0
- Devi scaricare anche il file jar del server: https://papermc.io/api/v1/paper/1.15.2/282/download
- incolla il file jar nella cartella "test_server" che hai estratto sul TUO PC
- rinomina il file .jar in `server.jar`
- incolla tutti quanti i plugin che servono per far funzionare itemsadder: https://itemsadder.plugin.ga/plugin-usage/tips-for-fastest-usage
- incolla ovviamente itemsadder.jar nella cartella plugins
- clicca due volte su start.bat
- connettiti al server Minecraft usando l'IP: `localhost`

fatto, ora potrai lavorare direttamente su questo server locale.. non dovrai preoccuparti di dropbox dato che è automatico il caricamento del pack, visto che è tutto sul tuo pc non dovrai caricare niente online, il tuo gioco "scaricherà" in automatico il resourcepack direttamente dal PC senza passare da internet.
Ripeto, non toccare il file config.yml sul server di test, non serve.

Una volta finito di modificare tutto quello che ti pare, aggiungere oggetti, modificare cose su itemsadder, eccetera: carica il file pack.zip su dropbox, copia il nuovo link, incollalo nel file config.yml sul tuo server ONLINE, quello reale non quello di test su cui hai lavorato poco fa.
Carica anche la cartella `plugins\ItemsAdder\data` sul server ONLINE, altrimenti non vedi nessun oggetto.

Spero di essere stato chiaro, più di così non so come spiegarmi

**Comment by Fargus5** [comment]
Grazie mille per ciò che hai scritto.

Senti ho una domanda semplice:

nel tuo file sword.yml in plugins/ItemsAdder/data/items_packs/itemsadder
in fondo c'è

`loots:
  blocks:
    nether_alchemy_ore:
      type: itemsadder:nether_alchemy_ore
      items:
        healing_crystals:
          item: itemsadder:healing_crystals
          min_amount: 1
          max_amount: 1
          chance: 10`

Perché lo hai messo li nelle spade e non hai creato un file yml apposta?
cosi una curiosità.

**Comment by LoneDev6** [comment]
> Perché lo hai messo li nelle spade e non hai creato un file yml apposta?
> cosi una curiosità.
Sarebbe stato meglio effettivamente metterlo in un file apposta, è stato messo nello stesso file dal convertitore da ItemsAdder v1 a v2, non li ho convertiti manualmente tutti gli oggetti.
Magari in un prossimo aggiornamento sposterò e riorganizzerò meglio i file di default del plugin


La cartella auto_generated non devi toccarla, contiene i file .json generati dal plugin partendo dalle immagini png.

Invece le cartelle block e item sono a tua disposizione per metterci i tuoi modelli per i blocchi e per gli item.






Comunque ci tengo a specificarti che nel prossimo update, nel tuo server di test sul tuo pc, ti basterà usare /iazip per vedere i config ricaricati, il pack.zip rigenerato e la texture applicata al tuo gioco, senza dover eseguire 3 comandi.

Nel server online però dovrai eseguire **/iazip**, **/iareload** e **/iatexture all** come consueto.




Se non hai più bisogno chiudi pure la issue

**Comment by Fargus5** [comment]
LoneDev, io avevo una spada senza file json... era solo l'immagine png... ho creato il file json prendendo spunto da altre spade già presenti nella lista nella cartella autogenerated ed ha funzionato tutto

credi che debba aggiustare tutto?

**Comment by LoneDev6** [comment]
Non devi creare manualmente il file anche perché se non sbaglio itemsadder poi resetta la cartella auto_generated ogni volta che usi /iazip.

Per creare un oggetto partendo solo da una texture .png devi fare così:
```Yaml
  ruby:
    display_name: Ruby
    permission: ruby
    resource:
      material: IRON_INGOT
      generate: true
      textures:
      - item/ruby.png
```

**Comment by Fargus5** [comment]
Caro LoneDev, ti ringrazio molto per il tuo prezioso aiuto. Ho tuttavia ancora una domanda. Ne avrò molto, ti prego sopportami. :)

Ho creato il test server nel mio pc.
Ho installato tutto items adder e anche epicbackpacks ed Essentials per avere una comodità nei comandi in game mode etc.

Senti, vorrei sapere... quando tutto è settato correttamente nel mio test server... dopo quando voglio trasportare nel server online devo aggiungere soltanto il pack.zip sul mio sito web e poi tutti gli items si scaricano da soli nelle varie cartelle oppure devo comunque aggiungerli io anche nel server online tutte le immagini ed i file json???

**Comment by Fargus5** [comment]
C'è anche un altra cosa che riguarda il  thin font

funziona molto bene e ti ringrazio di averlo aggiunto. C'è però una piccola dimenticanza da parte tua...

Non si applica dal momento in cui fai il login. Apply on Join : True attiva tutta la resouce pack e nonostante custom text sia su false, comunque te lo carica . In gioco quindi sei costretto a fare /iatexture perché esso non sia effettivamente preso in considerazione e che prevalga quindi il thin-font.

potresti rivedere questa cosina anche?


`  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: false
  delay-ticks: 1
  self-host:
    enabled: true
    server-ip: 127.0.0.1
    pack-port: 8163
  external-host:
    enabled: false
    url: http://www.survivalla.fun/respack/pack10.zip
  custom-font:
    enabled: false
    name: font.ttf
  thin-font:
    enabled: true`

**Comment by LoneDev6** [comment]
> 
> 
> Caro LoneDev, ti ringrazio molto per il tuo prezioso aiuto. Ho tuttavia ancora una domanda. Ne avrò molto, ti prego sopportami. :)
> 
> Ho creato il test server nel mio pc.
> Ho installato tutto items adder e anche epicbackpacks ed Essentials per avere una comodità nei comandi in game mode etc.

Ciao! Devi per forza caricare tutto per evitare desyncronizzazioni tra i file
