### ISSUE TITLE
[BUG] /iahud error null

### ISSUE THREAD

**Issue by choco3224** [LoneDev6/ItemsAdder#229]
**Describe the bug**
Error al poner el comando /iahud sale en la consola null
**To Reproduce**
/iahud sale en la consola null y el comando no hace nada

**Expected behavior**
Que hiciera algo pero solo sale null

**Screenshots**
[https://cdn.discordapp.com/attachments/695010844320202872/710068041542533120/unknown.png](https://cdn.discordapp.com/attachments/695010844320202872/710068041542533120/unknown.png)
**Info (please complete the following information):**
 - Server version:  paper 1.15.2
 - Client version: 1.15.2
 - Plugin version: 2.0.22

**Additional context**

**Comment by LoneDev6** [comment]
hello, thanks.
/iahud is an experimental command I introduced to make tests, don't use it, thanks

**Comment by choco3224** [comment]
¨/iaplayerstat writes LoneDev mana float 5¨ also produces null error
[https://cdn.discordapp.com/attachments/695010844320202872/710071645234135070/unknown.png](imagen)

**Comment by LoneDev6** [comment]
LoneDev is offline, use your own name instead of LoneDev
