### ISSUE TITLE
Destroying Furnitures and others inside worldguard regions

### ISSUE THREAD

**Issue by SushiBarIV** [LoneDev6/ItemsAdder#23]
Hello,

I've noticed that placers can destroy armorstand related Blocks, like Paintings and or Furnitures inside protected Regions, can you maybe add support for those things?

Greetings from Germany

**Comment by LoneDev6** [comment]
Did you set worldguard region rules properly?

**Comment by LoneDev6** [comment]
Did you set worldguard region rules properly?

Il giorno mar 30 lug 2019 alle ore 14:59 SushiBarIV <
notifications@github.com> ha scritto:
