### ISSUE TITLE
[BUG] I can't find any mineral

### ISSUE THREAD

**Issue by Deathroner** [LoneDev6/ItemsAdder#233]
I can't find any minerals in the game, neither do my users.

No AI mineral appears in game anymore :(

Config.yml : https://pastebin.com/EbRUnk16

That's my setup, can you help me?

**Comment by LoneDev6** [comment]
Hello!
Please read this and let me know: https://itemsadder.plugin.ga/faq/i-cant-find-any-mineral-ore
