### ISSUE TITLE
[BUG] don't see HUDs

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#237]
**Describe the bug**
Don't see HUDs.

**To Reproduce**
1. Go to server
2. don't see HUDs

**Expected behavior**
I was expecting HUDs.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/29830635/82118140-7948bf80-9775-11ea-89a5-47a2ef0927f8.png)
![unknown2](https://user-images.githubusercontent.com/29830635/82118142-7a79ec80-9775-11ea-8785-bc4196af8d58.png)
![unknown3](https://user-images.githubusercontent.com/29830635/82118143-7a79ec80-9775-11ea-866f-c16d1ba79e3e.png)
![unknown4](https://user-images.githubusercontent.com/29830635/82118144-7b128300-9775-11ea-86ae-48bb9a37d126.png)

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: optifine 1.15.2
 - Plugin version: 2.0.22

**Additional context**
LOG: https://pastebin.com/4WmK4htS

**Comment by LoneDev6** [comment]
Check if you enabled huds in config.yml

huds:
enabled: true

**Comment by 100petr** [comment]
See first screenshot.

**Comment by LoneDev6** [comment]
Do you have any plugin that alters actionbar?

**Comment by 100petr** [comment]
Plugins: http://prntscr.com/sivq83
![2020-05-18_11 48 56](https://user-images.githubusercontent.com/29830635/82199136-97d9c280-98fd-11ea-8e75-3c38af141be6.png)
Nothing shows in the action bar

**Comment by LoneDev6** [comment]
Are ItemsAdder items correctly loaded if you use /ia command?

**Comment by 100petr** [comment]
Yes. 
![2020-05-18_12 04 08](https://user-images.githubusercontent.com/29830635/82200762-b8a31780-98ff-11ea-8746-1cb6e62fa05a.png)

**Comment by LoneDev6** [comment]
send me your server IP

**Comment by 100petr** [comment]
82.208.17.29:27368

po 18. 5. 2020 v 12:30 odesílatel LoneDev <notifications@github.com> napsal:

**Comment by 100petr** [comment]
![2020-05-18_12 44 41](https://user-images.githubusercontent.com/29830635/82204557-66fd8b80-9905-11ea-91dd-6d0ab6fcab86.png)
With disabled resourcepack it looks HUDs are there (without texture)

**Comment by LoneDev6** [comment]
I noticed
