### ISSUE TITLE
[Suggestion] Protection Login Delay

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#239]
**Is your feature request related to a problem? Please describe.**
Quando un player entra nel gioco, muore facilmente perché non può muoversi mentre sta scaricando la texture pack.

**Describe the solution you'd like**
Vorrei che aggiungessi nel file config.yml una opzione simile a questa:

EnableProtectionLoginDelay: true/false
ProtectionLoginDelay: 60

Il valore è considerato in secondi

**Comment by LoneDev6** [comment]
Ottima idea, combinazione lo stavo già implementando :D
Sarà disponibile nel prossimo aggiornamento. Finchè il giocatore non avrà scaricato il pack sarà protetto e invisibile
