### ISSUE TITLE
ResourcePack not loading.

### ISSUE THREAD

**Issue by NeutralPlasma** [LoneDev6/ItemsAdder#24]
Hi!

So I made custom resource pack, followed instructions on the wiki, but for some reason, it cannot load Resource Pack. Throws that red error
![image](https://user-images.githubusercontent.com/25546803/62219806-446aa800-b3af-11e9-8083-a51ca6194534.png)

I've already talked to the developer on discord.

**Comment by LoneDev6** [comment]
https://lonedev.gitbook.io/itemsadder/faq/players-cant-see-textures
https://lonedev.gitbook.io/itemsadder/faq/resourcepack-not-loading
