### ISSUE TITLE
[BUG] cool sunglasses

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#240]
**Describe the bug**
Cool glasses appear overhead
**To Reproduce**
1. Go to server
2. Get cool glasses
3. Put on your cool sunglasses

**Expected behavior**
The glasses will be on your head

**Screenshots**
![2020-05-17_19 13 17](https://user-images.githubusercontent.com/29830635/82155777-8bab2200-9877-11ea-99c2-e7b3eb29e04b.png)

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: optifine 1.15.2
 - Plugin version: 2.0.22

**Additional context**

**Comment by LoneDev6** [comment]
Delete this file: plugins\ItemsAdder\data\resource_pack\assets\itemsadder\models\item\cool_sunglasses.json
and regenerate the resourcepack, it was already fixed in some previous updates.

let me know
