### ISSUE TITLE
[ERROR] Error in console, please help me.

### ISSUE THREAD

**Issue by Deathroner** [LoneDev6/ItemsAdder#241]
I have a console error, which is quite annoying. It appears very often.

https://pastebin.com/jhkS0qan

**Info:**
 - Server version: Tuinity 1.15.2
 - Client version: Vanilla 1.15.2
 - Plugin version: ItemsAdder 2.0.22

**Comment by LoneDev6** [comment]
It will be fixed in next update, reopen this issue if after update you still see it.
thanks
