### ISSUE TITLE
Get notify when resourcepack updated

### ISSUE THREAD

**Issue by Spliterash** [LoneDev6/ItemsAdder#2448]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

Spliterash#4116

### Describe the solution you'd like

When someone writes the /iazip command, it is executed instantly, and the resource pack generation is asynchronous. This is all very cool, but how do I know when the resource pack will be packaged ?
A simple Bukkit event will be enough for me that the resource pack is updated

### Is your feature request related to a problem?

....

### Describe alternatives you've considered

Only watch on resourcepack file in plugin directory, but i dont think is ok

**Comment by Spliterash** [comment]
I mean moment, when you execute /iazip, and server start packing zip. Im need wait packing end, and copy zip

**Comment by Spliterash** [comment]
What im do now
```java
val server = HttpServer.create(
    InetSocketAddress("0.0.0.0", config.getInt("server.port", 8080)),
    0
)
server.createContext("/refreshAndGet") { exchange ->
    try {
        val plugin = getProvidingPlugin(ItemsAdder::class.java)

        val iaFolder = plugin.dataFolder
        val resourcePack = File(iaFolder, "output/generated.zip")
        resourcePack.delete()

        log.info("Pre dispatch")
        Bukkit.getScheduler().callSyncMethod(this@HttpCommandExecutor) {
            Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "iazip")
        }.get()

        while (!resourcePack.isFile) {
            Thread.sleep(100)
        }
        while (!resourcePack.renameTo(resourcePack)) {
            log.info("Still waiting")
            Thread.sleep(100)
        }

        exchange.responseHeaders["Content-Type"] = "application/zip"
        exchange.sendResponseHeaders(200, resourcePack.length());

        IOUtils.copy(FileInputStream(resourcePack), exchange.responseBody)
        log.info("We done")
        exchange.close()
    } catch (ex: Exception) {
        ex.printStackTrace()
    }
}
```

**Comment by LoneDev6** [comment]
Did you try using the `ItemsAdderLoadDataEvent` event and check the cause if it's REALOAD?

**Comment by Spliterash** [comment]
![image](https://user-images.githubusercontent.com/22550546/227962771-99b834c6-0833-46a3-9e79-12e87fefe9ec.png)
![image](https://user-images.githubusercontent.com/22550546/227962691-3c543d6d-78f9-467f-ae12-da601ba86e58.png)
No, is not what im looking for

**Comment by LoneDev6** [comment]
I will implement `ItemsAdderPackCompressedEvent` in the next update.
This event is triggered right after the file is compressed and available.
