### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Dominik01201** [LoneDev6/ItemsAdder#2462]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

Domiis#5458

### What happened?

The problem is quite simple. When I configure the basic plugin everything works fine (I think so because it doesn't crash the server after 5-10 minutes of waiting). I want to upload this main texturepack. I upload it, and the error shows up a moment later.
P.S. I think another user's recent negative review aligns with my problem

The plugin is supported up to 1.19.3, so I wanted to test it too, but on the ProtocolLib website (Use build [616 ](https://ci.dmulloy2.net/job/ProtocolLib/616/artifact/target/ProtocolLib.jar )for 1.19.3) doesn't work, it shows 404. I know that this plugin doesn't really want to work with non-adapted versions. That's why I didn't test version 1.19.3, only 1.19.2 (besides the official one, I also tested the version given in the tutorial, up to 1.19.2, but it doesn't work either).

The error is not only when loading server - sometimes the error throws up 5 minutes after starting, everything works and suddenly boom or also after the command (but I do it after starting the server) /iazip

EDIT 1
However 1.19.4 is supported, my mistake. But...., it doesn't work anyway, it throws exactly the same error (same versions, just a different version of Protocollib #624).

EDIT 2
From what I can currently see (if anything changes, I'll let you know), version 3.4.1 (not 3.4.1-r2) works without any problem on version 1.19.4.

### Steps to reproduce the issue

It's basically 1:1 from the official guide:
1. Set self-host in config to true
2. Turn server on and off
3. Upload the latest version 2.0.8 txt (https://github.com/ItemsAdder/DefaultPack/releases/tag/2.0.8)
4. Extract, overwrite everything
5. Turn on server, wait 5 seconds to 5 minutes for an error.

### Server version

This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)
You are running the latest version

### ItemsAdder Version

3.4.1-r2

### ProtocolLib Version

5.0.0-SNAPSHOT-b606 (Use build [606](https://ci.dmulloy2.net/job/ProtocolLib/606/) for 1.19-1.19.2)

### LoneLibs Version

1.0.24

### FULL server log

https://pastebin.com/46D1be0H

**Comment by WolfLiSteel** [comment]
Hi. I have the same problem and same console errors. im using 1.19.2

What I tried : 
1. reseted the worlds included in the error - doesnt help (thought it was related to this 

"! [Mon 17:29:53 WARN  Minecraft] [ItemsAdder] Do not stop the server! Converting region file: region_custom_blocks | world | r.-13.-15.nbt
  [Mon 17:29:53 INFO  Minecraft] [ItemsAdder] Converted old region_custom_blocks of 'world' in 0ms.. Now deleting - r.-13.-15.nbt"

but it didnt help. 

2. since its chunk loading, it disabled ia ores, and it worked. it stopped crashing. SO it probably when either converting old ia blocks or the natural generation of ia ores. 


[2023-03-28-76.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11086269/2023-03-28-76.log)

**Comment by WolfLiSteel** [comment]
Got the same problem. Im using 1.19.2

I tried deleting the worlds included in the error but it didnt help. 
It stopped when i disabled IA ores natural generation in worlds.

[2023-03-28-76.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11086308/2023-03-28-76.log)

**Comment by LoneDev6** [comment]
Duplicate https://github.com/PluginBugs/Issues-ItemsAdder/issues/2450
