### ISSUE TITLE
I see bug form this plugin when using with other protection plugin.

### ISSUE THREAD

**Issue by Focusprw** [LoneDev6/ItemsAdder#25]
I see bug form this plugin when using with other protection plugin.
It is big of bug, You need to fix that fast.
Runner is paper version 1.14.4 and itemadder lasted update at 31-jul-19

Video ---> https://www.youtube.com/watch?v=pEB2EwP8_2I

Why I thing that is bug form plugin?
When I unload this plugin with plugman, This bug is disappear.
You can pm me for join to myserver for look this bug.

**Comment by LoneDev6** [comment]
Are you using the latest version of the protection plugin?
I'm using Griefprevention without any issue.

**Comment by Focusprw** [comment]
I have issue in plugin towny.
Pls check again, I think it is big bug.

Minecraft 1.14.4
Towny last update 01-Aug-19
Itemadder  last update 01-Aug-19

Any player normal can't be destroy map.
You need create town in map before build.
When I destory grass, any item drop form grass.

I've already contacted the owner plugin of towny.
He stated that this problem was not caused by his system.

If you can, contect me in discord for join to myserver to see this bug.
I will stay at your discord (1 PM - 11 AM). Name is NerdDev#5111.

Thank you.
Sorry, English is not my first language.

**Comment by LoneDev6** [comment]
Where can I contact towny dev? I want to talk to him directly so he can help me fixing this issue

**Comment by Focusprw** [comment]
You can contect with discord ---> https://discord.gg/QvgRpcs

**Comment by LoneDev6** [comment]
ty

**Comment by WindUnwaken** [comment]
> Are you using the latest version of the protection plugin?
> I'm using Griefprevention without any issue.

I'm using latest GP-16.11.6 runs on 1.14.4 have this issue

**Comment by LoneDev6** [comment]
> 
> 
> You can contect with discord ---> https://discord.gg/QvgRpcs
> And github ---> https://github.com/TownyAdvanced/Towny

He said he won't help me fixing the problem, it's not my plugin issue.. it's his plugin issue because he uses hacky ways to cancel block break. (highest event priority, which is bad)

**Comment by LoneDev6** [comment]
> 
> 
> > Are you using the latest version of the protection plugin?
> > I'm using Griefprevention without any issue.
> 
> I'm using latest GP-16.11.6 runs on 1.14.4 have this issue
> use pickaxe, breaks block still drops exp but block protect by plugin

I'll fix it in next update, thanks!

**Comment by TheMGRF** [comment]
This issue is still persisting with the latest builds of WorldGuard.

**Comment by LoneDev6** [comment]
Please send worldguard flags list

**Comment by TheMGRF** [comment]
![image](https://user-images.githubusercontent.com/16401884/64631243-9c54ef80-d3ee-11e9-89a9-c980bacdca1a.png)
I've also tried it with interact being set to false and it did not work.

**Comment by LoneDev6** [comment]
![immagine](https://user-images.githubusercontent.com/27242001/64632120-c7444100-d3f8-11e9-9b64-873a4ff5dffe.png)
I think it's mob-damage or damage-animals

**Comment by TheMGRF** [comment]
Not sure why it would be those two? But tried setting them anyway and unfortunately I'm still getting the same behaviour.

**Comment by LoneDev6** [comment]
This is my flags list, try to replace your list in regions.yml:

`flags:
            other-explosion: deny
            lava-fire: deny
            mypet-damage: deny
            water-flow: deny
            invincible: allow
            use: deny
            snow-fall: deny
            leaf-decay: deny
            firework-damage: deny
            mob-damage: deny
            passthrough: allow
            ravager-grief: deny
            mushroom-growth: deny
            lightning: deny
            ice-form: deny
            wither-damage: deny
            chorus-fruit-teleport: deny
            enderman-grief: deny
            pvp: deny
            creeper-explosion: deny
            vine-growth: deny
            damage-animals: deny
            snow-melt: deny
            tnt: deny
            entity-item-frame-destroy: deny
            ghast-fireball: deny
            frosted-ice-form: deny
            mycelium-spread: deny
            ice-melt: deny
            block-trampling: deny
            interact: deny
            vehicle-destroy: deny
            weather-lock: clear
            ride: deny
            fire-spread: deny
            sleep: deny
            vehicle-place: deny
            snowman-trails: deny
            block-break: deny
            entity-painting-destroy: deny
            lighter: deny
            pistons: deny
            block-place: deny
            enderpearl: deny
            soil-dry: deny
            build: deny
            item-frame-rotation: deny
            potion-splash: deny
            frosted-ice-melt: deny
            lava-flow: deny
            grass-growth: deny`

**Comment by LoneDev6** [comment]
@TheMGRF Should be fixed in latest version, let me know! 😄 
(update is scheduled to be published today)
