### ISSUE TITLE
[Suggestion] Hydration

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#252]
**Is your feature request related to a problem? Please describe.**
Ho notato che la sete manca di una sua configurazione personalizzabile

**Describe the solution you'd like**
Volevo cercare un immagine migliore della barra della sete, cosi son inciampato su questo:
[https://www.curseforge.com/minecraft/texture-packs/thirst-resource-pack](url)

Sarebbe carino che la barra della sete scenda seguento dei parametri un po più personalizzabili e che se non si beve si riscontrino degli effetti di debolezza e lentezza, fino a subire poi danno e morte. Sarebbe altresi carino aggiungere anche un sistema che ti faccia stare male se bevi l'aqua per terra con la tua mano (ora non puoi) oppure se la bevi attraverso uno strumento diverso da quelli nella lista dei Drinks all'interno del menu /ia.

Vorrei che si aggiungesse nel file di config.yml la possibilità di personalizzare tutti i parametri di cui parlerò di seguito nella proposta.

Walking one block adds 5 exhaustion. Running one block adds 15. Jumping adds 35. When exhaustion hits 600, you lose one hydration/thirst point. Drinking a bottle of water or drinking with your hand in a water in the ground will give you "Dehydration." Dehydration adds 10 exhaustion every tick. This was done to make getting better thirst restoration a priority. You can only make it display by making the thirst bar green, however.

Items that restore thirst correctly:
+ Itemsadder category Drinks

Dehydration comes from:
+ Bottle of Water (normal minecraft item)
+ Drinking the water of in the ground

**Comment by LoneDev6** [comment]
Ciao, la sete puoi personalizzarla in parte nel config: `plugins\ItemsAdder\data\items_packs\realcraft\huds.yml`.
Come vedi ci sono alcuni eventi speciali per cui scende.
Ti consiglio di cancellare questo file e farlo rigenerare al plugin dato che qualche aggiornamento fa ho ribilanciato leggermente i valori di come viene diminuita barra della sete e in quali biomi.

Come vedi puoi cambiare in base a quale livello di luce far scendere la sete (se si è all'esterno o in casa), in quale bioma, di quanto, ogni quanto...



Modificare la barra della sete copiandola dalla mod che hai mandato è semplice, ti basta aprire il file della mod con 7zip, cercare dove c'è il file immagine e modificare i miei file immagine che trovi qui `plugins\ItemsAdder\data\resource_pack\assets\realcraft\textures\font\hud\thirst_bar`
