### ISSUE TITLE
Emojis not sent in chat message when using `/e` command

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#2618]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

pitilon#6950

### What happened?

If I use /e emoji only text is sent (I have the latest essentials dev build, downloaded it now)

### Steps to reproduce the issue

Install essentials (+ ess chat)
Write, for example, /e signTab choose an emoji
Send it to chat
Look in the chat
Now try rewriting it manually and sending it to the chat

### Server version

Current: git-Purpur-1970 (MC: 1.19.4)

### ItemsAdder Version

3.4.1c (I noticed the problem already at the beginning of April, specifically with version 3.4.1-r4, but it may have existed longer)

### ProtocolLib Version

5.0.0-SNAPSHOT-639

### LoneLibs Version

 1.0.24

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/29830635/53eb6337-1ec1-4ba6-9a1b-bc115a237faa)
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/29830635/d3e4475d-69b1-4c5a-9514-b9632181ad7f)

**Comment by SirCraftypants** [comment]
Are you using EssentialsChat? I had nothing but problems with it in the past with emoji's until i switched to ChatControlRed

**Comment by PortableGames** [comment]
Same problem without essentials plugins on 1.19.4 

Uploading Minecraft 1.19.4 - Multiplayer (3rd-party Server) 2023-05-13 12-22-16.mp4…

**Comment by PortableGames** [comment]
And problem with rpghuds on newest vault

**Comment by PortableGames** [comment]
Uploading Minecraft 1.19.4 - Multiplayer (3rd-party Server) 2023-05-13 12-22-16.mp4…

![Uploading IMG_20230513_124232898_MFNR.jpg…]()

**Comment by PortableGames** [comment]
Clean server with only IA and necessary resources without any chat plugin. In /e command emoji are visible but not after sending

**Comment by SirCraftypants** [comment]
hmmm strange, lonedev should be back on Monday to help. If it's required and reverting back to the last working version isn't an issue until then i recommend doing that.

**Comment by PortableGames** [comment]
Uploading Minecraft.mp4…

**Comment by PortableGames** [comment]
![Screenshot_20230513-130414](https://github.com/PluginBugs/Issues-ItemsAdder/assets/89090940/a950e661-a846-4e53-a24b-f5af3aca79b2)
![Uploading Screenshot_20230513-130356.png…]()

**Comment by pojjang** [comment]
![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/68462454/d3e60f24-b0cc-422c-8be9-5678b50edd6b)

I have the same problem.

But if I put a plugin called VentureChat, it works.

Is there any way to fix this problem without installing chat manager plugin? Do I need to install a chat management plugin?

Version uses 1.19.4.

**Comment by LoneDev6** [comment]
> I will ask another question. Is there a version update that doesn't screw something up? :D

No :D Even Spigot/Paper itself fucks things up most of the times.
I try my best to maintain stability between updates :(

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/2677
