### ISSUE TITLE
[Suggestion] Add the interact_block_placed event

### ISSUE THREAD

**Issue by Jamm95** [LoneDev6/ItemsAdder#262]
**Problem**
There is not currently a way to trigger events when blocks are mined to my knowledge.

**Solution**
Add the "interact_block_placed" event type, as you suggested in your Discord.

**Result**
Custom blocks can be given events that trigger when they are mined. For example: a block that uses the explode action and blows up when it is mined.

**Comment by LoneDev6** [comment]
Will be available in the very next update ;)
