### ISSUE TITLE
[BUG] repair eat much 

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#263]
**Describe the bug**
repair eat much 

**To Reproduce**
1. use tool  to make its durability
2. repair it on anvil
3. See error

**Expected behavior**
eat 4 on repair

**Screenshots**
https://youtu.be/zDIE4IE3hzw

**Info (please complete the following information):**
 - Server version: spigoit 1.15.2
 - Client version: fabric 1.15.2 with wwe
 - Plugin version: 2.0.24

**Additional context**

**Comment by LoneDev6** [comment]
Hello, it's the same behaviour for vanilla pickaxes, it's not a bug:

Diamond:
![immagine](https://user-images.githubusercontent.com/27242001/83497921-7c54e700-a4bb-11ea-9f41-280346c217d3.png)
![immagine](https://user-images.githubusercontent.com/27242001/83497940-837bf500-a4bb-11ea-9d4e-63a38fbadb8c.png)

**Comment by Command1264** [comment]
No, what I mean is this:
https://www.youtube.com/watch?v=zDIE4IE3hzw&t=26s
Please look carefully at the number of repairs
vanilla tool only eat 4 diamonds
but, Itemsadder's tool eat 57(much than 4 or 5) ruby

**Comment by LoneDev6** [comment]
Thanks! I understand now.
I will publish an update, please reopen this issue if you still have the problem after update
