### ISSUE TITLE
Kicked With Java Messages

### ISSUE THREAD

**Issue by imbnc** [LoneDev6/ItemsAdder#2634]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

MBN#0252

### What happened?

Some players are getting kicked with multiple java error message about packet loss / packet larger than expected exc...
I tried everything and when i asked for help people asked to go to the items adder support or ask the plugin developer for some explanation and assistance where its mostly a resource pack issue.

### Steps to reproduce the issue

Its just that players join and get kicked randomly like thats whats killing me nothing even to see in the console.

### Server version

Current: git-Purpur-1970 (MC: 1.19.4)*
Previous: git-Paper-514 (MC: 1.19.4)

### ItemsAdder Version

ItemsAdder version: 3.4.1c

### ProtocolLib Version

ProtocolLib version: 5.0.0

### LoneLibs Version

LoneLibs version: 1.0.24

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/131328229/7a029432-a26e-46f4-9b83-a078ff3f42ad)
![farback](https://github.com/PluginBugs/Issues-ItemsAdder/assets/131328229/84e29446-e8b8-4470-a88d-1543b4fbcda2)
![image2](https://github.com/PluginBugs/Issues-ItemsAdder/assets/131328229/b502231e-390b-4001-b746-a00a3425162e)
![3333](https://github.com/PluginBugs/Issues-ItemsAdder/assets/131328229/7f6781e2-caf4-4104-a255-5f364612deee)

**Comment by LoneDev6** [comment]
Remove ViaVersion and similar plugins when testing, let me know if the issue still occurs.
Also which client version are these users using to connect?

**Comment by dinobossytnew** [comment]
> Remove ViaVersion and similar plugins when testing, let me know if the issue still occurs. Also which client version are these users using to connect?

to me it happens to me and it is not only that, it seems to me that viaversion is not in my pack sometimes to some it lets them enter and to others it does not happen to me sometimes the same cmd or another and literlamnete my log of ia does not iforma damage in fots neither in models something this zipiando badly the pack for some I can pass the log to you and several things if you want contact me to private I am in my sv with all my users.

**Comment by dinobossytnew** [comment]
[latest (1).log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11501514/latest.1.log)
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11501515/latest.log)
these 2 logs say that something is missing in the zip but of course I in the console when I use /iareload and iazip only warns me of small files that I did not place and it is my intention not to place them for now are only .metadata that are files that I have to add.

**Comment by dinobossytnew** [comment]
Some users load the pack perfectly and others not so well, I don't know what is wrong with them but 1 of the logs I passed to you shows the same as the one shown above.
The viaversion is not because it was working before.

**Comment by LoneDev6** [comment]
> to me it happens to me and it is not only that, it seems to me that viaversion is not in my pack sometimes to some it lets them enter and to others it does not happen to me sometimes the same cmd or another and literlamnete my log of ia does not iforma damage in fots neither in models something this zipiando badly the pack for some I can pass the log to you and several things if you want contact me to private I am in my sv with all my users.

Sorry I don't understand a word.

----

Anyway I cannot reproduce the issue, I even tried joining with different Minecraft versions so the issue is caused by something else we need to discover.

**Comment by dinobossytnew** [comment]
hmm check my server 1.19.4 - 1.19.3 java 17 , ip mc.valkycraft.com

**Comment by LoneDev6** [comment]
I'll wait for more info from the OP
