### ISSUE TITLE
[BUG] RPG Money

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#268]
**Describe the bug**
C'è un problema con RPGMoney che non fa droppare i soldi dai mob i mondi creati attraverso multiverse core.

Il plugin funziona perfettamente nei mondi generati di base

quindi world, world_nether e l'end

Ma in un mondo creato a parte... nonostante io abbia comunque specificato la sua esistenza in serverbooster e itemsadder ... i soldi non vengono droppati.

**Comment by LoneDev6** [comment]
Ciao non è un bug, devi aprire mobs.yml del plugin RPGMoney e copiare e incollare tutta la parte dei mob del mondo world e rinominarlo col nome del tuo mondo custom.

Come puoi vedere per ogni mondo c'è una sezione con prezzi diversi, così da bilanciare bene l'economia (esempio: per le farm del nether i mob droppano meno, mentre nel world normale gli stessi mob droppano di più).



fallo anche per blocks.yml sempre di RPGMoney.


Comunque non segnalare qui i bug di altri plugin, creerò delle altre pagine apposta su github
