### ISSUE TITLE
[BUG] Cant sit on furniture in towns. (Towny)

### ISSUE THREAD

**Issue by spiker5032** [LoneDev6/ItemsAdder#269]
**Describe the bug**
Outsiders with downy cannot sit on furniture because it says
"Outsiders cant destroy here"

**To Reproduce**
Make a town and ask someone to sit on furniture.

**Expected behavior**
Sit

**Screenshots**
https://cdn.discordapp.com/attachments/713843039898042389/714589900715982859/2020-05-25_17.24.43.png

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: default
 - Plugin version: 2.0.24

**Comment by LoneDev6** [comment]
In towny is it normally possible to sit on mobs and on minecarts/boats when you're in a town of another player?

let me know

**Comment by SirCraftypants** [comment]
Have you tried setting the worldguard flag `ia-furniture-sit` in each plot using the worldguard flag set command?
