### ISSUE TITLE
Some Suggestions.

### ISSUE THREAD

**Issue by SushiBarIV** [LoneDev6/ItemsAdder#27]
Hello,

- Making Armors repairable with those Materials, like repairing the Ruby Helmet with Rubys.
Maybe it could look like this in the config: ```repair_item: ruby``` (Should be working on Enchantments too, so they dont get removed)

- Shapeless Recipes (LonDev already know, but to sum up)

- Adding the Durability Text to all the tools in the **/ia** menu

- When an Sword for example, gets Enchanted with Sharpness, the Value in the Lore won't be 
higher. example: I have an Sword with 5 Attack Damage, so I enchant it with Sharpness 2, but the
Lore says it still has 5 Attack Damage, instead of 7 Attack Damage,  so the Message wont be updated.

Bugfixes:
- The Four Leaf Clover don't work with its luck feature.

**Comment by SushiBarIV** [comment]
- If you try to destroy a block in a protected region, the Protection Plugin doesn't matter,
  The Player gets the EXP from it and the Block for sure is protected, so they cant destroy it,
  but they get the EXP everytime they destroy the block.

**Comment by LoneDev6** [comment]
> 
> 
> Hello,
> 
>     *1 Making Armors repairable with those Materials, like repairing the Ruby Helmet with Rubys.
>       Maybe it could look like this in the config: `repair_item: ruby` (Should be working on Enchantments too, so they dont get removed)
> 
>     *2 Shapeless Recipes (LonDev already know, but to sum up)
> 
>     *3 Adding the Durability Text to all the tools in the **/ia** menu
> 
>     *4 When an Sword for example, gets Enchanted with Sharpness, the Value in the Lore won't be
>       higher. example: I have an Sword with 5 Attack Damage, so I enchant it with Sharpness 2, but the
>       Lore says it still has 5 Attack Damage, instead of 7 Attack Damage,  so the Message wont be updated.
> 
> 
> Bugfixes:
> 
>     *5 The Four Leaf Clover don't work with its luck feature.



> 
> 
>     6 If you try to destroy a block in a protected region, the Protection Plugin doesn't matter,
>       The Player gets the EXP from it and the Block for sure is protected, so they cant destroy it,
>       but they get the EXP everytime they destroy the block.



1. How would you be able to repair this? I wanted to stay as vanilla as possible, so you have to craft a new Ruby Pickaxe and put it+the old one in Anvil, to repair it.

2. I'll add them in some of next updates, it's not that easy to integrate on the current custom recipes behaviour

3. I'll fix this in next release, thanks!

4. I have to see how to add this feature, ty

5. https://minecraft.gamepedia.com/Luck Luck increases fishing and loot tables quality

6. You have to tell me which is the protection plugin. I'm using Worldguard and Griefprevetion and I have no issues

**Comment by LoneDev6** [comment]
Also please open a separate issue on github for every suggestion and problem or i can't handle it in the best way
