### ISSUE TITLE
[BUG] PlayerConsumeEvent ERROR

### ISSUE THREAD

**Issue by jdabrowsky** [LoneDev6/ItemsAdder#270]
On console I have a lot of "Could not pass event Player ItemConsumeEvent to ItemsAdder":
https://pastebin.com/G6xEpyp0

I noticed that if someone plant rice, instead of rice, grows wheat.

Regards,
JD

**Comment by LoneDev6** [comment]
Will be fixed in next update.

About the seconds issue of rice, what do you mean?
Please post the bug in separate issue page..

thanks
