### ISSUE TITLE
[BUG] repair to too many times and appear negative durability

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#271]
**Describe the bug**
repair to too many times and appear negative durability

**To Reproduce**
1. use demoniac hammer(I only test demoniac hammer) to low durability
2. repair it
3. Repeat 1,2 step many times

**Expected behavior**
can normal fix it 

**Screenshots**
https://youtu.be/62Rq1r5Ly0Q

**Info (please complete the following information):**
 - Server version: Spigot 1.15.2
 - Client version: fabric 1.15.2 with WWE
 - Plugin version: 2.0.24

**Additional context**

**Comment by LoneDev6** [comment]
Hello, can you please use /iatag command holding the bugged hammer and send me the result?
Thanks!

**Comment by Command1264** [comment]
![image](https://user-images.githubusercontent.com/50344708/83519698-0da17900-a50f-11ea-9a89-ee7d9022b602.png)

**Comment by Command1264** [comment]
{CustomModelData:10,Damage:1396,itemsadder:{namespace:"itemsadder",max_custom_durability:1561,id:"demoniac_hammer",custom_durability:-195,fake_durability:169.0d},display:{Lore:['{"text":"§7破壞方塊時會掉落經驗值"}','{"text":""}','{"text":"§b範圍 3x3x3"}','{"text":"§7耐久度： 169 / 1561"}'],Name:'{"text":"§f§4§l惡魔錘"}'},Enchantments:[{lvl:5s,id:"minecraft:efficiency"},{lvl:3s,id:"minecraft:fortune"},{lvl:3s,id:"minecraft:unbreaking"}]}

**Comment by LoneDev6** [comment]
Somehow custom durability and vanilla durability become negative after repair.
Please let me know after update if you still can do that.
I will publish the update today
