### ISSUE TITLE
[BUG] Changing the prefix in the language does not change it in game

### ISSUE THREAD

**Issue by SubliminalChaos** [LoneDev6/ItemsAdder#273]
I am using ItemsAdder, and when I change the prefix in the /plugins/ItemsAdder/lang/en.yml file, in the game the plugin continues to use the prefix "[ItemsAdder]".  I have successfully changed other messages, but changing the prefix in the en.yml file does not change it in game.

**To Reproduce**
1 Stop server.
2 Change the prefix in the en.yml file.
3 Restart server.
4 In game with needed permissions, execute: /iagive %player% itemsadder:hamburger 4
<<substitue %player% for a player!>>
5 The prefix on the message you see will be "[ItemsAdder]" not what you changed it to.

**Expected behavior**
Repeat steps 1-4 above, but in step 5 see the prefix that you selected.

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: Minecraft Launcher 2.1.14930 74aff9973027d6b19574aca645722dce58e1d587
 - Plugin version: 2.0.24

If questions about report can ask me on discord.  Hope I explained good.  - waqe

**Comment by LoneDev6** [comment]
Fixed, thanks
