### ISSUE TITLE
[Suggestion] API - Custom Block Break Event

### ISSUE THREAD

**Issue by brettsaunders21** [LoneDev6/ItemsAdder#274]
**Is your feature request related to a problem? Please describe.**
I have been developing a plugin using yours as a dependency and have built custom logic on top of the custom blocks which requires me to listen for block break event to de-register a block in my plugin. If a custom block is setup with something like only break with a pickaxe then you are cancelling the event, which I don't catch so I de-register the block.

**Describe the solution you'd like**
Create a custom onCustomBlockBreakEvent which is called when ever a custom block is broken and passes data from BlockBreakEvent

**Comment by LoneDev6** [comment]
Will be added in next update and available under the Events package :)
