### ISSUE TITLE
[BUG] Ores not dropping

### ISSUE THREAD

**Issue by Jirsaacek** [LoneDev6/ItemsAdder#275]
**Describe the bug**
When I get custom ores from iaget, iagive or ChestShop shop and place them, they have no drops. 
**To Reproduce**
1. Get ores with iaget or iagive command
2.  Place them
3. Break them
4. No drops... 

**Expected behavior**
Ores should drop materials they are supposed to

**Info (please complete the following information):**
 - Server version: Paper 1.15.2 #322
 - Plugin version: 2.0.24

**Additional informations**
Not dropping only when players place ores, when OP place them, it works fine.

**Comment by LoneDev6** [comment]
Are you in a no-drops protected area?
do you get any error in console?
did you disable anything in the configs?

thanks

**Comment by Jirsaacek** [comment]
There are no errors in console and it's happening everywhere, even in non-protected areas.

Here's config https://pastebin.com/FS24sYjw

Ty :)

**Comment by LoneDev6** [comment]
What is your world name?
Did you edit the file blocks.yml?

**Comment by Jirsaacek** [comment]
World name is "world" and here's blocks.yml, we changed nothing

https://pastebin.com/QqQbMqJi

Ty :)

**Comment by LoneDev6** [comment]
Can you make a video of the issue?
Thanks a lot

**Comment by Jirsaacek** [comment]
https://youtu.be/3U0mU-FXlBE

Ores in video are from ChestShop, iaget and iagive, as you can see, no drops :/

**Comment by LoneDev6** [comment]
Did you place them in survival? Try to place them in creative.
That's really strange.

Are vanilla ores dropping correctly?

**Comment by Jirsaacek** [comment]
Vanilla ores are ok.
When OP places them in survival or creative it's ok, but when players place them in creative or survival, it's not working.
Thanks a lot :)

**Comment by LoneDev6** [comment]
Mmmh... really strange, can you test this on a test server on your PC?
I suspect it's another plugin interfering.
Let me know, thanks a lot for your info

**Comment by Jirsaacek** [comment]
Tested on test server, still not dropping


![received_925514151203442](https://user-images.githubusercontent.com/63473875/83656478-e3f45a80-a5bf-11ea-9979-ed64e39e106b.png)

**Comment by 100petr** [comment]
The player destroy itemsadder ore with silk touch, when he place it and wanted to destroy without silk touch, nothing fell.

**Comment by QuiquePineyro** [comment]
I have the same problem

**Comment by LoneDev6** [comment]
Fixed in new update 2.0.27.
I removed previous check that prevented players from getting drops from placed blocks, idk why I added this check in the past
