### ISSUE TITLE
[Suggestion] hope can support drop mcMMo's exp

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#277]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
loots:
  blocks:
    end_diamond_ore:
      enabled: true
      type: itemsadder:end_diamond_ore
      items:
        DIAMOND:
          item: DIAMOND
          min_amount: 2
          max_amount: 5
          chance: 100
        mcmmo:
          item: mcmmo.mining.exp
          min_amount: 2
          max_amount: 5
          chance: 100
        

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/50344708/83356114-6bf71c00-a396-11ea-9b7d-854b207df887.png)

**Comment by LoneDev6** [comment]
You could create a custom item that issues[ this command](https://github.com/mcMMO-Dev/mcMMO/wiki/Command-reference#addxp) on right click: 
```
/addxp [player] <skill> <xp>
```

and make it drop from the block you want, this is the easiest way.

Read here about the execute_commands: https://itemsadder.plugin.ga/plugin-usage/adding-content/item-properties/events/actions

```yaml
execute_commands:
  first_example:
    command: 'addxp {player} mining 10'
    as_console: true
```
