### ISSUE TITLE
Problem with setting chairs while sneaking

### ISSUE THREAD

**Issue by Padlick01** [LoneDev6/ItemsAdder#28]
If you place a chair on a second floor of your house and the floor is only one block thick, it falls down to the first floor.

**Comment by LoneDev6** [comment]
I can't reproduce this. I'm using latest PaperSpigot

**Comment by Padlick01** [comment]
I use latest spigot. Maybe spigot bug then?

**Comment by LoneDev6** [comment]
I can reproduce this problem only on some houses, it's really strange

**Comment by LoneDev6** [comment]
wait.. maybe i misunderstood.
Are you shift-clicking the floor of your house while placing?
Shift+click when placing furnitures is useful if you want to make the furniture to be spawned inside the block. So if you have a barrel block you can for example shift+click it with mini_fridge and the fridge will act like a barrel.. try that
