### ISSUE TITLE
Bug items

### ISSUE THREAD

**Issue by choco3224** [LoneDev6/ItemsAdder#281]
**Is your feature request related to a problem? Please describe.**
from one day to the next the following error came up with some menu items

Paper-spigot 1.15.2

![imagen](https://user-images.githubusercontent.com/12982009/83496308-31d26b00-a4b9-11ea-87bc-7a573b859e21.png)
![imagen](https://user-images.githubusercontent.com/12982009/83496376-4dd60c80-a4b9-11ea-9951-34a9fefe6210.png)

**Comment by LoneDev6** [comment]
Please try to regenerate the pack using /iazip, upload to dropbox (if you're using dropbox) and use /iareload then /iatexture (from your client)

**Comment by choco3224** [comment]
I already did it and it's still the same

**Comment by LoneDev6** [comment]
So basically it randomly bugged out after a day?
Did you delete the files these categories are using?
For example I see the icons missing which are from mcicons folder

**Comment by Deathroner** [comment]
That happened to me loading new textures, I will soon report that since I left it on hold.

Anyway, the texture that I install, is visible only with OPTIFINE, but not with minecraft vanilla.

> Entonces, ¿básicamente salió al azar después de un día?
> ¿Eliminó los archivos que utilizan estas categorías?
> Por ejemplo, veo los iconos que faltan que son de la carpeta mcicons

**Comment by LoneDev6** [comment]
I suggest you to make sure your pack is updated, you used /iareload and /iatexture
