### ISSUE TITLE
[Suggestion] Custom Block Place Event

### ISSUE THREAD

**Issue by brettsaunders21** [LoneDev6/ItemsAdder#282]
**Is your feature request related to a problem? Please describe.**
When dealing with custom blocks, your plugin is replacing the block that the player places, this means that plugins using block place event would have to do something like a Delayed Runnable before checking if its a custom block and carrying out their own actions.

**Describe the solution you'd like**
Similar to my other feature request for block break event, add a custom block place event that passes normal block place event data, but is triggered when a custom block is placed. This would make it simpler to work with and also mean no need to check if custom block.

**Comment by LoneDev6** [comment]
Will be added in next update and available under the Events package :)

**Comment by brettsaunders21** [comment]
Thanks for the Interact and Break events. Just wondering if I missed something, you did or next update, but there doesn't seem to be a block place event.
Thanks

**Comment by LoneDev6** [comment]
Wops I forgot to add it, I will add this in the very next update
