### ISSUE TITLE
[BUG] can use multiple break with survival mode destroy survival mode can't destroy's block

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#285]
**Describe the bug**
can use multiple break with survival mode destroy survival mode can't destroy's block

**To Reproduce**
1. place command_block or other...
2. enter command "/gamemode survival"
3. enter command "/deop Command1"(no permission)
4. use can multiple break's tool to multiple break
5. see error

**Expected behavior**
they can't break

**Screenshots**
https://youtu.be/e6-Oe_PvdCk

**Info (please complete the following information):**
 - Server version: Spigot 1.15.2
 - Client version: fabric 1.15.2 with WWE
 - Plugin version: 2.0.25

**Additional context**

**Comment by LoneDev6** [comment]
Thanks, will be fixed in next update
