### ISSUE TITLE
[BUG] break to fast and repair it ,appear negative durability

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#288]
I don't know how to open it. So...

**Describe the bug**
break to fast and repair it ,appear negative durability
I test . Only demoniac hammer and diamond hammer have this bug

**To Reproduce**

1.use demoniac hammer to low durability repair it
2.Repeat 1,2 step many times
3.See error

or

1.use demoniac hammer with haste effect level 100 to break block(i think to fast to break block can spawn this error)
2.break block to low durability
3. See error

**Expected behavior**
durability must to positive durability 

**Screenshots**
https://youtu.be/62Rq1r5Ly0Q

**Info (please complete the following information):**
Server version: Spigot 1.15.2
Client version: fabric 1.15.2 with WWE
Plugin version: 2.0.26

**Additional context**
demoniac hammer:
{CustomModelData:10,Damage:1541,itemsadder:{namespace:"itemsadder",max_custom_durability:1561,id:"demoniac_hammer",custom_durability:-30,fake_durability:22.0d},display:{Lore:['{"text":"§7破壞方塊時會掉落 經驗值"}','{"text":""}','{"text":"§b範圍 3x3x3"}','{"text":"§7耐久度： 22 / 1561"}'],Name:'{"text":"§f§4§l惡魔錘"}'}}

diamond hammer:
{CustomModelData:2,Damage:1539,itemsadder:{namespace:"itemsadder",max_custom_durability:1561,id:"diamond_hammer",custom_durability:22,fake_durability:22.0d},display:{Lore:['{"text":"§7耐久度： 22 / 1561"}'],Name:'{"text":"§f§f鑽石槌"}'}}

**Comment by LoneDev6** [comment]
I think I cannot reproduce this in 2.0.17, please update and let me know.
I will publish it today
