### ISSUE TITLE
[BUG] flow, fall

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#289]
**Describe the bug**
Water / lava does not flow, gravel / sand does not fall

**To Reproduce**
1. Go to ocean biome
2. Destroy blocks using demoniac hammer
3. Water / lava does not flow, gravel / sand does not fall

**Expected behavior**
Water /lava will flow and gravel / sand will fall

**Screenshots**
![2020-06-04_18 26 10](https://user-images.githubusercontent.com/29830635/83785316-6dc02880-a691-11ea-9a85-0dcc2d953b06.png)
![2020-06-04_18 26 21](https://user-images.githubusercontent.com/29830635/83785319-6ef15580-a691-11ea-9e8e-cb7126cca1d9.png)
![2020-06-04_18 26 31](https://user-images.githubusercontent.com/29830635/83785325-6f89ec00-a691-11ea-825b-756131161738.png)

**Info (please complete the following information):**
 - Server version: paper 1.15.2 #334
 - Client version: optifine 1.15.2
 - Plugin version: 2.0.25

**Additional context**
Slimefun has an explosive pickaxe which destroys 3 * 3 * 3 and water flows and gravel falls.

**Comment by LoneDev6** [comment]
I don't think I will fix this because this "bug" is intentional.
I don't update physics of blocks to avoid lag
