### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by loganpenin1** [LoneDev6/ItemsAdder#290]
I have a problem using Towny and ItemsAdder. The problem it's that when I use both plugins in my testing servers I can see the actionbar with no problems. Then I put the same configuration in the server of my community and I see every-actionbar of every plugin (and it alternates between mana and thirst bar) except the towny wich is the most important actionbar for my server, and I don't know why, because in my testing server it works. My question is if I can set the priority of the actionbar used by ItemsAdder. Maybe I can priorize the towny actionbar.

**To Reproduce**
1. Go to or any server with towny and ItemsAdder
2. Enter a town field or the wilderness and see that the actionbar can be showed or not (not in my case)
3. You can see titles if configured, but not actionbar wich normally says the propietary of that chunk.

**Expected behavior**
See actionbar of towny wich says the propietary and if that chunk it's on sale.

**Screenshots**
What should happen:
![image](https://user-images.githubusercontent.com/66191749/83932465-172e1980-a779-11ea-8f7e-5696d95e01a7.png)

![image](https://user-images.githubusercontent.com/66191749/83932488-375dd880-a779-11ea-885e-97964509123e.png)

What actually happens in my main Server:
(There is not alternancy betweent actionbars)

![image](https://user-images.githubusercontent.com/66191749/83932503-53617a00-a779-11ea-85f5-b7d965444d2e.png)

**Info:**
 - Server version: paper 1.15.2
 - Client version: fabric 1.15.2
 - Plugin version: 
        - For ItemsAdder - 2.0.25
        - For Towny - 0.96.1.0

**Comment by LoneDev6** [comment]
This cannot be fixed as ItemsAdder uses actionbar to show its custom HUDs.
You'd have to check if Towny has a setting to use chat/bossbar instead of actionbar to show messages.
