### ISSUE TITLE
[BUG] Ores in exorbitant amounts.

### ISSUE THREAD

**Issue by Deathroner** [LoneDev6/ItemsAdder#291]
I decided to report this as it is the 3rd time I got caught on this. I would like you to integrate something to solve this problem, which incidentally, causes the tps of my server to drop excessively.

The amount of ores are exorbitant, the truth is that I had to restart the map from scratch for this.  
But will it happen again?

At the moment, I have disabled "ItemsAdder" to avoid this and to be able to back up the maps of my users -.-

I will leave you a video, and my main settings are the default settings, I have not touched anything and it is not the first time this happens, I need to deliver the server on June 15, but I do not know if this will happen again, it is really annoying .

**Evidence**
https://youtu.be/fSpBbIpCo5w

config.yml: https://pastebin.com/2hL1rzBK
converter.yml: https://pastebin.com/VgjRN7gd

minerals.yml: https://pastebin.com/bvyRsFvp

I would be grateful if you could bring a solution to this problem, since I am sure it will happen again and again, because it happened to me two times before.

I await your response.

**Info:**
 - Server version: Tuinity 1.15.2 
 - Client version: Optifine 1.15.2
 - Plugin version: ItemsAdder 2.0.26

I updated the plugin, but the problem is from previous versions, I am telling you for sure.

**Comment by Zangerine** [comment]
This isn't a bug at all. Go into ItemsAdder/data/items_packs/itemsadder/ and edit blocks.yml.

Go to "worlds_populators:" and either remove the ores from the populator or change their "chance:" setting to something lower (i.e. Ruby from 70% chance to 5% chance).

**Comment by LoneDev6** [comment]
I think you probably edited the blocks.yml in order to spawn too many ores, you should leave it as default
