### ISSUE TITLE
[BUG] Console spam

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#292]
**Describe the bug**
In console are spamming numbers

**To Reproduce**
1. Destroying blocks with demoniac hammer
2. See console 

**Expected behavior**
They will not spam numbers

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/29830635/83936614-6601a080-a7c5-11ea-86de-c69ffd237b86.png)

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: 1.15.2
 - Plugin version: 2.0.26

**Comment by LoneDev6** [comment]
Fixed, thanks
