### ISSUE TITLE
When minerals are produced, add conditions to determine the biome

### ISSUE THREAD

**Issue by yebanme** [LoneDev6/ItemsAdder#293]
Minerals can now be specified only in certain worlds, but not in certain biomes,If biome can be specified, different minerals can be found in different biome

They look something like this
worlds_populators:
  ruby_ore:
    block: itemsadder:ruby_ore
    worlds:
    - world
    **biome:
    - savanna**
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 50.0
    max_height: 45
    min_height: 25
    amount: 2
    iterations: 1

**Comment by LoneDev6** [comment]
https://github.com/LoneDev6/Issues-ItemsAdder/issues/124

**Comment by LoneDev6** [comment]
Added
