### ISSUE TITLE
[BUG] [REOPEN] Ore Spawn info doubles on /iareload

### ISSUE THREAD

**Issue by Padlick** [LoneDev6/ItemsAdder#298]
**Describe the bug**
Everytime you do "/iareload", the ore spawn info in /ia doubles.
It should be fixed since 2.0.25 but isn't.

**To Reproduce**
1. Do "/ia" and see it one time
2. Do "/iareload"
3. Do "/ia" and see it two times
4. Do it again and see it three times

**Expected behavior**
After "/iareload" it should be written only one time

**Screenshots**
Video: https://youtu.be/6f6HYfoy9QE

**Info (please complete the following information):**
 - Server version: paper 1.15.2 git-paper-301
 - Client version: 1.15.2 + optifine
 - Plugin version: 2.0.26

**Comment by LoneDev6** [comment]
Thanks, fixed now
