### ISSUE TITLE
[BUG] multiple break drops ores instead of coal, diamonds, redstone etc

### ISSUE THREAD

**Issue by Padlick** [LoneDev6/ItemsAdder#299]
**Describe the bug**

**To Reproduce**
1. get a diamond or demoniac hammer WITHOUT silk touch
2. break a cobblestone or something else with coal ore, redstone ore etc around it
3. get coal ore instead of coal, same goes for redstone, diamonds, lapis, etc

**Expected behavior**
It should drop coal, diamonds, etc instead of it's ores. 

**Info (please complete the following information):**
 - Server version: paper 1.15.2 git-paper-347
 - Client version: 1.15.2 + optifine
 - Plugin version: 2.0.26

**Comment by LoneDev6** [comment]
Strange, I tested with my current version with no issue, try to update to 2.0.27 maybe I fixed it some weeks ago and I don't remember.
I will publish the update today
