### ISSUE TITLE
problem with diamond hammer

### ISSUE THREAD

**Issue by Padlick01** [LoneDev6/ItemsAdder#30]
My config options for diamond hammer:

diamond_hammer:
  enabled: true
  permission: diamond_hammer
  model_id: 2
  vanilla_type: DIAMOND_PICKAXE
  name: '&3&lDiamanthammer'
  lore:
    - "&7Baut eine 3x3 Fläche ab"
  events:
    block_break:
      multiple_break:
        keep_ores: false
        drop_all_blocks:
          enabled: true
          need_silk_touch: false
        size: 3
  craft_recipe:
    enabled: true
    pattern:
      - ddd
      - dsd
      - XsX
    ingredients:
      s: STICK
      d: DIAMOND

Problem:
It is breaking every block how it should, but redstone ore remains. It is the only block the diamond hammer isn't mining in a 3x3 (as my team and users see atm)

**Comment by LoneDev6** [comment]
the hammer doesn't drop ores even if it has drop_all_blocks or silktouch enabled, it would be too OP.
Your users have to break the ores with another pickaxe after revealing them with the hammer

**Comment by Padlick01** [comment]
First thing.
I think, the decision for "what is op?" is a thing, that the network decides.

Second.
If you have the option "keep-ores" and I set it to false, then I want to have it on false. So that the hammer breaks everything and drops everything.

**Comment by LoneDev6** [comment]
let me know if it's fixed

**Comment by Padlick01** [comment]
Jep, it's fixed. Thank you :)
Sorry that I was a bit rude. Hadn't a good day. 

But different, I dont know why, but the hammer doesnt work for some people. For some it does, for some it doesnt everytime. Also we removed our Anticheat but same thing.

**Comment by LoneDev6** [comment]
> 
> 
> Jep, it's fixed. Thank you :)
> Sorry that I was a bit rude. Hadn't a good day.
> 
> But different, I dont know why, but the hammer doesnt work for some people. For some it does, for some it doesnt everytime. Also we removed our Anticheat but same thing.

no problem!
it's strange btw.. maybe some plugin interfering? a lot of plugins are bad coded and interfer with simple things I do in my plugin..
