### ISSUE TITLE
McMMO Infinite XP Bug

### ISSUE THREAD

**Issue by Jamm95** [LoneDev6/ItemsAdder#300]
**Description**
If you use a tool which can't break a block to break a block (for example: custom axe to break a custom block which can't be broken by axes), it will still give you the McMMO XP for "breaking" said block. You can do it infinitely for unlimited XP.

**To Reproduce**
Use a custom axe to break a custom block while McMMO is enabled.

**Expected behavior**
The block should not give any McMMO XP since it was not really broken.

**Info**
 - Server version: Paper 1.15.2
 - Client version: Vanilla
 - Plugin version: 2.0.26

**Comment by LoneDev6** [comment]
Should be fixed in 2.0.27, please let me know after the release is online
