### ISSUE TITLE
Custom ores only generate in the level-name world

### ISSUE THREAD

**Issue by byXToGo** [LoneDev6/ItemsAdder#302]
Custom ores can only generate in the level-name world that's set in the server.properties. Because minecraft stores the player data in this world it's impossible to regenerate the world as farmworld which makes the ore generation feature nearly useless for all servers that have a farmworld. I hope this can be fixed asap ^-^

**Comment by Padlick** [comment]
Not that correct. You can change, where ore's spawn. 
(ItemsAdder > data > item_packs > itemsadder > blocks.yml > world-populators)
When you have an farmworld plugin, you have to regenerate the world and after that do "/iareload". Then the ores willl spawn in that worlds correctly.

**Comment by byXToGo** [comment]
Well, that's the point. This doesn't work. When I change the world where they spawn, they don't generate. I've reloaded the plugin, restarted the server, recreated the world. But when I set the desired world as as the level-name, it works

**Comment by LoneDev6** [comment]
I don't understand the issue.
You can add as many worlds you want, just set it in the blocks.yml file

https://itemsadder.plugin.ga/faq/blocks-minerals-issues/i-cant-find-any-mineral-ore

**Comment by byXToGo** [comment]
I've described my problem well enough. I know that I can set other worlds on the yml file but it doesn't work unless the world is also the one specified as level-name. And that's the issue I'm reporting. I'm well aware that this isn't correct but then I wouldn't report it here.

**Comment by Xuwznln** [comment]
are you using 1.16?

**Comment by LoneDev6** [comment]
Did you try enabling `log-generation` in your config.yml? It will print in console each time an ore is generated.
Keep in mind that the world must not be a pregenerated world and you must visit new chunks in order to see ores generated.
https://itemsadder.plugin.ga/faq/blocks-minerals-issues/i-cant-find-any-mineral-ore

Let me know

**Comment by LoneDev6** [comment]
Any news?
