### ISSUE TITLE
[BUG]  Text character error

### ISSUE THREAD

**Issue by 1425115471** [LoneDev6/ItemsAdder#304]
1. Text character error
![image](https://user-images.githubusercontent.com/29402452/85028400-9d9d1f00-b1ad-11ea-8fe3-7308d4294d5c.png)
![image](https://user-images.githubusercontent.com/29402452/85028433-a55cc380-b1ad-11ea-8cf1-9455d1b073e6.png)

2.How to hide the line of the first picture

- Server version: (example: paper 1.15.2)
 - Client version: (example: fabric 1.15.2)

**Comment by R-Josef** [comment]
Please open your client and turn off force unicode in option - language. these boxs are font characters whitch is not display.

**Comment by LoneDev6** [comment]
https://itemsadder.plugin.ga/faq/huds-emojis-guis-font/i-cant-see-emoji-guis-huds
