### ISSUE TITLE
[Suggestion] Config to completely disable Custom Blocks

### ISSUE THREAD

**Issue by Maitlans** [LoneDev6/ItemsAdder#306]
**Is your feature request related to a problem? Please describe.**
I'm already setup using MMOItem's for my custom blocks and I recently found out about ItemsAdder which adds a lot of functionalities but it's conflicting with MMOItem's custom blocks and it's making them not show.

**Describe the solution you'd like**
Completely disable Custom blocks in ItemsAdder's side. To allow for the MMOItem's compability.

**Comment by Zangerine** [comment]
Just empty the blocks.yml file and save a blank file. Don't delete it as it'll remake the file on reboot.

**Comment by LoneDev6** [comment]
Please send me some info about MMOItem blocks and also how it's conflicting with it

**Comment by Maitlans** [comment]
Hello, so the issue is when I have ItemAdder on and I place an MMOItem's custom block it won't actually place it it'll just be a regular mushroom block, at times it'll flash the block and then revert to a regular mushroom block. As well as existing placed MMOItem blocks will break with ItemAdder enabled. 

I'm not sure if this link would help but: https://github.com/Indyuce/mmoitems/wiki/Custom-Blocks

**Comment by LoneDev6** [comment]
MMOItem should implement ItemsAdder API and check if it's an ItemsAdder block, then avoid resetting the placed block data
