### ISSUE TITLE
Error in obtaining item after adding configuration file

### ISSUE THREAD

**Issue by DaBinin** [LoneDev6/ItemsAdder#3095]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

DaBin#3056

### What happened?

I added the PNG file I wanted, but what I obtained in the game was a paper

### Steps to reproduce the issue

I'm not sure

### Server version

implementing api version 1.19.4-R0.1-SNAPSHOT

### ItemsAdder Version

itemsadder version 3.6.1-beta

### ProtocolLib Version

Protocolib version 5.0.0

### LoneLibs Version

lonelibs version 1.0.27

**Comment by LoneDev6** [comment]
Please provide your server log.
It's impossible to help without any information.
