### ISSUE TITLE
Block Position/rotate

### ISSUE THREAD

**Issue by AlChimiK2D** [LoneDev6/ItemsAdder#31]
I have a problem : the blocks from the plugin have a 45° rotation fail.
https://zupimages.net/up/19/32/9ofa.png

**Comment by LoneDev6** [comment]
Hi, as I said in forum this is only a client glitch when you disable use_lightweight_blocks in config or when you use model_id > 160.
In order to fix the rotation just leave server and rejoin

**Comment by LoneDev6** [comment]
Should be fixed in IA 2.0 (I'm going to publish it in some days).
I added a small delay on each block place event and seems to have fixed that problem.
If that happens again please reopen this issue on github. Thanks
