### ISSUE TITLE
[HELP] New item texture, mixed with other items

### ISSUE THREAD

**Issue by Deathroner** [LoneDev6/ItemsAdder#311]
**Describe the bug**
We created a Twitch cap in blockbench, in the program it looks perfect, but when installing it in ItemsAdder, it mixes with the texture of some plugin blocks.

Is there anything you recommend to me to fix this?

**Screenshots**
https://imgur.com/a/h1UcAvM

**Info (please complete the following information):**
 - Server version: PaperMC 1.16.1 (I updated today, but it also happened in previous versions)
 - Client version: Minecraft 1.15.2
 - Plugin version: 2.0.30

**Additional context**
I want to keep adding new items to the server, but I would like a suggestion from you to improve them, maybe you think wrong; I do not know.

**Comment by LoneDev6** [comment]
mhhh this is really strange, please open the cap json file you have in the pack.zip file and check if its textures are right.
ItemsAdder is not editing any texture so surely it's a mistake your artist did while exporting the texture.

let me know

**Comment by Deathroner** [comment]
https://imgur.com/a/RkjBAaG

This is what the texture looks like in blockbench
I export the file in .json

https://pastebin.com/gqUkCfTV

Do you think there is an error? At least I notice that it is fine ... Sorry for asking these kinds of questions; but i would like to understand what i am failing so i dont have to bother you with this.

**Comment by LoneDev6** [comment]
No seems to be fine.. are you using optifine or similar?
it's really strange as it has nothing to do with ItemsAdder, seems Minecraft is loading the wrong texture

Check if these files are right:
        "1": "itemsadder:items/s2s2",
        "2": "itemsadder:items/negro",
        "3": "itemsadder:items/twitch",
        "particle": "itemsadder:items/s2s2"

they should be in the folder:
assets\itemsadder\textures\items\.....

(anyway you should not use the folder "items" but the folder "item"
