### ISSUE TITLE
[BUG] Items from ItemsAdder are changed when being creative

### ISSUE THREAD

**Issue by Deathroner** [LoneDev6/ItemsAdder#313]
When getting an item from ItemsAdder in creative mode, the items become what the texture is based on.

For example, the mysterious sword is changed to a diamond sword.
It happens with all the items, but I realized that it only happens when in creative game mode.

I made a video so you can see what happens.

Also when viewing the NBT information before and after, you can see that it changes; loses the attributes of "ItemsAdder"

**Video:** https://youtu.be/N10aEv-YHO0

 - Server version: PaperMC 1.16.1
 - Client version: Vanilla 1.16.1
 - Plugin version: ItemsAdder 2.0.32

**Comment by Deathroner** [comment]
- When this happens, there is no error in console

**Comment by LoneDev6** [comment]
This bug is not related to itemsadder, please try the plugin on a clean server.
There is surely another plugin which is interfering. I suspect ViaVersion but I'm not sure.

Thanks for the report
