### ISSUE TITLE
[ERROR] InventoryClickEvent to ItemsAdder v2.0.32

### ISSUE THREAD

**Issue by Deathroner** [LoneDev6/ItemsAdder#314]
I have an error in the console, I do not know the reason why it happens. But I inform you so that you are aware.

https://pastebin.com/3jv1Ugx4

- Server version: PaperMC 1.16.1
- Client version: Vanilla 1.16.1
- Plugin version: ItemsAdder 2.0.32

**Comment by Alejitus** [comment]
In my case it happens when renaming or trying to rename an item in an anvil.

https://pastebin.com/Eg8eGSTw

**Comment by LoneDev6** [comment]
Thanks, will be fixed in next update
