### ISSUE TITLE
[BUG] Item Can't Repair or Craft if Material Change Its Name

### ISSUE THREAD

**Issue by Xuwznln** [LoneDev6/ItemsAdder#315]
**Describe the bug**
Upgraded from 1.15 to 1.16, get item from IA menu will have different name with 1.15. This cause old material cant be used anymore unless I correct its name manually. Is it possible to detect item usage with item nbt? I think itemsadder.id is a nice identity.

**To Reproduce**
1.get a material like amethyst
2. change its item name
3. try crafting with it.

**Info (please complete the following information):**
Paper1.16.1-36
ItemsAdder 2.0.32

**Comment by LoneDev6** [comment]
Mhh what do you mean with "has different name with 1.15", I didn't change anything

Please make some screenshots to explain

**Comment by Xuwznln** [comment]
Item that get from 1.15.2
![O0SGX20(2943GE4Q`FSGQWK](https://user-images.githubusercontent.com/18435084/86468481-108bc580-bd6a-11ea-8a33-c0524989ce8a.png)
![P`JA 6GP5223%VK9D0)J3EL](https://user-images.githubusercontent.com/18435084/86468490-1681a680-bd6a-11ea-8d9b-b36bbcd3f686.png)

Item that get from 1.16.1
![~I5%5QQQ1W(UJ}9Z78VR00F](https://user-images.githubusercontent.com/18435084/86468506-1e414b00-bd6a-11ea-9ab1-21f7119b2a67.png)
![V3VW2LNG{~IH(GT{HW{2G81](https://user-images.githubusercontent.com/18435084/86468509-200b0e80-bd6a-11ea-8cd7-d07ca50ff53a.png)

**Comment by LoneDev6** [comment]
Mmh... really strange, recipes should ignore item name.. that's strange

**Comment by Xuwznln** [comment]
Still no, I tested on Paper-46

**Comment by LoneDev6** [comment]
Will be fixed in next update, thanks for the report!
