### ISSUE TITLE
API Methodes to interact with thrist and mana

### ISSUE THREAD

**Issue by imparium-de** [LoneDev6/ItemsAdder#316]
**Is your feature request related to a problem? Please describe.**
Yes, first we a running a bungeecord network and we need some methodes to synchronize the mana and thrist between servers
also we want to add some custom items which use mana and bring some features that we can't aqquire with itemsadder alone

**Describe the solution you'd like**
Some methodes like
public static int getThirstLevel(Player target){

}

and 
public static void setThirstLevel(Player target,int level){

}
//Same for mana

**Describe alternatives you've considered**
well a other idea where a ThristLevelChangeEvent und ManaLevelChangeEvent its not really a alternative but it would be usefull to 
Thanks in advance
- ImparumServerTeam

**Comment by LoneDev6** [comment]
Hello!

You can already access these values using the current API :D

```Java
PlayerHUDsHolderWrapper huds = new PlayerHUDsHolderWrapper(player);
PlayerQuantityHudWapper manaHud = new PlayerQuantityHudWapper(huds, "magiccraft:mana_bar");
manaHud.setFloatValue(2.0f);
```

There is also a command `/iaplayerstat write LoneDev mana float 3` (in this case you use the player_stat_name, not the namespaced id of the mana bar)


I see you need some events, but the easiest thing to do it to sync the mana value between servers when the user leaves one server and enters the other one
