### ISSUE TITLE
Grenades bypass essentialsx protection

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#3166]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

pitilon

### What happened?

On the server, I use essentialsx + essentialsxprotect as protection against the destruction of blocks by explosions (tnt, creeper, ...). Using an itemsadder grenade still destroys blocks. From what I found out from the players, it's nothing new and it's been going on for at least six months.

### Steps to reproduce the issue

Download essentials, essentialsprotect, IA
Turn on explosion protection in essentials
Try the grenade from IA

### Server version

Current: git-Purpur-2062 (MC: 1.20.1)*
Previous: git-Purpur-2060 (MC: 1.20.1)
* You are running the latest version

### ItemsAdder Version

ItemsAdder version 3.6.2-beta-r4

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### LoneLibs Version

LoneLibs version 1.0.27

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/PluginBugs/Issues-ItemsAdder/assets/29830635/a9772dc1-3634-4c56-be2a-209d9b32ff5f)
I have all explosion protection enabled in essentials.

https://github.com/PluginBugs/Issues-ItemsAdder/assets/29830635/7b5c5840-b7b1-4f84-83dc-15234c5528fb

**Comment by LoneDev6** [comment]
This is a totally different issue compared to the linked ones and was already fixed.


https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/f4d10d82-7ac2-4aad-94f9-f08edaf0c1fc


What you are reporting here seems to be related to grenades explosions not respecting EssentialsX rules.
To create explosions I use this Bukkit code:
```java
world.createExplosion(block.getLocation(), power, false, true, player)
```



https://github.com/PluginBugs/Issues-ItemsAdder/assets/27242001/4a322174-652c-49ae-9620-786a6e807512



As you can see I call the `createExplosion` method and I also specify the player as parameter.
EssentialsX should listen to the proper Bukkit event and avoid explosions triggered by the Bukkit API from damaging blocks.
This also damages vanilla blocks, it's not only an ItemsAdder blocks problem, the two issues are unrelated.

[EntityExplodeEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityExplodeEvent.html), [BlockExplodeEvent](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/block/BlockExplodeEvent.html).
