### ISSUE TITLE
[BUG] ia blocks turns to mushroom

### ISSUE THREAD

**Issue by Agaloth** [LoneDev6/ItemsAdder#319]
**Describe the bug**

**To Reproduce**
1. Go to somewhere to build
2. Use ia blocks and make a floor our of it
3. once you made a 32x32 floor with the same block break one somewhere
4. Mushroom should spread when trying to break mushroom blocks

**Expected behavior**
Having the custom blocks turned into mushroom and have to break the whole floor to fix it.

**Screenshots**
![A5EF8DD0-08FA-47ED-BEA8-EE81E006DD38](https://user-images.githubusercontent.com/33335971/86923121-e8b3ad80-c12d-11ea-9057-11056ed30280.png)

**Info (please complete the following information):**
 - Server version: Paper build 370
 - Client version: 1.14.4 - 1.15.2
 - Plugin version: 2.0.32

**Additional context**
The builds were here for 8 days

**Comment by LoneDev6** [comment]
Closing as said via Discord private message, will reopen if the issue would happen again
