### ISSUE TITLE
Custom blocks does not damage tools

### ISSUE THREAD

**Issue by MrCoby220** [LoneDev6/ItemsAdder#32]
Custom blocks do not use durability on your tools since they are mushrooms could be fixed by checking when a custom block is broken and manually removing durability off the held tool, here is a fix i made that could be improves

`public static void damageTool(Player player, Block block) {
    ItemStack item = player.getInventory().getItemInMainHand();
    Damageable damage = (Damageable) item.getItemMeta();
    if(damage.getDamage() >= item.getType().getMaxDurability()-1) {
        player.playSound(player.getLocation(), Sound.ENTITY_ITEM_BREAK, 1, 1);
        player.getWorld().spawnParticle(Particle.ITEM_CRACK, player.getLocation().add(0, 1, 0), 10, item);
        player.getInventory().setItemInMainHand(new ItemStack(Material.AIR));
        player.getWorld().dropItemNaturally(block.getLocation(), ItemsAdder.getCustomBlock(block)); //Need to be changed to the item drop thats in the config
        block.setType(Material.AIR);
    }else {
        damage.setDamage(damage.getDamage()+1);
        player.getInventory().getItemInMainHand().setItemMeta((ItemMeta) damage);
    }
}`

**Comment by LoneDev6** [comment]
Thanks I'll include this fix in next releases :D
