### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by tlw12344** [LoneDev6/ItemsAdder#323]
ive installed the plugin multiple times from fresh installs and tried converting my old files i get the plugin to run fine but that asoon as i do /ia and click something i get kicked off my server with is error 

 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: minecraft:generic_armor  

it pretty much bans me from joining and the only way of joining back is to delete the plugin im not too sure what the problem is as we have had this on the 1.15.2 java server and it ran fine updating to the itemsadder v2 on 1.16.1 has seemed to have broke it

**Comment by LoneDev6** [comment]
You're using an old 1.16.1 build, please install latest ItemsAdder + latest spigot build.
https://serverjars.com/
