### ISSUE TITLE
[BUG] ItemsAdder WorldEdit - //replace & copy/paste & undo

### ISSUE THREAD

**Issue by Golshr** [LoneDev6/ItemsAdder#328]
**Describe the bug**
The //replace command does not seem to work when block to replace is a ItemsAdder block (//replace <thisone> <block>) and show a "Too many arguments." error.
The copy/paste command does not give the same result, IA blocks in result are replaced by other IA blocks.
Undo comment does not give the same result as before the last command

**To Reproduce**
1. Select 2 points with WorldEdit
2. do //replace <iablock> <block>
It looks like when there is an IA block in the first position, the replace command act like //set command

When you copy/paste a bunch of blocks, or when you replace them with normal blocks with a command and then undo it, every REAL blocks are replaced by TILE blocks

**Screenshots**
see https://imgur.com/a/7hHhvJA (see comments for context)

**Info (please complete the following information):**
 - Server version: Spigot 1.15.2
 - Client version: Optifine 1.15.2
 - Plugin version: 2.0.37

**Additional context**
Please note that : 
- in real_blocks_ids_cache.json, the white block that being replaced/set to emerald is id 55
- in items_ids_cache.json, the pink block that is not supposed to be here is id 55

**Comment by LoneDev6** [comment]
Thanks! I'm trying to find the best way to fix this, actually it's a bit difficult to bypass this problem because of how Worldedit api works, my addon is an "hack" for Worldedit because its api doesn't provide everything I need.

I will try to fix this bug this week

**Comment by LoneDev6** [comment]
Should be fixed in some of the latest updates for ItemsAdder addon 
https://www.spigotmc.org/resources/extension-itemsadder-worldedit.79012/
