### ISSUE TITLE
can't make my  custom thing 

### ISSUE THREAD

**Issue by MusicTW** [LoneDev6/ItemsAdder#33]
![2019-08-15_19 13 47](https://user-images.githubusercontent.com/52475422/63091599-6ceac880-bf91-11e9-9ab6-d6f47217c602.png)
![2019-08-15_19 15 04](https://user-images.githubusercontent.com/52475422/63091601-6ceac880-bf91-11e9-83c4-4c6421d5de9d.png)

**Comment by LoneDev6** [comment]
https://lonedev.gitbook.io/itemsadder/faq/compatibility-with-other-plugin

> - CraftEnhance, this plugin messes up ItemsAdder custom recipes logic and creates duplication bugs. So please don't use it 
> - Plugins that customize crafting table behaviour and recipes

Please check if you have some plugin that messes up with recipes, try the plugin on a clean server with only ItemsAdder installed
