### ISSUE TITLE
[Need improve] Custom Ores

### ISSUE THREAD

**Issue by a7ssan** [LoneDev6/ItemsAdder#332]
**Describe the bug**
You can find ores at any height

**To Reproduce**
1. Create world with EWG
2. Pre-generate world
3. Open X-ray
4. Look ores where spawn

**Expected behavior**
Ores under Grass by 1 block only!!

**Video**
https://youtu.be/mE158PB9M0U

**Info (please complete the following information):**
 - Server version: Spigot 1.16.1 (latest build)
 - Client version: fabric 1.16.1 & x-ray mod
 - Plugin version: 2.0.37

**Additional context**
Using epic world generator plugin.

**Comment by LoneDev6** [comment]
Post screenshots please, thanks

**Comment by LoneDev6** [comment]
This is not a bug, you have to open blocks.yml file and remove DIRT from materials list in ruby_ore populator.

```yaml
replaceable_blocks:
    - STONE
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL```
