### ISSUE TITLE
[Suggestion] Custom Emojis API

### ISSUE THREAD

**Issue by BurakDorman** [LoneDev6/ItemsAdder#333]
We can use the expression "ItemsAdder.getCustomItem("mcicons:icon_confirm")" with Skript to get custom items directly, that's nice but what about custom emojis? I did try their unicode number but they wasn't parsed. I need to use custom emojis with Skript. Please add some API to get emojis, thanks!

**Comment by LoneDev6** [comment]
You can already get emojis using the ItemsAdder java api: 
```Java
new FontImageWrapper("twitteremojis:confirm").getString()
```

I will add also skript method in next update:
```
command /emojitest:
	trigger:
		set {iconConfirm} to fontimage "twitteremojis:confirm"
		message "Good: %{iconConfirm}%"
```
