### ISSUE TITLE
[BUG] Itemsadder

### ISSUE THREAD

**Issue by JeotekINV** [LoneDev6/ItemsAdder#341]
te lo spiego brevemente , metto la tx dell'acqua e della birra ( fatte da me ) dentro la texture su itemsadder/texture/item e dopo dalla cartella data/items_pack/itemsadder/drinks aggiungo i vari dati per fare l'acqua e la birra indicando dove giusto anche la texture da prendere per l'acqua e quella epr la birra, però dopo avere caricato la tx e reloaddato mi mostra la texture del bloody mary su entrambi le bibite aggiunge , come se venne prese di default , come posso fare?

**Info (please complete the following information):**
 - Server version: paper 1.14.4)
 - Plugin version: 2.0.41

**Comment by LoneDev6** [comment]
Send me your full server log
