### ISSUE TITLE
Cant change the attack damage flag and cant hide it[BUG] 

### ISSUE THREAD

**Issue by Bobbyharron** [LoneDev6/ItemsAdder#342]
Im trying to delete the attack damage and attack speed flag but any of the hide flags works, then i realized the flags are on the english file with also dont works when you edit it, i tried to delete the lines and change a single letter and it just dont change.

**Comment by LoneDev6** [comment]
Please elaborate, I don't understand what you are trying to do.
Thanks and have a nice day
