### ISSUE TITLE
[BUG] RessourcePack CustomModelData

### ISSUE THREAD

**Issue by istarengwa** [LoneDev6/ItemsAdder#343]
**Describe the bug**
Hello, I have a problem, when I use an item to make a texture with the "custommodeldata" it does not work when it is already used by the plugin. While it works when the base minecraft item is not used by itemadders. I have to turn off my machine, then turn it on to make a modification of the files already used by itemadders, and my job is to delete at first /iazip

**Expected behavior**
I would like that as for a file not used by the plugin, it works

**Screenshots**
https://zupimages.net/viewer.php?id=20/31/4aly.png    :  An item that doesn't work with a single itemadders item
https://zupimages.net/viewer.php?id=20/31/0ssg.png   :  An item that does not work with multiple itemadders items
https://zupimages.net/viewer.php?id=20/31/oztt.png    :  A working object without an itemadders item

**Info (please complete the following information):**
 - Server version: purpur-688 (paper spigot 130)
 - Plugin version: 2.0.41

**Comment by LoneDev6** [comment]
You can create a "dummy" item to "lock" the custommodeldata you need to be set to a specific png file or json model
https://itemsadder.plugin.ga/plugin-usage/adding-content/item-properties/resource#manually-specify-custom_model_data
