### ISSUE TITLE
[BUG] Unknow Errors in console

### ISSUE THREAD

**Issue by TurkiyeOyuntv** [LoneDev6/ItemsAdder#346]
**Describe the bug**
I don't know whats the problem. I just put my custom music disc to jukebox then picked the disc and tried to do it again but it didn't let me insert custom music disc, then I checked the console and saw lots of error messages (sorry, my English is bad)

**Screenshots**
![image](https://user-images.githubusercontent.com/49758008/89191257-562af080-d5ab-11ea-9e53-17a1bdd44ea1.png)

**Info**
 - Server version: Paper 1.14.4
 - Plugin version: ItemsAdder v2.0.41

**Comment by LoneDev6** [comment]
send full log, thanks

**Comment by TurkiyeOyuntv** [comment]
it fixed when i update the server to 1.16.2 (sorry for late answer)
