### ISSUE TITLE
[BUG] Connection times out when trying to access server.

### ISSUE THREAD

**Issue by donut4490** [LoneDev6/ItemsAdder#347]
**Describe the bug**
Connection times out when trying to access server. Only happens when ItemsAdder is loaded.
No plugins but ItemsAdder and dependencies installed, can't connect via bungee or directly.
I can load ItemsAdder after joining with PlugMan but then if i leave I can't join again.
Resource pack works, self hosted.

**To Reproduce**
1. Move ItemsAdder into plugins folder.
2. Start server.
3. Attempt to join server
or
1. Start server.
2. Join server.
3. Move ItemsAdder into plugins folder.
4. Load ItemsAdder with PlugMan.
5. Leave server.
6. Attempt to rejoin server.

**Expected behavior**
Well, not this. I haven't ran my server in a couple of months, but I expected to be able to join it with ItemsAdder running.

**Screenshots**
Not applicable, nothing in console.

**Info (please complete the following information):**
 - Server version: Paper 1.16.1
 - Client version: Optifine 1.16.1
 - Plugin version: 2.0.41 HOTFIX

**Additional context**
Not sure what else to add.

**Comment by LoneDev6** [comment]
1. what is your hosting service?
2. what happens if you deny the resourcepack download
3. can i see your server log?

thanks

**Comment by donut4490** [comment]
nfi what happened but it seems to have fixed itself. i've been having weird issues with my internet, seems to be something on the isp side so i'm just gonna close it since this specific issue is no longer a thing. thanks anyway!
