### ISSUE TITLE
[BUG] 1.16.2 update error [SOLVED by update LoneLib]

### ISSUE THREAD

**Issue by SgtLegoTown** [LoneDev6/ItemsAdder#351]
last update LoneLib Fixed it

**Describe the bug**
Exception while reading a NBT File!

**To Reproduce**
1. start server

**Expected behavior**
during the server start or restart

**Screenshots**

**Info (please complete the following information):**
 - Server version: Spigot 1.16.2 build 2
 - Client version: Default Minecraft
 - Plugin version: 2.0.42
**Additional context**

https://pastebin.com/iurzFJxp

**Comment by LoneDev6** [comment]
Update LoneLibs and let me know
