### ISSUE TITLE
[BUG] World populator

### ISSUE THREAD

**Issue by Yassounou** [LoneDev6/ItemsAdder#352]
Hello,

I set world populator to true, in config file like this 
` worlds-populators:
    log-loading: true
    log-loading-disabled: false
    log-loading-no-populators: false
    log-generation: true`

 then generate a new world using multivers but there is no ores ! 

and i didn't understrand this 
`you are searching ores in a world with custom name. You have to add the world name in the file: plugins\ItemsAdder\data\items_packs\itemsadder\blocks.yml for each ore`

How to do it please ???

**Comment by LoneDev6** [comment]
https://itemsadder.plugin.ga/faq/blocks-minerals-issues/i-cant-find-any-mineral-ore
