### ISSUE TITLE
[BUG] model_id - help with configuration

### ISSUE THREAD

**Issue by istarengwa** [LoneDev6/ItemsAdder#353]
**Describe the bug**
Hello, I have a problem ^^ When I create a new item with the customitemdata as you showed me previously, it works for the first item of each material used, then doesn't work for the rest. 

**Expected behavior**
For the first items its work. I would like the custom to be the same price for all the objects, because if I give the item with the iagive I have the right texture, but if I give the item with the plugin which uses the customdata I only have the texture of the first customdata created by me or by you depending on the material use.

**Screenshots**
https://zupimages.net/viewer.php?id=20/33/uiqm.png    : item with custom model id in the folder item_pack
https://zupimages.net/viewer.php?id=20/33/su4g.png    : json file create in models in resource pack

**Info (please complete the following information):**

Server version: purpur-688 (paper spigot 130)
Plugin version: 2.0.42

**Comment by LoneDev6** [comment]
Try to delete storage/items_ids_cache.yml file and restart
then use /iareload and /iazip

**Comment by istarengwa** [comment]
This is the correct solution =D
