### ISSUE TITLE
Force load texturepack

### ISSUE THREAD

**Issue by Gizmo0oDev** [LoneDev6/ItemsAdder#3532]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

gizmo0o

### Describe the solution you'd like

A way to force players to use the resource pack by making it so if they dont they get kicked or something.

### Is your feature request related to a problem?

Players sometimes dont get prompted or can just ignore the prompt

### Describe alternatives you've considered

Using alternative plugins for this but they only work when the server pack is in the server.properties file not using ItemsAdder

**Comment by LoneDev6** [comment]
There is already implemented, check the config.yml file
