### ISSUE TITLE
[BUG] Error Console Chunckload world_nether

### ISSUE THREAD

**Issue by istarengwa** [LoneDev6/ItemsAdder#354]
**Describe the bug**
I have a server with several datapack which modifies the biomes of the worlds "world" and "world_nether". When I load chunks from the world "world" no problem, on the other hand when I load chunks from the world "world_nether" here is what the console spam me, it gave 2mo of logs in 2 minutes, just from this message.

https://pastebin.com/bz8SCeFM

the datapack is "incendium"

**Comment by LoneDev6** [comment]
What is your spigot username?

**Comment by istarengwa** [comment]
I did the test with purpur-719 which is a version of paper. The version is specified on the error messages on the pastebin. server crash with the latest version of purpur (paper 1.16.2)

**Comment by LoneDev6** [comment]
> What is your spigot username?
