### ISSUE TITLE
[Suggestion] Items that put a potion effect to the target that is being hit by it

### ISSUE THREAD

**Issue by Bobbyharron** [LoneDev6/ItemsAdder#355]
it could be great to have the option to deal a potion effect to a player when you hit it with a custom item

**Comment by ArgonGaming** [comment]
Use a custom enchants plugin, and otherwise, I'm pretty sure that's already possible, at least with wearing armor and gaining effects.

**Comment by LoneDev6** [comment]
Added new upcoming update https://itemsadder.plugin.ga/plugin-usage/adding-content/item-properties/events/actions
