### ISSUE TITLE
Huge issue with sticks

### ISSUE THREAD

**Issue by Bobbyharron** [LoneDev6/ItemsAdder#356]
this is the third time the stick default texture of minecraft gets bugged as it dont have texture (i dont touched nothing about the stick texture) some people see the stick as always and some sees a black and purple square, the thing is that everyone has the texture pack and the issue only happen when the texturepack is loaded. I tried to add the stick texture but still the same, i need a fix ASAP as the moment, the stick texture still bugged in my server.

**Comment by LoneDev6** [comment]
Do not delete the issue template.
