### ISSUE TITLE
[Support] Cant link more than 1 model with a crossbow as material

### ISSUE THREAD

**Issue by Bobbyharron** [LoneDev6/ItemsAdder#358]
**Describe the bug**
I cant find a way to make custom modells follow a chain like the crossbow models, taking for example the shotgun in the preview items. When i put all the models together (x_0 x_1 x_charged x_firework) it only load one model)

**To Reproduce**
1. make an item with a crossbow as material
2. make custom models with names as the shotgun models.

**Expected behavior**
link every model in his phase (unload, 0,1,2 loaded, firework)

**Screenshots**
https://i.imgur.com/MuA7iv0.png (unloaded musket with his correct model and the only one working)
https://i.imgur.com/sHmFx1r.png (loaded musket with the unloaded model, with isnt the right one)

**Info (please complete the following information):**
 - Server version: paper 1.16.1
 - Client version: 1.16.1
 - Plugin version: 2.0.41

**Comment by Bobbyharron** [comment]
> Send screenshots of your folder where you put musket models, also send the .yml part where you created the musket item

i pass you the entire files:
Itempacks yml:
https://www.dropbox.com/s/j9n6g2ic9v8w30m/armas.yml?dl=0
itempack directory of the musket:
![1](https://user-images.githubusercontent.com/65925795/90984673-c9a29b00-e576-11ea-9e83-a2aea18335c8.png)


resourcepack yml:
https://www.dropbox.com/s/j9n6g2ic9v8w30m/armas.yml?dl=0
resourcepack directory of the musket:
![2](https://user-images.githubusercontent.com/65925795/90984682-d58e5d00-e576-11ea-9dd2-90e9d59b5edc.png)

**Comment by LoneDev6** [comment]
Mhhh, by "(loaded musket with the unloaded model, with isnt the right one)" you mean that it's rotated which is not right?
If I recall Minecraft do rotate the model, you may try to rotate it in order to fix that issue.
Let me know
