### ISSUE TITLE
Use font images in text display

### ISSUE THREAD

**Issue by HielkeMaps** [LoneDev6/ItemsAdder#3588]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

Text Displays are great for displaying text. Sadly ItemsAdder placeholders don’t work with them. It would make an awesome addition if it did. You’re looking for the “text” nbt component.

### Is your feature request related to a problem?

I want to use Text Displays to show my font images.

### Describe alternatives you've considered

I think you can copy the generated font Unicode from the console to achieve this, but this is cumbersome.

**Comment by Andre601** [comment]
Are the text display entities generated manually, or are you using a plugin that updates them?
If you use a plugin, check if it supports PlaceholderAPI. And if it does, use the `%img_<font_image_name>%` placeholder.

**Comment by HielkeMaps** [comment]
Thanks for the reply! I’m creating the text displays myself, together with the Axiom mod. Works really intuitive, if only ItemsAdder placeholder worked ;)

**Comment by Andre601** [comment]
> Thanks for the reply! I’m creating the text displays myself, together with the Axiom mod. Works really intuitive, if only ItemsAdder placeholder worked ;)

You mention a mod, does it mean you run a hybrid server?
Because such servers are generally not supported nor recommended to be used due to them breaking a lot of API.

**Comment by HielkeMaps** [comment]
No, the mod is just on my client, I use the Axiom paper plugin to make Axiom work with my server.
