### ISSUE TITLE
[BUG] Item-Model Override Issues

### ISSUE THREAD

**Issue by ItsSynchro** [LoneDev6/ItemsAdder#363]
**Describe the bug**
Upon changing my model ids for a completely different plugin in order to use an optifine texturepack along side it, it appears that ItemAdder items are overriding the textures. 

**To Reproduce**
Video Demonstration: https://youtu.be/PLw0J8-Euvc
Link to Texturepack and item-models.yml: https://www.planetminecraft.com/texture-pack/slimefun-texture-by-raulh22/

**Expected behavior**
Prevent ItemAdder textures from overriding the item-models.yml file I have added to the Slimefun folder.

**Info (please complete the following information):**
 - Server version: Tuinity 1.16.1
 - Client version: Optifine 1.16.1
 - Plugin version: 2.0.42

**Comment by LoneDev6** [comment]
I think you'd have to create a ItemsAdder pack to handle these custom items by slimefun, this could help you: https://github.com/LoneDev6/ItemsAdder/issues/283#issuecomment-638123518

let me know

**Comment by LoneDev6** [comment]
I'm working on it for you, I'm converting the pack manually, I will release it this week

**Comment by LoneDev6** [comment]
https://www.spigotmc.org/resources/addon-slimefun-compatibility-for-itemsadder.83877/
