### ISSUE TITLE
[BUG] Invincibility Stays After Loading

### ISSUE THREAD

**Issue by ItzM1k3y** [LoneDev6/ItemsAdder#365]
After adding IA and its dependencies (and no other plugin or config changes), I've noticed a small amount of players will be invincible even after loading in the resource pack. Maybe 2 out of every 100 players. This is fixed after the server restarts or if they disable server resource packs in their server settings, but if they don't disable the pack it will happen every time they relog or join the server again until the next restart (I'm assuming an /iazip will fix this as well if they don't cancel the download, but we're doing our best not to constantly force people to load the pack).

In terms of reproducing it, I have only have guesses. My main guess is that they cancel the resource pack download midway through and it for some reason disables the slowfall and invisibility effects, but not the invincibility. I haven't been able to get this to happen for myself yet.

If someone were to cancel the resource pack download mid-download, I'd expect all of the effects given while loading to be removed.

 - Server version: Tuinity 1.16.1 (Build 145)
 - Client version: 1.16.1, I'm not aware if there were any similarities between clients that had the issue besides the version.
 - Plugin version: 2.0.41

**Comment by 100petr** [comment]
I have the same problem, it never occurred to me that it could be an itemsadder. Tuinity 1.16.2 - git-Tuinity-"b8468b7" (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by LoneDev6** [comment]
Will be fixed in the new update
