### ISSUE TITLE
Mending doesn't work on custom items [BUG] 

### ISSUE THREAD

**Issue by Agaloth** [LoneDev6/ItemsAdder#366]
**Describe the bug**
Mending doesn't repair the custom items.

**To Reproduce**
1. Go to /ia
2. Click on an custom item
3. Enchant it with mending and mine, hit
4. Mending won't repair it

**Expected behavior**
Mending should repair the custom items

**Screenshots**
I think it's unneccesary since mending is the non working feature.

**Info (please complete the following information):**
 - Server version: purpur 1.16.1 build 710
 - Client version: Minecraft 1.16.1 optifine
 - Plugin version: 2.0.42

**Comment by LoneDev6** [comment]
Be sure to check it using the F3+H tooltip.
Check if durability increases, I'm 99.9% sure it works fine as I didn't change anything in the mending code.

Let me know

**Comment by Agaloth** [comment]
Well, it doesn’t go up :/

**Comment by Agaloth** [comment]
Well, it doesn’t go up but it correctly does with non custom items.

**Comment by Agaloth** [comment]
Well, it doesn’t go up but it correctly does with non custom items.

**Comment by Agaloth** [comment]
Well, it doesn’t go up but it correctly does with non custom items.

**Comment by Agaloth** [comment]
Well, it doesn’t go up but it correctly does with non custom items.

**Comment by Agaloth** [comment]
Well, it doesn’t go up but it correctly does with non custom items.

**Comment by Agaloth** [comment]
Well, it doesn’t go up but it correctly does with non custom items.

**Comment by Agaloth** [comment]
Well, it doesn’t go up but it correctly does with non custom items.

**Comment by Agaloth** [comment]
Well, it doesn’t go up but it correctly does with non custom items.

**Comment by Agaloth** [comment]
Sorry about the spam (github phone doesn’t say if you sent it or not)

**Comment by LoneDev6** [comment]
Works perfectly, I just tested.

- Get a custom pickaxe
- Mine some blocks
- Throw an exp bottle and get the exp
repaired
