### ISSUE TITLE
Smelting recipe issue.

### ISSUE THREAD

**Issue by TheMGRF** [LoneDev6/ItemsAdder#37]
Block that is smelting "pauses" once one is smelted (as if it doesn't recognise the products as the same item).

https://i.gyazo.com/d9b3e04cdb4078f13975fb707b921c9c.mp4

**Comment by LoneDev6** [comment]
can you send screenshot with items info hover message? Thanks

**Comment by TheMGRF** [comment]
https://i.gyazo.com/74a2a4cbf37ff22fb974c834fa50a41f.mp4

**Comment by LoneDev6** [comment]
Are you using any custom recipes plugin? They break itemsadder functionality

**Comment by TheMGRF** [comment]
We were using one a while back but that hasn't been installed for a while.

**Comment by TheMGRF** [comment]
Someone else on the server also just reported this:
https://i.gyazo.com/251b51cae5a31d55faae7868cac9a095.mp4

Clay will only smelt into its brick form one at a time unless the item from the result slot is moved.

**Comment by LoneDev6** [comment]
Sadly I can't fix this because as soon as I set an item as result in the furnace the loading bar resets and get stuck.
I think it's an internal vanilla behaviour I can't change only with a plugin.
If anyone has any advice I'd be happy to fix the issue

**Comment by LoneDev6** [comment]
Should be fixed in latest version I'm going to publish, let me know
