### ISSUE TITLE
[BUG] Custom Item Textures not Working (1.16.2)

### ISSUE THREAD

**Issue by Ixiplious** [LoneDev6/ItemsAdder#371]
### **Describe the bug**
Whenever I try to make a custom item texture, it never appears properly.

I can get my item using **/iaget customnamespace:magicite**, but the item texture is just an iron ingot.

I have made sure that the directories of my namespace and textures are correct, which they are.

### **SCREENSHOTS:**
**In customnamespace/minerals.yml:**
![image](https://user-images.githubusercontent.com/29444591/91777125-dd1bba80-eba3-11ea-9f2a-a67dd11bd5d3.png)

**Here's what my image texture directory is. (namespace is blocked in red)**
![image](https://user-images.githubusercontent.com/29444591/91776913-5535b080-eba3-11ea-8825-e887bda05b13.png)

**When I try to give myself the item, as you can see in the following image, it does not show up. You can see some of the base custom items on the right working.**
![image](https://user-images.githubusercontent.com/29444591/91776987-84e4b880-eba3-11ea-8166-9aa735d69f8f.png)

**Expected behavior**
The texture should show up on my custom item, but it doesn't seem to work. All other items that are included in the base plugin have working custom textures but not mine.

**Info (please complete the following information):**
 - Server version: 1.16.2
 - Plugin version: 2.0.43

**Comment by LoneDev6** [comment]
Be sure you're following the tutorial completely.

Remember to reupload the zip file if you're using dropbox hosting and execute /iatexture command from your client (not console).


If you're using selfhost be sure to use /iazip command
