### ISSUE TITLE
[BUG] Item not showing

### ISSUE THREAD

**Issue by lubek-dc** [LoneDev6/ItemsAdder#373]
**Describe the bug**
the item not showing

**To Reproduce**
1.im create the custom item
2.run server
3.write command /iaget myitems:op
4.and get ItemNotFound
**Expected behavior**

**Screenshots**
![2020-09-02_11 08 47](https://user-images.githubusercontent.com/70327203/91962340-b036e700-ed0c-11ea-9076-19757dec2178.png)

**Info (please complete the following information):**
 - Server version: PaperSpigot 1.16.1
 - Client version: Optifine 1.16.1
 - Plugin version: 2.0.42
 - Using Self-host

**Additional context**
code:
https://pastebin.com/BFvygk7G

**Comment by LoneDev6** [comment]
I fixed it for you: https://pastebin.com/iq8Lb4MS


Please be sure:
- you're not using TAB, use only spaces.
- be sure you're using the right indentation
- use this website to check if your YAML file is valid https://codebeautify.org/yaml-validator
- READ SERVER LOGS, ItemsAdder will throw errors if you make mistakes in your files.

Have a nice day
