### ISSUE TITLE
Slimefun pack replaces some minecraft textures and makes some invisible [BUG] 

### ISSUE THREAD

**Issue by Agaloth** [LoneDev6/ItemsAdder#377]
**Describe the bug**
Putting the slimefun pack makes some textures invisible.

**To Reproduce**
1. Download the slimefun addon texture pack
2. Upload it
3. Put it in game

**Expected behavior**
Some minecraft blocks are modified and some are invisible

**Screenshots**
https://cdn.discordapp.com/attachments/533413171403292712/755115305155428402/unknown.png

**Info (please complete the following information):**
 - Server version: Purpur 1.16.1
 - Client version: Vanilla 1.16.1
 - Plugin version: 2.0.45

**Comment by LoneDev6** [comment]
Fixed! Thanks
