### ISSUE TITLE
[BUG] Console warning when box only drops exp

### ISSUE THREAD

**Issue by yebanme** [LoneDev6/ItemsAdder#379]
**Describe the bug**
When a block only drops exp, a warning message appears when the plugin starts or reloads the plug-in console

![image](https://user-images.githubusercontent.com/20102749/93326481-70fbb080-f84b-11ea-8c5e-8e0aac7ea568.png)

**Additional context**
![image](https://user-images.githubusercontent.com/20102749/93326721-d9e32880-f84b-11ea-9267-a8eeac3e13a3.png)

**Comment by LoneDev6** [comment]
Will be fixed in next update, thanks
