### ISSUE TITLE
Custom Blocks in Stonecutters

### ISSUE THREAD

**Issue by TheMGRF** [LoneDev6/ItemsAdder#38]
Custom blocks that are placed in Stonecutters are able to be turned back into their Andesite form/counterparts.
![image](https://user-images.githubusercontent.com/16401884/64487599-7be13580-d234-11e9-806f-9785ae01ad3e.png)

**Comment by LoneDev6** [comment]
Fixed in upcoming release, users won't be able to get the item (I can't remove the recipes list, I can only cancel usage of stonecutter).

I'll publish in some minutes
