### ISSUE TITLE
[BUG] Invisible players after you TP or TPA to them

### ISSUE THREAD

**Issue by antibitcoin** [LoneDev6/ItemsAdder#381]
**Describe the bug**
When you teleport to a player they are not visible to you, they are hidden even if you have ability to see vanished players, you cannot see them, their armor or anything about them being there just because they have an itemadder item on them or their hand, this bug is reported by all my players.

**To Reproduce**
1. do /tpa playername
2. the player is not there after he accepts your tpa.
3. Relog and you see him again.
Note: if there is players near him you can see those, also if he have no itemsAdder items on him this bug doesn't happen.

**Expected behavior**
I expect to teleport to someone and actually see them without me or them having to relog.

**Screenshots**

https://prnt.sc/uikwdm

**Info (please complete the following information):**
 - Server version: paper 1.16.3
 - Client version: vanilla 1.16.3
 - Plugin version: 2.0.46

**Additional context**
Plugins (72): AdvancedEnchantments, AntiCheatReloaded, AntiSeedCracker, ArmorStandEditor, AuctionHouse, AutoBroadcast, Bank, BetterSleeping3, BuycraftX, Citizens, CitizensCMD, Clans, ClansChatAddon, ClansChestAddon, ClansCreateAddon, ClansRenameAddon, ClansShowAddon, ClansStatsAddon*, CommandAlias, Core, CustomHeads*, DailyBonus, DeathMessagesPrime, DiscordSRV, DynamicIcon*, EnchantmentLock, Essentials, EZColors, FrozenJoin, HolographicDisplays, IllegalStack, ImageOnMap, Item2Chat, ItemEditor, ItemsAdder, LagAssist, LightAPI*, LoneLibs, Lottery, LPC, LuckPerms, MapManager, OpenInv, PacketListenerApi*, PL-Hide, PlaceholderAPI, PlayerListDeluxe*, PlayerParticles, PlayerVaults, Playtimes*, PlugMan, ProtocolLib, QuickBoard*, SaveRodOfficial*, Sentinel, ShopGUIPlus, SilentBans*, SilkSpawners, SimpleRename, SpecializedCrates, TCPShield*, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, VoteParty, Votifier, VotingPlugin, Wands, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by LoneDev6** [comment]
Why should this be related to ItemsAdder?

**Comment by LoneDev6** [comment]
So it was light api or not?
Thanks a lot for the info!
