### ISSUE TITLE
[BUG] Server Dump on fresh install

### ISSUE THREAD

**Issue by RedZephon** [LoneDev6/ItemsAdder#384]
**Describe the bug**
On a fresh install of ItemsAdder, server dumps thread

**To Reproduce**
1. Install Paper MC
2. Install ItemsAdder
3. Start Server

**Expected behavior**
Server starts normally

**Info (please complete the following information):**
 - Server version: Paper 1.16.3 196
 - Client version: Minecraft 1.16.3
 - Plugin version: 2.0.46

**Additional context**
>.... [06:21:07 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-196 (MC: 1.16.3) ---
>.... [06:21:07 ERROR]: The server has not responded for 10 seconds! Creating thread dump
>.... [06:21:07 ERROR]: ------------------------------
>.... [06:21:07 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
>.... [06:21:07 ERROR]: ------------------------------
>.... [06:21:07 ERROR]: Current Thread: Server thread
>.... [06:21:07 ERROR]: PID: 16 | Suspended: false | Native: false | State: RUNNABLE
>.... [06:21:07 ERROR]: Stack:
>.... [06:21:07 ERROR]: com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
>.... [06:21:07 ERROR]: com.mojang.serialization.DataResult$$Lambda$661/497424937.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.util.Either$Left.map(Either.java:38)
>.... [06:21:07 ERROR]: com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
>.... [06:21:07 ERROR]: com.mojang.serialization.OptionalDynamic.flatMap(OptionalDynamic.java:36)
>.... [06:21:07 ERROR]: com.mojang.serialization.OptionalDynamic.asString(OptionalDynamic.java:46)
>.... [06:21:07 ERROR]: net.minecraft.server.v1_16_R2.DataConverterBlockRename.a(SourceFile:35)
>.... [06:21:07 ERROR]: net.minecraft.server.v1_16_R2.DataConverterBlockRename$$Lambda$4540/777491324.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.Typed.lambda$updateCap$9(Typed.java:164)
>.... [06:21:07 ERROR]: com.mojang.datafixers.Typed$$Lambda$4536/252941622.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.optics.Traversal$Instance$1.lambda$wander$0(Traversal.java:34)
>.... [06:21:07 ERROR]: com.mojang.datafixers.optics.Traversal$Instance$1$$Lambda$4537/1153560984.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.util.Pair$Instance.traverse(Pair.java:90)
>.... [06:21:07 ERROR]: com.mojang.datafixers.optics.profunctors.TraversalP$1.lambda$wander$0(TraversalP.java:50)
>.... [06:21:07 ERROR]: com.mojang.datafixers.optics.profunctors.TraversalP$1$$Lambda$4538/1108513284.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.optics.Traversal$Instance$1.lambda$wander$0(Traversal.java:34)
>.... [06:21:07 ERROR]: com.mojang.datafixers.optics.Traversal$Instance$1$$Lambda$4537/1153560984.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.optics.Traversal$Instance$1.lambda$wander$0(Traversal.java:34)
>.... [06:21:07 ERROR]: com.mojang.datafixers.optics.Traversal$Instance$1$$Lambda$4537/1153560984.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.Typed.updateCap(Typed.java:164)
>.... [06:21:07 ERROR]: com.mojang.datafixers.Typed.update(Typed.java:138)
>.... [06:21:07 ERROR]: com.mojang.datafixers.Typed.update(Typed.java:133)
>.... [06:21:07 ERROR]: net.minecraft.server.v1_16_R2.DataConverterBlockRename.a(SourceFile:34)
>.... [06:21:07 ERROR]: net.minecraft.server.v1_16_R2.DataConverterBlockRename$$Lambda$4446/897445901.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.DataFix.lambda$null$3(DataFix.java:86)
>.... [06:21:07 ERROR]: com.mojang.datafixers.DataFix$$Lambda$4517/66647551.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp$$Lambda$4516/1091525169.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp$$Lambda$4516/1091525169.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp$$Lambda$4516/1091525169.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp$$Lambda$4516/1091525169.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp$$Lambda$4516/1091525169.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp$$Lambda$4516/1091525169.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp$$Lambda$4516/1091525169.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp$$Lambda$4516/1091525169.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp$$Lambda$4516/1091525169.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp$$Lambda$4516/1091525169.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp$$Lambda$4516/1091525169.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp.lambda$null$5(Comp.java:69)
>.... [06:21:07 ERROR]: com.mojang.datafixers.functions.Comp$$Lambda$4516/1091525169.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.types.Type.capWrite(Type.java:167)
>.... [06:21:07 ERROR]: com.mojang.datafixers.types.Type.lambda$readAndWrite$9(Type.java:159)
>.... [06:21:07 ERROR]: com.mojang.datafixers.types.Type$$Lambda$4514/45846929.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
>.... [06:21:07 ERROR]: com.mojang.serialization.DataResult$$Lambda$661/497424937.apply(Unknown Source)
>.... [06:21:07 ERROR]: com.mojang.datafixers.util.Either$Left.map(Either.java:38)
>.... [06:21:07 ERROR]: com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
>.... [06:21:07 ERROR]: com.mojang.datafixers.types.Type.readAndWrite(Type.java:158)
>.... [06:21:07 ERROR]: com.mojang.datafixers.DataFixerUpper.update(DataFixerUpper.java:84)
>.... [06:21:07 ERROR]: org.bukkit.craftbukkit.v1_16_R2.legacy.CraftLegacy.<clinit>(CraftLegacy.java:327)
>.... [06:21:07 ERROR]: org.bukkit.craftbukkit.v1_16_R2.util.CraftLegacy.fromLegacy(CraftLegacy.java:22)
>.... [06:21:07 ERROR]: org.bukkit.craftbukkit.v1_16_R2.inventory.CraftItemFactory.getItemMeta(CraftItemFactory.java:52)
>.... [06:21:07 ERROR]: org.bukkit.craftbukkit.v1_16_R2.inventory.CraftItemFactory.getItemMeta(CraftItemFactory.java:48)
>.... [06:21:07 ERROR]: org.bukkit.inventory.ItemStack.getItemMeta(ItemStack.java:552)
>.... [06:21:07 ERROR]: org.bukkit.inventory.ItemStack.getDurability(ItemStack.java:230)
>.... [06:21:07 ERROR]: org.bukkit.craftbukkit.v1_16_R2.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:34)
>.... [06:21:07 ERROR]: org.bukkit.craftbukkit.v1_16_R2.inventory.CraftRecipe.lambda$toNMS$1(CraftRecipe.java:23)
>.... [06:21:07 ERROR]: org.bukkit.craftbukkit.v1_16_R2.inventory.CraftRecipe$$Lambda$4378/1184237927.apply(Unknown Source)
>.... [06:21:07 ERROR]: java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
>.... [06:21:07 ERROR]: java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
>.... [06:21:07 ERROR]: java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
>.... [06:21:07 ERROR]: java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
>.... [06:21:07 ERROR]: java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
>.... [06:21:07 ERROR]: java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
>.... [06:21:07 ERROR]: java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
>.... [06:21:07 ERROR]: net.minecraft.server.v1_16_R2.RecipeItemStack.<init>(RecipeItemStack.java:31)
>.... [06:21:07 ERROR]: org.bukkit.craftbukkit.v1_16_R2.inventory.CraftRecipe.toNMS(CraftRecipe.java:23)
>.... [06:21:07 ERROR]: org.bukkit.craftbukkit.v1_16_R2.inventory.CraftShapedRecipe.addToCraftingManager(CraftShapedRecipe.java:55)
>.... [06:21:07 ERROR]: org.bukkit.craftbukkit.v1_16_R2.CraftServer.addRecipe(CraftServer.java:1306)
>.... [06:21:07 ERROR]: org.bukkit.Bukkit.addRecipe(Bukkit.java:761)
>.... [06:21:07 ERROR]: dev.lone.itemsadder.e.h.a.a(SourceFile:111)
>.... [06:21:07 ERROR]: dev.lone.itemsadder.e.h.c.c.a(SourceFile:61)
>.... [06:21:07 ERROR]: dev.lone.itemsadder.e.b.a(SourceFile:832)
>.... [06:21:07 ERROR]: dev.lone.itemsadder.e.b$$Lambda$4377/1105440196.run(Unknown Source)
>.... [06:21:07 ERROR]: org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
>.... [06:21:07 ERROR]: org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
>.... [06:21:07 ERROR]: net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
>.... [06:21:07 ERROR]: net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
>.... [06:21:07 ERROR]: net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
>.... [06:21:07 ERROR]: net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
>.... [06:21:07 ERROR]: net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [06:21:07 ERROR]: net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3047/1642651659.run(Unknown Source)
>.... [06:21:07 ERROR]: java.lang.Thread.run(Thread.java:748)
>.... [06:21:07 ERROR]: ------------------------------
>.... [06:21:07 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
>.... [06:21:07 ERROR]: ------------------------------
>.... [06:21:12 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH - git-Paper-196 (MC: 1.16.3) ---
>.... [06:21:12 ERROR]: The server has not responded for 15 seconds! Creating thread dump
>.... [06:21:12 ERROR]: ------------------------------
>.... [06:21:12 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
>.... [06:21:12 ERROR]: ------------------------------
>.... [06:21:12 ERROR]: Current Thread: Server thread
>.... [06:21:12 ERROR]: PID: 16 | Suspended: false | Native: false | State: RUNNABLE
>.... [06:21:12 ERROR]: Stack:
>.... [06:21:12 ERROR]: java.lang.Object.hashCode(Native Method)
>.... [06:21:12 ERROR]: java.util.HashMap.hash(HashMap.java:339)
>.... [06:21:12 ERROR]: java.util.HashMap.containsKey(HashMap.java:596)
>.... [06:21:12 ERROR]: java.util.HashSet.contains(HashSet.java:204)
>.... [06:21:12 ERROR]: java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:173)
>.... [06:21:12 ERROR]: java.util.Collections$2.tryAdvance(Collections.java:4719)
>.... [06:21:12 ERROR]: java.util.Collections$2.forEachRemaining(Collections.java:4727)
>.... [06:21:12 ERROR]: java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
>.... [06:21:12 ERROR]: java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:272)
>.... [06:21:12 ERROR]: java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
>.... [06:21:12 ERROR]: java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
>.... [06:21:12 ERROR]: java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
>.... [06:21:12 ERROR]: java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
>.... [06:21:12 ERROR]: java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
>.... [06:21:12 ERROR]: java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
>.... [06:21:12 ERROR]: net.minecraft.server.v1_16_R2.RecipeItemStack.buildChoices(RecipeItemStack.java:40)
>.... [06:21:12 ERROR]: org.bukkit.craftbukkit.v1_16_R2.inventory.CraftRecipe.toNMS(CraftRecipe.java:29)
>.... [06:21:12 ERROR]: org.bukkit.craftbukkit.v1_16_R2.inventory.CraftShapedRecipe.addToCraftingManager(CraftShapedRecipe.java:55)
>.... [06:21:12 ERROR]: org.bukkit.craftbukkit.v1_16_R2.CraftServer.addRecipe(CraftServer.java:1306)
>.... [06:21:12 ERROR]: org.bukkit.Bukkit.addRecipe(Bukkit.java:761)
>.... [06:21:12 ERROR]: dev.lone.itemsadder.e.h.a.a(SourceFile:111)
>.... [06:21:12 ERROR]: dev.lone.itemsadder.e.h.c.c.a(SourceFile:61)
>.... [06:21:12 ERROR]: dev.lone.itemsadder.e.b.a(SourceFile:832)
>.... [06:21:12 ERROR]: dev.lone.itemsadder.e.b$$Lambda$4377/1105440196.run(Unknown Source)
>.... [06:21:12 ERROR]: org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
>.... [06:21:12 ERROR]: org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
>.... [06:21:12 ERROR]: net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
>.... [06:21:12 ERROR]: net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
>.... [06:21:12 ERROR]: net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
>.... [06:21:12 ERROR]: net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
>.... [06:21:12 ERROR]: net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [06:21:12 ERROR]: net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3047/1642651659.run(Unknown Source)
>.... [06:21:12 ERROR]: java.lang.Thread.run(Thread.java:748)
>.... [06:21:12 ERROR]: ------------------------------
>.... [06:21:12 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
>.... [06:21:12 ERROR]: ------------------------------

**Comment by LoneDev6** [comment]
Try using normal spigot, see if error occurs anyway.
Thanks

Download from here: https://serverjars.com/

**Comment by RedZephon** [comment]
I get the same server dump when using Spigot instead of Paper.

**Comment by RedZephon** [comment]
So far it seems to just be when the server starts. This is on a dev server just for testing so the hardware isn’t amazing. I haven’t pushed it to my production server yet. The plugin appears to work fine after I’m just worried to install on production and cause issues.

**Comment by LoneDev6** [comment]
It's a warning thrown by Paper itself which reports that ItemsAdder is taking more than 10 seconds to load recipes at startup, it's loading more than 500 different recipes.

You can safely ignore this as most server hardware is fast enough ;)
