### ISSUE TITLE
/iastats (A command that will list useful information for adding your own items)

### ISSUE THREAD

**Issue by spiker5032** [LoneDev6/ItemsAdder#388]
**Is your feature request related to a problem? Please describe.**
Just that most people I feel dont know about the limits of blocks/pack size they have.

**Describe the solution you'd like**
When typing /iastats it would show the following

1. Your Used ??/191 REAL block IDs (In console but would be better in-game as well for editing packs on the fly)
2. Amount of armor stands being used by ItemsAdder. (Just a stat and maybe a command to clear these)
3. Resource Pack Size 36.1/50MB (Im pretty sure the limit is 50MB so I know .ogg files take alot of space this is a needed feature when editing)
4. How many custom ores spawned? (Not needed but would be nice)

**Describe alternatives you've considered**
Checking console

**Additional context**
Technically if you are savvy with itemsadder non of this is really needed.
But for the average user this would be a very helpful addition.
I can say for myself I spend alot of time making content and these additions would be a godsend.

**Comment by LoneDev6** [comment]
Very cool and smart idea, I will implement the doable features requested

**Comment by LoneDev6** [comment]
Will be added in next update

![image](https://user-images.githubusercontent.com/27242001/93880123-3d060c80-fcdd-11ea-8af8-817d6eaedf36.png)
