### ISSUE TITLE
[BUG] Light source blocks not working

### ISSUE THREAD

**Issue by ArgonGaming** [LoneDev6/ItemsAdder#389]
**Describe the bug**
Light source blocks (the light of them) breaks when doing this action:

**To Reproduce**
1. Set any "REAL" or "TILE" block to glowstone OR set a light source (or both)
2. Place it (It should work fine, especially since it is also glowstone)
3. Place another one right on top or to the side of it (As long as its connected to it)
4. Break one of those blocks
5. Light source goes dark.

**Expected behavior**
It should stay lit, just as real light sources work.

**Info (please complete the following information):**
 - Server version: Paper 1.16.2
 - Client version: Optifine 1.16.2
 - Plugin version: 2.0.48

**Comment by LoneDev6** [comment]
Sadly I cannot fix this: https://www.spigotmc.org/threads/lightapi-fork.278321/page-5#post-3791778
