### ISSUE TITLE
[BUG]  an error occurred when enabling the resource pack

### ISSUE THREAD

**Issue by AcesGamingUK** [LoneDev6/ItemsAdder#390]
**Describe the bug**
it started yesterday with people getting `Internal Exception: Java.io.IOException: an existing connection was forcibly closed by the remote host` when they have server resource packs set to `enabled`,
switching to `prompt` resolves this but only until next login where it reverts back to `enabled`
it seems to be a timeout while downloading the pack instantly on join,
is there anything I can change to resolve this?
I'm using paper 1.16.3

today my issue has escalated to the pack failing altogether and not allowing anyone the server
`an error occurred when enabling the resource pack. Please contact admins or disable resource packs.`

**To Reproduce**
Steps to reproduce the behaviour:
1. click join server
2. See error

**Expected behaviour**
to join server 

**Screenshots**
![image](https://user-images.githubusercontent.com/16180389/93866026-1042fc80-fcbf-11ea-95f5-c4396c726675.png)
![image](https://user-images.githubusercontent.com/16180389/93866091-2486f980-fcbf-11ea-8628-66fbad902456.png)

**Info (please complete the following information):**
 - Server version: git-Paper-202 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
 - Client version: 1.16.3 with optifine
 - Plugin version: ItemsAdder version 2.0.47

**Additional context**
if I set `  kick-player-on-fail:` to `false` that it gets stuck on 
![image](https://user-images.githubusercontent.com/16180389/93868133-ef2fdb00-fcc1-11ea-85e9-e4dd5ceb500b.png)

forcing user to force close Minecraft,
also OP users don't have this issue as I assume they bypss some checks?

**Comment by LoneDev6** [comment]
- check if you have another plugin that is applying another resourcepack, if yes disable it
- "it started yesterday", I doubt that it bugs out of nowere, check if an admin of you server installed a new plugin or if edited any config file yesterday
- send your FULL server file log
- try to use Spigot instead of paper and check if it's the issue  https://serverjars.com/


let me know! have a nice day

**Comment by LoneDev6** [comment]
Also read this: 
https://itemsadder.plugin.ga/faq/plugin-doesnt-work/resourcepack-not-loading
https://itemsadder.plugin.ga/faq/plugin-doesnt-work/players-cant-see-textures

**Comment by AcesGamingUK** [comment]
`check if you have another plugin that is applying another resourcepack, if yes disable it`
>i don't have any other plugins the mess with resources,
`"it started yesterday", I doubt that it bugs out of nowere, check if an admin of you server installed a new plugin or if edited any config file yesterday`
> well it did, and no config edits have been made, and no new/updated plugins during this timeframe
`send your FULL server file log`
>[Log](https://pastebin.com/MQBTu9EG)
`try to use Spigot instead of paper and check if it's the issue https://serverjars.com/`
>I use paper because it has anti x-ray, so I wont be running with spigot, and yes tested on backup and it occurs there too

**Comment by LoneDev6** [comment]
I read: 
```
[ItemsAdder] Loaded class org.apache.commons.io.filefilter.IOFileFilter from HackedCore v2.69.0 which is not a depend, softdepend or loadbefore of this plugin.
```
Please try to remove HackedCore and restart.


Let me know

**Comment by AcesGamingUK** [comment]
ok i removed hackedcore, and the plugin that depended on it, and from tests it seems to have resolved the issue,
however only if the plugin isn't loaded... 
so is there a war around this?

**Comment by LoneDev6** [comment]
Please ask HackedCore to update "org.apache.commons.io" libs in his plugin, seems they are using an outdated version, probably because I don't see any other reason why this lib could interfer.. I just guessed since I saw the Warning message and I was right.

Let me know what the dev answers, you can also send him this github issue link if you want

**Comment by AcesGamingUK** [comment]
the dev has [resolved ](https://www.spigotmc.org/resources/hackedcore-hackedserver-library.68979/update?update=362925) this issue so now the plugin is compatible,
ill go ahead and close this as no longer an issue
thank you for the assistance

**Comment by LoneDev6** [comment]
No problem!
Thank you for finding out this other plugin bug

**Comment by mrpunky** [comment]
I'm having the same problem, what do you suggest I do?
