### ISSUE TITLE
[BUG]  Unbreakable Hammer

### ISSUE THREAD

**Issue by Jirsaacek** [LoneDev6/ItemsAdder#392]
**Describe the bug**
When player is repeatedly using /fix on Demoniac Hammer, durability becomes a negative number and hammer never breaks. 

**To Reproduce**
1. Mine few blocks
2. Use /fix on Demoniac Hammer
3. Repeat until bug appears

**Expected behavior**
Hammer should work normally 

**Info (please complete the following information):**
Tuinity v1_16_R2
Itemsadder 2.0.48

**Comment by LoneDev6** [comment]
Which plugin has the /fix command?

Just tried with EssentialsX command and I have no issue.
Also I noticed you're using an unofficial Spigot fork, please try this on original Spigot and check if the issue occurs anyway.

Have a nice day
