### ISSUE TITLE
[BUG] Zip file direct download link not recognized as zip file

### ISSUE THREAD

**Issue by benevolent2012** [LoneDev6/ItemsAdder#395]
**Describe the bug**
The zip file direct download link shows the following error:
```Resourcepack URL is not valid. Not a zip file. Type: text/plain; charset=UTF-8```
![image](https://user-images.githubusercontent.com/68626312/94323245-e05b5980-ff49-11ea-901f-66d528644e0f.png)

**To Reproduce**
1. Set the link (https://www.naturecraft.world/wp-content/uploads/2020/09/pack.zip) as the download link.
2. Start the server

**Expected behavior**
Resource pack recognized as zip file

**Screenshots**
(attached above)
**Info (please complete the following information):**
 - Server version: paper 1.16.2
 - Client version: vanilla 1.16.2
 - Plugin version: 2.0.48

**Additional context**

**Comment by benevolent2012** [comment]
I know it works with dropbox, but I would like to use other direct download links, if possible.

**Comment by LoneDev6** [comment]
Wordpress seems to mess with download file type, the error is pretty clear.
Minecraft won't download the pack successfully if data type is not set to application/zip.

Please upload the file in the main root of your FTP server and allow direct download, don't use Wordpress uploads directory.

Thanks
