### ISSUE TITLE
[Suggestion] Sounds Overhaul for custom blocks!

### ISSUE THREAD

**Issue by ArgonGaming** [LoneDev6/ItemsAdder#401]
**Is your feature request related to a problem? Please describe.**
I do get frustrated when I set a block to a custom block and it only applies its effects during a place event. Everything else is usually configured within the ymls of the plugin itself. That is understandable, as these are custom blocks and technically (At least for "real" blocks) they are mushroom blocks. They have limitations. However..

**Describe the solution you'd like**
It would be nice to implement a stable and consistent feature that somehow replaces the sounds of the custom blocks to what they are set to.

**An Example**
I have created a black dyed netherbricks block via ItemAdder. This is a custom block, set to be "real" aka a mushroom block state. I also set in the config yml for it to be a netherbrick block. This allows me to place the block and hear the sounds as if I am placing a netherbrick block. However, when I walk over these blocks, or break them, they revert back to sounding like mushroom blocks. This typically breaks the immersion of the block in my opinion, and with the mining issue already being an immersion breaker, sounds would be a very nice touch to combat this everlasting problem. Thank you!

**Comment by LoneDev6** [comment]
Thanks! This will be added in the next update.
Keep in mind that I can only customize place and break sounds, other sounds cannot be changed in any clean way sadly.
