### ISSUE TITLE
[Suggestion] opposite direction for chair entity

### ISSUE THREAD

**Issue by Makkief** [LoneDev6/ItemsAdder#403]
I checked new opposite_direction property.
It gives furniture model 180 degree rotation.

But, what I asked was **giving 180 degree rotation for chair entity**.

I noticed that when player sit on a furniture chair model, it creates 1 more entity.
I guessed it's another armorstand or something.

It's not urgent. Take your time.

**Comment by LoneDev6** [comment]
Will be added in next update, thanks
