### ISSUE TITLE
Give redstone power to custom block will make it become noteblock again

### ISSUE THREAD

**Issue by jeffry1829** [LoneDev6/ItemsAdder#4034]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

jeffry1829

### What happened?

Give redstone power to custom block will make it become noteblock again, and you can even use that to change block type by changing the tone of the noteblock.

### Steps to reproduce the issue

Place any custom block that is made of noteblock, give redstone power to it.

### Server version

1.21.1-2305-fdfc12e (MC: 1.21.1)

### ItemsAdder Version

4.0.2-beta-release-12

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### LoneLibs Version

1.0.58

### Full Server Log

https://mclo.gs/dxJI6bB

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/0bfcdfd7-22b1-4e40-810f-c674b9a4e84d)

**Comment by LoneDev6** [comment]
Can't reproduce, probably these blocks failed to some some time ago or the custom region files were deleted/corrupted during a server crash.
https://github.com/user-attachments/assets/d919b673-0213-488c-9d91-8179b6c5e4ac
