### ISSUE TITLE
[BUG] menu IA doppio dopo installazione ultimo update

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#405]
**Describe the bug**
Ho installato l'ultimo update del di itemadder e ho notato che il menu IA ha dobbiato tutti gli items.

![image](https://user-images.githubusercontent.com/20026629/95000479-84d04200-05c1-11eb-89f6-b015ac29c2c3.png)

come nell'immagine... poi non ho nemmeno tentato di vedere i mob nuovi che hai aggiunto oppure i liquidi. ancora non provo nemmeno a toccarli quelli.

io ho solo preso il file .jar e l'ho droppato nel server

**Comment by LoneDev6** [comment]
ciao!
negli ultimi update ho modificato come vengono gestite le categorie.
dovresti rimuovere le tue categorie dal file ia_gui.yml e metterle in un nuovo file nella tua cartella del namespace.

https://itemsadder.plugin.ga/plugin-usage/ia

poi ti basta cancellarlo e ricaricare il plugin.

**Comment by Fargus5** [comment]
Grazie mille. Risolto

**Comment by Fargus5** [comment]
C'è una cosa che non è chiara.

dove lo devo creare questo file? ed inoltre se volessi che gli items si aggiungano alle già attuali catagorie di default come devo fare?

**Comment by Fargus5** [comment]
@LoneDev6

**Comment by LoneDev6** [comment]
Lo devi creare dentro il tuo namespace, puoi crearne quanti ne vuoi.
Da alcuni update ho sganciato le categorie IA dal file ia_gui.yml così ognuno può creare le proprie categorie direttamente nel proprio namespace. Questo per facilitare l'installazione degli addon.

Segui qui la guida: https://itemsadder.plugin.ga/plugin-usage/ia

Devi spostare tutte le tue categorie dal file ia_gui.yml in un nuovo file che creerai

**Comment by Fargus5** [comment]
si ma il link che mi stai dando non mi dice abbastanza.
il flie con dentro le categorie del mio namespace lo posso chiamare come mi pare?
lo metto dove? dentro una cartella? la cartella la chiamo come?
opure posso mettere i file delle categorie anche stesso dentro la cartella varius_config?

e poi se non voglio creare categorie, come faccio per far in modo che gli oggetti siano visibili nelle categorie già esistenti?

ad esempio builder's basic l'addon... come faccio per aggiungere i blocchi nella categoria di default dei blocchi già presenti?

e lo stesso per slimefun... l'unico modo per vedere tutto è cliccando su ALL..

ma come faccio io a creare le categorie di tutte queste cose?

ti rendi conto del lavoro assurdo?

**Comment by LoneDev6** [comment]
> il flie con dentro le categorie del mio namespace lo posso chiamare come mi pare?

Sì come sempre, i file .yml che sono dentro le cartelle dei namespace (in items_packs) puoi chiamarli come vuoi da sempre, per facilitare l'organizzazione.

> lo metto dove? dentro una cartella? la cartella la chiamo come?

lo metti dentro una cartella che vuoi tu, di un tuo namespace. Puoi chiamare il file categorie.yml o come vuoi tu.

> opure posso mettere i file delle categorie anche stesso dentro la cartella varius_config?

non usare le mie cartelle, crea tu tutti i namespace che ti pare, in caso di aggiornamento poi non ci capisci niente perché non sai che cartelle puoi cancellare perché hanno sia la roba mia che tua


> e poi se non voglio creare categorie, come faccio per far in modo che gli oggetti siano visibili nelle categorie già esistenti?

Ti basta chiamare la categoria nello stesso modo dell'altra, verranno aggiunti gli oggetti in automatico alla categoria originaria teoricamente.

> ma come faccio io a creare le categorie di tutte queste cose?

queste cose quali? se ti riferisci al pack slimefun serve per slimefun4 non serve per utilizzare questi oggetti ingame.
Quegli oggetti sono da lasciare lì e vengono utilizzati da slimefun4 per rappresentare i suoi oggetti  usando le texture di itemsadder, non devi usarli come oggetti per il gioco in sè. Puoi vederli nel menu /ia solo per questione di coerenza per far vedere che sono stati caricati, non per poterli usare per altri scopi.

> ti rendi conto del lavoro assurdo?

a voglia che mi rendo conto, chi credi che abbia creato gli oggetti uno ad uno? 
Non può sempre essere tutto automatico e di certo non te lo posso fare io, se devi gestire un server devi anche essere pronto a dedicare ore a configurare, come posso automatizzare tutto?
Cioè non posso sapere come vuoi tu le categorie e come le vuole un altro utente, non posso automatizzare questo..

Poi conta che tutte le categorie degli oggetti di itemsadder già creati da me sono già presenti e preparate da me, non capisco che difficoltà ci sia nell'aggiungere i tuoi oggetti a quelle categorie ora che sai che ti basta crearne con nome identico in modo che vengano unite in automatico alle mie.

Per esempio se hai la categoria swords di itemadder ti basta crearne una con lo stesso nome swords e metterci i tuoi oggetti, dopodiché vedrai che appariranno tutti insieme

**Comment by Fargus5** [comment]
ok va bene ti ringrazio.
