### ISSUE TITLE
[BUG] Players who aren't OPed cannot load the texture pack

### ISSUE THREAD

**Issue by ItsMacs** [LoneDev6/ItemsAdder#406]
**Describe the bug**
Only opped and players with "*" permission can load the texture.
Others just get kicked with the error "An error occurred while loading the texture pack."

**To Reproduce**
Join if not opped.

**Expected behavior**
Players load texture on join without being prompted.

**Screenshots**

**Info (please complete the following information):**
 - Server version: YAPFA 1.15.2
 - Client version: 1.14.4 Badlion
 - Plugin version: 2.1.12

**Additional context**
I'll provide my config file down below

[ItemsAdder.zip](https://github.com/LoneDev6/ItemsAdder/files/5322331/ItemsAdder.zip)

**Comment by LoneDev6** [comment]
Please send your **complete** server log

**Comment by xSorch** [comment]
Same issue here for some reason, didn't use to be like that: https://paste.helpch.at/zosumofizi.md

**Comment by LoneDev6** [comment]
> 
> 
> Same issue here for some reason, didn't use to be like that: https://paste.helpch.at/zosumofizi.md

Your log is literally full off errors,
please consider enabling debug option to print item loading so you can check which item has wrong enchant property set.
```
[ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[13:49:22] [Server thread/WARN]: java.lang.IllegalArgumentException: Enchantment cannot be null
```

**Comment by ItsMacs** [comment]
[2020-10-06-5.log.gz](https://github.com/LoneDev6/ItemsAdder/files/5332491/2020-10-06-5.log.gz)

**Comment by xSorch** [comment]
I am aware of some the errors, and will fix but not sure if that is what causing the permission issues.

**Comment by LoneDev6** [comment]
@ItsMacs did you set the permissions correctly? https://itemsadder.plugin.ga/plugin-usage/permissions

**Comment by ItsMacs** [comment]
Yup, the plugin just doesn’t seem to care about LuckPerms on join

**Comment by LoneDev6** [comment]
This is strange, my plugins just uses the [hasPermission ](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/permissions/Permissible.html#hasPermission(java.lang.String)) function so Luckperms should provide a proper result


Can you try this on a clean server on your PC? Using latest itemsadder (and dependencies) + latest Spigot (not forks) + luckperms?

thanks

**Comment by xSorch** [comment]
Weird, now it seem to all be fine for me without having done any changes

**Comment by ItsMacs** [comment]
The plugin works without anything else.
I assume there's a problem with some other plugin.
Thank you guys for the patience.

**Comment by LoneDev6** [comment]
There is no problem, let me know which plugin is the cause.
You can identify it removing one plugin at time.

Have a nice day!
