### ISSUE TITLE
[BUG] Items are not spawning how they are set up in the configs

### ISSUE THREAD

**Issue by ZeonBT** [LoneDev6/ItemsAdder#407]
I’m not sure if anyone else is having this same problem but with the new updates from IA I’ve tried spawning some of my custom vehicles and they are coming out with the correct name bit the models are completely different, I’ve not hives if you change around the black_bed.json order the cars will move around in order like if you spawn a custom red car it would spawn a custom pink car I will upload screen shoots of the issues soon I’m not on mc right now,

**Comment by ZeonBT** [comment]
![2020-10-04_01 07 15](https://user-images.githubusercontent.com/44127152/95004077-63ca1a00-05de-11eb-8c87-85b1edbc1b9c.png)
![2020-10-04_01 02 51](https://user-images.githubusercontent.com/44127152/95004078-64fb4700-05de-11eb-8bdd-1dc516064c1a.png)
![2020-10-04_01 02 50](https://user-images.githubusercontent.com/44127152/95004079-6593dd80-05de-11eb-96ba-cbaacb8ada6d.png)
![2020-10-04_01 07 22](https://user-images.githubusercontent.com/44127152/95004080-662c7400-05de-11eb-82c5-0f5e41ce1127.png)
![2020-10-04_01 07 20](https://user-images.githubusercontent.com/44127152/95004082-66c50a80-05de-11eb-9aee-4ee24cefba59.png)
![2020-10-04_01 07 19](https://user-images.githubusercontent.com/44127152/95004083-675da100-05de-11eb-9d57-3684798e076a.png)
![2020-10-04_01 07 18](https://user-images.githubusercontent.com/44127152/95004085-67f63780-05de-11eb-86c7-37aff4f33d5e.png)
![2020-10-04_01 07 17](https://user-images.githubusercontent.com/44127152/95004086-67f63780-05de-11eb-97f9-087b160cc0b8.png)

**Comment by ZeonBT** [comment]
these are all the different type of cars i have and every one is wrong

**Comment by LoneDev6** [comment]
try to delete the file: "plugins\ItemsAdder\storage\items_ids_cache.yml" (MAKE A BACKUP BEFORE DELETING IT).
then regenerate the resourcepack with /iazip

**Comment by ZeonBT** [comment]
Right i tried what you said it did sort out half of the problems, I reloaded a new ID cache and found out the cause of the problem, as before adding a number to a model on the .json as the cache and the ymal normally didn't effect, but i noticed that the models in the ymal, json and cache all has to be in the same order which i didn't know is a thing now, thanks for the help

**Comment by LoneDev6** [comment]
Let me know if i can close this issue report, have a nice day!

**Comment by ZeonBT** [comment]
Yeah sure bud if there anything else wrong I'll let you know
