### ISSUE TITLE
[Suggestion] Assign a texture to the mobs in mythicmobs.

### ISSUE THREAD

**Issue by mA0w0** [LoneDev6/ItemsAdder#409]
Seeing Creatures Plus and IAMobs Addon for compatibility with Lib's Disguises

With the Lib's Disguises feature, only player-shaped skins can be assigned to mobs, but Enderman and others do not.

 I've seen the ItemsAdder add-on work around those issues. Ender dragon and silverfish.

If the mobs added by mythicmobs can be assigned by the texture of itemsadder, it is ideal that the advanced mob behavior can be controlled by mythicmobs and the mob texture can be controlled by itemsadder.

MythicMobsDisguise:
     Type: ITEMSADDER
     Skin:'ITEMSADDER_ITEMSID'
Or hook from itemsadder to mob of MythicMobs
Actually, the file structure and hook format will be left to LoneDev. It is just an example.

**Comment by LoneDev6** [comment]
Thanks, I already implemented that in the new upcoming update.
I will release it this week ;)
