### ISSUE TITLE
Items with attack_damage properties don't work/display properly

### ISSUE THREAD

**Issue by TheMGRF** [LoneDev6/ItemsAdder#41]
Items given specific_properties such as "attack_damage" and maybe "attack_speed" don't seem to apply properly, it is always 1. Might be graphical since I couldn't tell a difference really.
![image](https://user-images.githubusercontent.com/16401884/64712382-03d47300-d4b3-11e9-95ef-9c9bd6cfb903.png)
![image](https://user-images.githubusercontent.com/16401884/64712423-164eac80-d4b3-11e9-8584-92d45ad3d69b.png)

**Comment by LoneDev6** [comment]
Problem is that these specific properties can be set only on swords and guns, do I need to handle them also on axes and or other items?

**Comment by LoneDev6** [comment]
Should be fixed in IA 2.0 (I'm going to publish it in some days).
Now you'll be able to set item attributes for each item, not only swords and guns.
Please after the update reopen this issue on github if this bug occurs again.
