### ISSUE TITLE
[Suggestion] Emoji support for item names

### ISSUE THREAD

**Issue by xSorch** [LoneDev6/ItemsAdder#410]
Seem to not be possible to use emoji names in item names for custom textures.

info:
  namespace: myitems
items:
  halloweenpickaxe:
    display_name: ':jackolantern: &6&lHalloween 2020 Pickaxe :jackolantern:'

This is the result: https://gyazo.com/8fb95ca55dcadaf9a37b10cd0f1bc4e9

**Comment by xSorch** [comment]
Same goes for TAB https://gyazo.com/76ccf267d53f630c587bd00c426f552f
Using: https://www.spigotmc.org/resources/tab-1-5-x-1-16-x.57806/

**Comment by ArgonGaming** [comment]
Use `/e (emoji name)`, then copy that specific unicode and use it in your configurations

**Comment by xSorch** [comment]
Thanks, worked!
