### ISSUE TITLE
[BUG] The display of attack Speed of sword is inconsistent with the setting

### ISSUE THREAD

**Issue by yebanme** [LoneDev6/ItemsAdder#411]
**Describe the bug**
After modifying the attack speed in the config file,
 the default attack speed is still displayed in the game

**To Reproduce**
1. Modify attack speed in config file
2. Reload plugin
3. Attack speed is still displayed at 1.6

**Expected behavior**
Normal display of attack speed

**Screenshots**
![image](https://user-images.githubusercontent.com/20102749/95419653-a2f4c400-096c-11eb-9120-728cbf0d3d0a.png)

**Info (please complete the following information):**
 - Server version: Paper 1.16.3 git-Paper-216
 - Client version: fabric 1.16.3
 - Plugin version: 2.1.2

**Additional context**
ruby_sword:
    display_name: '&frubysword'
    permission: Commongoods
    resource:
      material: DIAMOND_SWORD
      generate: true
      textures:
      - item/ruby_sword.png
    durability:
      max_custom_durability: 1639
    attribute_modifiers:
      mainhand:
        attackDamage: 8.0
        attackSpeed: 2.6

**Comment by LoneDev6** [comment]
Thanks! I will post an update to fix this
