### ISSUE TITLE
IA and MMOItems Incompatible Blocks [BUG] 

### ISSUE THREAD

**Issue by kiloRs** [LoneDev6/ItemsAdder#416]
**Describe the bug**
When using 1.16.3, and the latest MMOItems, and ItemsAdder, I am unable to use the block system from MMOItems, while having ItemsAdder installed, because ItemsAdder overrides the blocks. I would like to use parts of IA, without having to use the block system. Is there a way to fix this? Maybe some sort of toggle of the block system in the configs?

**To Reproduce**
Install MMOItems, setup blocks.
Install IA, then try to place blocks in MMOItems, or view already placed blocks, and they come out wrong, even when using the original texture pack (not the one used with IA)

**Expected behavior**
Ability to break and see the blocks from MMOItems while IA is installed.

**Screenshots**

**Info (please complete the following information):**
- Latest IA
- 1.16.3
- MMOItems Latest Dev

**Additional context**
The blocks either show up as mushroom blocks, or don't work correctly while IA and MMOItems are installed on server.

**Comment by LoneDev6** [comment]
How could you manage the textures of MMOItems? You'd have to manually merge the itemsadder pack with MMOitems and I give no support for these manual changes ad they may alter the plugin and deal to bugs.
Anyway in the **next update** you have to set these values in config.yml and everything should work fine
```
  disable-REAL-behaviour__DISABLE_AT_YOUR_OWN_RISK: true
  disable-REAL_TRANSPARENT-behaviour__DISABLE_AT_YOUR_OWN_RISK: true
```

keep in mind that after this setting ItemsAdder won't fix glitched mushroom blocks around the world anymore, so please don't open support requests for this.

Have a nice day! and i hope this helped you
