### ISSUE TITLE
Saplings for custom trees

### ISSUE THREAD

**Issue by spiker5032** [LoneDev6/ItemsAdder#417]
Is your feature request related to a problem? Please describe.
Ability to get/make saplings for the custom trees and any that a user decides to make such as lemon tree

Describe the solution you'd like
A value to set a sapling as the sapling/seeds to grow a tree

Sapling: true
SaplingLogtype: newtrees:cherry_tree_log
SaplingLeaftype: newtrees:cherry_tree_leaves

Maybe a value that allows you to not grow them in certain biomes?
BiomeBlacklist: Mesa, Tundra

Describe alternatives you've considered
Just spawning in the regular world and breaking/building my own trees

Additional context

This would allow players to make tree farms from these custom trees and add alot more as far as customization is considered for addon pack makers like myself

**Comment by ArgonGaming** [comment]
Good one

**Comment by Bossbirdyman51** [comment]
Good idea ^^

**Comment by LoneDev6** [comment]
Thanks, this will be added in the next update
