### ISSUE TITLE
[Suggestion] About the animation function of custom mobs

### ISSUE THREAD

**Issue by mA0w0** [LoneDev6/ItemsAdder#418]
Currently, you need to make your own animation.

It's possible to have an animation of a few mobs, but it's pretty hard to accommodate if there are many mobs.

Would you like to be able to make the animation behave the original default behavior?

Or will a model of default behavior be distributed?

As far as I can see the texture, it seems to be created in mcmeta format, but I don't know the editor that supports it.

**Comment by LoneDev6** [comment]
Hello!
You can create your own animations with this tutorial: https://www.youtube.com/watch?v=ZwdqY-7pYu4
I didn't link it in my wiki because for now it's not a really fast way to do it, I may release my own tool in the future.

**Comment by mA0w0** [comment]
Is it possible to specify vanilla movements instead of homebrew animations?
Is it impossible to implement such a feature?

**Comment by LoneDev6** [comment]
I don't understand what you mean..
if you're asking if it's possible to use the same animations as the vanilla mob no, this is not possible and won't ever be.
It will be possible only if Mojang adds this feature but I highly doubt they will soon.

There are other plugins which allows you to do this but they are hacky and have a lot of downsides which I don't really want to list

**Comment by mA0w0** [comment]
That's right.
I understand what I want to know.
Thank you very much.

**Comment by LoneDev6** [comment]
No problem! :D
