### ISSUE TITLE
[BUG] Tree Blocks not Showing Correctly

### ISSUE THREAD

**Issue by Xuwznln** [LoneDev6/ItemsAdder#419]
**Describe the bug**
Tree blocks sometimes disappear and become air blocks while sometimes they show itself. Maybe a showing bug if using chorus?

**To Reproduce**
1. Spawn a tree with command.
2. Randomly break some blocks and you will see.

**Expected behavior**
Tree Blocks not Showing Correctly

**Screenshots**
https://sm.ms/image/wxzY5ePUCTlvkAh
https://sm.ms/image/89NoYruDWztsQPw

**Info (please complete the following information):**
 - Server version: 1.16.3
 - Client version: 1.16.21
 - Plugin version: 2.1.3

**Comment by LoneDev6** [comment]
Try in survival, this should happen only in creative mode as the client doesn't send some packets to the server
