### ISSUE TITLE
[BUG] missing texture

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#420]
**Describe the bug**
missing fill texture

**To Reproduce**
1. Install the addon for sf https://www.spigotmc.org/threads/addon-slimefun4-compatibility-for-itemsadder.463173
2. Open /sf guide 
3. Click on Settings & Info
4. Click on Slimefun4 Contributors

**Expected behavior**
There will be no free slot

**Screenshots**
![image](https://user-images.githubusercontent.com/29830635/95677592-d3d03580-0bc6-11eb-8d18-d7597cf067c6.png)

**Info (please complete the following information):**
 - Server version: paper 1.16.3 #216
 - Client version: 1.16.3
 - Plugin version: 2.1.3

**Comment by 100petr** [comment]
https://github.com/Slimefun/Slimefun4/pull/2490

**Comment by LoneDev6** [comment]
it's a slimefun bug
