### ISSUE TITLE
ItemsAdder makes the server lowkey unplayable [BUG] 

### ISSUE THREAD

**Issue by ItsMacs** [LoneDev6/ItemsAdder#421]
**Describe the bug**
Before I enable ItemsAdder, I have an avg of 19.90 TPS.
After enabling it, or if I start up the server with it enabled (it really doesn't make a difference for the performance), the server just straight-up crashes on player join or has an avg of not more than 7 TPS.
I've also used timings to find out that ItemsAdder takes up like 900% of tick time, wasted on block physics even when there is no block update whatsoever.
I don't know what to do, I need IA for my server but I also need it not to have this kind of performance.

**To Reproduce**
1. Enable the server with IA in the plugins folder

**Expected behavior**
The plugin not taking up this much computing space

**Info (please complete the following information):**
 - Server version: YAPFA 1.15.2
 - Client version: Badlion 1.15.2
 - Plugin version: 2.1.5

**Comment by LoneDev6** [comment]
Are you sure there is no 0tick farm or something similar that triggers a loooot of Block Physics? I had another client with this problem and they fixed it finding the farm which was causing the lag.
Other than this, please provide a timings report of your server so I can take a look and see exactly where is the source of the problem.

Also try the plugin using original Spigot or Paper, I didn't test the plugin on this fork YAPFA 


Have a nice day!

**Comment by ItsMacs** [comment]
There were lag farms.
I’m stupid.
Thank you for your time

**Comment by LoneDev6** [comment]
No problem mate, you're not stupid! It's Minecraft stupid 😆 farms lag is insane sometimes...
Let me know which type of farms were lagging the server and send some screenshots if you want, I may add detection to my other plugin: https://www.spigotmc.org/resources/72184/
