### ISSUE TITLE
[BUG] Crashes and custom ores spawn rate

### ISSUE THREAD

**Issue by NightsRevelation** [LoneDev6/ItemsAdder#423]
Hey.
**Intro:** 
So me and another owner are setting up a server along with some other people, and we're running into major crashes and some bugs.
**Problems:**
The first and biggest problem is with the world crashing. Sometimes it's when executing a random command and sometimes it just happens at random.
The second "bug" or issue as it would be more appropriate, is the fact that the custom ores are spawning at an extreme rate thus making the gameplay overpowered. Getting amethyst crystals and making a 13atk sword with no cooldown with just wooden tools is pretty op.
I will try getting a console log from the developer but in the meantime im hoping some issues could be solved before that.
Another bug is the custom ores are spawning on top of mushroom trees, covering it completely as seen in the picture below.
**Pictures:**
![2020-10-13_15 43 38](https://user-images.githubusercontent.com/72892247/96046516-e7ec8f00-0e73-11eb-9aad-f3248a89ac71.png)
![2020-10-13_15 43 36](https://user-images.githubusercontent.com/72892247/96046519-e9b65280-0e73-11eb-99ad-77fbb339a4b9.png)

I hope some issues are able to be solved before sending a console log, i'll try to get the dev to send me one and i'll forward it here.
Thanks!

**Comment by 100petr** [comment]
what version of IA do you have? I had a similar problem in an older version and the update helped solve it.

**Comment by LoneDev6** [comment]
Hello,
you erased the issue template so there are a lot of missing info for me to help you... I have no clue which server version is, which itemsadder version..
Please open a new issue ad DON'T erase the content.
Follow the guidelines.

Have a nice day
