### ISSUE TITLE
Items Adder World Edit Fail[BUG] 

### ISSUE THREAD

**Issue by DerVillion** [LoneDev6/ItemsAdder#424]
With a custom block doing //set with it "//set derblocks:caution_block"

 - Server version: spigot 1.16.3
 - Client version: Aristois client 1.16.3
 - Plugin version: 2.1.5

[img]https://i.imgur.com/plQxoQD.png[/img]

**Comment by LoneDev6** [comment]
Hello! try to logout and login again, this is a Minecraft bug that I can't fix.
Sometimes the block spawns like this as it's a client bug.
I hope you understand and have a nice day
