### ISSUE TITLE
[Suggestion] Custom Sound Play

### ISSUE THREAD

**Issue by BurakDorman** [LoneDev6/ItemsAdder#425]
**Is your feature request related to a problem? Please describe.**
Vanilla playsound command cannot be executed from the console for custom sounds if player is not in the main world, main world is level-name in server.properties

**Describe the solution you'd like**
We should be able to use custom (resource pack) sounds with /iasound command.
A command like /iasound will let us play custom sounds everywhere for everyone.

**Additional context**
Vanilla playsound command doesn't function properly, please try it for players that are not in "world" world. It might be about multiverse worlds, I don't know because I have too many multiverse worlds.

**Comment by LoneDev6** [comment]
Will be added, thanks!
