### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by DerVillion** [LoneDev6/ItemsAdder#426]
Last night I finished and added a bunch of blocks. Went to bed, today when I woke up, most of them are not working. I changed nothing in the server files and no one but me has host access.

 - Server version: spigot 1.16.3
 - Client version: clean 1.16.3
 - Plugin version: 2.1.6 (updated and tried on 2.1.7)

https://imgur.com/NlplIRe
https://imgur.com/ga7AkDG

I am available to send you the files if needed. I thought you had fixed this.... There is no error in console while loading the server nor on reloading the plugin.

 ( DerVillion#1308 )

**Comment by LoneDev6** [comment]
Chatted on discord
