### ISSUE TITLE
[BUG] Could not pass event PlayerCommandPreprocessEvent

### ISSUE THREAD

**Issue by finder1793** [LoneDev6/ItemsAdder#427]
It appears in the most recent update a error appears in consoles. 
https://pastebin.com/bskryMPE <-error from logs
Reproduction would be issuing a command. 

The command does as expected but just throws out that exception.

**Screenshots**

**Info (please complete the following information):**
 - Server version: 1.16.3 Paper
 - Client version: 1.16.3 Optifine
 - Plugin version: 2.1.7

**Additional context**
Also I do apologize if i totally did this in wrong format >.< I never really report bugs

**Comment by LoneDev6** [comment]
Thanks I will publish an update asap
