### ISSUE TITLE
[BUG] Crashing world and too many ores.

### ISSUE THREAD

**Issue by NightsRevelation** [LoneDev6/ItemsAdder#428]
**Describe the bug**
So me and another owner are setting up a server along with some other people, and we're running into major crashes and some bugs.
The first and biggest problem is with the world crashing. Sometimes it's when executing a random command and sometimes it just happens at random.
The second "bug" or issue as it would be more appropriate, is the fact that the custom ores are spawning at an extreme rate thus making the gameplay overpowered. Getting amethyst crystals and making a 13atk sword with no cooldown with just wooden tools is pretty op.
I will try getting a console log from the developer but in the meantime im hoping some issues could be solved before that.

**To Reproduce**
1. Enter server
2. Go to world
3. Do anything random or start teleporting someone
4. Watch as server crashes.

**Expected behavior**
What was expected to happen was for everything to be running smoothly and not suddenly crashing.

**Screenshots**
![2020-10-13_15 43 36](https://user-images.githubusercontent.com/72892247/96296843-3a52ba80-0ff0-11eb-824e-743302573b8b.png)
![2020-10-13_15 43 38](https://user-images.githubusercontent.com/72892247/96296846-3c1c7e00-0ff0-11eb-8079-90e13b215855.png)

**Info (please complete the following information):**
 - PaperMC 1.16.3
 - Tested on all types of clients, fabric, forge, badlion, vanilla.
 - Plugin version: 2.1.2

**Additional context**
I will try to update with console log if its possible.

**Comment by LoneDev6** [comment]
please update the plugin to the very latest version, thanks.
If the problem is still occurring please send a new message here with the crash log
