### ISSUE TITLE
[BUG] text duplication

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#430]
**Describe the bug**
The text is duplicated in the console. No errors https://pastebin.com/aMBKspts

**To Reproduce**
1. Install IA (and other necessary plugins)
2. Go to server
3. Write anything to chat
4. See console

**Expected behavior**
The message will not be duplicated in the console

**Screenshots**
![2020-10-17_08 58 48](https://user-images.githubusercontent.com/29830635/96330632-0c549100-1057-11eb-98eb-c3cb27d9ca91.png)
![image](https://user-images.githubusercontent.com/29830635/96330634-0d85be00-1057-11eb-823e-cfc908b0e4d1.png)

**Info (please complete the following information):**
 - Server version:  PaperMC 1.16.3, Build 232
 - Client version: optifine 1.16.3
 - Plugin version: 2.1.8

**Comment by NessunoMC** [comment]
Same problem.

**Comment by LoneDev6** [comment]
i will post an update, it's a debug message leftover i forgot to remove

**Comment by 100petr** [comment]
![image](https://user-images.githubusercontent.com/29830635/96698074-fa435d00-138c-11eb-8eaa-96787f072edb.png)
again any debug messages?

**Comment by LoneDev6** [comment]
I'm sorry I have to stop coding on night.
Disable this in config.yml "fix-real-blocks-drops-chorus-water-bug__disable-for-more-performance"
Also I think I will remove this fix as it's too resource intensive I think.. I have to find another way to disable breaking chorus with water. Any idea?
