### ISSUE TITLE
[BUG] Unable to replace leather_boots.json or crossbow.json

### ISSUE THREAD

**Issue by NessunoMC** [LoneDev6/ItemsAdder#431]
If I try to update some files, for example, leather_boots.json (used for the VehiclesPlus Pro) or crossbow.json (used by Quality Armory) from `data/resource_pack/assets/minecraft/models/item` when I run the command /iareload /iazip and upload the texture on Dropbox it regenerates by default these files.

**Comment by LoneDev6** [comment]
spiegato su chat spigotmc
