### ISSUE TITLE
[BUG] 1.14.4 possible bug 

### ISSUE THREAD

**Issue by AmazonOmega** [LoneDev6/ItemsAdder#432]
**Describe the bug**
Everytime I do iazip and iareload my console goes a bit crazy. 

https://pastebin.pl/view/9f793fb2

**To Reproduce**
1.Install fresh Plugin.
2.After you do Iazip and iareload command this erros would flod the console. 

**Expected behavior**
Not this many erros.

**Screenshots**
- - -

**Info (please complete the following information):**
 - Server version: (spigot 1.14.4)
 - Client version: (java 1.14.4)
 - Plugin version: ( 2.1.8)

**Comment by LoneDev6** [comment]
Make sure you're running the very latest Paper or Spigot 1.14.4, download it here: https://serverjars.com/

(I'd use 1.16.3.. 1.14.4 is the most unstable Minecraft version btw)
