### ISSUE TITLE
[BUG] All custom items have a christmas skin

### ISSUE THREAD

**Issue by ItsMacs** [LoneDev6/ItemsAdder#433]
**Describe the bug**
Whenever I add custom items to ItemsAdder, it makes them only have a Christmas skin.

**Expected behavior**
Items having their skin

**Screenshots**
https://i.imgur.com/uaoBHG3.png

**Info (please complete the following information):**
 - Server version: Paper 1.15.2
 - Client version: Badlion 1.15.2
 - Plugin version: 2.1.8

**Additional context**
ItemsAdder folder: https://drive.google.com/file/d/1OqeMdvtRwiyK5NwicBBs46oEO472hija/view?usp=sharing

**Comment by LoneDev6** [comment]
Controlla bene di aver usato /iazip e per sicurezza di aver eseguito /iatexture sul tuo gioco per forzare il download del pack nuovo.

Comunque controlla bene di aver seguito il tutorial alla perfezione: https://itemsadder.plugin.ga/plugin-usage/resourcepack-hosting/resourcepack-on-dropbox

**Comment by ItsMacs** [comment]
Ho seguito il tutorial alla perfezione, tutto è aggiornato e ho fatto i comandi corretti, ma il problema rimane.

**Comment by LoneDev6** [comment]
Contattami via messaggio privato su SpigotMC.org e mandami il tuo log completo del server e zip della cartella configurazione di ItemsAdder così controllo.

buona giornata :D

**Comment by ItsMacs** [comment]
Grazie, a te :D
