### ISSUE TITLE
[BUG] Off hand bug

### ISSUE THREAD

**Issue by VulkanoTG** [LoneDev6/ItemsAdder#434]
**Describe the bug**
When we press the F key to change the item to a secondary hand, it generates an error on the console

**To Reproduce**
1- install de plugin
2- press the F key with a sword in hand

**Screenshots**
https://pastebin.com/GzNwd4eH

**Info (please complete the following information):**
 - Server version: Paper 1.16.3 - build-240
 - Client version: Vanilla 1.16.3
 - Plugin version: 2.1.8

**Comment by LoneDev6** [comment]
Update ProtocolLib and let me know
https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/
