### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by DerVillion** [LoneDev6/ItemsAdder#435]
I have done /iareload /iazip and /iatexture all

but my players dont load some of the textures, even though I have them all.

I dont know how to replicate this.

 - Server version: spigot 1.16.3
 - Client version: clean 1.16.3
 - Plugin version: 2.1.8

![2020-10-20_22 43 15](https://user-images.githubusercontent.com/62299145/96647485-a8b3b780-1325-11eb-96ed-5cd07402dea5.png)

![Untitled](https://user-images.githubusercontent.com/62299145/96647545-c3862c00-1325-11eb-96cc-e0988325a8ff.png)

**Comment by DerVillion** [comment]
This specific player had downloaded the texturepack for the first time (never joined the server before)

**Comment by LoneDev6** [comment]
are they using a custom client? forge? fabric? optifine?

**Comment by DerVillion** [comment]
I am using aristois hacked client, they where in default minecraft

**Comment by DerVillion** [comment]
I can let you in the server if you want to check it for yourself. I can't be with you atm (working) but in like 3/4 hours

**Comment by LoneDev6** [comment]
np, i wait

**Comment by DerVillion** [comment]
They where using the default client.
I can join very soon if you are free now

**Comment by DerVillion** [comment]
I am available now.

I've added a few bows, but none of them are working. I added 51 new ones and I get this error:
https://hatebin.com/vphdvnmsqr

I can also make a different bug report.

**Comment by DerVillion** [comment]
You can forget the last comment, after a full server restart, it started working again.
Although the users that have joined , they can see the bows, the ores are still broken for them, but not for me (on my home pc)
Here at work, with a clean minecraft, the ores still don't work

**Comment by LoneDev6** [comment]
https://github.com/LoneDev6/ItemsAdder/issues/454
