### ISSUE TITLE
[BUG] Enchants on swords do not work

### ISSUE THREAD

**Issue by MrFreasy** [LoneDev6/ItemsAdder#436]
**Describe the bug**
I configured the "enchants" section of the swords, but it doesn't seem to work when I get the item from the GUI in the game.

**To Reproduce**
1. Go to 'swords.yml'
2.  Add to masters_sword
     _enchants:
        DAMAGE_ALL: 5_
3. Save and restart server
4. Item without enchants

**Expected behavior**
Get the sword from the GUI with enchant sharpness 5.

**Screenshots**
![ItemsAdder](https://i.imgur.com/pA216NH.png)
![ItemsAdder](https://i.imgur.com/b2c3LMg.png)

**Info (please complete the following information):**
 - Server version: Yatopia.jar #125 (1.16.3)
 - Client version: Optifine 1.16.3
 - Plugin version: 2.1.9

SpigotMC user: EpicProt

**Comment by LoneDev6** [comment]
```yml
enchants:
- DAMAGE_ALL:5
```
instead of
```yml
enchants:
  DAMAGE_ALL: 5
```
