### ISSUE TITLE
[BUG] extract-default-items:false and extract-default-resources:false doesn't work

### ISSUE THREAD

**Issue by NessunoMC** [LoneDev6/ItemsAdder#440]
**Describe the bug**
Setting up

extract-default-items: false
extract-default-resources: false

it still overrides the default items and resorces running the /iazip command.

**To Reproduce**
1. Go to 'plugins/ItemsAdder/'
2. Open 'config.yml'
3. Scroll down to

extract-default-items: true
extract-default-resources: true'

4. Change as

extract-default-items: false
extract-default-resources: false

**Expected behavior**
Using the /iazip command it shouldnt override the items and resources.

**Screenshots**
No.

**Info (please complete the following information):**
 - Server version: PaperSpigot 1.15.2 # 389
 - Client version: 1.15.2
 - Plugin version: 2.1.10

**Additional context**
No.

**Comment by LoneDev6** [comment]
Which files are overridden?

.json files under assets/minecraft folder are always overridden by the plugin and this cannot be disabled

**Comment by LoneDev6** [comment]
This feature will be added today with the new release.
You'd just need to enable this setting in config.yml:
```
    overwrite-vanilla-models__DISABLE_AT_YOUR_OWN_RISK: true
```
