### ISSUE TITLE
Emoji in chat (with kingdoms+) 

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#442]
Se si tenta di utilizzare l'emoji non si può fare più `:smile:` non sarà letto come un sorriso, ma solo come un testo

---

Fargus21/10/2020
Ha già risposto
Crypto Morin#6126
The plugin already uses the parsed chat message.
It uses the "HIGHEST" priority (which can be changed in config)
ItemsAdder isn't open source, so I can't really check anything.
You might want to change chat priority to "MONITOR" it might work
But it's not recommended
LoneDev21/10/2020
figurati provo sempre a rispondere a tutti, grazie!
comunque prova a impostare così in config.yml:

font_images:
  chat:
    enabled: true
    replace-only-packets: true

però mi sembra strano, se non sbaglio è già abilitato di default replace-only-packets.
Questo permette di sistituire le emoji (:smile:) con la loro icona corrispondente (:smile:) direttamente prima che il pacchetto arrivi al client, quindi viene eseguitp dopo il chat event di cui parla Crypto
fammi sapere se ce l'avevi abilitato o no
Fargus21/10/2020
fammi sapere se ce l'avevi abilitato o no
@LoneDev 
font_images:
  negative-spaces-font:
    enabled: true
  chat:
    enabled: true
    replace-only-packets: true
    doublecheck-permission__disable-for-more-performance: false

tutto già abilitato
ma considera che con essentials funziona benissimo. è per forza una compatibilità mancante con kingdoms+... perché se disabilito questo, i smile funzionano
(secondo me)

LoneDevIeri alle 15:08
è molto strano

se riesci reportamelo su github così in settimana sistemo

**Comment by LoneDev6** [comment]
Probabilmente sarà fixato nel prossimo update, fammi sapere se dà ancora problemi.
Lo rilascerò a breve

**Comment by Fargus5** [comment]
> Probabilmente sarà fixato nel prossimo update, fammi sapere se dà ancora problemi.
> Lo rilascerò a breve

Zero errori nella console dopo il primo avvio del server a seguito del tuo ultimo aggiornamento:

https://log.mtxserv.com/EArywKy

Ma per quanto concerne le emoji, resta sempre cosi:

![image](https://user-images.githubusercontent.com/20026629/97898688-7c8e3280-1d38-11eb-9fa7-321bd80f8e78.png)

**Comment by LoneDev6** [comment]
Fixed in 2.1.16 update
