### ISSUE TITLE
[BUG] ItemsAdder pack seems to reload twice

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/ItemsAdder#446]
**Describe the bug**
Sometimes seems to reload twice.
- on /iazip
- on join sometimes

Also: 
- Messages of "applying resourcepack" in console are duplicated.
- Sometimes users gets the "an error occurred enabling the resourcepack" but the pack loads fine

**To Reproduce**
Unknown

**Comment by jiajunmao** [comment]
Can confirm this issue happens

**Comment by LoneDev6** [comment]
Should be fixed in next release
