### ISSUE TITLE
Can Cheat Item-Adder Items Temporary

### ISSUE THREAD

**Issue by JaHollYT** [LoneDev6/ItemsAdder#45]
Hey, i found a bug how to cheat item-adder items temporary. When you drop or move the item then it despawns. Also sometimes other players cant see the cheatet item your hand.
So its no big Problem but maybe you can fix.

You can see here what i mean:
https://www.youtube.com/watch?v=E6iYOF-hYjI&feature=youtu.be

**Comment by LoneDev6** [comment]
It's a Minecraft known ghost items glitch, not an ItemsAdder bug
