### ISSUE TITLE
[BUG] SlimeFun

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#451]
Buongiorno, sto provando ad usare la slimefun, ma c'è un problema.

![image](https://user-images.githubusercontent.com/20026629/97292516-a08ad900-184b-11eb-87d3-b986c6ddaaaf.png)

dopo aver posizionato tutto correttamente, il sistema di generazione di carbone parte, ma quando arriva a 100% non crea il carbone.

![image](https://user-images.githubusercontent.com/20026629/97292486-98cb3480-184b-11eb-8b1c-afaf71128466.png)

**Comment by Fargus5** [comment]
E poi non capisco il senso di usare il blocco di carbone come carburante, per creare altro carbone.

**Comment by LoneDev6** [comment]
Non credo che sia collegato ad itemsadder dato che il pack di itemsadder per la slimefun è solo grafico, dovresti reportarlo agli sviluppatori di Slimefun4, mi sembrano parecchio disponibili: https://github.com/Slimefun/Slimefun4/issues
