### ISSUE TITLE
[BUG] Crash Report

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#452]
Ho avuto 3  crash del server

for the crash error, I saw these two:
at me.imdanix.caves.generator.
at dev.lone.itemsadder

https://log.mtxserv.com/Hz9Zta8

https://log.mtxserv.com/9u5Cuc2

https://log.mtxserv.com/GPnNKmk

Non so da che cosa dipendano, ci capisci qualcosa?

[crash-2020-10-27_18.24.57-server.txt](https://github.com/LoneDev6/ItemsAdder/files/5447020/crash-2020-10-27_18.24.57-server.txt)

**Comment by Fargus5** [comment]
https://github.com/LoneDev6/ItemsAdder/issues/452

**Comment by LoneDev6** [comment]
Seems this plugin is accessing my trees blocks on generation in an asynchronous way which is not good.
You should ask DangerousCaves author about that.
If they are accessing the block in a sync way let them know to just add a try and catch of type java.lang.IllegalStateException here:
https://github.com/imDaniX/Dangerous-Caves-2/blob/89f3d466fd5c2a5dadefb7e20001a39c78d12a9a/DangerousCaves/src/main/java/me/imdanix/caves/generator/AbstractStructure.java#L67



Fammi sapere cosa rispode, nel frattempo puoi disattivare le chest spawnate dal plugin dato che è quello che fa crashare
