### ISSUE TITLE
[BUG] Texture bugs occur when custom model data is added to an item that has the behavior of changing the default item depending on the conditions.

### ISSUE THREAD

**Issue by mA0w0** [LoneDev6/ItemsAdder#453]
Assigning custom model data to the compass goes crazy

I used the Slimefun add-on to assign custom model data to items that use the compass as a material.
The original compass disappears.

As one solution
I looked at'minecraft:item/compass' and added an image to'minecraft:textures' in the resource pack and the texture bug was fixed.
Since it is only an image, there is no compass function.
I couldn't think of anything else.

the compass json doesn't have a model reference for the direction, but iazip overwrites the json so you can't do anything about it.

Elytra should also be a broken Elytra if it has a durability of 1, but that doesn't happen.

This is also because the model is not changed because there is no description in json.

I feel that it can be solved by referring to the default compass or Eritra in the base similar to the crossbow, but I could not think of a solution because it is currently forced by iazip.

"parent": "item/generated" >> "parent":"item/base/compass"

Probably there are others, but I found these two.

Should I give up the texture of the compass?
Is it possible to change the item icon for leather armor?

plugin-2.1.13
paper-251

![2020-10-30_04 36 23](https://user-images.githubusercontent.com/72402669/97693205-2aed6a00-1ae4-11eb-8c34-fb256fb3c2d9.png)
![2020-10-29_19 19 04](https://user-images.githubusercontent.com/72402669/97693213-2de85a80-1ae4-11eb-860f-feb7bbde67f7.png)
![f407f39abcf52ee178aa09c88db4fbc4](https://user-images.githubusercontent.com/72402669/97693515-a222fe00-1ae4-11eb-9430-db30a5560083.png)
![6a6429477039caaeb71ba28bf022b2d8](https://user-images.githubusercontent.com/72402669/97694318-b4ea0280-1ae5-11eb-8055-967575f1e1c2.png)

**Comment by LoneDev6** [comment]
Will be fixed, thanks
