### ISSUE TITLE
[BUG] TRANSPARENT block IDs

### ISSUE THREAD

**Issue by mA0w0** [LoneDev6/ItemsAdder#456]
plugin-2.1.13
paper-251

When I updated to the latest version, I also started to see it.

The already generated file is fine, but when I add a new block and the custom model data json is generated, the numbers are negative and are not applied correctly. Even if you specify the model ID and generate it, it was a negative number, so I think that automatic generation will probably be the same.

This could be avoided by manually rewriting the numbers.

![b0dea5dcec732ccb548fa355215d34f6](https://user-images.githubusercontent.com/72402669/97733972-df56b280-1b1b-11eb-8271-379e853d56a5.png)
![86088b92407d74960ab66207e7cae04e](https://user-images.githubusercontent.com/72402669/97734045-fb5a5400-1b1b-11eb-8537-09c59c8f67b2.png)
![f4302b0ec2061505ee35df0f45811b63](https://user-images.githubusercontent.com/72402669/97733848-b33b3180-1b1b-11eb-94aa-8be7d55d7b90.png)

**Comment by LoneDev6** [comment]
Are you 100% sure you're using 2.1.13?

**Comment by mA0w0** [comment]
Yes···

**Comment by LoneDev6** [comment]
Post the complete config for hologram_projector.
Btw I didn't understand why you're editing slimefun models.. this pack is only used by slimefun internally and it's not meant to be edited.

**Comment by mA0w0** [comment]
When I updated to 2.1.13 and added the block, it became -191, and when I checked the added json, it just consisted of -1 and 0.

Btw I didn't understand why you're editing slimefun models .. this pack is only used by slimefun internally and it's not meant to be edited.

I don't understand what this means.

Is it wrong to assign a texture to slimefun by adding custom model data with itemsadder and matching the custom model data ID of slimefun?

**Comment by mA0w0** [comment]
You may have misunderstood.

It was only -191 after the update, and I'm not sure if it's the same for other blocks just because I added a slimefun block at that time.

I just posted an image of what happened at that time.

**Comment by LoneDev6** [comment]
I don't think the negative ID is related to the "-191" message you see.
Post the content of "storage\items_ids_cache.yml" file

**Comment by mA0w0** [comment]
I have configured a new server.
Even in the default state, it seems to be'-191/63 REAL_TRANSPARENT block'.

![5e41c236a7bf51a2997499d811a72579](https://user-images.githubusercontent.com/72402669/97893600-d6145280-1d74-11eb-921f-899b20168b46.png)
![c61178c20fa842762d8c595472d4f0b3](https://user-images.githubusercontent.com/72402669/97893603-d6ace900-1d74-11eb-9193-127edacd55c3.png)

**Comment by mA0w0** [comment]
Even if you don't configure anything, it's -191, which is very strange.
![a72cbbe96b7c34ba9a46a114e2a1270a](https://user-images.githubusercontent.com/72402669/97894498-e7aa2a00-1d75-11eb-9574-1eadc14c574e.png)

**Comment by LoneDev6** [comment]
Ignore this counter. It will show negative number if there is no REAL_TRANSPARENT block in the plugin.
This is not related to your initial issue

**Comment by mA0w0** [comment]
[items_ids_cache.txt](https://github.com/LoneDev6/ItemsAdder/files/5476688/items_ids_cache.txt)

**Comment by LoneDev6** [comment]
After the latest update does it still generate -1 as ID for hologram_projector?

**Comment by mA0w0** [comment]
As far as I tried it easily, it seems that it is only on the display, and there seems to be no problem in generation.

**Comment by LoneDev6** [comment]
Perfect!

**Comment by mA0w0** [comment]
Even if the version was downgraded, -191 did not change, so it may be because the number of items exceeded 1000. At 700, it was displayed normally in the old version.
I forgot some of the previous versions ＞ ＜
