### ISSUE TITLE
Trinkets (Artifacts) add the ability to add permanent buffs to players (night vision, strength, etc) while holding a custom item

### ISSUE THREAD

**Issue by DerVillion** [LoneDev6/ItemsAdder#459]
I think its a great feature and very self-explanatory. Good luck o/

Trinkets (Artifacts) add the ability to add permanent buffs to players (night vision, strength, etc) while holding a custom item (off or main hand) like the Mage Robe

**Comment by LoneDev6** [comment]
you can easily do that setting an high duration value: https://gaming.stackexchange.com/questions/120492/how-do-i-get-unlimited-potion-effect
