### ISSUE TITLE
[BUG] Bugged mushrooms fix not working

### ISSUE THREAD

**Issue by TheTrippyTree** [LoneDev6/ItemsAdder#460]
**Describe the bug**
Even with "Fix-bugged-mushrooms" enabled in the configuration, I am still seeing plenty of glitched mushrooms in Dark Forests and Mushroom Fields. In Dark Forests, bugged mushrooms appear on the edge of the biome. In Mushroom Fields, they appear on the edge of the biome and also on top of hills within the biome. They are extremely common and have been pointed out by players. Is the setting broke? If I could disable huge mushrooms entirely, I would, but I haven't seen a plugin that does that.

**To Reproduce**
1. Enable "Fix-bugged-mushrooms" in config.yml.
2. Add custom blocks.
3. Find a Dark Forest.
4. Look around the edges of the biome for bugged mushrooms.
5. Find Mushroom Fields.
6. Look at the top of hills for bugged mushrooms.

**Expected behavior**
Huge mushrooms should not be composed of custom blocks.

**Screenshots**
![2020-10-30_17 56 58](https://user-images.githubusercontent.com/43531808/97762448-ef9c6c80-1ade-11eb-9d82-4e9980544e22.png)

**Info (please complete the following information):**
 - Server version: Paper 1.16.3
 - Client version: OptiFine 1.16.3 G3
 - Plugin version: 2.1.13

**Additional context**
The severity of the bug appears to depend on how many custom blocks you have.

**Comment by LoneDev6** [comment]
Check in which biome these blocks are and send me it here, I will check if it's resource intensive to fix or not, thanks.
My plugin fixes 90% of bugged mushrooms inside the world but sometimes it can miss some in charge of more performance.
My plugin will skip the blocks to avoid wasting CPU time if a mushroom tree is in the middle of two biomes and one of them is not in my list of possible biomes to fix

**Comment by TheTrippyTree** [comment]
Biomes that were reported so far:
-Beach
-Birch Forest (+Birch Forest Hills)
-Tall Birch Forest (+Tall Birch Hills)
-Forest
-Mountains
-Plains
-River

It's happening in just about every biome that surrounds a Dark Forest. Ideally, the chunks immediately surrounding every Dark Forest should be checked for mushroom blocks.

I don't know the ins and outs of this plugin having not seen the source code, but perhaps the surrounding chunks could be flagged during world generation. If a chunk is generated and it belongs to a Dark Forest, the chunk and its 8 surrounding chunks are flagged as needing to be checked for bugged mushrooms.

If this cannot be done, would you consider adding a toggle for the plugin to check every biome? I'm not sure what the severity of the performance impact is, but I would like to do some testing with it as my server is quite beefy.

**Comment by LoneDev6** [comment]
Thanks, will be added in the next update in config.yml.
remember to set it to true after the update (enabled: true)
```
    seach-also-in-these-biomes:
      enabled: true
      mushroom-biomes:
        - BEACH
        - BIRCH_FOREST
        - BIRCH_FOREST_HILLS
        - FOREST
        - MOUNTAINS
        - MOUNTAIN_EDGE
        - GRAVELLY_MOUNTAINS
        - PLAINS
        - RIVER
```
