### ISSUE TITLE
[BUG] Long resourcepack loading

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#463]
**Describe the bug**
Long resourcepack loading

**To Reproduce**
1. Go to server
2. Write /iareload or /iazip
3. See error

**Expected behavior**
Reloading will be immediately.

**Screenshots**
Nothing

**Info (please complete the following information):**
 - Server version: paper 1.16.3
 - Client version: optifine 1.16.3
 - Plugin version: 2.1.13

**Additional context**
Log: https://pastebin.com/gd1HvEC6
Now it only takes a long time to load on the test server, on a normal server it crashes.

**Comment by LoneDev6** [comment]
Only thing I noticed is that it's slow on saving itemsadder regions data.
Maybe it's a slow drive? Which drives is your hosting using?

Thanks

**Comment by 100petr** [comment]
Hosting uses some SSDs, there has never been a problem in the past and everything else works normally.

**Comment by LoneDev6** [comment]
Very strange.
Do you have a huge itemsadder region file?
check inside your worlds folders and inside "region_custom_block" and "region_custom_liquids".
Check if some of them has a big size

**Comment by 100petr** [comment]
![image](https://user-images.githubusercontent.com/29830635/97855737-7f1e6700-1cfb-11eb-8066-ce9950943443.png)

**Comment by 100petr** [comment]
![image](https://user-images.githubusercontent.com/29830635/97855853-af660580-1cfb-11eb-9e63-cfd31e01f794.png)

**Comment by 100petr** [comment]
I tried it on a server where I only uploaded the IA folder and deleted the storage and it still does. 
![image](https://user-images.githubusercontent.com/29830635/97862828-4b950a00-1d06-11eb-856d-4cdef9f9e452.png)
![image](https://user-images.githubusercontent.com/29830635/97862856-56e83580-1d06-11eb-8ad6-04db7e634f82.png)
Log: https://pastebin.com/8ySQ0fRL

**Comment by LoneDev6** [comment]
Do you force call iareload on server startup somehow?

**Comment by 100petr** [comment]
No

**Comment by 100petr** [comment]
![image](https://user-images.githubusercontent.com/29830635/97884814-d423a280-1d26-11eb-881b-108c7ffc2a87.png)
Ale psal jsem výše "I tried it on a server where I only uploaded the IA folder and deleted the storage and it still does."

**Comment by LoneDev6** [comment]
Delete fixed_mushrooms_chunks.nbt and restart.
Try if performance is better.

**Comment by 100petr** [comment]
https://pastebin.com/XLDxnN3B still

**Comment by LoneDev6** [comment]
I literally have no idea.
It's like something is calling /iareload after the plugin loaded

**Comment by 100petr** [comment]
I wrote an iareload to see the lag message

**Comment by LoneDev6** [comment]
So this happens even with a clean 0bytes  fixed_glitched_blocks.nbt file?

**Comment by 100petr** [comment]
It looks like it works after removing fixed_glitched_blocks.nbt with the stopped server. But I would still leave it open until I try it tomorrow morning on a normal server.

**Comment by 100petr** [comment]
It works, thanks.
