### ISSUE TITLE
[BUG] Piston Glitch

### ISSUE THREAD

**Issue by BlitzGamer-88** [LoneDev6/ItemsAdder#464]
**Describe the bug**
So when I have put a piston near a custom block facing another way than the custom block but it is powered and I break the piston, the hand of the piston will remain.

**To Reproduce**
1. Put a custom block on the ground like ruby_ore
2. Put a lever in the block that is in a diagonal with the custom block and make it to be Powered (ON)
3. Put a piston facing up inbetween the lever and the custom block and break the powered piston.

**Images**
https://i.imgur.com/Qzn567x.png

**Expected behavior**
I would expect the piston to break completely and not just half of it

**Info (please complete the following information):**
 - Server version: Paper version git-Paper-251 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
 - Client version: 1.16.3
 - Plugin version: 2.1.10

**Comment by LoneDev6** [comment]
Will be fixed, thanks
