### ISSUE TITLE
[BUG] Bossbar bugs

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/ItemsAdder#465]
**Describe the bug**
- If you set a bossbar to a wither based custom mob it will result as duplicate.
- The custom bar is not removed after you kill the boss, this probably happens with any custom mob with custom bossbar .

https://cdn.discordapp.com/attachments/770690407712948244/771792018698403910/video0.mov

**Comment by SirCraftypants** [comment]
This command will remove the dead bossbar.

/bossbar remove

**Comment by LoneDev6** [comment]
Fixed in the latest update
