### ISSUE TITLE
[BUG] About the texture color of leather armor

### ISSUE THREAD

**Issue by mA0w0** [LoneDev6/ItemsAdder#466]
I am impressed that the latest version has textures assigned to leather.

However, there is a difference in the color of the item texture when linking with slimefun.

I don't know if this is a slimefun issue or an ItemsAdder issue.

Not only the color but also the texture of some items does not change.

The texture itself should be reflected in slimefun.
Some of them remain black and do not change.

ItemsAdder is more correct.

![2020-11-03_04 52 02](https://user-images.githubusercontent.com/72402669/97913298-6eb8cb80-1d91-11eb-8576-372d75daf276.png)
![2020-11-03_04 52 28](https://user-images.githubusercontent.com/72402669/97913302-6fe9f880-1d91-11eb-9c02-3a46f96513e8.png)
![2020-11-03_05 01 35](https://user-images.githubusercontent.com/72402669/97913720-12a27700-1d92-11eb-9966-0f0300a5dfa0.png)
![2020-11-03_05 02 17](https://user-images.githubusercontent.com/72402669/97913727-146c3a80-1d92-11eb-96bf-f5f0f47ff731.png)

**Comment by LoneDev6** [comment]
Mhhhh I think it's a slimefun issue on how it colors leather armor, their formula probably is not precise
