### ISSUE TITLE
Commands not working [BUG] 

### ISSUE THREAD

**Issue by NotJKT** [LoneDev6/ItemsAdder#467]
**Describe the bug**
When I do a command like /ia all it does is respond with /ia and other commands like /iablock 
![2020-11-02_17 08 13](https://user-images.githubusercontent.com/73316105/97935630-04227400-1d2e-11eb-8e41-ead2d6a37574.png)

**To Reproduce**

**Expected behavior**
I expected the commands to execute and for example /ia to open up the gui

**Screenshots**

**Info (please complete the following information):**
 - Server version: spigot 1.16.4
 - Client version: optifine 1.16.4
 - Plugin version: 2.1.14

**Additional context**

**Comment by LoneDev6** [comment]
Plugin is surely disabled.
Anyway you didn't provide any log for me to tell you what the issue is
