### ISSUE TITLE
Offset placeholder stopped showing up[BUG] 

### ISSUE THREAD

**Issue by diontimmer** [LoneDev6/ItemsAdder#468]
After updating to 2.1.14, all of my offset placeholders have stopped showing up in my menus, might be related to the new patch in the update.

The offset placeholder does not seem to apply when opening a menu from another plugin, the expected behaviour would be for it to catch and set the graphic back.
![e63d9504e3304eaa91991368bdb175db](https://user-images.githubusercontent.com/825343/97949595-1f0edb80-1d62-11eb-8d4e-b85477012089.jpg)

**Info (please complete the following information):**
 - Server version: paper 1.16.3
 - Client version: 1.16.3
 - Plugin version: 2.1.14

**Comment by LoneDev6** [comment]
Thanks! I will fix this in next release
