### ISSUE TITLE
[BUG] Armors in gui

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#469]
**Describe the bug**
Armors in gui is invisible

**To Reproduce**
1. Go to server
2. Write /ia
3. See gui

**Expected behavior**
Items in Armor in gui will be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/29830635/97970957-9bd1a200-1dc2-11eb-9e18-e4cdf828c223.png)
![image](https://user-images.githubusercontent.com/29830635/97970982-a55b0a00-1dc2-11eb-9e5a-a7d6193a46d6.png)

**Info (please complete the following information):**
 - Server version: paper 1.16.3
 - Client version: optifine 1.16.3
 - Plugin version: 2.1.14

**Additional context**
It will probably be something with yesterday's update.

**Comment by 100petr** [comment]
Currently also tested with the ia and lonelibs update. It is still not visible.

**Comment by LoneDev6** [comment]
Thanks, I found the cause
