### ISSUE TITLE
AdvancedBanker not working properly 

### ISSUE THREAD

**Issue by JP2K** [LoneDev6/ItemsAdder#47]
I recently bought the plugin AdvancedBanker with the username JP2K. I configured it with the /abadmin tool to dissable the xp and deposit function. however players can still deposit their xp and get bank checks. Any help on how to dissable it? 

preferably i would like to delete the entire bottom row, basically from the "deposit xp" to the "money in this page". is that possible. since the config.yml seemed pretty limited. 

Also the shift right click to edit banker is also not working. even though i am an op and also have added the permissions for this action.

Important EDIT: I am using PaperSpigot. Might this be the cause? Even though i ran your compatibility check and all of your plugins were compatible

If its not possible personally. Would it be possible for you make a custom banker gui for me?

-Kind Regards JP2K

**Comment by LoneDev6** [comment]
Hello, please use this GitHub only for ItemsAdder reports and report other plugins bugs in my Discord or via SpigotPM. Thanks!

I added two new config options in config.yml for you! :D
exp_deposit_button: true
money_deposit_button: true


check Spigot page for the update
