### ISSUE TITLE
[BUG] plugin conflicting with groupmanager

### ISSUE THREAD

**Issue by Stoniasawsome** [LoneDev6/ItemsAdder#471]
**Describe the bug**

**To Reproduce**
install lonelibs and itemsadder  (i use all the addons) (havent tried it without them)
install groupmanager and make a few groups
manuadd player groupname
mansave

**Expected behavior**
When i use itemsadder and lonelib with groupmanager for permissions my players rank tags dont go away, meaning once they are promoted they keep their old tag and get a new tag resulting in 2 rank tags in chat. Itemsadder or lonelibs seems to be somehow creating an info section in my groupmanager user files that looks like this.

users:
  0901c687-c261-300e-90bd-eae532512c62:
    lastname: kalose
    group: default
    subgroups: []
    permissions: []
    info:
      prefix: '&5[&cGERM&5]&b '
      suffix: ''
  11951307-a9b9-36c2-bf0c-c42dc338772b:
    lastname: CommanderBlock
    group: grasshopper
    subgroups: []
    permissions: []
    info:
      prefix: '&5[&cGERM&5]&b '
      suffix: ''
  25964d75-97aa-3426-bea9-91360a1caa3c:
    lastname: Steve_French_
    group: shark
    subgroups: []
    permissions: []
    info:
      prefix: '&e'
      suffix: ''
  dc10a575-55b0-3f14-bb14-23d9561afa86:
    lastname: GumbyBlock
    group: grasshopper
    subgroups: []
    permissions:
    - cmi.command.sethome.3
    info:
      prefix: '&5[&cGERM&5]&b '
      suffix: ''

its not suppose to have the prefix and suffix under an info: section in users

my users are to look like this or they get 2 tags

users:
  0901c687-c261-300e-90bd-eae532512c62:
    lastname: kalose
    group: default
    subgroups: []
    permissions: []
  11951307-a9b9-36c2-bf0c-c42dc338772b:
    lastname: CommanderBlock
    group: grasshopper
    subgroups: []
    permissions: []
  25964d75-97aa-3426-bea9-91360a1caa3c:
    lastname: Steve_French_
    group: shark
    subgroups: []
    permissions: []
  dc10a575-55b0-3f14-bb14-23d9561afa86:
    lastname: GumbyBlock
    group: grasshopper
    subgroups: []
    permissions:
    - cmi.command.sethome.3

**Screenshots**
![2020-11-04_18 05 21](https://user-images.githubusercontent.com/13128666/98187583-42ab6080-1edf-11eb-8a6e-de330986a754.png)

this is a screenshot of groupmanager having a seizure over lonelibs when i do manuadd player groupname. 

**Info (please complete the following information):**
 - Server version: (spigot 1.16.3)
 - Client version: (1.16.3)
 - Plugin version: (2.1.15b)

**Additional context**
There is no error, in the console about this when it happens. The reason i know its lonelibs or itemsadder is because i removed all the other plugins and used process of elimination

**Comment by Stoniasawsome** [comment]
was a settings in the config

**Comment by LoneDev6** [comment]
Which setting in which config of which plugin?
Thanks

**Comment by Stoniasawsome** [comment]
it was the string of settings in the itemsadder plugin that says   vault-prefix-suffix: all those settings i just disabled at the same time, and it went away.


-----Original Message-----

**Comment by LoneDev6** [comment]
I think that you have to wait 30 seconds in order to see the vault prefix value updated since that's how it's configured in itemsadder.
![image](https://user-images.githubusercontent.com/27242001/98259668-b2265c00-1f82-11eb-8e68-e6374acc34df.png)
Since vault doesn't provide any event for that change I have to update the prefix each X interval, I set 30 seconds to avoid high CPU usage.
