### ISSUE TITLE
[BUG] Error with Vault

### ISSUE THREAD

**Issue by argenisRO** [LoneDev6/ItemsAdder#472]
**Describe the bug**
ItemsAdder doesn't work when running with Vault v1.7.3 (latest)

**To Reproduce**
1. Apply the 4 IA plugins (Lonelib, ProtocolLib, LightAPI, IA)
2. Run Server, let everything load then turn off the server
3. Apply Vault to the plugins folder and start the server
4. Get into Minecraft and join the server

**Expected behavior**
Compatibility with Vault

**Screenshots**
https://mcpaste.io/18c3c8a663ecbb73

![iaerror](https://user-images.githubusercontent.com/11830002/98189557-35907080-1ee3-11eb-93ca-6c9af9491217.png)

**Info**
 - Server version: Paper 1.16.3 (# 253)
 - Client version: Minecraft 1.16.3 (Vanilla)
 - Plugin version: **2.1.15b**

**Additional context**
Plugin works fine as soon as I remove Vault.
This does not happen with versions older than 2.1.14.
(Assuming when Mimic and Suffix support for Vault was added)

**Comment by LoneDev6** [comment]
Strange, I downloaded it from here and seems to work fine: https://github.com/MilkBowl/Vault/releases/tag/1.7.3

Anyway I will post an update today, let me know if it fixes the issue.
After the update download new IA and redownload Vault from the URL I sent you
