### ISSUE TITLE
[BUG] CRITICAL Startup Error

### ISSUE THREAD

**Issue by ArgonGaming** [LoneDev6/ItemsAdder#475]
Error Logs:
https://pastebin.com/X0bAZn3T

**Info (please complete the following information):**
 - Server version: Paper 1.16.4
 - Client version: Vanilla 1.16.4
 - Plugin version: 2.1.16

**Comment by 100petr** [comment]
The same problem #478

**Comment by JustiinGER** [comment]
Please give us the full log.
Because i have not that problem. Its probaly a dependency that is outdated.

**Comment by LoneDev6** [comment]
Update LoneLibs
