### ISSUE TITLE
[Suggestion] Developer API public repository?

### ISSUE THREAD

**Issue by BlitzGamer-88** [LoneDev6/ItemsAdder#476]
Hello.

I would love to see the Developer API for the ItemsAdder plugin uploaded in a public repository.

You may ask why is that needed? 
1. Well a lot of developers can't afford or simply won't buy the plugin to add support for ItemsAdder to their plugins.
2. It would make the life of those who bought it as well a lot easier, allowing them to use buildtools like maven or gradel without having to import the plugin jar every time they make a plugin that needs to support IA.

I feel like if the Dev API would be uploaded to a public repository it would make life a lot easier for developers, which would add support for this plugin into their plugins which would also benefit you since they can advertise "IA support" and it would send players to see what IA is and what a great plugin it is.

Thank you for your time!

**Comment by ArgonGaming** [comment]
https://itemsadder.plugin.ga/developers/java-api Have you seen this yet?

**Comment by BlitzGamer-88** [comment]
The thing is that API is written inside the plugin jar. To access it you need to import the plugin jar. That's exactly why I made this suggestion.

**Comment by R-Josef** [comment]
https://github.com/LoneDev6/ItemsAdder-API#-packages
Look at the README.md, there is a public repo. you can use maven or gradle.
