### ISSUE TITLE
ItemsAdder Citizens console error? [BUG] 

### ISSUE THREAD

**Issue by Agaloth** [LoneDev6/ItemsAdder#477]
**Describe the bug**
Just a console error that randomly pops up.

**To Reproduce**
1. Have Citizens
2. Maybe have CitizensCMD?
3. Have ItemsAdder 2.1.16

**Expected behavior**
https://paste.ubuntu.com/p/jkTVSbFWFt/ this error should appear.

**Info (please complete the following information):**
 - Server version: Purpur-710 1.16.1
 - Client version: Minecraft 1.16.1
 - Plugin version: 2.1.16

**Comment by LoneDev6** [comment]
Thanks, fixed in the upcoming update
