### ISSUE TITLE
[BUG] nbt problem

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#478]
**Describe the bug**
The itemsadder does not start.

**To Reproduce**
1. Upgrade server from 1.16.3 to 1.16.4
2. See console

**Expected behavior**
The itemsadder starts.

**Screenshots**
![image](https://user-images.githubusercontent.com/29830635/98333221-8a75d900-2000-11eb-9cd3-95f447012f20.png)

**Info (please complete the following information):**
 - Server version: tuinity 1.16.4
 - Plugin version: 2.1.16

**Additional context**
I tried to delete fixed_mushrooms_chunks.nbt according to this https://github.com/LoneDev6/ItemsAdder/issues/231, it still doesn't work. 
![image](https://user-images.githubusercontent.com/29830635/98333441-0e2fc580-2001-11eb-9e48-7033d439529a.png)
Full log: https://pastebin.com/y1jaTG0K

**Comment by 100petr** [comment]
Ops, duplicate https://github.com/LoneDev6/ItemsAdder/issues/475

**Comment by JustiinGER** [comment]
Hello, i see you have LoneLibs version 1.0.4 installed.
There is a new version 1.0.5 available.
Try to reproduce the error with this version of LoneLibs and without IALibs 1.0 because that is outdated.

**Comment by 100petr** [comment]
You are right about lonelibs, I updated it on the test server but not on the normal one. I'll try it tomorrow morning.

**Comment by LoneDev6** [comment]
Just update LoneLibs to latest version 😄 

IALibs is old and not needed, just to inform everyone.

**Comment by 100petr** [comment]
After uninstalling ialibs, resourcepack does not work and itemsadder spam error.
[latest.log](https://github.com/LoneDev6/ItemsAdder/files/5504436/latest.log)

**Comment by 100petr** [comment]
So it does the same thing 4 months ago, so I still had it on the server.

**Comment by 100petr** [comment]
[latest.log](https://github.com/LoneDev6/ItemsAdder/files/5504450/latest.log)
With the new version of lonelibs.

**Comment by LoneDev6** [comment]
ItemsAdder works perfectly on latest Paper 1.16.4, I tested it.
It has some bugs but the resourcepack works fine..

**Comment by 100petr** [comment]
I found it, it's antibotdeluxe, I contact their support, thank you.

**Comment by LoneDev6** [comment]
I wonder why these guys don't update their libs EVERYTIME 🤦‍♂️ 
Thanks for the patience mate

**Comment by 100petr** [comment]
So I'm thinking, can't it have something to do with #260?

**Comment by LoneDev6** [comment]
I don't understand how it could be related.

Anyway if you removed AntiBotDeluxe and ItemsAdder works fine it's because AntiBotDeluxe is using an old version of apache libs.
Ask them to update them
