### ISSUE TITLE
[BUG] Don't Load Textures

### ISSUE THREAD

**Issue by RickyLaChow** [LoneDev6/ItemsAdder#479]
**Describe the bug**
I follow the guide but, the output is []
I'm trying to add BetterRanks

**Screenshots**
![2020-11-05_23 11 34](https://user-images.githubusercontent.com/25041502/98349136-eac54480-2019-11eb-9caa-325ff248beb8.png)

**Info (please complete the following information):**
 - Server version: 1.16.4
 - Client version: 1.16.4
 - Plugin version: Lastest 2.1.16

**Comment by LoneDev6** [comment]
Check this: https://itemsadder.plugin.ga/faq/huds-emojis-guis-font/i-cant-see-emoji-guis-huds

if still doesn't work try to regenerate the zip file using /iazip and if you're using external host reupload the pack and update the url in config.yml

**Comment by RickyLaChow** [comment]
Ciao Lone, a me sembra di aver fatto tutto correttamente ma non funziona
Vedo tutto giusto tipo :Cutie: o :Coal: ma quelli di betterranks li vedo []
Sei disposto a passarmi la texturepack con le cose di betteranks dentro?

https://www.dropbox.com/s/xhhix63h774ngkk/prova_surv.zip?dl=1 
Questa è la texture pack
Mentre per quanto riguarda la cartella ItemsAdder ho unzippato i file come c'è scritto nel tutorial

**Comment by LoneDev6** [comment]
C'è qualcosa che non va nel resourcepack, sei sicuro di aver usato il comando /iazip?..
Il file zip che mi hai mandato l'ho controllato e non va bene, mancano proprio i rank nel file assets\minecraft\font\default.json.
Questo significa che il file zip del resourcepack che stai usando probabilmente non è stato generato correttamente.
Se hai usato /iazip assicurati di star caricando su dropbox il file pack.zip e non il mio.
https://itemsadder.plugin.ga/plugin-usage/resourcepack-hosting/resourcepack-on-dropbox
![immagine](https://user-images.githubusercontent.com/27242001/98559161-94206a80-22a6-11eb-91a7-5872993f34e6.png)


Oltre a questo, sei sicuro di avere il file data\items_packs\betterranks\ranks.yml?


Se hai seguito il tutorial alla lettera è impossibile che non funzioni

**Comment by RickyLaChow** [comment]
mancano proprio i rank nel file assets\minecraft\font\default.json.
Mmh, Si perchè facendo /iazip a me non crea la cartella


C'è un passaggio che mi sfugge
![2020-11-09_16 28 23](https://user-images.githubusercontent.com/25041502/98560962-a0a5c280-22a8-11eb-9aef-7b185f708166.png)
Facendo /iazip e scaricando il file non dovrebbe funzionare?

**Comment by LoneDev6** [comment]
Il file lo trovi nella cartella del tuo server sotto `plugins\ItemsAdder\data\resource_pack\pack.zip` come indicato nello screenshot

**Comment by RickyLaChow** [comment]
Grazie mille dell'aiuto LoneDev!
Ho risolto mi mancava questo pezzo, potevo arrivarci ma non avevo inteso.

**Comment by RickyLaChow** [comment]
Lone, ho un altro problema chi non è op non vede la TAG developer e cose così
Ho aggiunto betterranks.admin ma non lo vedono lo stesso

**Comment by LoneDev6** [comment]
Controlla di aver aggiornato itemsadder a 2.1.17

nessun problema!

**Comment by RickyLaChow** [comment]
Itemsadder è alla versione 2.1.18

**Comment by LoneDev6** [comment]
dove non viene mostrato il TAG developer e "cose così"

per aiutarti mi servono più informazioni che puoi, screenshot ecc

**Comment by RickyLaChow** [comment]
![2020-11-10_11 44 52](https://user-images.githubusercontent.com/25041502/98664071-2e85ba00-234a-11eb-9ad8-dd67d3413675.png)
Come vedi da questo screenshot senza l'OP non vedo le varie emoji e tag
Mentre quando ho ricevuto l'op vedo le varie emoji e tag

**Comment by LoneDev6** [comment]
Che plugin usi per la chat?
Se usi CMI leggi qui: https://itemsadder.plugin.ga/compatibility-with-other-plugins/compatible/cmi

Ma comunque dovrebbe funzionare anche per gli altri, ti basta cambiare la formattazione della chat impostando come prefisso %vault_prefix% (leggi il tutorial che ti ho inviato qui sopra)

**Comment by RickyLaChow** [comment]
Per la Chat utilizzo EssentialsChat 
Comunque grazie mille

**Comment by LoneDev6** [comment]
Manca il permesso `ia.user.image.chat`

**Comment by RickyLaChow** [comment]
Nono quel permesso è presente

**Comment by LoneDev6** [comment]
Ah okay perfetto allora
