### ISSUE TITLE
Error Loading newest Item Adder version

### ISSUE THREAD

**Issue by JaHollYT** [LoneDev6/ItemsAdder#48]
Hey, there is an Error by try loading the newest Item Adder Version:

21.09 17:52:40 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-192]
21.09 17:52:40 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-192]
21.09 17:52:40 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-192]
21.09 17:52:40 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-192]
21.09 17:52:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-192]
21.09 17:52:40 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-192]
21.09 17:52:40 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-192]
21.09 17:52:40 [Server] INFO at dev.lone.itemsadder.Main.onEnable(Unknown Source) ~[?:?]
21.09 17:52:40 [Server] INFO at dev.lone.itemsadder.Main.w(Unknown Source) ~[?:?]
21.09 17:52:40 [Server] INFO at dev.lone.itemsadder.i.a.<init>(Unknown Source) ~[?:?]
21.09 17:52:40 [Server] INFO at dev.lone.itemsadder.i.a.update(Unknown Source) ~[?:?]
21.09 17:52:40 [Server] INFO java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyInputStreamToFile(Ljava/io/InputStream;Ljava/io/File;)V
21.09 17:52:40 [Server] ERROR Error occurred while enabling ItemsAdder v1.1.24 (Is it up to date?)
21.09 17:52:40 [Server] INFO |_____|\__\___|_| |_| |_|___/_/    \_\__,_|\__,_|\___|_|   
21.09 17:52:40 [Server] INFO _| |_| ||  __/ | | | | \__ \/ ____ \ (_| | (_| |  __/ |   
21.09 17:52:40 [Server] INFO | | | __/ _ \ '_ ` _ \/ __| / /\ \ / _` |/ _` |/ _ \ '__|
21.09 17:52:40 [Server] INFO | | | |_ ___ _ __ ___  ___   /  \   __| | __| | ___ _ __ 
21.09 17:52:40 [Server] INFO |_   _| |                       /\      | |   | |          
21.09 17:52:40 [Server] INFO _____ _                                 _     _           
21.09 17:52:40 [Server] INFO ------ ItemsAdder ------
21.09 17:52:40 [Server] INFO [ItemsAdder] Enabling ItemsAdder v1.1.24

**Comment by LoneDev6** [comment]
Please install https://dev.bukkit.org/projects/plugman 
it will solve your compatibility issue
