### ISSUE TITLE
[BUG] Damage lore not updated according to enchants

### ISSUE THREAD

**Issue by MrFreasy** [LoneDev6/ItemsAdder#481]
**Describe the bug**
I configured the "enchants" section of the swords, but when I see the item from the GUI in the game the weapon stats don't change according to the enchants applied.

**To Reproduce**
- Go to 'swords.yml'
- Add to masters_sword
```
   enchants:
    - DAMAGE_ALL: 5
```
- Save and restart server

**Expected behavior**
Weapon stats should change based on the enchants applied.
For example if I put sharpness on a sword it should modify the damage in the weapon stats and not show the "attackDamage" found in the "attribute_modifiers" that is refer to the "smooth" sword without enchants.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/46691191/98363107-bad46c00-202e-11eb-9de5-9c812b722f64.png)
![image](https://user-images.githubusercontent.com/46691191/98364003-44d10480-2030-11eb-8f5c-1288be13a994.png)

**Info (please complete the following information):**
- Server version: git-Yatopia-"94afff9" (1.16.3)
- Client version: Optifine 1.16.3
- Plugin version: 2.1.16

SpigotMC user: EpicProt

**Comment by LoneDev6** [comment]
Grazie, verrà corretto nel prossimo aggiornamento
