### ISSUE TITLE
[BUG] Issue with Font GUIs

### ISSUE THREAD

**Issue by ArgonGaming** [LoneDev6/ItemsAdder#483]
![image](https://user-images.githubusercontent.com/30943826/98425651-fc333e80-2063-11eb-9254-5650e98607da.png)
![image](https://user-images.githubusercontent.com/30943826/98425658-02291f80-2064-11eb-8fc4-6f2cc7cf7055.png)

**Comment by ArgonGaming** [comment]
Update: It would seem this is related to the emojis themselves 
![image](https://user-images.githubusercontent.com/30943826/98425738-44eaf780-2064-11eb-92fb-7b469b06ff15.png)

**Comment by LoneDev6** [comment]
Seems font offsets fail to load somehow.
I find it strange that started happening from nowhere, surely something changed in your configs or resourcepack, did you edit anything recently?

Please try to update to the very latest itemsadder and regenerate the resourcepack zip.
Also make sure you're not using a unofficial minecraft client.

let me know
I close this in the meantime as works fine in normal conditions.

**Comment by ArgonGaming** [comment]
Updated to latest, and zipped once again. I think it started happening after I added the official itemadder ranks font addon

**Comment by ArgonGaming** [comment]
Client was Optifine 1.16.4

**Comment by ArgonGaming** [comment]
Update: Removed Betterranks Addon, no solution in issue so far

**Comment by LoneDev6** [comment]
I have no idea sincerly, I'm sure if you follow the tutorial it works fine as I do tests before releasing updates.
Anyway, send me your clientside log. Get it from logs folder inside your Minecraft installation

**Comment by ArgonGaming** [comment]
[latest.log](https://github.com/LoneDev6/ItemsAdder/files/5517692/latest.log)

**Comment by LoneDev6** [comment]
This is not the client log, I asked "Get it from logs folder inside your Minecraft installation"

**Comment by ArgonGaming** [comment]
My bad, here you go:
https://www.dropbox.com/s/b459d43vv9b7os1/latest.log?dl=0

(Log was a big size)

**Comment by LoneDev6** [comment]
(I downloaded and deleted your log message to avoid people from getting personal info from it, just in case)

Error: `java.io.FileNotFoundException: minecraft:textures/font/unicode_page_12.png`

Also `com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 4 column 31 path $.pack.description`

Do you have any other pack enabled in your game? They may override my custom fonts.

**Comment by ArgonGaming** [comment]
I did not have any other packs installed at the time, and I am not the only player who has this issue now that I tested it, it seems to be a pack issue itself

**Comment by LoneDev6** [comment]
send me all your itemsadder configs via discord message in a zip file

**Comment by JulesFX** [comment]
i have the same issue

**Comment by LoneDev6** [comment]
This issue report is almost 3 years old. 
Please do not message on very old issue reports.
