### ISSUE TITLE
[BUG] Blocks aren't working in 1.16.4

### ISSUE THREAD

**Issue by Jirsaacek** [LoneDev6/ItemsAdder#484]
**Describe the bug**
When you have TILE block and place it in 1.16.4 it just shows pig spawner without texture, when mined there's no drop. 

**To Reproduce**
1. Get TILE block
2. Place it
3. There's just pig spawner

**Expected behavior**
It should place normal custom block as it did before

**Comment by LoneDev6** [comment]
Thanks, fixed in the upcoming update
