### ISSUE TITLE
[BUG] Door glitch when next to IA REAL block

### ISSUE THREAD

**Issue by Golshr** [LoneDev6/ItemsAdder#485]
Hi, 'sup

**Describe the bug**
When you put a door next to an IA block and you try to open it by right-clicking on the door block directly next to the IA block, the door seems to open but you can't go through it.
When you try to open it with redstone, it doesn't open at all, or only one part of the door

**To Reproduce**
1. Place a door
2. Place an IA REAL block next to one part of the door blocks
3. Open it by right-clicking on the door block next to the IA block
4. Try to walk through and fail

**Expected behavior**
You are supposed to be able to walk through the door

**Screenshots**
![image](https://user-images.githubusercontent.com/17353049/98469098-fcefe000-21dd-11eb-9b98-2e648a1ffdea.png)

**Info**
 - Server version: spigot 1.16.3)
 - Client version: vanilla 1.16.3)
 - Plugin version: 2.1.16
 - Protocollib version : v4.6.0-SNAPSHOT-b482

**Additional context**
TILE block does not produce the bug

Please note that I had really strange behaviors when I placed a button on an IA block and broke the IA block, the button was still in place, floating. I think the reason of those 2 bugs are the same, so I won't create a new issue for that.
I gave you the Protocollib version, because I think the problem may come from a packet issue.

**Comment by LoneDev6** [comment]
Thanks, fixed in the upcoming update
