### ISSUE TITLE
[BUG] Diamond Hammer's AOE can break bedrock.

### ISSUE THREAD

**Issue by Ochiona** [LoneDev6/ItemsAdder#487]
**Describe the bug**
With a Diamond Hammer you can get Bedrock using its 3x3 AOE mining ability.

**To Reproduce**
Step 1. Go to Bedrock in world, ie. right above it's general spawn location y=5.
Step 2. Either craft or get Diamond Hammer.
Step 3. Mine adjacent to bedrock, ie. stone near it, any block near it.
Step 4. Continue to do this until bedrock drops. (this doesn't happen all the time, once in like 40 or so adjacent block breaks).
Step 5. Get Bedrock, Profit? or Abuse?

**Expected behavior**
Not being able to get bedrock.
Keep in mind, Slime-fun utilizes a bedrock breaker, while I don't think this is affecting it there may be a reason the "ability" to break bedrock is there. Either way, this is broken for Factions.

**Screenshots**
https://ibb.co/cQxQrrW

**Info (please complete the following information):**
 - Server version: Paper on Bukkit 1.16.3-R0.1-SNAPSHOT
 - Client version: 1.8-1.16.4 (Via-Version and Via-Backwards)
 - Plugin version: 2.1.16

**Additional context**

**Comment by LoneDev6** [comment]
Very strange I thought I had fixed that like one year ago.
can you make a video?
I just tried and the bug doesn't happen, maybe you got a plugin which is interfering with drops?

Anyway, test the plugin on a clean server and see if the problem is there, let me know
