### ISSUE TITLE
[BUG] /iazip create wrong bow model

### ISSUE THREAD

**Issue by patatoplugin** [LoneDev6/ItemsAdder#489]
**Describe the bug**
I use /iazip  and in resourcepacks/assets/minecraft/models/item/bow.json,it don't have bow-pulling model
**To Reproduce**
1.use /iazip
2.look the resoucepacks

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server version: 1.16.3
 - Client version: 1.16.3
 - Plugin version: 2.1.16

**Additional context**

**Comment by LoneDev6** [comment]
Delete the bow file and use the /iazip command again.
I just tested and is generated correctly
