### ISSUE TITLE
[BUG] /iasummon Error

### ISSUE THREAD

**Issue by harshit2608** [LoneDev6/ItemsAdder#490]
**Describe the bug**
When used /iasummon it throws error "An internal error occurred while while attempting to tab-complete this command"

**To Reproduce**
Write command /iasummon 

**Expected behavior**
Item adder should be able to list the custom mobs that i have added and spawned them on command

**Error**
https://pastebin.com/YeV6WSxW

**Info (please complete the following information):**
 - Server version: git-Paper-261 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
 - MythicMobs version: 4.10.1
 - Item Adder version: 2.1.15

**Comment by LoneDev6** [comment]
Somewhere you set REDSTONE_BLOCk instead of REDSTONE_BLOCK
