### ISSUE TITLE
[BUG] Resource Pack not loading fully. Error in console included in desc.

### ISSUE THREAD

**Issue by jallen6769** [LoneDev6/ItemsAdder#491]
When players join the server, sometimes the resource pack says it applies but it doesn't. I get an OpenGL Error 1281 (Invalid Value) as well as an error in the console that says "Unhandled exception number 128/256 occured in onPacketReceiving(PacketEvent) for ItemsAdder"

I expected the resource pack to load for all players. I don't have any other plugins that manage a resource pack either.

https://gyazo.com/47edd149651152f488edd3956bed2240

Server is Paper 1.16.3 version 231

**Comment by ArgonGaming** [comment]
You should probably show the full error log (if not the whole log for that secession), and OpenGL Errors are clientslide.

**Comment by jallen6769** [comment]
Thats good that its only clientside but that is the only error in the console

**Comment by LoneDev6** [comment]
Send the whole log
