### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Ashuniva** [LoneDev6/ItemsAdder#498]
**Describe the bug**
So, I was testing out my armors, and when I put a full set of armor on I just took no pvp damage and mob damage.

**To Reproduce**
1. Go to /ia
2. Click on any full armor set
3. Scroll down to put the armor on
4. See error Try to take mob or pvp damage, it might just be my  server

**Expected behavior**
You will take no damage

**Screenshots**
It requires a video and 2 people which I sadly don't have right now.

**Info (please complete the following information):**
 - Server version: 1.16.4
 - Client version: Paper 1.16.4
 - Plugin version: 2.1.19

**Additional context**
Only has happend with two armor sets so far in testing, mysterious and a set I added called dragon, and sometimes happens with ruby

**Comment by Ashuniva** [comment]
I also added an addon, and this only started happening after I added it.

**Comment by LoneDev6** [comment]
Can you test the plugin on a clean server with only itemsadder and its dependencies?
There is no god mode for any of the armors, this seems an external problem.

let me know how the test goes
