### ISSUE TITLE
[BUG] With Gui

### ISSUE THREAD

**Issue by Bossbirdyman51** [LoneDev6/ItemsAdder#499]
Hi,
I have 5 server, one for test and other.
In my test server ( local ) i have configured all of item and minerals with texture and all it's work.
But when i move with winscp all of my file on server i don't have gui when i say /ia or hydratation bar ( water bar )
I have some problem too with texture hydratation bar have wooden pickaxe and other item don't have the good texture.

For this problem I have say to the folder 777 permission.

 - Server version: 1.16.3
 - Client version: 1.16.2
 - Plugin version: 2.1.17

**Additional context**
I modify all of item in plugins/itemsadder/data/itemsadder and items.yml, minerals.yml etc... 
I need to create a custom folder ?
Thanks for help

**Comment by LoneDev6** [comment]
Make sure to use /iazip also on the online server and if you're using dropbox reupload the pack.zip file getting it from the online server.

Seems the textures mapping generated by the local server differ from the online server. It's rare but can happen

**Comment by Bossbirdyman51** [comment]
Yes I use iazip and place new file in custom texturepack I retest it tomorrow

**Comment by Bossbirdyman51** [comment]
I have this error : [05:05:04] [Craft Scheduler Thread - 29/INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.categories_view.font_image.name
[05:05:04] [Craft Scheduler Thread - 29/INFO]: [ItemsAdder] GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.category_view.font_image.name
[05:05:04] [Craft Scheduler Thread - 29/INFO]: [ItemsAdder] Loaded 1 categories
[05:05:04] [Craft Scheduler Thread - 29/INFO]: [ItemsAdder] Loaded items and stuff in 2176ms
[05:05:04] [Craft Scheduler Thread - 6/INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip

**Comment by LoneDev6** [comment]
Did you delete the mcguis folder?
That's what the error tells: "GUI error: can't find font_image. Check ia_gui.yml, attribute: settings.categories_view.font_image.name"
It means that the gui texture set in ia_gui.yml under "categories_view.font_image.name" was not found in the plugin.

**Comment by Bossbirdyman51** [comment]
I have delete all file and upload the file of local server and now all it's work, i have add permission for file and user / group ( Debian )

**Comment by Ezz-Eldeen** [comment]
I'm sorry could you please explain to me the difference between the "online server" and the "local server" I'm encountering the same issue and I'm using drop box to host the resourcepack. I do /iazip on the server, get the generated.zip file and upload it to dropbox but it appears that I'm missing a few images related to the gui, any fixes?
