### ISSUE TITLE
Vehicles crash server

### ISSUE THREAD

**Issue by MrCoby220** [LoneDev6/ItemsAdder#50]
Step by step guide to crash your server with vehicles

#1 craft a vehicle
#2 go in the end
#3 ride your vehicle
#4 drive in the void

**Comment by LoneDev6** [comment]
A nice thing would be to provide a valid crash log or something as it's not happening based on my tests on my online server.

Thanks

**Comment by MrCoby220** [comment]
you can close this :) my bad
