### ISSUE TITLE
[Support request] Problem with texturepack

### ISSUE THREAD

**Issue by blacklorem** [LoneDev6/ItemsAdder#504]
**Describe the bug**
Ciao Matteo, sono lorenzo, un collega di Claudio (Fargus) sul server stiamo riscontrando un problema con la texture, ogni volta che vado ad apportare delle modifiche e le salvo, ma eseguo il comando /iareload e /iazip, queste modifiche vanno cancellate.
PS. La console non mostra alcun tipo di errore

Attendo risposta, grazie mille.

Lorenzo

**Comment by Fargus5** [comment]
Buongiorno, lo spiego un attimino meglio..

Questa è la resourcepack che utilizzo per Itemsadder: http://www.survivalla.fun/respack/pack39.zip


Questa è invece la resource pack che vorrei inserire dentro la resourcepack che utilizzo di itemsadder: 
https://www.dropbox.com/s/2grkgbgmovyqmw0/QualityArmoryV2.1.9.zip?dl=1

Il problema è che, non so per quale motivo... i file che modifico si **resettano**

**Comment by LoneDev6** [comment]
Imposta questo nel config.yml di itemsadder:
```
overwrite-vanilla-models__DISABLE_AT_YOUR_OWN_RISK: false
```

**Comment by blacklorem** [comment]
@LoneDev6 , abbiamo modificato l'overwrite, ma la texture al riavvio si resetta.
Dopo il riavvio la texture è tornata così (dal niente è comparsa una diamond sword)
[crossbow.zip](https://github.com/LoneDev6/ItemsAdder/files/5556744/crossbow.zip)

Io ho provato ad unire la texture di QA a quella di Itemadder, ma il tutto non funziona.

**Comment by LoneDev6** [comment]
> Dopo il riavvio la texture è tornata così (dal niente è comparsa una diamond sword)

Non capisco cosa intendi, questo è il vostro file e vedo le varie spade configurate:
https://pastebin.com/tyjrLszb

Dov'è comparsa la diamond sword? Non capisco bene.




Vado a intuito.. secondo me per risolvere dovete impostare dei custom_model_id molto alti per le armi di quality armor, invece di impostarne di bassi. I custom model data più bassi li prende in automatico itemsadder.
Quindi (sperando si possa altrimenti è pessimo) su quality armor cambiate il custom model data dalle varie armi e fate di conseguenza nel crossbow.json.
