### ISSUE TITLE
[BUG] Test Server Broken!

### ISSUE THREAD

**Issue by BlitzGamer-88** [LoneDev6/ItemsAdder#505]
Seems like the test server is broken (test.plugin.ga). Well at least ItemsAdder on it is. Well more likely parts of it is. When you do `/ia` you get the "internal error" message. Since I don't have access to console :) I don't know what the problem is but someone mentioned it in the IA discord server so I decided to make a thread to make sure LoneDev sees it.

I know quite a few people use the test server to see what the plugin can do but not a lot of them will consider buying it when they see it doesn't even work on the test server.

https://i.imgur.com/XBCWOZB.png

That's all. thanks for your time and thanks to @modii101#7784 on discord for letting me know about this.

**Comment by LoneDev6** [comment]
Thanks, i will fix it today, I didn't notice the plugin was inactive since I didn't join for days
