### ISSUE TITLE
[BUG] Shield blocking model

### ISSUE THREAD

**Issue by TheTrippyTree** [LoneDev6/ItemsAdder#507]
**Describe the bug**
Shield blocking models are not working.

**To Reproduce**
1. Create a custom shield with a '_blocking' model.
2. Block with the shield in first person view.
3. Blocking shield model is not displayed.

**Expected behavior**
The blocking model should be displayed.

**Info (please complete the following information):**
 - Server version: Paper 1.16.4
 - Client version: 1.16.4
 - Plugin version: 2.1.19

**Additional context**
After inspecting models\item\shield.json, the blocking model definition is present in the 1.16.3 version of IA, but not 1.16.4.

**Comment by TheTrippyTree** [comment]
Looks like this also affects bows, crossbows and fishing rods.

**Comment by LoneDev6** [comment]
Thanks, i will fix that in the next update
