### ISSUE TITLE
MineTinker

### ISSUE THREAD

**Issue by RickyLaChow** [LoneDev6/ItemsAdder#508]
Puoi aggiungere il collegamento con MineTinker?
Perchè quando l'item livella non rimane come impostato ma diventa ciò che è di default 
es. Spada di Rubino è fatta con WOODEN_SWORD non appena il plugin va in azione e imposta il livello ecc

**Comment by LoneDev6** [comment]
Dovresti contattare lo sviluppatore di MineTinker.
Puoi fornirgli la tua copia di itemsadder senza problemi in modo che possa usare l'API, basta che non la condivida online.
