### ISSUE TITLE
[BUG] Block updates when next to an AI block

### ISSUE THREAD

**Issue by Golshr** [LoneDev6/ItemsAdder#509]
**Describe the bug**
Some block updates doesn't work when next to IA block.

**To Reproduce**
1. Place a block that is usually updated when a block next to it is changes, next to an IA block
2. Make an action that should update the block
3. It doesn't work

**Expected behavior**
Updates are supposed to happen.

**Screenshots**
Well, here is a video for every tested interaction, I don't know if there's any more that doesn't work. [YouTube](https://www.youtube.com/watch?v=GOMmI39thWU) The black block is an IA block

**Info (please complete the following information):**
 - Server version: Spigot 1.16.3
 - Client version: Vanilla1.16.3
 - Plugin version: 2.1.19

**Comment by LoneDev6** [comment]
Hello!
I had to introduce some blocks for the custom blocks feature as Minecraft breaks every custom block texture on chain updates.
I don't this there is a way to fix these problems as they technically are not bugs but it's intended.
Sadly if I remove these checks every surrounding custom block will lose its texture.

I hope Mojang/Spigot addresses that in the future allowing us to disable block updates for Mushrooms.
