### ISSUE TITLE
Can't repair custom armors, tools, weapons.

### ISSUE THREAD

**Issue by MrCoby220** [LoneDev6/ItemsAdder#51]
So when you try to repair anything such as armors, tools, swords that are made out of custom materials example amethyst you can put the item (armors, tools and swords) in the anvil fine but when you add the repair material (amethyst) in the other slot it glitches the inventory to where you can't take out anything 

Expectation :

Being able to set an item in the config as a repair material
lets say i got a custom sword called BoneSword i would want to be able to set an atribute example 

repair_meterial: bone (or item adders ids)

and then i would be bale to use bones to repaird BoneSword in an anvil

**Comment by MrCoby220** [comment]
Also mending does not work :)

**Comment by LoneDev6** [comment]
Use latest version, anvil repair got added: https://www.mc-market.org/resources/10839/update?update=35355

https://app.gitbook.com/@lonedev/s/itemsadder/items-properties/durability/anvil-repair
"- added new attribute "specific_properties.anvil_repair_item" that allows you to specify which item can be used to repair an item in Anvil"
