### ISSUE TITLE
[BUG] Empty line on armor lore

### ISSUE THREAD

**Issue by TheTrippyTree** [LoneDev6/ItemsAdder#511]
**Describe the bug**
Custom armors have a blank line in the lore.

**Expected behavior**
Armor lore should not have an empty line.

**Screenshots**
![2020-11-15_15 57 25](https://user-images.githubusercontent.com/43531808/99196886-11435800-275d-11eb-9465-721379960037.png)
![2020-11-15_16 09 57](https://user-images.githubusercontent.com/43531808/99196887-130d1b80-275d-11eb-8849-8220193adf34.png)

**Info (please complete the following information):**
 - Server version: Paper 1.16.4
 - Client version: 1,16,4
 - Plugin version: 2.1.19

**Comment by LoneDev6** [comment]
Thanks, I noticed in 1.16.2 they added a new attribute to hide that line (it was the "Dyed" line).
Before 1.16.2 it wasn't possible.

I will fix that in next update
