### ISSUE TITLE
[BUG] I get an error when generating pack.zip with iazip.

### ISSUE THREAD

**Issue by mA0w0** [LoneDev6/ItemsAdder#512]
https://pastebin.com/HzHmZYfF

I get an error, but it seems to be generated after that, the effect of another plugin?

ItemsAdder: 2.1.19
Paper: 279

**Comment by LoneDev6** [comment]
Please read here and let me know if it works: https://github.com/LoneDev6/ItemsAdder/issues/463#issuecomment-720544088
