### ISSUE TITLE
[BUG] Ores dont generate

### ISSUE THREAD

**Issue by lubek-dc** [LoneDev6/ItemsAdder#513]
Hi, Ores dont generate

**Comment by LoneDev6** [comment]
This report is invalid.
Please do not erase the issue template, answer all the questions provided.

**Comment by LoneDev6** [comment]
Also be sure to read here: https://itemsadder.plugin.ga/faq/blocks-minerals-issues/i-cant-find-any-mineral-ore

**Comment by lubek-dc** [comment]
thx
