### ISSUE TITLE
[BUG] Mysterius_Head

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#515]
[14:53:17]: [INFO] [ItemsAdder] Result item itemsadder:mysterious_head not found in crafting recipe recipes.crafting_table.mysterious_head, file /data/items_packs/itemsadder/armors.yml

Matteo, buongiorno, spero tu abbia una buona settimana.

Senti come mai itemsadder:mysterious_head è inesistente?

**Comment by LoneDev6** [comment]
Non so dove stai leggendo mysterious_head dato che questo oggetto non esiste nei miei config.
C'è il mysterious_hood che è un cappello nel file hats.yml

**Comment by Fargus5** [comment]
Mi esce scritto nella console :)

**Comment by LoneDev6** [comment]
Controlla dentro armors.yml, io son sicuro di non averlo mai creato, forse in una versione iniziale di itemsadder ma ora non esiste più quell'oggetto.

Se puoi rimuovi la ricetta segnalata nel log
