### ISSUE TITLE
[BUG]  Wrong Mob Name

### ISSUE THREAD

**Issue by Jirsaacek** [LoneDev6/ItemsAdder#517]
When you set custom item as an custom mob drop, and then look what it drops from, it says vanilla mob's name, not custom mob's name. 
In screenshot: That item drops from custom mob named "Scarecrow", but it says it drops from "Husk" which is mob I just used as an AI.

![2020-11-16_19 07 39](https://user-images.githubusercontent.com/63473875/99291103-91da8500-283f-11eb-9597-bd14b400dd4c.png)

**Comment by LoneDev6** [comment]
Thanks, this will be fixed in next update
