### ISSUE TITLE
[SUGGESTION] Cooldown Timer for events

### ISSUE THREAD

**Issue by Talesu** [LoneDev6/ItemsAdder#518]
Add a event feature that adds the possible variable to add cooldown to a event action

This seems a good idea, like some events play particles/sound/cmd and adding a cooldown adds more strategy to certain items.

This would open loads of possibilities just with a small cooldown event action variable.

Thanks Lone for reading and helping me lately :)

Much love,
- Talesu

**Comment by LoneDev6** [comment]
Thanks for the suggestion, this will be added in the upcoming update
