### ISSUE TITLE
[BUG] Plugin crash and don't start

### ISSUE THREAD

**Issue by yttalium** [LoneDev6/ItemsAdder#519]
Server version : Paper 1.16.4 #282
Client version : 1.16.4
Plugin version : 2.1.16 to 2.1.20

Hello, when I start my server, the plugin start but crash in step "Found resourcepack folder:"
I try to start with just the plugin and all addons (ProtocolLib, IALib, lonelib, libdisguises and LightAPI all last version) but nothing change.

Error : http://pastebin.fr/73873

Have a good day :)

**Comment by LoneDev6** [comment]
Update LoneLibs, thanks
