### ISSUE TITLE
I dont know how to call it. Plugin disables itself in 1.1.27 

### ISSUE THREAD

**Issue by Padlick01** [LoneDev6/ItemsAdder#52]
When I start my server, ItemsAdder is disabling itself with this error code:
https://pastebin.com/r8xbvGDc

And when I unload it via Plugman and load it again, it is a different error code:
https://pastebin.com/tGMHLttC

It says something with cooked_sausage, so I give you the config for cooked_sausage:
https://pastebin.com/jfUC1U2H

I really hope you can help me :D As I think that you can.^^

**Comment by LoneDev6** [comment]
Please update to latest Paper or Spigot version, thanks!
It was an old Minecraft bug they fixed

**Comment by Padlick01** [comment]
Have updated to latest paper now. Still the same issue.

**Comment by LoneDev6** [comment]
Contact me via PM and share full log of your server, thanks

**Comment by Padlick01** [comment]
It got fixed in a dev version he sent me.
