### ISSUE TITLE
[BUG] Strange Error

### ISSUE THREAD

**Issue by ArgonGaming** [LoneDev6/ItemsAdder#520]
Hey! A strange error occurred and wanted to report it to see it's origins/reasons, and if it is a concern or easily fixable!

https://pastebin.com/aFs01uwm

Plugin Ver: 2.1.20
Spigot: Paper 1.16.4

**Comment by LoneDev6** [comment]
Seems someone is trying to break a furniture which was removed from the itemsadder configs, you can ignore the error, anyway I will add a check to silently ignore the armorstand instead of throwing the warning in console.
thanks for the report
