### ISSUE TITLE
[Suggestion] Silencing giving message

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#525]
Matteo, potresti per favore mettere questo messaggio in silent

obtained-item: '&7Obtained item &e{item}'

per esempio aggiungendo silent alla fine del comando di give.

/iagive LoneDev itemsadder:tomato 1 silent

ne ho veramente bisogno perché ho collegato i give ai drop di mythicmobs 

e la chat ovviamente spamma come se non ci fosse un domani

**Comment by LoneDev6** [comment]
Verrà aggiunto nel prossimo aggiornamento, grazie
