### ISSUE TITLE
incompatibility with LootChest

### ISSUE THREAD

**Issue by sl44n3sh** [LoneDev6/ItemsAdder#528]
please solve

**Comment by LoneDev6** [comment]
Add more details, I don't know what you mean with "please solve".
Thanks.

You basically erased the issue template, this is not a good idea to have a fix as it takes more time for me to ask more details about the problem.

**Comment by SirCraftypants** [comment]
> 
> 
> please solve

If you want Lootchest to be compatible with Itemsadder then you need to get the Developer of LootChest to make his plugin compatible with Itemsadder.

From the looks of it Lootchest does not support nbt/custom model data.

**Comment by LoneDev6** [comment]
Ask LootChest dev to include NBT support, I cannot fix it on my own.
Have a nice day
