### ISSUE TITLE
Emojis not working with holographic displays.

### ISSUE THREAD

**Issue by ValouProjet** [LoneDev6/ItemsAdder#531]
**Describe the bug**
2 days ago i decided to update itemsadder to the newest version (2.1.20).
Before the update, my emojis were working fine (i'll take the  example with the lock symbol :_lock_: 🔒 ). When i typed :_lock_: in the chat, it gave me the right symbol (🔒) , same in the holograms of holographic displays (so it was working perfectly).
But after the update, all my symbols in my holograms were changed into another ones for no reasons.. (for example the lock symbol into the right_arrow symbol...). 

**So** : 
* in the chat : emojis are working fine. 
* in the holograms : it's weird...

**To Reproduce**
I don't know.. I just update ItemsAdder and still have the same version of Holographic displays (the last one v2.4.5).

**Expected behavior**
When it type in the chat, it gives me the right symbols.
BUT, in the holograms it doesn't give ANY symbols (it doesn't replace :_lock_: by 🔒 )
BUT, my old symbols in the holograms were changed into another random symbols (i don't know why) (for example from 🔒  to 💯).
I just want to have the right symbol.

**Screenshots**
Look on the screen to understand the following sentences.
BEFORE THE UPDATE I HAD 🔒 **Votes** (perfect).
AFTER THE UPDATE I HAVE the left arrow symbol **Votes** (new random symbol but not the 🔒 symbol.. so it changed itself randomly ??).
AND WHEN I WANT TO CREATE A NEW HOLOGRAM WITH :lock: it doesn't work... (as u can see on the screen it doesn't replace :_lock_: by 🔒 ).
![2020-11-28_17 20 31](https://user-images.githubusercontent.com/57060565/100520464-1614fc80-319e-11eb-8543-73e831e3e06c.png)

**Info**
 - Server version: spigot 1.15.2
 - Client version: minecraft launcher 1.15.2
 - Plugin version: 
* ItemsAdder : 2.1.20 (the last one)
* Holographic display : v2.4.5 (the last one)

**Comment by LoneDev6** [comment]
Thanks, in next update you will be able to use PlaceholderAPI to use emojis.
For example `%img_smile% `will show a smile

**Comment by LoneDev6** [comment]
https://itemsadder.plugin.ga/compatibility-with-other-plugins/compatible/holographic-displays
