### ISSUE TITLE
Armors not showing Armor & Armor thoughness.

### ISSUE THREAD

**Issue by ValouProjet** [LoneDev6/ItemsAdder#532]
**Describe the bug**
I have a problem i hadn't with the last versions of IA.
When i put my cursor on sword, pickaxes, etc... it gives me the stats (attack speed & attack dmg), all is normal and working fine.
However, when i put my cursor on a piece of armor (whatever it is, your armors or mines) it doesn't show me the stats (armor & armor thoughness). It worked fine in the past... Any ideas ?

**To Reproduce**
Just create a piece of armor, whatever it is.

**Expected behavior**
I just want the armors to show their stats (armor & armor thoughness).

**Screenshots**
1.  You can see that the swords (tools too) are working.
2. Armors are not showing their stats (but it show the durability).
![2020-11-28_23 16 54](https://user-images.githubusercontent.com/57060565/100527146-d49d4500-31cf-11eb-96d1-7cd4b593c2b0.png)

![2020-11-28_23 16 55](https://user-images.githubusercontent.com/57060565/100527143-d23aeb00-31cf-11eb-97b7-a8529fd48e02.png)

**Info (please complete the following information):**
 - Server version: spigot 1.15.2
 - Client version: basic minecraft launcher in 1.15.2
 - Plugin version: 2.1.20 (latest ;))

**Additional context**
Nope.

**Comment by SirCraftypants** [comment]
Add Lore, problem solved.

  camo_boots:
    display_name: Camo Boots
    permission: camo-boots
    resource:
      generate: true
    lore:
      - '&2Armor 3'
      - '&2Toughness 3'      
    durability:
      max_custom_durability: 325
    specific_properties:
      armor:
        slot: FEET
        color: 385800
    attribute_modifiers:
      feet:
        armor: 3
        armorToughness: 3

**Comment by SirCraftypants** [comment]
may be you can return the favor and answer my query about how you managed to hide the color hex code from shwoing on your armour.

**Comment by ValouProjet** [comment]
Thanks for the answer, but i still think that's a bug we didn't have in the last versions of IA.
I don't even know how i did that (i think it's in IA by default?) : there is an example with a helmet i made (without colo code showing) :

  casquerubis:
    display_name: '&rCasque en rubis'
    permission: armures
    resource:
      generate: true
    durability:
      max_custom_durability: 388
    specific_properties:
      armor:
        slot: head
        color: b02e26
    attribute_modifiers:
      head:
        armor: 3.5
        armorToughness: 2

As u can see there is no line for the colo code.
I checked in my config.yml file and same, nothing about color codes showing or not.
Maybe u should update your version ? I don't know.
Have a nice day !

**Comment by SirCraftypants** [comment]
I figured it out, item id tooltips was enabled, i disabled it and the hex code disappeared and was replaced by the word 'dyed' which i then removed by removing the word from my resource pack lang file.

At least lore is a temporary solution until the issue is solved.

**Comment by LoneDev6** [comment]
Armor attributes will be re-added in new update, thanks for the report

**Comment by SirCraftypants** [comment]
So to be clear, it's the custom attributes from the yml files that are going to appear on the Custom Armor and not the leather armor attributes correct. I don't want the leather armors attributes showing.

**Comment by LoneDev6** [comment]
![image](https://user-images.githubusercontent.com/27242001/101189976-0c850c00-3658-11eb-9d87-90bed08a20b8.png)
