### ISSUE TITLE
[BUG] Shift-Click crafting duplication glitch

### ISSUE THREAD

**Issue by will-turner123** [LoneDev6/ItemsAdder#535]
**Describe the bug**
Shift-clicking an item which cannot be stacked, such as the diamond hammer, while crafting more than one of the item will fill the players inventory with the item without taking the crafting ingredients

**To Reproduce**
1. Craft the recipe as shown in the screenshot
2. Shift-Click the recipe result

**Screenshots**
https://gyazo.com/1374fa30259fca5fd7e129bc9f6ae86d

**Info**
 - Server version: paper 1.16.4
 - Client version: Minecraft 1.16.4
 - Plugin version: 2.1.20

**Additional context**

**Comment by LoneDev6** [comment]
Please make sure you don't have any plugin that handles custom recipes, this could potentially break ItemsAdder.
https://itemsadder.plugin.ga/compatibility-with-other-plugins/not-compatible

An easy way to find out if it's an ItemsAdder bug is to create a very simple test server on your PC and install onl ItemsAdder + its dependencies.

Let me know, have a nice day
