### ISSUE TITLE
[BUG]  I have modified things in the GUI / ia. But what I get is that my data is wrong. I enter information like

### ISSUE THREAD

**Issue by chadedas** [LoneDev6/ItemsAdder#537]
**Describe the bug**
I have modified things in the GUI / ia. But what I get is that my data is wrong.
I enter information like
   1:
     display_name: furniture-01
     permission:
     lore:
     - 'lore-decorative-item'
     resource:
       material: PURPUR_BLOCK
       generate: false
       model_path: new_furniture / 1
     behaviors:
       furniture:
         small_hitbox: false
         solid: true

But what has been
  furniture-01 in the shape of furniture-37 that I entered   HELP ME PLEASEE

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server version: spigot 1.16.3
 - Client version: original 1.16.3
 - Plugin version: 2.1.20

**Additional context**

**Comment by chadedas** [comment]
Now I can fix it.
Just enter   plugins \ ItemsAdder \ storage \ items_ids_cache

And delete everything in it   It will fill in new information automatically.  THX

**Comment by LoneDev6** [comment]
be careful deleting the items_ids_cache file, make a backup before deleting it as it may bug already crafted items textures
