### ISSUE TITLE
Vehicles Incompatibility with Towny 

### ISSUE THREAD

**Issue by JaHollYT** [LoneDev6/ItemsAdder#54]
When I try to enter a Vehicle in a Town, i just feel out the world. In a Wilderness Zone its working perfect, but when you come in a town you get dropt of the vehicle or fell out of the world.
That Problem appears with GoCarts and Airplanes but not with the Shopping-Carts.

Using newest ItemAdder Version - 1.1.32
And Newest Towny Devbuild - 0.94.0.16 for 1.14 
(https://github.com/TownyAdvanced/Towny/releases/tag/0.94.0.16)

**Comment by LoneDev6** [comment]
Thanks man, we already contacted towny dev and doesn't want to fix the issue, I can't do much about that.

I'll try to investigate more but as I said, Towny dev basically just refused to fix the issue
