### ISSUE TITLE
[BUG] Update Error 2.1.21

### ISSUE THREAD

**Issue by SirCraftypants** [LoneDev6/ItemsAdder#540]
**Describe the bug**
I just updated todays version of Itemsadder 2.1.21 on 1.16.4 and i'm getting this Error

https://paste.helpch.at/qinuvifufe.md

**Info (please complete the following information):**
 - Server version: paper 1.16.4
 - Client version: MC 1.16.4
 - Plugin version: 2.1.21

**Comment by SirCraftypants** [comment]
Ran iazip from console and got these errors 

https://paste.helpch.at/ajotacamav.sql

**Comment by LoneDev6** [comment]
Are you running latest PlaceholderAPI?

**Comment by LoneDev6** [comment]
"error: " +

**Comment by SirCraftypants** [comment]
no, im on .6

i will update now

**Comment by SirCraftypants** [comment]
Updated to latest PlaceholderAPI.

Getting this error  https://paste.helpch.at/zamevobizu.cs

**Comment by LoneDev6** [comment]
Running PlaceholderAPI version: "2.10.9" and it's working perfectly, sincerly I have no idea

**Comment by LoneDev6** [comment]
test the new itemsadder update

**Comment by SirCraftypants** [comment]
Whatever you did has fixed it, thank you very much, appreciate your time.
