### ISSUE TITLE
[Suggestion / INFO or BUG ?] Permission for Machine 

### ISSUE THREAD

**Issue by Bossbirdyman51** [LoneDev6/ItemsAdder#542]
Hi,

I need to use or interact with custom machine like coffee machine with permission.
I see in furniture.yml a coffee.machine, so I add in LuckPerms : 
- coffee.machine
- ia.user.ia.coffee.machine
- ia.user.craft.coffee.machine
- ia.user.ia
I test with : ia.user.ia.* and ia.user.craft.* and doesn't work too.

But it doesn't work...

Thanks for your help

**Comment by Bossbirdyman51** [comment]
It' was not a bug, I have deleted NoVillagerTrade, but can you add permission to interact with furniture ?

**Comment by LoneDev6** [comment]
As we said on Discord I think that a permission property for the trade_machine would be good.
I add this now
