### ISSUE TITLE
[BUG] NullPointer after trying to fix the mipmap bug

### ISSUE THREAD

**Issue by imparium-de** [LoneDev6/ItemsAdder#543]
**Describe the bug**
After deleting the files mentioned in the spigot update post, I used the `/iazip` command. Ingame is a stuck bossbar saying "Compressing..."

**To Reproduce**
1. Delete the files in `plugins\ItemsAdder\data\resource_pack\assets\mcicons\textures\item`
2. Restart the server
3. Use the `/iazip` command

**Expected behavior**
No error message

**Screenshots**
-

**Info (please complete the following information):**
 - Server version: Paper 1.16.4
 - Client version: Optifine 1.16.4
 - Plugin version: 2.1.21

**Additional context**
Pastebin: https://pastebin.com/uZ7Yi0FX

**Comment by LoneDev6** [comment]
This error has to do with the selfhost server not being loaded correctly, try to restart the server.
If doesn't work send the complete log

**Comment by imparium-de** [comment]
A restart didn't fix it. Here's the complete log: https://pastebin.com/4WWd6bFJ

**Comment by LoneDev6** [comment]
"java.net.BindException: Address already in use: JVM_Bind"

Somehow the port 8163 is already in use.
Try to change the port in config.yml of itemsadder and make sure to open it.
You can set for example 8164

**Comment by imparium-de** [comment]
Okay that did it, thanks! <3 We had to completely restart the root server. Seems like something got stuck there :D
