### ISSUE TITLE
[Suggestion] Musica nelle regioni di worldguard o custom itemsadder regions

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#545]
Ciao Matté, come va? tta post?

Senti, in considerazione del fatto che hai già aggiunto la possibilità di aggiungere nuove musiche / effetti / suoni / voci / etc...  perché non aggiungi anche la possibilità di riprodurli all'interno di determinate regions già preesistenti come quelle di worldguard oppure anche permettendo a ItemsAdder di creare delle custom region (oppure, perché non entrambe le cose per far contenti tutti gli utenti)?

Potrebbe essere molto interessante come feature, per il semplice fatto che NON ESISTE sul mercato attuale un plugin che faccia questo lavoro correttamente e con i suoni customs.

Fammi sapere che ne pensi, discutiamone.

Cia

**Comment by LoneDev6** [comment]
Questo dovrebbe già fare un ottimo lavoro, dacci un'occhiata: https://dev.bukkit.org/projects/regionjukebox
