### ISSUE TITLE
[BUG] Major TPS drops (emoji related?)

### ISSUE THREAD

**Issue by Projecki** [LoneDev6/ItemsAdder#547]
**Describe the bug**
Major TPS drops.

**Screenshots**
![image](https://user-images.githubusercontent.com/65093423/101413526-0f773b00-38aa-11eb-8c78-636e51359215.png)

This dev.lone.itemsadder seems to be a decent portion of the tick, doing a lot of deserializing on the main thread.
Oh wow it gets even worse, so 21% of the tick already is the itemsadder thing.
![image](https://user-images.githubusercontent.com/65093423/101413564-1e5ded80-38aa-11eb-958f-d6f9b3f41aad.png)
![image](https://user-images.githubusercontent.com/65093423/101413575-21f17480-38aa-11eb-8ccf-136efdf3cf8c.png)
Yep this thing is everywhere, I wouldn't be surprised if it was 30-40% of the tick given it runs expensive operations on every single packet sent.
Literally everywhere, could be as high as 50% of the tick tbh

I think if you got rid of this itemsadder plugin you'd double your TPS. Potentially it's something they can fix though.

https://spark.lucko.me/#GzYSFwlfkI https://timings.aikar.co/?id=863a680c8a574eb293fc1bdfd8c7e24c#timings

These are the words of Paul Sauve from the Airplane team.

**Info (please complete the following information):**
 - Server version: Airplane-Lite 1.16.4
 - Plugin version: 2.1.2

**Comment by LoneDev6** [comment]
Open config.yml and set these options:
```yml

    replace-only-packets: false
    doublecheck-permission__disable-for-more-performance: false
```


let me know
