### ISSUE TITLE
[BUG] Multiple Break

### ISSUE THREAD

**Issue by MrFreasy** [LoneDev6/ItemsAdder#548]
**Describe the bug**
By modifying the demon hammer and setting the multiple break with size 2 and depth 2, it's like you set it with size 1 and depth 2

**To Reproduce**
1. Go to ItemsAdder/data/items_packs/itemsadder
2. Open tools.yml
3. Scroll down to line 891-892
4. Change size and depth to 2

**Expected behavior**
Should break a cube of blocks 2x2

**Screenshots**
![Screenshot_5](https://user-images.githubusercontent.com/46691191/101415329-fe4d1f00-38e7-11eb-996d-972c13b05f46.png)

**Info:**
 - Server version: Yatopia version git-Yatopia-"94afff9" (MC: 1.16.3)
 - Client version: 1.16.4
 - Plugin version: 2.1.22

**Comment by LoneDev6** [comment]
You can't break 2x2 as where should be the center block? It would mine decentered.
So you have to use 3, 6, 9 etc.

Anyway send me a screenshot of the hole so I can see what you mean precisely, thanks

**Comment by MrFreasy** [comment]
![Nuovo-video](https://user-images.githubusercontent.com/46691191/101490344-81ab5680-3962-11eb-95c4-d4603c61261c.gif)

**Comment by LoneDev6** [comment]
> 
> 
> You can't break 2x2 as where should be the center block? It would mine decentered.
> So you have to use 3, 6, 9 etc.
> 
> Anyway send me a screenshot of the hole so I can see what you mean precisely, thanks

As I said, you can't break 2x2 holes, only 3x3, 6x6, 9x9 etc
