### ISSUE TITLE
[BUG] Stacked loots

### ISSUE THREAD

**Issue by MrFreasy** [LoneDev6/ItemsAdder#549]
**Describe the bug**
I added the possibility of getting pickaxes by breaking blocks.
Sometimes multiple pickaxe are gived at the same time and stacked.
I don’t know if it works with low chance in the config, but a lot of users reported it to me.

**To Reproduce**
1. Go to ItemsAdder/data/items_packs/itemsadder
2. Open tools.yml
3. Scroll down to the end
4. Paste this https://hastebin.com/uvezecakik.yaml

**Expected behavior**
Should give only one pickaxe

**Screenshots**
![image](https://user-images.githubusercontent.com/46691191/101416281-c8a93580-38e9-11eb-8a6b-f381b17a094c.png)
![image](https://user-images.githubusercontent.com/46691191/101416303-db236f00-38e9-11eb-9903-5091154887c2.png)

**Info:**

Server version: Yatopia version git-Yatopia-"94afff9" (MC: 1.16.3)
Client version: 1.16.4
Plugin version: 2.1.22

**Comment by LoneDev6** [comment]
By "multiple" how many you mean?
I mean, the stack is made of how many pickaxes and do you know which ones in this list are affected?

Thanks

**Comment by MrFreasy** [comment]
It does with all the pickaxes on the list.
Gives 3 stacked pickaxes to the player

**Comment by LoneDev6** [comment]
I tried for over 30 minutes and not a single time I got a stack of pickaxes, always only 1.
You should try on a clean server, it surely is an incompatibility with one of the other plugins
