### ISSUE TITLE
NoSuchMethod Error and Plugman isnt helping.

### ISSUE THREAD

**Issue by salemthewolf** [LoneDev6/ItemsAdder#55]
10.10 01:57:09 [Server] Server thread/INFO Enabling ItemsAdder v1.1.33
10.10 01:57:10 [Server] Server thread/INFO ------ ItemsAdder ------
10.10 01:57:10 [Server] Server thread/INFO _____ _ _ _
10.10 01:57:10 [Server] Server thread/INFO |_ _| | /\ | | | |
10.10 01:57:10 [Server] Server thread/INFO | | | |_ ___ _ __ ___ ___ / \ __| | __| | ___ _ __
10.10 01:57:10 [Server] Server thread/INFO | | | __/ _ \ '_ ` _ \/ __| / /\ \ / _` |/ _` |/ _ \ '__|
10.10 01:57:10 [Server] Server thread/INFO _| |_| || __/ | | | | \__ \/ ____ \ (_| | (_| | __/ |
10.10 01:57:10 [Server] Server thread/INFO |_____|\__\___|_| |_| |_|___/_/ \_\__,_|\__,_|\___|_|
10.10 01:57:10 [Server] Server thread/INFO Loading items...
10.10 01:57:16 [Server] Server thread/INFO Can't find custom item named 'FIREWORK' to complete the recipe registration
10.10 01:57:17 [Server] Server thread/ERROR Error occurred while enabling ItemsAdder v1.1.33 (Is it up to date?)
10.10 01:57:17 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.getI18NDisplayName()Ljava/lang/String;
10.10 01:57:17 [Server] INFO at dev.lone.itemsadder.f.j.bB(Unknown Source) ~[?:?]
10.10 01:57:17 [Server] INFO at dev.lone.itemsadder.f.j.bA(Unknown Source) ~[?:?]
10.10 01:57:17 [Server] INFO at dev.lone.itemsadder.f.k.bI(Unknown Source) ~[?:?]
10.10 01:57:17 [Server] INFO at dev.lone.itemsadder.c.a.bn(Unknown Source) ~[?:?]
10.10 01:57:17 [Server] INFO at dev.lone.itemsadder.c.a.<init>(Unknown Source) ~[?:?]
10.10 01:57:17 [Server] INFO at dev.lone.itemsadder.Main.bJ(Unknown Source) ~[?:?]
10.10 01:57:17 [Server] INFO at dev.lone.itemsadder.Main.onEnable(Unknown Source) ~[?:?]
10.10 01:57:17 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Spigot_Latest.jar:git-Spigot-94af569-d6b3edd]
10.10 01:57:17 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [Spigot_Latest.jar:git-Spigot-94af569-d6b3edd]
10.10 01:57:17 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [Spigot_Latest.jar:git-Spigot-94af569-d6b3edd]
10.10 01:57:17 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [Spigot_Latest.jar:git-Spigot-94af569-d6b3edd]
10.10 01:57:17 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [Spigot_Latest.jar:git-Spigot-94af569-d6b3edd]
10.10 01:57:17 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [Spigot_Latest.jar:git-Spigot-94af569-d6b3edd]
10.10 01:57:17 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [Spigot_Latest.jar:git-Spigot-94af569-d6b3edd]
10.10 01:57:17 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [Spigot_Latest.jar:git-Spigot-94af569-d6b3edd]

I've installed Plugman and nothing seems to be helping.
Plugins installed:
https://imgur.com/a/cpUX4wE

**Comment by LoneDev6** [comment]
Hello, please install paper spigot or wait me to update the plugin to support spigot
https://papermc.io/downloads
