### ISSUE TITLE
[BUG] adding-content/advanced/sounds (shuffle system)

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#550]
Ciao, Matté, Tu hai detto questo:

![image](https://user-images.githubusercontent.com/20026629/101418536-67d02c00-38ee-11eb-9543-0a9c17f2d1be.png)

Io ho scritto cosi:

```
	},
	"ikson":{
		"sounds":[
			"music:music/ikson-lights",
			"music:music/ikson-togheter"
		]
	}

```

Ed il risultato è che viene riprodotta solamente la prima canzone.
La seconda non si sente mai.

**Comment by LoneDev6** [comment]
Mi sembra strano, Minecraft dovrebbe estrarne una in automatico.. non è qualcosa che gestisoc io ma il client.
Quindi quando esegui il suono "ikson" estrae uno dei suoni lì sotto che si trovano nei percorsi:
assets/music/sounds/music/ikson-lights
assets/music/sounds/music/ikson-togheter

**Comment by Fargus5** [comment]
Io posso assicurarti che ho provato a fare almeno 25 volte il comando /playsound e mi esce sempre solo la prima song.

![image](https://user-images.githubusercontent.com/20026629/101521343-06f43280-3986-11eb-9fca-2e1dddfa80c3.png)

**Comment by Fargus5** [comment]
@LoneDev6 Può essere che su Paper questo shuffle non esista? In caso scusami, non potresti renderlo tu randomico?

**Comment by LoneDev6** [comment]
Non è Paper a gestire i suoni ma il client che ne sceglie uno a caso nella lista, sinceramente non ne ho idea.

Per esempio questo funziona correttamente:
```yml
	"item.philosopher_stone.use":{
		"sounds":[
			"itemsadder:item/philosopher_stone/use1",
			"itemsadder:item/philosopher_stone/use2",
			"itemsadder:item/philosopher_stone/use3"
		]
	},
```

**Comment by Fargus5** [comment]
io se faccio /playsound itemsadder:item/philosopher_stone/use1 master Fargus
nemmeno funziona.... 

Quindi non so che dirti... se tu provassi a caricare due canzoni lo noteresti anche tu che non si sentono in maniera randomica.

Forse questa cosa del random è applicata solo e soltanto sull'item essendo la pietra un oggetto.
Ma per una musica non funziona.

**Comment by Fargus5** [comment]
Io sinceramente non vedo differenze nel tuo file e nel mio

![image](https://user-images.githubusercontent.com/20026629/102674012-d0dc5d00-4194-11eb-8c0f-b12f879a52bb.png)


![image](https://user-images.githubusercontent.com/20026629/102674044-dd60b580-4194-11eb-82e7-fb89c1c0e616.png)


Perché a te funziona e a me no?

**Comment by Fargus5** [comment]
Trovato l'errore.

Chiedo venia. Sono io che sono deficente in inglese
