### ISSUE TITLE
[BUG] Eat event can't be cancelled

### ISSUE THREAD

**Issue by YoutubeNosios** [LoneDev6/ItemsAdder#555]
**Describe the bug**
When I add a
`cancel: true`
In an eat event it doesn't cancel

**To Reproduce**
Add this item
`items:
  sweet_candy:
    display_name: "Sweet Candy"
    permission: adamantium.give
    resource:
      material: APPLE
      generate: true
      textures:
      - item/sweet_candy.png
    events:
      eat:
        cancel: true
        play_sound:
          name: itemsadder:ambient.angelic
          volume: 3
          pitch: 1
        decrement_usages:
          amount: 1`
And eat it

**Expected behavior**
Item shouldn't disappear when eaten

**Info (please complete the following information):**
 - Server version: spigot 1.16.4
 - Client version: 1.16.4
 - Plugin version: 2.1.22

**Comment by LoneDev6** [comment]
fixed in the new update, please let me know if it's working for you
