### ISSUE TITLE
(Maybe) Bugs with ores

### ISSUE THREAD

**Issue by ValouProjet** [LoneDev6/ItemsAdder#556]
I have 2 bugs (idk if we can call the second one a bug) for you today  :

**1]** When you create a mineral for a colored name and an enchant on it AND u set that you can get it throught an ore, when u'll receive from it, it will give you this mineral WITHOUT the enchantment AND WITHOUT the colored name.

Example : I create a ruby (that i name &cRubis with the enchantment protection I on it) and i create a ruby ore. I set that i can drop the ruby mining this ruby ore. But when the mineral drop the ruby, the ruby is no longer enchanted and it has NOT the name &cRubis but in white (&rRubis or &fRubis).

**2]** In the V1 of IA, there was an option to disable the silk touch (when u mine an ore). I looked into the new wiki and didn't find this option, so i went to the V1 wiki, tried the option "drop_on_silktouch: false" but it doesn't work. Did you remove this option ?

**3]** (it's a question)
Is there a way to disable the enchantment fortune on an ore ?
I don't want my players to get more than 1 mineral / ore.

**Comment by LoneDev6** [comment]
Please when you report: avoid removing the whole issue template and answer all the questions you see in the page.
Open an issue report for each of the bugs you find, thanks for the patience.
