### ISSUE TITLE
[BUG] Huge error message when using Java SE JDK 15

### ISSUE THREAD

**Issue by imparium-de** [LoneDev6/ItemsAdder#557]
**Describe the bug**
Players getting kicked when trying to join and a huge error message appears in the console.

**To Reproduce**
1. Download and install the Java SE Development Kit 15 from https://www.oracle.com/de/java/technologies/javase-jdk15-downloads.html
2. Start the server
3. Try to join the server

**Expected behavior**
No error and kick

**Info (please complete the following information):**
 - Server version: Paper 1.16.4
 - Client version: Optifine 1.16.4
 - Plugin version: 2.1.22b

**Additional context**
We're trying to use newer versions than Java 8, because after the release of MC 1.17, things like Paper Spigot and QuickShop Reremake will drop support for legacy Java versions.

**Comment by LoneDev6** [comment]
Maybe send me the error?
Thanks

**Comment by imparium-de** [comment]
Oh sorry. Seems like I was too tired yesterday...
https://pastebin.com/NH2xubTk

**Comment by LoneDev6** [comment]
Thanks a lot.
Is this problem happening only in Java8+?
Are you using the very latest protocollib? https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

Thanks!

**Comment by LoneDev6** [comment]
I checked more in detail ad the problem is here: https://helpch.at/docs/1.15/org/bukkit/entity/Player.html#setPlayerListName-java.lang.String-

I suspect it's a Paper bug as this error said basically that the function failed to be called, which is not normal.
Please try the plugin on normal Spigot and/or update Paper and let me know, thanks.

**Comment by imparium-de** [comment]
Sorry for the late reply. It was actually related to ProtocolLib. We just updated it to the newest build (Build #487) and it doesn't happen anymore. Oh and with the old ProtocolLib version, it was still happening on the most recent Spigot and Paper version.

Thanks for your help! As always much appreciated ^^
