### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by trizoney** [LoneDev6/ItemsAdder#559]
Added the
ia.user.ia permission to my server and my players who did /ia only saw a redstone block when they did it.  When I opped myself I could see the items though. When I deopped myself it was the same for me.

**Comment by LoneDev6** [comment]
Please avoid erasing the issue template.. I cannot help you without the info requested in the template.
Refer to the other issues pages to see how it works.

Anyway I don't understand what you mean. be sure to give the appropriate permissions to your users.
https://itemsadder.plugin.ga/plugin-usage/permissions

ia.user.ia
ia.user.ia.*
ia.user.craft.*
