### ISSUE TITLE
Conflicting resource packs: Itemsadder and QualityArmory

### ISSUE THREAD

**Issue by salemthewolf** [LoneDev6/ItemsAdder#56]
I've been on a server that used both of these addons and the items never had problems rendering. I'm getting an issue where only 1 resource pack is able to be active at once. If Itemsadder is active, the QualityArmory weapons will be error blocks. If QA is active, then Itemsadder will be feathers. Is there a way to either merge the resource packs together or to allow both to activate simultaneously?

**Comment by LoneDev6** [comment]
I have no experience with quality armor so I can't really help you in detail.
But as far as you copy everything from itemsadder resourcepack and paste it into quality armor should work fine.
Let me know

**Comment by JaHollYT** [comment]
So i got the same Problem with the Magic Plugin from NathanWolf on Spigot.
Itemadder and the Plugin have a .json file in the models-->item Folder for gold Tools and i don't know how to combine these, cause in both files there is a lot of stuff writen in.

**Comment by LoneDev6** [comment]
Send here a screenshot of some of the contents of Magic Plugin gold tool file

**Comment by JaHollYT** [comment]
![Magicplugin_gold_axejson](https://user-images.githubusercontent.com/48917504/66830697-61e2f300-ef56-11e9-9c5d-a2ca92fa58a5.PNG)

Here are the complet Gold-Tool-Jsons:

[MagicPlugin-GoldTools.zip](https://github.com/LoneDev6/ItemsAdder/files/3729155/MagicPlugin-GoldTools.zip)

**Comment by LoneDev6** [comment]
For example you have to:
- rename magic plugin golden_axe.json file to magic_golden_axe.json, paste it in "item" folder of my resourcepack
- copy and paste Magic plugin textures from Magic resourcepack to mine (in this case textures are staff_wolf, staff_wolf_top, staff_wolf_bottom)
- open my golden_axe.json file and add this line at the start of "overrides":
{"predicate": {"custom_model_data":0}, "model": "item/magic_golden_axe"},

- reload resourcepack and see


I tested it and it's working file that way, let me know :D

**Comment by JaHollYT** [comment]
Thank you so so so much!!
Works perfect!

**Comment by Zand-MC** [comment]
@salemthewolf Did you manage to get it working (itemsadder + Qa) Can u send me your files if you have I'm Having the same problem

**Comment by LoneDev6** [comment]
This method worked on v1.0, v2.0 is different.
Closing the issue.
Refer to these: 
https://github.com/LoneDev6/ItemsAdder/issues/150
https://github.com/LoneDev6/ItemsAdder/issues/154
