### ISSUE TITLE
[BUG] Hud/ Titles Issue

### ISSUE THREAD

**Issue by SirCraftypants** [LoneDev6/ItemsAdder#567]
**Describe the bug**
Because of my stupid Host, they completely gzipped every single file on my Server and then claimed they couldn't restore my server because they no longer take backups every 12 hours so i had to completely start all over again as my last backup was on a previous minecraft version.

So fresh install on my Server, installed the 2.1.23 version of IA and installed LoneLibs 1.0.7.

The Thirst bar is enabled, Mana bar disabled but this is how it looks. Huds is enables true in Config.

![2020-12-23](https://user-images.githubusercontent.com/66942713/103014117-223e7080-4536-11eb-8656-15f40392ede0.png)

    Server version: Paper 1.16.4
    Client version: Mojang 1.16.4
    Plugin version: 2.1.23

**Comment by SirCraftypants** [comment]
![Uploading 2020-12-23 (1).png…]()

**Comment by SirCraftypants** [comment]
Lonelibs has failed to install, i'm attempting to install it again.

**Comment by SirCraftypants** [comment]
Confirmed LoneLibs 1.0.7 is not generating it's Folder when i do a clean install.

**Comment by SirCraftypants** [comment]
Did a complete fresh install with 2.1.22b IA and 1.0.6 Lonelibs and it's still exactly the same.

**Comment by SirCraftypants** [comment]
This is from a fresh install with unicode off

**Comment by 100petr** [comment]
use /iatexture
if you see bugged numbers

**Comment by SirCraftypants** [comment]
Thanks yeah i've just noticed you've made changes to the resource pack and i have a custom resource pack, not just itemsadders resource pack.

I will endeavor to find the changes and match accordingly.

**Comment by SirCraftypants** [comment]
You need to update your font/default file in your resource pack with the same file from Itemsadders pack.zip

**Comment by LoneDev6** [comment]
> 
> 
> **Describe the bug**
> Because of my stupid Host, they completely gzipped every single file on my Server and then claimed they couldn't restore my server because they no longer take backups every 12 hours so i had to completely start all over again as my last backup was on a previous minecraft version.
> 
> So fresh install on my Server, installed the 2.1.23 version of IA and installed LoneLibs 1.0.7.
> 
> The Thirst bar is enabled, Mana bar disabled but this is how it looks. Huds is enables true in Config.
> 
> ![2020-12-23](https://user-images.githubusercontent.com/66942713/103014117-223e7080-4536-11eb-8656-15f40392ede0.png)
> 
> ```
> Server version: Paper 1.16.4
> Client version: Mojang 1.16.4
> Plugin version: 2.1.23
> ```

did you solve your issue?
anyway may I advice you a better hosting? This is the hosting I use and I've never had any problem: https://bit.ly/2MOtOR5

**Comment by SirCraftypants** [comment]
Hi, it was because when i updated from 1.15. to 1.16, there were changes
you made in the resource pack, i eventually located the changes and updated
my resource pack as i run my own. Thanks, you can close.

**Comment by LoneDev6** [comment]
ohh very nice, happy you fixed
