### ISSUE TITLE
[BUG] campfire drop

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#568]
**Describe the bug**
After destroying the campfire in survival mode, the items don't drop

**To Reproduce**
1. Go to survival
2. Place campfire
3. Place items on it
4. Destroy campfire (in survival)
5. no drop

**Expected behavior**
When destroying a campfire in the survival, the items drop.

**Screenshots**
Video: https://youtu.be/Uefc23OuBk8

**Info (please complete the following information):**
 - Server version:  paper 1.16.4 build 343
 - Client version: optifine 1.16.4
 - Plugin version: 2.1.23 

**Additional context**
I noticed that there is something about it in the config, but I think I have everything right. https://pastebin.com/DEJr5pAA

**Comment by SirCraftypants** [comment]
In the Config there is a setting to prevent a Campfire from being lit when placed to create a more realistic affect but, Itemsadder wouldn't be the cause of Campfires not dropping their items, another Plugin is likely causing it.

**Comment by 100petr** [comment]
which plugin?
![Uploading image.png…]()

**Comment by SirCraftypants** [comment]
i don't think this has anything to do with it but just below the campfire unlit when placed setting in the config, set     allow-any-item: true

**Comment by 100petr** [comment]
Look at my configuration, I have it set up that way.
![image](https://user-images.githubusercontent.com/29830635/103087413-af8dcd80-45e7-11eb-933a-19cd9bcad884.png)

**Comment by SirCraftypants** [comment]
try removing FakaHedaMineenquey, restart server and see if that fixes it

**Comment by 100petr** [comment]
No, this is a hosting plugin for monitoring.

**Comment by SirCraftypants** [comment]
hold on a minute

**Comment by SirCraftypants** [comment]
are you talking about the vanilla campfire or the IA campfire

**Comment by 100petr** [comment]
vanilla

**Comment by SirCraftypants** [comment]
I can be 100% certain that IA wouldn't prevent a vanilla block from dropping its items, nor would any of your other current plugins. Go to Minecraft's Discord, maybe they can help you.

**Comment by 100petr** [comment]
I will switch the client to 1.16.3 and go try it directly on the test server.

**Comment by SirCraftypants** [comment]
I'm on Paper Spigot 1.16.4 with all the last 5 versions of IA and Lonelibs, i can confirm that the Campfire has always and continues to drop it's items, it's definitely something else.

**Comment by 100petr** [comment]
I'm on Paper Spigot 1.16.4 with all the last 5 versions of IA and Lonelibs, i can confirm that the Campfire has always and continues to drop it's items, it's definitely something else.

**Comment by 100petr** [comment]
um, it works on the test server. so i will try to restart config.

**Comment by 100petr** [comment]
After restarting the config, the drop works. I'm going to look for differences.

**Comment by 100petr** [comment]
There are a lot of differences, I'll start with a new config. Thank you for your time
