### ISSUE TITLE
[BUG] Resource pack downloaded twice

### ISSUE THREAD

**Issue by azukaar** [LoneDev6/ItemsAdder#569]
**Describe the bug**

**To Reproduce**
1. Go to Server

**Expected behavior**
I would expect the download to happen once

**Screenshots**

**Info (please complete the following information):**
 - Paper 1.16.4
 - Vanilla
 - IA v2.1.23

**Additional context**

I am using a resource pack with this config :

resource-pack:
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: false
  delay-ticks: 1
  title:
    enabled: true
  self-host:
    enabled: false
    server-ip: 127.0.0.1
    pack-port: 8163
  external-host:
    enabled: true
    url: http://XXX-IP-XXXX/pack2.zip

**Comment by LoneDev6** [comment]
Thanks, I have to find the reason why this happens only on external-host, not when using self-host.
Sorry for the inconvenience

**Comment by LoneDev6** [comment]
Does this happens to every user? Did you try to reupload the pack on dropbox with another name and change url in config.yml?
I tried and I cannot manage to make this happen on Itemsadder v2.1.23, I can't find the reason why this happens on your server

**Comment by azukaar** [comment]
It is uploaded on a server and downloaded via IP
I think I have fixed it, the resource pack was downloaded twice only when there was an error in the /iazip command (missing chisel)
But since I have fixed this error the double download doesn't happen anymore
By the way a bit of  a sidetrack: I seem unable to use https:// rather than http:// for the URL of the pack is that just me ?

**Comment by LoneDev6** [comment]
mmhhh well Minecraft is strange sometimes, if I recall it sometimes rejects HTTPS certificates when downloading the resourcepacks, there is nothing I can really do about that without modding the game.
Anyway HTTPS is not needed as it's not sensitive data, if possible use http
