### ISSUE TITLE
[BUG] Usages are broken, Can't create single use items for tokens / vouchers

### ISSUE THREAD

**Issue by azukaar** [LoneDev6/ItemsAdder#572]
**Describe the bug**
Essentially you can't create single use items...
If you set the number of usage on an object to 0, it will let you use it once, that is a problem because it's obviously supposed to be out of usages, the idea is that if you do that, let say I have 3 single use items stacked, it will check the number of usage left, and remove all 3 of them.
If I set it to 1, people can actually use it twice

**Expected behavior**
0 should not work, 1 should be single usage

**Comment by LoneDev6** [comment]
Thanks for the report, this was fixed in the new update. Let me know if it works for you
