### ISSUE TITLE
[BUG] Luminous objects go dark when user w/o building perms hits them

### ISSUE THREAD

**Issue by imparium-de** [LoneDev6/ItemsAdder#574]
**Describe the bug**
When a player hits a luminous object in an area where he doesn't have building permissions (i.e. Spawn), it goes dark and you have to break and place it again

**To Reproduce**
1. Place a luminous object like the Christmas tree
2. Ask someone without permissions to hit it
3. See that it goes dark

**Expected behavior**
The lamps should not go dark when a user without permissions hits them

**Screenshots**
https://streamable.com/ej583z

**Info (please complete the following information):**
 - Server version: Paper 1.16.4
 - Client version: 1.16.4 with OptiFine HD_U_G5
 - Plugin version: 2.1.23

**Additional context**

**Comment by LoneDev6** [comment]
Thanks for the report, this was fixed in the new update. Let me know if it works for you

**Comment by imparium-de** [comment]
It's fixed, thanks!
