### ISSUE TITLE
[BUG] Items lost textures, when player open inventory.

### ISSUE THREAD

**Issue by ProXEQ** [LoneDev6/ItemsAdder#577]
When player opens inventory, items lost textures. I've noticed that NBT tags are getting removed.

This bug occurs only on gm. Creative. Console not shows any errors.

**Comment by LoneDev6** [comment]
Please don't erase the issue template, I need all the info required to fix your issue.
Anyway this doesn't happen on Spigot/Paper 1.16.4, seems to be something about another plugin interfering or an unofficial Spigot fork.
