### ISSUE TITLE
[BUG] Grenade Item issue.

### ISSUE THREAD

**Issue by kamyu1537** [LoneDev6/ItemsAdder#578]
**Describe the bug**
I use egg or show ball when I equip grenades to sub hand, it works like same with grenades.

**To Reproduce**
1. Equip grenade to sub hand.
2. Equip egg to main hand.
3. And then Throw
4. Bomb

**Expected behavior**
It shouldn't explode.

**Screenshots**
none

**Info (please complete the following information):**
 - Server version: Tuinity 1.16.4
 - Client version: Optifine 1.16.4
 - Plugin version: 2.1.23

**Additional context**
nothing

**Comment by LoneDev6** [comment]
Thanks for the report, this was fixed in the new update. Let me know if it works for you
