### ISSUE TITLE
[BUG] Fuel bossbar can not show again after player rejoin

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#581]
**Describe the bug**
Fuel bossbar can only shows when player first join server after server restart.

**To Reproduce**
1. Join server
2. Right click vehicle and see fuel bossbar
3. Leave server, then rejoin server
4. Right click vehicle and no fuel bossbar shows

**Info (please complete the following information):**
 - Server version: tuinity 1.16.4
 - Client version: vanllia 1.16.4
 - Plugin version: 2.1.23

**Additional context**
This will happen when every player every rejoin.

**Comment by LoneDev6** [comment]
Thanks for the report, this was fixed in the new update. Let me know if it works for you
