### ISSUE TITLE
[BUG] Wailat NPE while reloading ItemsAdder

### ISSUE THREAD

**Issue by QuentiumYT** [LoneDev6/ItemsAdder#583]
**Describe the bug**
While doing `/iareload` and facing a custom block, a NPE error occurs, if you're facing a vanilla block, everything's fine

**To Reproduce**
1. Face a ItemsAdder TILE (or REAL) block
2. Open chat and run `/iareload`
3. Look at the console and see the NPE error

**Expected behavior**
No error should be written in the console :stuck_out_tongue: 

**Screenshots**
![moX-](https://user-images.githubusercontent.com/35229942/104217441-b025c100-543b-11eb-95f0-7a753fe89da1.png)

**Info (please complete the following information):**
 - Server version: Paper 1.16.4 build 390
 - Client version: Optifine 1.16.4
 - Plugin version: ItemsAdder 2.1.23 / Wailat 1.0.4

**Additional context**
None

**Comment by LoneDev6** [comment]
Thanks for the report, this was fixed in the new update. Let me know if it works for you.
You will have to update Wailat and ItemsAdder to the latest version.
