### ISSUE TITLE
[BUG] Custom Boss Bar is causing errors and not removing Boss Bars on v2.1.24

### ISSUE THREAD

**Issue by IshKaigen** [LoneDev6/ItemsAdder#586]
Im on Purpurclip Build #951 version 1.16.4 as my server jar. Boss Bar refuses to remove itself after killing a custom mob.

Error:
https://pastebin.com/DWZX9N5X
This is constantly spammed in my console.
**Yes im using the latest ItemsAdder Build from Spigot**

**Comment by LoneDev6** [comment]
thanks, I will fix it today
