### ISSUE TITLE
its possible change fire colors?

### ISSUE THREAD

**Issue by danielzinh** [LoneDev6/ItemsAdder#588]
I'm running a server at 1.16.4 and saw that mojang recently added a new type of fire:

![image](https://user-images.githubusercontent.com/50877639/104645513-e5c1e880-568d-11eb-8854-96b7c4b540d5.png)

its possible change his color? if yes, how? thanks :)

**Comment by LoneDev6** [comment]
Would be very cool but sadly Minecraft didn't add a "color" attribute to the fire, they just added a new fire texture, so we cannot change fire color for now
