### ISSUE TITLE
emoji not passing on chat control

### ISSUE THREAD

**Issue by dryter97** [LoneDev6/ItemsAdder#59]
like the title say its prety much it. i can cast a nick name using emoji with cmi through chat control. because im using cmi placeholder. maybe you could suggest something i know its more chatcontrol thing. im just advising you about this chatcontrol messy stuff

**Comment by LoneDev6** [comment]
you can use **/e smile** and press **tab** to autocomplete. After this you get smile emoji, copy and paste it into your nickname

**Comment by dryter97** [comment]
nvm working fine now it was issus on chat control listener. but nice to
know about this one we can already do /nick :zebra:dryter97 per exemple to
get a pretty nice zebra emoji with the name. after you just need to be sure
to give correct acces to the player with the /nick acces on the plugins.
cmi is doing great so far about it!

**Comment by LoneDev6** [comment]
Good to know you managed to find a solution :D
