### ISSUE TITLE
[BUG] ItemsAdder fails to load, spams errors in Console in v2.1.26

### ISSUE THREAD

**Issue by IshKaigen** [LoneDev6/ItemsAdder#590]
ItemsAdder v2.1.26 now refuses to load and spams this error in my server console:
https://pastebin.com/q56hJ4c4
The plugin attempts to load but never does so with that error constantly spamming the console.
I used Both Purpur Build #956 and Yatopia Build #40, same error on both server jars.

**Comment by LoneDev6** [comment]
Please provide the full server log.
Seems another plugin is using an old version of org.apache.commons.io.FileUtils which is interfering with LoneLibs.

You should identify which plugin is the problem searching for something similar to
`Loaded class org.apache.commons.io.FileUtils from XXXX which is not a depend, softdepend or loadbefore of this plugin.`.

Then remove the plugin or ask the plugin author to update apache FileUtils
