### ISSUE TITLE
[Suggestion] Hope can remove totem effect

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#592]
**Is your feature request related to a problem? Please describe.**
On use /iaplaytotemanimation ,it will run out totem effect.
Hope can remove it.

**Describe the solution you'd like**
cancel that effect

**Describe alternatives you've considered**
none

**Additional context**
![image](https://user-images.githubusercontent.com/50344708/104834661-e0f27400-58db-11eb-8152-8a621e0d142d.png)

**Comment by LoneDev6** [comment]
Hello!
Sadly it's clientside and I cannot remove it, maybe you can prove me wrong but I doubt there's any way to remove this particle
