### ISSUE TITLE
[BUG] 1.16.5 error

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#594]
**Describe the bug**
After upgrading to 1.16.5, I see error in the console. https://pastebin.com/8DA19zVH

**To Reproduce**
1. Upgrade server to 1.16.5
2. See console

**Expected behavior**
There will be no error in the console

**Info (please complete the following information):**
 - Server version: Paper version git-Paper-428 (MC: 1.16.5)
 - Plugin version: 2.1.26

**Comment by Xwdit** [comment]
Same error

**Comment by LoneDev6** [comment]
Fixed in the next update
