### ISSUE TITLE
Cant see crafting Recipies

### ISSUE THREAD

**Issue by JaHollYT** [LoneDev6/ItemsAdder#60]
Hey, every time i try to see a recipe in the GUI by clicking on it, the console gives an error:

15.10 09:15:20 [Server] ERROR Could not pass event InventoryClickEvent to ItemsAdder v1.1.36
15.10 09:15:20 [Server] INFO java.lang.IllegalArgumentException: Name cannot be null
15.10 09:15:20 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at org.bukkit.Material.matchMaterial(Material.java:4275) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at org.bukkit.Material.matchMaterial(Material.java:4259) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at dev.lone.itemsadder.c.a.a(Unknown Source) ~[?:?]
15.10 09:15:20 [Server] INFO at dev.lone.itemsadder.c.a.a(Unknown Source) ~[?:?]
15.10 09:15:20 [Server] INFO at dev.lone.itemsadder.c.a.b(Unknown Source) ~[?:?]
15.10 09:15:20 [Server] INFO at dev.lone.itemsadder.f.h.a(Unknown Source) ~[?:?]
15.10 09:15:20 [Server] INFO at dev.lone.itemsadder.f.c.a(Unknown Source) ~[?:?]
15.10 09:15:20 [Server] INFO at dev.lone.itemsadder.f.b.a(Unknown Source) ~[?:?]
15.10 09:15:20 [Server] INFO at com.b.a.a.c.j.a(Unknown Source) ~[?:?]
15.10 09:15:20 [Server] INFO at com.b.a.a.c.f.a(Unknown Source) ~[?:?]
15.10 09:15:20 [Server] INFO at com.b.a.a.a.b(Unknown Source) ~[?:?]
15.10 09:15:20 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1127.execute(Unknown Source) ~[?:?]
15.10 09:15:20 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:20 [Server] INFO CONSOLE issued server command: /list 
15.10 09:15:21 [Multicraft] Skipped 139 lines due to rate limit (30/s)
15.10 09:15:21 [Server] ERROR Could not pass event InventoryClickEvent to ItemsAdder v1.1.36
15.10 09:15:21 [Server] INFO java.lang.IllegalArgumentException: Name cannot be null
15.10 09:15:21 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at org.bukkit.Material.matchMaterial(Material.java:4275) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at org.bukkit.Material.matchMaterial(Material.java:4259) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at dev.lone.itemsadder.c.a.a(Unknown Source) ~[?:?]
15.10 09:15:21 [Server] INFO at dev.lone.itemsadder.c.a.a(Unknown Source) ~[?:?]
15.10 09:15:21 [Server] INFO at dev.lone.itemsadder.c.a.b(Unknown Source) ~[?:?]
15.10 09:15:21 [Server] INFO at dev.lone.itemsadder.f.h.a(Unknown Source) ~[?:?]
15.10 09:15:21 [Server] INFO at dev.lone.itemsadder.f.c.a(Unknown Source) ~[?:?]
15.10 09:15:21 [Server] INFO at dev.lone.itemsadder.f.b.a(Unknown Source) ~[?:?]
15.10 09:15:21 [Server] INFO at com.b.a.a.c.j.a(Unknown Source) ~[?:?]
15.10 09:15:21 [Server] INFO at com.b.a.a.c.f.a(Unknown Source) ~[?:?]
15.10 09:15:21 [Server] INFO at com.b.a.a.a.b(Unknown Source) ~[?:?]
15.10 09:15:21 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1127.execute(Unknown Source) ~[?:?]
15.10 09:15:21 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2310) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-210]
15.10 09:15:21 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-210]

I am Using the newest Itemadder version and the latest version of PaperMC 1.14.4.
The Recipie Command also gives an internal server error.

**Comment by LoneDev6** [comment]
https://www.mc-market.org/resources/10839/update?update=35035

https://www.mc-market.org/resources/10839/update?update=34973

![image](https://user-images.githubusercontent.com/27242001/66827016-1d535980-ef4e-11e9-8419-a8ae00d83661.png)


![image](https://user-images.githubusercontent.com/27242001/66827020-20e6e080-ef4e-11e9-87a0-2f5778c7587d.png)

**Comment by JaHollYT** [comment]
[menu.zip](https://github.com/LoneDev6/ItemsAdder/files/3729128/menu.zip)

Sorry, i can't find my mistake, i added the things. Maybe you see it

**Comment by LoneDev6** [comment]
You have to copy and paste text i posted here under warning title:

https://www.mc-market.org/resources/10839/update?update=35035
https://www.mc-market.org/resources/10839/update?update=34973

paste texts under this:
![immagine](https://user-images.githubusercontent.com/27242001/67032510-08c0be00-f114-11e9-9a41-c146a2466ce7.png)
