### ISSUE TITLE
Plugin Randomly Disabled

### ISSUE THREAD

**Issue by TheMGRF** [LoneDev6/ItemsAdder#61]
Just updated to the latest build on MCMarket (1.1.36b) and after about 3 minutes ItemsAdder disabled itself with this stack trace.
![image](https://user-images.githubusercontent.com/16401884/66859066-76d57b80-ef82-11e9-87c4-7accf9442ea9.png)

**Comment by LoneDev6** [comment]
Can you tell me if that happens again? Seems solved

**Comment by TheMGRF** [comment]
Yup appears to be resolved now thanks!
