### ISSUE TITLE
Issue while trying to break IA Armorstand Blocks..

### ISSUE THREAD

**Issue by SushiBarIV** [LoneDev6/ItemsAdder#64]
Hello,

I were just trying to break entity blocks like the Halloween Pumpkin,
But wasn't working out, it just appears an error in my Console: https://hastebin.com/ahubigesum.bash

Plugins:  https://hastebin.com/usepaqahun.md

**Comment by LoneDev6** [comment]
Did you try restarting your server?
I think this is a ProtocolLib bug and I hope they'll fix it.

Let me know if restarting fixes the issue. Thanks

**Comment by SushiBarIV** [comment]
It don't fix my issue, tried that already multiple times :o
I'm going to try an different version of ProtocolLib and tell you if it worked or not.

**Comment by LoneDev6** [comment]
this one? http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastStableBuild/

**Comment by SushiBarIV** [comment]
Yes, that worked. 
Thank you LoneDev :)

**Comment by SushiBarIV** [comment]
I left an review for ItemsAdder on Mc-market ;)

**Comment by LoneDev6** [comment]
Oh now I see who you are :D thanks!
