### ISSUE TITLE
BLAZE_POWDER not detected as an item

### ISSUE THREAD

**Issue by Sylvenight** [LoneDev6/ItemsAdder#65]
I've tried to use blaze powder in a crafting recipe and as ammo and it hasn't worked. It just detected it as nothing. Extremely vague but that's all I know.

**Comment by Sylvenight** [comment]
BLAZE_ROD doesn't appear to work either.

**Comment by LoneDev6** [comment]
plugin version?
server version?
can you share your .yml file?

**Comment by LoneDev6** [comment]
Hello?

**Comment by Sylvenight** [comment]
Yes, sorry. No vanilla items are working as ammo.
Plugin version: 1.1.38
Server version: Paper 223
The issue is at the ember_celica gun. I changed the ammo to ruby for the time being.
[guns.zip](https://github.com/LoneDev6/ItemsAdder/files/3775904/guns.zip)

**Comment by LoneDev6** [comment]
Should be fixed in IA 2.0+
