### ISSUE TITLE
Packet Stuff (again)

### ISSUE THREAD

**Issue by Padlick01** [LoneDev6/ItemsAdder#67]
Hey, got this error spam today in console:
https://pastebin.com/rdjurMM0

Unfortunately I don't know how to trigger this error.

Waterfall #296
Paper #221

IA ver 1.1.38

**Comment by LoneDev6** [comment]
Latest protocollib? http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

**Comment by Padlick01** [comment]
Had an dev version. Installed the latest stable build.
But I can't say if it's fixed or not, 'cause it's an rare error spam :/

**Comment by Padlick01** [comment]
Seems to be fixed.

**Comment by LoneDev6** [comment]
Did you fix updating or?

**Comment by Padlick01** [comment]
Yes
