### ISSUE TITLE
[SUGGESTION] API: get Drops of an custom block

### ISSUE THREAD

**Issue by Padlick01** [LoneDev6/ItemsAdder#69]
When you have an item, for example aqua aura, that drops from Aqua Aura ore, and you break an ore, there should be a method to get drops from that.

like
ItemsAdder.getCustomDrops(ItemnameInConfig string)

In my example above something like
>ItemsAdder.getCustomDrops("aqua_aura_ore")
Should return an ItemStack or string from NameInConfig

**Comment by LoneDev6** [comment]
Interesting idea, I'll definitely add this in next updates, thanks a lot!

**Comment by Padlick01** [comment]
Or other thing;

ItemsAdder.getCustomDrops("aqua_aura_ore")

should return every item that could be dropped (ignoring chance)
For chance, you could to

ItemsAdder.getCustomBlockDropChance(NameInConfig string, NameInConfig string)

First string is the block and second the item where you want to have the chance. It should return something like 0.1 (for a chance of 10%) and so on. If you insert in string 2 an item, that can't be dropped from that block, it could return NULL or 0 (for 0%)

**Comment by LoneDev6** [comment]
Added some updates ago:
getCustomBlockLoot(lock, tool, includeSelfBlock)
