### ISSUE TITLE
Unrecognized recipe on startup

### ISSUE THREAD

**Issue by BillyGalbreath** [LoneDev6/ItemsAdder#7]
Spoke to you about this in Discord, but moving to a GH ticket for completeness.

Sometimes when players join the console will give errors about unrecognized recipes. It is random which recipe it says, and random on which players this happens to.

This does not seem to effect anything in game, the recipe still work like expected, even for the player these triggered for.

![image](https://user-images.githubusercontent.com/332527/60617454-69143580-9d99-11e9-9aa8-c461c48ff695.png)

**Comment by LoneDev6** [comment]
I don't know if it's fixable. I have to find a way to unregister my custom recipes from the game because now I'm using an hacky way to handle recipes reload. Do you know if there's a way to unregister a specific recipe by namespacekey?

**Comment by ShaneBeee** [comment]
From my understanding, this is more of a client -> server issue.
Here is what happens:

Lets say I join your server (before installing this plugin)... the server sends me all the available recipes.
Then you install this plugin on your server, which the plugin removes a recipe (lets say the campfire recipe, just for this story)
Next time I join the server, the client checks in with the server, and that recipe is removed, so the client gets a little confused, which throws that error in the console of the server.

From my understanding there is no way around this. Basically any plugin that is removing a recipe from the server that the client has previously loaded before, will throw this error, ONE TIME when the player joins. 
Even though it's marked as an error, it's not a big deal, and can be ignored.

**Comment by LoneDev6** [comment]
I fixed that using https://www.spigotmc.org/resources/console-spam-fix.18410/
Maybe I'll implement an internal fix in ItemsAdder to do that message removal without external plugin

**Comment by LoneDev6** [comment]
Should be fixed in latest version of plugin that will be published on McMarket, I'll upload as soon as possible.
https://www.mc-market.org/resources/10839/
