### ISSUE TITLE
cant activate after reinstall

### ISSUE THREAD

**Issue by salemthewolf** [LoneDev6/ItemsAdder#70]
I edited the license.yml like before with my email and transaction date, but I cant get it to activate.
<img width="327" alt="javaw_SFfCx5Ako3" src="https://user-images.githubusercontent.com/21348439/67707026-1f76d880-f990-11e9-89a8-00a7fc3d97a8.png">

**Comment by Padlick01** [comment]
Can confirm. That only happens, when you do a clean install without licence, insert licence data and restart it with PlugMan. Only server restart fixes it.

**Comment by salemthewolf** [comment]
not quite. I uninstalled, restarted. Reinstalled, restarted. Edited license.yml, restarted. Tried to use plugman to enable it, got the same prompt again.

**Comment by LoneDev6** [comment]
Please contact me via PM on forum where you bought plugin since it's a payment related issue.
Thanks
