### ISSUE TITLE
[Suggestion] API Additions

### ISSUE THREAD

**Issue by TheMGRF** [LoneDev6/ItemsAdder#71]
> As mentioned in Discord.

Custom events would be heavily beneficial to have (like CustomBlockPlace/Break).

Custom objects like `CustomItem` to be returned from things like `#getCustomItem` that allows getting of the Bukkit ItemStack but contains useful information immediately like getting the custom model data, name, permission etc.

**Comment by LoneDev6** [comment]
https://github.com/LoneDev6/ItemsAdder/issues/282
https://github.com/LoneDev6/ItemsAdder/issues/274
