### ISSUE TITLE
Cannot retrieve entity from ID onPacketReceiving

### ISSUE THREAD

**Issue by TheMGRF** [LoneDev6/ItemsAdder#72]
Had a couple issues pop in the console earlier today related to the PacketEvent. Had something like this before ages ago but it was fixed.

https://pastebin.com/MmpxzN1A

**Comment by LoneDev6** [comment]
I think this is a ProtocolLib bug.
Did you update to latest version of protocollib for 1.14?

**Comment by TheMGRF** [comment]
Fixed by updating to the latest build of ProtocolLib.

**Comment by TheMGRF** [comment]
Issue is still persisting. Nothing really changed and tried updating ProtocolLib again. Console still getting spammed with errors.

**Comment by LoneDev6** [comment]
I think it's a ProtocolLib bug as that's what I do. Doesn't make sense that sometimes works and sometimes not:
![immagine](https://user-images.githubusercontent.com/27242001/68377944-8d1ec380-014b-11ea-8c6b-8feaea8b395c.png)

**Comment by LoneDev6** [comment]
I found this, maybe it's related, what you think? https://github.com/filoghost/HolographicDisplays/issues/135

**Comment by TheMGRF** [comment]
Tried updating both HolographicDisplays, Citizens and ProtocolLib again error is still being produced. Thanks for the reference to the other issue but the error is still persisting and directly referencing ItemsAdder.

**Comment by LoneDev6** [comment]
I've done more tests but I can't find the source of this problem.. I think it's a ProtocolLib bug.
Also I don't receive this error on my server and I have Citizens, HolographicDisplays and ProtocolLib.

I have no clue.

Does it still show up on your server?

**Comment by TheMGRF** [comment]
Was working fine for a while but its now erroring again 🤦‍♂

**Comment by LoneDev6** [comment]
Are you reloading plugin at runtime? Anything strange?

**Comment by TheMGRF** [comment]
Nope don't use /reload or reloaders. Error seams to have disappeared again... No changes made. Very bizarre.

**Comment by LoneDev6** [comment]
I do think it's a ProtocolLib bug, as I'm not making strange checks or something. Just using ProtocoLib method to get entity id
