### ISSUE TITLE
Items vanishing when put in elytra slot

### ISSUE THREAD

**Issue by ArathiaMC** [LoneDev6/ItemsAdder#73]
Hello,

Most (or all) items in the ItemsAdder plugin vanishes/disappears when you put them in the Elytra slot in your inventory. This is a major issue since players will accidentally put their items in that slot (especially items such as the wearable wings), and therefore they will lose the item permanently.

Hope this can be solved quickly.
Thanks.

**Comment by LoneDev6** [comment]
Does this still happens on latest version?
I've done some tests without success, can't get the issue.
Maybe it's another plugin?

**Comment by LoneDev6** [comment]
Hello, any news? I can't reproduce that problem
