### ISSUE TITLE
[Dupe Bug & Suggested Solution] Dupe Bug for Dropping Items From Blocks

### ISSUE THREAD

**Issue by pinkpig3777** [LoneDev6/ItemsAdder#75]
The default setup has a chance for crystals to drop when breaking nether quartz ore. This allows players to farm it using silk touch to silk the nether ore, then mine it to drop crystals, and repeat. The wiki does offer a feature for this:
drop_on_silktouch: false
However, it appears to only support the block settings and not the item settings. In other words, it'll prevent users from silk touching the nether quartz ore block which makes it impossible to obtain nether quartz ore as a block which we don't want. We want crystals to not drop when the block is silk touched.

In other words, could you add support for:
"drop_on_silktouch: false"
for the mineral section like so:
https://hastebin.com/bowecagusu.bash

**Comment by LoneDev6** [comment]
Please add cancel_on_silktouch instead of drop_on_silktouch.
set cancel_on_silktouch: true

Let me know

**Comment by LoneDev6** [comment]
@pinkpig3777 still occurs?

**Comment by pinkpig3777** [comment]
> @pinkpig3777 still occurs?
Not sure, I don't own a server anymore sorry.
