### ISSUE TITLE
Problem with ctm optifine textures in >160 blocks

### ISSUE THREAD

**Issue by iAgus23** [LoneDev6/ItemsAdder#76]
I have a problem, i exceeded 160 blocks and i had problems with the 45° rotation, then i saw that going out and entering the server again was solved. But then i saw a bigger problem, is that in blocks >160 the optifine ctm textures do not apply, in any case. I have 179 blocks, so there are 19 that are practically without texture because it only loads the default but not the ctm. Can this be fixed? Greetings

https://i.imgur.com/hASgkDT.png
https://i.imgur.com/fXBrlG0.png

**Comment by LoneDev6** [comment]
Hello!
Sorry I didn't find any fix, It's a client bug I hope Mojang will fix in 1.15.
Please use ids before 160. I'm trying to add more blocks to reach id 200 but it's not easy.

Also about CTM: If you refer to this problem I can't fix it, it's a Optifine bug: https://github.com/sp614x/optifine/issues/2268

**Comment by LoneDev6** [comment]
Duplicate https://github.com/LoneDev6/ItemsAdder/issues/31
