### ISSUE TITLE
Blockstate Update

### ISSUE THREAD

**Issue by TheMGRF** [LoneDev6/ItemsAdder#78]
Blockstates seem to update when a sticky piston pulls 2 or more custom blocks. Pushing does not work, seemingly only pulling.

https://i.gyazo.com/7d7a592f2b8e26d9e8c92694d2d1ab18.mp4

**Comment by LoneDev6** [comment]
I hope they will add this option: https://github.com/PaperMC/Paper/issues/2649
Btw in the mean time, do you think will be better to disable pushing/pulling custom blocks with sticky pistons?

**Comment by LoneDev6** [comment]
Should be fixed in IA 2.0 (I'm going to publish it in some days).
Now users should be able to use redstone near and on custom blocks without bugging them
