### ISSUE TITLE
Custom Crops not working properly

### ISSUE THREAD

**Issue by Moosebobby123** [LoneDev6/ItemsAdder#79]
Custom seeds are not working properly unless their base crop is set to "WHEAT" in the config. Other plants such as Beetroot, Carrots, and potatoes are not working. See gyazo gif: [https://gyazo.com/4ad8b8706cf935f5ec3e6548fae1c02d]

Here is how my config is for a plant: 
tomato_seed:
  enabled: true
  model_id: 1
  name: '&7Tomato Seeds'
  events:
    block_break:
      drop_this_item:
        from_vanilla_block: GRASS
        chance: 5
        min_amount: 1
        max_amount: 2
  specific_properties:
    crop_block: BEETROOT
    result:
      item: tomato
      min_amount: 1
      max_amount: 3

**Comment by LoneDev6** [comment]
Did you try this in a clean server?
So default garlic_seeds is not working too?

`garlic_seeds:
  enabled: true
  permission: garlic_seeds
  model_id: 2
  name: '&fGarlic Seeds'
  events:
    block_break:
      drop_this_item:
        from_block:
          GRASS:
            chance: 5
            min_amount: 1
            max_amount: 2
  specific_properties:
    crop_block: CARROTS
    result:
      item: garlic
      min_amount: 1
      max_amount: 2
  craft_recipe:
    enabled: true
    amount: 2
    pattern:
      - XXX
      - XOX
      - XXX
    ingredients:
      O: garlic`
