### ISSUE TITLE
Taking items from /ia without perms easily

### ISSUE THREAD

**Issue by DataSlurmph** [LoneDev6/ItemsAdder#80]
Hello, all of my players have recently been able to take working items from /ia using the common minecraft bug where you shift + right click to put the item in your inventory and then exit off of a GUI very fast and the item appears in your inventory but usually is a fake item and doesn't actually exist in your inventory, but when my players do /ia and do that same bug they can actually keep the item, it appears in their inventory and can fully use it, drag it around and I can take it from their inventory. I can't enable /ia on my server and people can't see what the recipes are anymore which is very annoying.

**Comment by LoneDev6** [comment]
- Spigot version (use /version command)
- plugins list
- any error in log?
- video?
