### ISSUE TITLE
ERROR Console texture pack

### ISSUE THREAD

**Issue by istarengwa** [LoneDev6/ItemsAdder#86]
hello, the texture pack shows me an error in the console. Most players can download it with a display error in the %. And another part of the players crash when downloading. 

Minecraft Paper Spigot 1.15.2 

Download -24234253625431% : https://image.noelshack.com/fichiers/2020/11/6/1584186924-2020-03-14.png

Error Console : https://pastebin.com/nMQEScag

**Comment by LoneDev6** [comment]
@istarengwa 
Can you send me your config.yml file? thanks

**Comment by LoneDev6** [comment]
@istarengwa 
Percentage is fixed in 2.0.1 version of IA.
About the error, please be sure to reset your config.yml after update, let me know if happens again.
If yes please reopen this issue

**Comment by istarengwa** [comment]
Hello, Many things to say.

When I use your link, or mine, or the server port, the download is done with each new launch of our launcher, which was not the case in the first version of the plugin. There was a load on each connection, but not a download. And the download starts 2 times each time.

Once the download is complete, if I use the server port or my link. After disabling mana and thirst, it displays "null" several times continuously on the player screen, this is not the case with your link

When I use the server port, it always shows me the negative download.

I saw that in the server-resource-pack folder of .minecraft or my launcher, the files accumulate with each download of your resource pack.

https://zupimages.net/viewer.php?id=20/12/ikyt.png

my configuration is your basic configuration

**Comment by LoneDev6** [comment]
this will be fixed in next update.
The problem of files accumulating seems to be related to invalid download percentage shown

**Comment by LoneDev6** [comment]
@istarengwa let me know if is still happening after the latest updates
