### ISSUE TITLE
Collection of issues and suggestions

### ISSUE THREAD

**Issue by Andre601** [LoneDev6/ItemsAdder#88]
I found multiple bugs but also had some ideas for new implementation of stuff to ItemsAdder.
Since this would create like 5+ issues did I decide to instead make one major issue, that contains both bug-reports and suggestions, to have one major *checklist* in some way.

## Information
**Server type and version**: PaperMC 1.15.2 (Build 132)
**Plugins loaded**:
```
AdvancedTabOverlay*, CoreProtect, DeluxeChat, Essentials, EssentialsSpawn, HelpPagePlus, IALibs, ItemsAdder, LightAPI*, LuckPerms, MessageAnnouncer, PlaceholderAPI, ProtocolLib, ServerListPlus*, Vault, WorldBorder
```

### Actionbar displays `null` when in Spectator mode
**Original issue**: NaN

When you switch into Spectator mode does the Actionbar suddenly display `null`

### Loading URL for resourcepack freezes server
**Original issue**: #87 

When ItemsAdder loads the URL (`[ItemsAdder] Checking resourcepack url...`) does the server freeze for more than 10 seconds, causing a Thread dump.

Latest Log: https://mcpaste.io/f7f1cfe520637652

### Amnethyst Ore generates as Block of Amnethyst Chrystal
**Original issue**: NaN

ItemsAdder generates `Block of Amnethyst Chrystal` instead of `Amnethyst Ore` in the world, making it look really weird.

![2020-03-15_14 43 52](https://user-images.githubusercontent.com/11576465/76703280-ecc84500-66d0-11ea-9661-40bfec7017cb.png)

### Mining Crying Obsidian fails sometimes
**Original issue**: NaN

When mining Crying Obsidian with a pickaxe (in my case with diamond) does it sometimes drop the block, but sometimes also nothing. And in some cases even mushrooms, when the texture is bugged.
No errors or similar in console.

![crying obsidian bug](https://thumbs.gfycat.com/AggressiveDefinitiveIcelandicsheepdog-small.gif)

### Player is stuck on loading resource pack when invalid
When the provided resource pack is invalid in a way (causing ItemsAdder to send an Error) can it happen that the player is stuck on the screen of downloading the resourcepack, causing a softlock, as the player will be unable to exit the game through the menu (Pressing escape). Only options of disconnects are kicking the player or shutting down the server (or the player forcefully closes the window of Minecraft)

I highly suggest to auto-kick the player with the error message as reason, instead of just sending the message, to prevent such softlocks.

### Add configuration option to make item a fuel-source
I suggested this on the Discord already, but it would be nice to have an option to set a custom item as a fuel for furnaces.
That way could f.e. the Coal nugget be used as a separate fuel for the furnace that can smelt 1/9 of what coal can smelt.

So the option should perhaps have the following options:
- How long it lasts (In ticks or seconds?)
- Restrict it to specific furnaces maybe?
- If it would return an item (i.e. similar to Lava bucket which gives back the bucket)

### Add chrystals/ors to loot-table of mines
If possible would it be really cool to add the chrystals/ores to the loot table used for mineshafts, so that they would appear in chest minecarts.

**Comment by LoneDev6** [comment]
https://github.com/LoneDev6/ItemsAdder/issues/92
https://github.com/LoneDev6/ItemsAdder/issues/93
https://github.com/LoneDev6/ItemsAdder/issues/94
https://github.com/LoneDev6/ItemsAdder/issues/95
https://github.com/LoneDev6/ItemsAdder/issues/96
https://github.com/LoneDev6/ItemsAdder/issues/97
https://github.com/LoneDev6/ItemsAdder/issues/98
