### ISSUE TITLE
ERROR [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder

### ISSUE THREAD

**Issue by JaHollYT** [LoneDev6/ItemsAdder#89]
New Update Produces Error on join: Using paper 1.14.4 & newest ItemAdder Version

ERROR [ItemsAdder] Unhandled exception occured in onPacketSending(PacketEvent) for ItemsAdder
15.03 17:10:46 [Server] INFO java.lang.NoSuchMethodError: net.minecraft.server.v1_14_R1.MinecraftKey.b()Ljava/lang/String;
15.03 17:10:46 [Server] INFO at dev.lone.itemsadder.d.f.d.a.d.onPacketSending(Unknown Source) ~[?:?]
15.03 17:10:46 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
15.03 17:10:46 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
15.03 17:10:46 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
15.03 17:10:46 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
15.03 17:10:46 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
15.03 17:10:46 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
15.03 17:10:46 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
15.03 17:10:46 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
15.03 17:10:46 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
15.03 17:10:46 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
15.03 17:10:46 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
15.03 17:10:46 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:200) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:169) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1521) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1494) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.RecipeBookServer.a(RecipeBookServer.java:142) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerList.a(PlayerList.java:169) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1255) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-210]
15.03 17:10:46 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-210]

**Comment by LoneDev6** [comment]
Please install the very latest Paper 1.14.4 build: https://papermc.io/legacy

**Comment by JaHollYT** [comment]
Still the same error. 
What i forgot to say: i have the Resource-Pack part in ItemAdder disabled, i use another Plugin for that :)

**Comment by LoneDev6** [comment]
Thanks, seems Spigot changed name of a method, I'll post an update today, after the update let me know if error occurs again or not.
If yes please reopen this issue. Thanks! :D
