### ISSUE TITLE
Infinite chunk loads when custom ore generation settings set too high

### ISSUE THREAD

**Issue by BillyGalbreath** [LoneDev6/ItemsAdder#9]
_This is not my own bug, but was reported to me in the [Paper discord](https://discord.gg/papermc) server. Adding as GH ticket for completeness._

Someone came into paper discord with a timings report where ItemsAdder is infinitely loading chunks. From examining the code, it look like an ore generation set way too high (user error). Thought I'd bring this up to you, since it is a concern, none the less.

`chunk.getBlock()` in the `ChunkLoadEvent` will cause neighbor chunks to load if the block is at the chunk edge. If every chunk has an IA block at the chunk edge this will trigger an infinite loading scenario. See line 105 of `dev.lone.itemsadder.c.c.b`

It's a common problem we're seeing with `BlockPopulators`, too

For reference, here's someone else trying to follow the path in the timings report:

![image](https://user-images.githubusercontent.com/332527/60618127-f60bbe80-9d9a-11e9-8572-b00ab8b0e245.png)

And here's the timings report in question https://timings.aikar.co/?id=bc60b224af2b45c3bbaa4f16b5014105

**Comment by LoneDev6** [comment]
I see.. mh, it's strange because my logic avoids to generate blocks too near to chunk edges to be sure not to trigger load of near chunks..
I'd like to see blocks.yml to check if they messed up with generation settings

**Comment by LoneDev6** [comment]
Last update should address this issue, let me know, version 1.0.33

**Comment by LoneDev6** [comment]
Seems to be fixed in latest releases of PaperSpigot + ItemsAdder
