### ISSUE TITLE
Resource Pack always redownloaded

### ISSUE THREAD

**Issue by spathizilla** [LoneDev6/ItemsAdder#90]
**Info:**
Server: Paper(132) 1.15.2-R0.1-SNAPSHOT
IAVersion: 2.0 Beta

**Problem:**
When connecting to the server with the resource pack configured to be remotely hosted, it is always redownloaded fully. In version 1, a redownload would only be triggered upon a pack update. 

In addition it appears to download twice although I have yet to confirm this with the actual webserver logs.

**Reproduction:**
1) Download pack.zip from the resource_pack directory
2) Upload to webserver of choice
3) Set url in config.yml to be the remotely hosted pack.zip
    Also set self-host.enabled to false
4) Start server
5) Connect to server - pack is downloaded (and should be cached)
Wait until fully loaded
6) Disconnect from server
7) Reconnect to server - pack is downloaded again (should be using the cached download before)

In version 1, it would cache the pack inside minecraft correctly and only download upon an update

**Comment by LoneDev6** [comment]
Today I'll publish an update which will address this issue.
Let me know if that issue occurs again after new update ;)

**Comment by spathizilla** [comment]
Will do.

**Comment by spathizilla** [comment]
Seems fixed in latest build.
