### ISSUE TITLE
Custom block shows Mushroom Block also

### ISSUE THREAD

**Issue by spathizilla** [LoneDev6/ItemsAdder#91]
Info:
Server: Paper(132) 1.15.2-R0.1-SNAPSHOT
IAVersion: 2.0 Beta

Problem:
In Beta 2.0, a previously working block is now showing the underlying mushroom block.

![image](https://user-images.githubusercontent.com/638845/76712917-ce843880-6714-11ea-9e26-dbd2fa2d5a4a.png)

I can provide the block model if required.

**Comment by spathizilla** [comment]
Everything was converted automatically.

**Comment by spathizilla** [comment]
Still an issue on 2.0.1

**Comment by LoneDev6** [comment]
Thanks I'm working on it, will let you know

**Comment by LoneDev6** [comment]
Please send me your .json model

**Comment by LoneDev6** [comment]
> 
> 
> Still an issue on 2.0.1

Thanks a lot for the report, I found the issue.
Will be fixed in 2.0.2 release
