### ISSUE TITLE
Player is stuck on loading resource pack when invalid

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/ItemsAdder#96]
### Player is stuck on loading resource pack when invalid
When the provided resource pack is invalid in a way (causing ItemsAdder to send an Error) can it happen that the player is stuck on the screen of downloading the resourcepack, causing a softlock, as the player will be unable to exit the game through the menu (Pressing escape). Only options of disconnects are kicking the player or shutting down the server (or the player forcefully closes the window of Minecraft)

I highly suggest to auto-kick the player with the error message as reason, instead of just sending the message, to prevent such softlocks.

**Comment by LoneDev6** [comment]
@Andre601
Can you please send me privately on Discord your invalid pack and config.yml? The one which freezes client with loading text.
Thanks

**Comment by Andre601** [comment]
I don't have it anymore, unless IA saves it somewhere.
I could try changing the IP to url to see if it would happen again

**Comment by LoneDev6** [comment]
> 
> 
> I don't have it anymore, unless IA saves it somewhere.
> I could try changing the IP to url to see if it would happen again

I can't reproduce the issue, I admit it happened some times to me at early testing on ItemsAdder so I'd like to understand what's the precise cause of this bug (it's a client bug, it's not normal to let the client stay truck on infinite loading, I'm not sending the pack multiple times)

**Comment by Andre601** [comment]
I've managed to reproduce the error again.
This time did the plugin throw an error tho, which is about the URL being invalid.

resourcepack:
[pack.zip](https://github.com/LoneDev6/ItemsAdder/files/4338602/pack.zip)

Screen of being stuck on the loading screen:
![image](https://user-images.githubusercontent.com/11576465/76766774-cff74480-6798-11ea-97d0-fb937ae0163d.png)

Last time did it not throw an error about the URL being invalid, which it does now although the URL was the same in both cases.
An A-Record is setup to point the sub-domain towards the IP of the server and an SRV-Record to change server-port to the one used for the server.
Could one possible issue be the fact, that the subdomain is being proxied by Cloudflare?

**Comment by LoneDev6** [comment]
Send me your config.yml privately on Discord (add me if you didn't).
I don't know if your host is using cloudflare, but I can check if you send me your config.yml file

**Comment by Andre601** [comment]
I now face the same issue again, BUT this time with the IP itself.
I did nothing more than updating the plugin to 2.0.1-BETA (Deleting config, regenerating it and then applying the information).

No errors or stacktraces in the console. Just the warning of ItemsAdder in Chat:
```
[ItemsAdder] An error occurred when enabling the resourcepack. Please contact admins or disable resourcepacks.
```

**Comment by LoneDev6** [comment]
> 
> 
> I now face the same issue again, BUT this time with the IP itself.
> I did nothing more than updating the plugin to 2.0.1-BETA (Deleting config, regenerating it and then applying the information).
> 
> No errors or stacktraces in the console. Just the warning of ItemsAdder in Chat:
> 
> ```
> [ItemsAdder] An error occurred when enabling the resourcepack. Please contact admins or disable resourcepacks.
> ```
> 
> Whatever you changed in the system now breaks it even more.
> 
> Also, am I still for an option to kick the player when they resourcepack failed to load, since they CAN and WILL be stuck on the load screen which is a softlock that nobody wants.

Please share the exact server log you had when you got stuck downloading.
Also send me your config.yml

thanks!

**Comment by LoneDev6** [comment]
Ia 2.0.2 will have this:
`kick-player-on-fail: false`

under `resource-pack:`

**Comment by Andre601** [comment]
Logs show nothing in that regard. Only that I joined and later got kicked from Console.

```
17.03 12:24:45 [Server] INFO UUID of player Andre_601 is 286f8d0c-b571-4720-b7ab-f2929cb38120
17.03 12:24:47 [Connect] User Andre_601, IP *.*.*.87
17.03 12:24:47 [PebbleHost] Andre_601 ran command Message of the Day
17.03 12:27:20 [Server] INFO CONSOLE issued server command: /kick Andre_601
17.03 12:27:20 [Disconnect] User Andre_601 has disconnected, reason: Kicked from server.
17.03 12:27:20 [Server] INFO Andre_601 left the game
17.03 12:27:20 [Server] INFO Player Console kicked Andre_601 for Kicked from server..
17.03 12:27:20 [PebbleHost] *@*.ch ran command: kick Andre_601
17.03 12:27:20 [Server] WARN handleDisconnection() called twice
```

**Comment by LoneDev6** [comment]
And client log?

**Comment by Andre601** [comment]
The issue was resolved.
It was an extra http:// at the beginning of the URL that was added, causing the URL to be invalid.

**Comment by LoneDev6** [comment]
> 
> 
> The issue was resolved.
> It was an extra http:// at the beginning of the URL that was added, causing the URL to be invalid.

Perfect!
I hope Mojang will also add a check for this in 1.16, to avoid that no sense loop

**Comment by Andre601** [comment]
The issue is actually more on Spigots end as the URL simply won't work in a way, when using vanilla and the server.properties file (Client still asks if you want to download it, but won't actually load it)

**Comment by LoneDev6** [comment]
Thanks for the report: https://hub.spigotmc.org/jira/browse/SPIGOT-5624
