### ISSUE TITLE
Issue: Custom Ores not dropping.

### ISSUE THREAD

**Issue by Ch3rryP** [LoneDev6/ItemsAdder#99]
I've mined Aqua, Amethyst and Ruby and Coal Dirt Ore and nothing is dropping for me. When I mined Lapis, I got Amethyst Prism though. Also, Crying Obsidian spawns randomly and when I hit it, no drop and turns to mushroom blocks.

**Comment by LoneDev6** [comment]
Please update to 2.0.1 and reset world if possible.
Sadly 2.0 had a bug that didn't save most of the blocks correctly.
Also you must set everything to false in converter.yml if you don't need conversion of old blocks and items in real time (blocks already placed in world and items in inventories made with 1.0).

Let me know
